elizaOS/eliza

src/index.ts
doesn't support multiple agents or switching.
Related to #40 
This provides a way to test your characters on the command line before integrating with discord or twitter.
=> provide a way to chat directly with the agent via the command line 

renovate.json
Adding Renovate and grouping packages together.
It will require adding a free GitHub marketplace plugin
* https://github.com/marketplace/renovate
=> Initial commit for adding Renovate autoupdater.

core/src/adapters/postgres.ts
n/a postgres bug fixes. unique is a special keyword in postgres. Empty room ids, and not setting up query parameters correctly.
low
updates postgres queries
=> postgres updates

package-lock.json, package.json, src/clients/twitter/generate.ts, src/clients/twitter/search.ts, src/clients/twitter/utils.ts
Shorten bot response length in order not to go over twitter limit
=> feat: Shorten response verbosity

core/src/core/generation.ts, core/src/core/models.ts
grok-beta integrated.
everyone gets a free Eliza until end of year.
accelerate.
https://docs.x.ai/api/integrations#openai-sdk
=> Implement grok beta

packages/client-telegram/src/index.ts
tg.start() is added; agents starts
=> telegram: start agent after client initialization

packages/core/src/models.ts
Quality of llama generated responses
Low, simple increase of numbers
Weak llama responses
Generate more creative responses via a higher temp
Cause we ball
=> Increased llama and llama based model temperatures

README.md, README_JA.md
I created Japanese translated README.
=> docs: add a new Japanese README

README.md, README_FR.md, README_KOR.md
Add Korean and French README
Translate
=> Add Korean and French README

.env.example, packages/client-discord/src/index.ts, packages/plugin-image-generation/src/index.ts, packages/plugin-solana/src/actions/pumpfun.ts
working pumpfun.ts calls to image gen
discord just works
issues currently with twitter & tg not calling any actions on anything not related to just these actions
once those are fixed this will also just work
apikey has to be openai not togetherai (will figure out good solutions for that)
=> added working pumpfun.ts

README_KOR.md
hope you can enjoy it ! 
make sure I translated correctly for use translator :) 
everything will be correct 99%
=> README_KOR.md Korean version edited by a Korean 

packages/adapter-postgres/package.json, packages/adapter-sqlite/package.json
=> fix: dev build

docs/api/enumerations/ModelProviderName.md, docs/docs/advanced/fine-tuning.md, docs/docs/api/enumerations/ModelProviderName.md, docs/docs/guides/configuration.md, docs/docs/quickstart.md
This PR enhances the documentation for the recently [merged Heurist integration](https://github.com/ai16z/eliza/commit/4d1e66cbf7deea87a8a67525670a963cd00108bc) by:
1. Adding Heurist configuration details to quickstart guide
2. Including example usage for image generation
3. Documenting Heurist API key setup
4. Adding detailed model provider configuration information
Documentation (enhancing existing documentation)
Added/Updated:
- ✨ Added Heurist API key configuration in quickstart environment variables
- 📝 Added image generation configuration guide
- 💡 Added example usage for generateImage with PepeXL model
- 🔄 Updated model provider enumeration documentation
- 🛠️ Added fine-tuning settings for Heurist models
=>  Update Heurist Integration Documentation and Examples

packages/core/src/runtime.ts
Fixes bug in agent runtime getRecentMessageInteractions doesnt wait for the promises before formating
Bug fixes 
No
=> fix: bug in getRecentMessageInteractions not awating for promisses before formating

packages/agent/src/index.ts, packages/core/src/types.ts
- Allows installing clients from plugins
=> feat: install clients from plugin

README.md, README_TR.md
✨ Added complete Turkish (TR) translation that:
- Maintains original document structure and layout
- Preserves all formatting, emojis, and technical terms
- Retains all original links and image references
- Includes full translation of all sections (Features, Use Cases, Quick Start, etc.)
- Updates language selector in Translations section
🌍 This translation is part of our internationalization efforts to make Eliza more accessible to Turkish-speaking developers.
=> docs: add Turkish (TR) translation of README

packages/agent/src/index.ts, packages/client-twitter/src/interactions.ts, packages/core/src/models.ts, pnpm-lock.yaml
=> fix: console

.env.example, docs/docs/quickstart.md
ai16z docs - update since GROK support was added in #296.
Low
Simply adding `GROK_API_KEY` to doc
docs
For users to use GROK
no
N/A
=> docs: add GROK_API_KEY

packages/plugin-starknet/src/actions/unruggable.ts, packages/plugin-starknet/src/index.ts
Low
Adds the deploy token action from Unruggable Memes to the Starknet plugin
=> feat: unruggable on starknet

packages/adapter-postgres/package.json, packages/adapter-postgres/tsconfig.json, packages/adapter-sqlite/package.json, packages/adapter-sqlite/tsconfig.json, packages/adapter-sqljs/tsconfig.json, packages/adapter-supabase/tsconfig.json, packages/client-auto/tsconfig.json, packages/client-direct/tsconfig.json, packages/client-discord/tsconfig.json, packages/client-telegram/package.json, packages/client-telegram/tsconfig.json, packages/client-twitter/tsconfig.json, packages/plugin-bootstrap/tsconfig.json, packages/plugin-image-generation/tsconfig.json, packages/plugin-node/tsconfig.json, packages/plugin-solana/tsconfig.json, packages/plugin-starknet/tsconfig.json, packages/plugin-trustdb/tsconfig.json, packages/plugin-video-generation/.npmignore, packages/plugin-video-generation/tsconfig.json
=> fix: configs

docs/docs/community/contributing.md, docs/docs/packages/plugins.md, packages/client-discord/src/messages.ts, packages/client-discord/src/voice.ts, packages/core/src/test_resources/constants.ts, packages/plugin-bootstrap/src/evaluators/fact.ts, packages/plugin-bootstrap/src/evaluators/goal.ts, packages/plugin-bootstrap/src/providers/facts.ts, packages/plugin-image-generation/src/index.ts, packages/plugin-video-generation/src/index.ts
- fixes more imports around the place
=> fix: imports

packages/client-discord/src/voice.ts
- fixes issue if bot does not have the perms
=> fix: voice perms

packages/client-twitter/src/post.ts
[Twitter dry run not working](https://github.com/ai16z/eliza/issues/451)
Affects anyone working to improve their agents and trying to test their changes
This PR reenables the TWITTER_DRY_RUN flag
Bug fix
None
It's straightforward enough to just look at the 4 lines :)
N/A
N/A
N/A
=> fix: X dry run

docs/src/components/HomepageHeader/index.js
Replaces `npm package coming soon` with `npm install @ai16z/eliza`
Update
=> Add npm install instructions to homepage header

docs/docs/community/streams/2024-11-15.md
None
Fix my name
Documentation / Archive correction
autotranslate got it really wrong
If a docs change is needed: I have updated the documentation accordingly.
=> docs: Fix my name in stream notes

packages/client-github/.npmignore, packages/client-github/package.json, packages/client-github/src/index.ts, packages/client-github/tsconfig.json, packages/client-github/tsup.config.ts, pnpm-lock.yaml
ingest github repos into knowledge base
=> feat: init github client

.github/pull_request_template.md
None
Updated PR template to ask for discord username 
Process: Template update
Because we have more contributors than official devs and we want to increase communication
=> docs: Add Discord username question

docs/docs/community/contributing.md
=> docs: Update Contributors to bring inline with PR468

packages/core/package.json, packages/core/src/tests/token.test.ts
- removes dep to stop circular deps
=> fix: remove sol dep

packages/adapter-postgres/.npmignore
=> fix: issue with npm

packages/adapter-postgres/src/index.ts, packages/client-discord/src/voice.ts, packages/core/src/memory.ts, packages/core/src/runtime.ts, pnpm-lock.yaml
=> fix: services fix

packages/client-discord/src/voice.ts
=> fix: discord voice memory id not unique

packages/plugin-node/package.json, pnpm-lock.yaml
https://github.com/echogarden-project/echogarden/commit/fb44fb384c824eb6e2ea090e4e03490d6ad8766f
Low
Updates to latest echogarden which fixes a case sensitive file system issue in the upstream.
Eliza was crashing on linux w/o this change
Testing on Linux, but also easy to see that the `main` field for echogarden had `API` when that director was `api`
0xflick
=> fix: bump echogarden to fix case sensitive issue

docs/docs/community/streams/2024-11-22.md
Community Stream docs
Low
Timestamps and notes for weekly meeting
Improves docs
https://ai16z.github.io/eliza/docs/community/stream-notes/
No
`YoungPhlo`
`User ID: 296887155819675650`
=> Add community stream notes for WDYGDTW 2

docs/sidebars.js
add link to hats protocol presentation in docs sidebar
=> feat: update sidebars

packages/core/src/memory.ts, packages/core/src/types.ts
=> fix: add Memory Manager getMemoriesByRoomIds missing tableName param

packages/core/src/knowledge.ts
knowledge module is exporting process insteand of preprocess
=> fix: knowledge module exporting process

packages/client-farcaster/src/client.ts, packages/core/src/types.ts
adds missing farcaster templates to character type
=> fix: add client farcaster templates to character type

.github/pull_request_template.md, packages/plugin-solana/src/providers/trustScoreProvider.ts
Running `pnpm run build` breaks due to an incorrect argument in turstScoreProvider.ts
No risk - this fixes a typo that broke package builds
Fixes CI and all package builds
Bug fix
Run `pnpm run build` locally and check CI
=> fix: node package builds

docs/docs/community/streams/2024-11-26.md
Documentation of a16z AI Agent Dev School Session 1
Low - This is a documentation-only change adding new stream notes.
Adds detailed documentation for the first a16z AI Agent Dev School session, covering Shaw's deep dive into the Eliza framework, including implementation details, architecture decisions, and future development plans.
Documentation
None, documentation review is sufficient. Verify that:
- All links to YouTube videos are working
- Content is properly formatted
- Information is accurate to the session content
- Sidebar position is correct (6)
=> Notes for AI Agent Dev School #1

README.md
=> add connection instruction for connecting with X

packages/client-direct/src/index.ts, packages/core/src/generation.ts, packages/core/src/types.ts, packages/plugin-web-search/.npmignore, packages/plugin-web-search/package.json, packages/plugin-web-search/src/index.ts, packages/plugin-web-search/tsconfig.json, packages/plugin-web-search/tsup.config.ts, scripts/build.sh
related: https://github.com/ai16z/eliza/issues/363
=> integrate tavily

packages/plugin-tee/package.json
Low
Plugin-TEE is missing the `viem` package dependency that is used in the `DeriveKeyProvider`.
Bug Fixes
No
=> fix: add missing viem dependency

Dockerfile, docker-compose.yaml
Low, only pertains to docker users.
Docker was broken with turbo update. This reduces build times.
- Fixes Docker builds
Docker agent running in TEE
=> fix: update docker image to support turbo and reduce build time

docs/api/functions/generateCaption.md, docs/api/functions/generateImage.md, docs/api/functions/generateMessageResponse.md, docs/api/functions/generateObject.md, docs/api/functions/generateObjectArray.md, docs/api/functions/generateObjectV2.md, docs/api/functions/generateShouldRespond.md, docs/api/functions/generateTextArray.md, docs/api/functions/generateTrueOrFalse.md, docs/api/functions/generateWebSearch.md, docs/api/functions/handleProvider.md, docs/api/functions/splitChunks.md, docs/api/interfaces/GenerationOptions.md, docs/docs/community/streams/2024-11-24.md, docs/docs/community/streams/2024-11-28.md, docs/docs/community/streams/2024-11-29.md, docs/sidebars.js
- Add missing links to streams
- Add notes from recent spaces
- Update API docs
=> feat: add new pages, update sidebar

packages/core/src/knowledge.ts
Right now we're only providing 3 snippets of knowledge to the model when generating responses. We should increase this a bit to provide more context.
Low
=> feat: increase knowledge context

.gitpod.yml, README.md
We can run this with Gitpod which helps a lot with environment.
Just click the button in readme :  `Open In Gitpod `
=> Add running with Gitpod

client/package.json, eslint.config.mjs, package.json, packages/core/package.json, pnpm-lock.yaml
This PR merges in some more dependency updates and fixes a linting issue
=> feat: more dependency updates

.env.example, agent/src/index.ts, packages/core/src/generation.ts, packages/core/src/models.ts, packages/core/src/types.ts
This PR merges https://github.com/ai16z/eliza/pull/747 and fixes a case issue on generation for switching
=> Integrate more LLMs, fix case issue in switch

.github/workflows/release.yaml
Because the latest head and latest tag differ, there will be untracked files when checking out the latest tag. This PR fixes that by cleaning out untracked files.
=> fix: part 2 of updating the npm publish workflow

.github/workflows/release.yaml
We need to use `from-package` when calling `lerna publish`
=> fix: lerna publish command

docs/docs/guides/docker-setup.md
Added further troubleshooting steps:
- Clearing old images.
=> fix: docker-setup.md

.github/workflows/release.yaml
Fixed a bug with the release script which tried to generate the github release automatically. Instead, I'm changing this workflow so it runs after we create a release on github
=> fix: run release workflow after a github release is created

docs/docs/packages/plugins.md
There were quite a few repeated sections in these docs while I was reading them so i fixed them here
=> fix: plugins docs

docs/docs/guides/local-development.md
Update the Node.js requirement per https://github.com/ai16z/eliza/blob/main/package.json#L49C18-L49C24
=> Update Node version in local-development.md

.env.example, packages/core/src/models.ts
=> Add google model env vars

scripts/dev.sh
Improvement to the dev script.
=> chore: enhance dev script, performance improvement and add help message

packages/core/src/models.ts, packages/core/src/tests/models.test.ts
https://console.groq.com/docs/deprecations
Update models for groq as some will be deprecated per https://console.groq.com/docs/deprecations.
=> chore: update models for groq

README_KOR.md
Low: This change only standardizes the link label and does not affect core functionality.
It updates the label text for the Community and Contact links to ensure consistency.
Improvement
No documentation changes are needed.
Check the updated sections of the code that include the Community and Contact link label text.
1. Navigate to the screen containing the Community and Contact links.
2. Verify that the link label text is consistent across the UI.
=> chore: Consistent language for Community & Contact link label

packages/client-telegram/src/messageManager.ts
Response memories in the telegram client are being tagged wrong as the userId it should be the agentId
=> fix: telegram response memory userId to agentId

docs/docs/core/characterfile.md
=> fix: a typo in characterfile.md

README.md, README_DE.md
=> feat: create README_DE.md

.env.example, packages/core/src/models.ts
Close https://github.com/ai16z/eliza/issues/988
Allow users to configure models for openai and anthropic
=> feat: allow users to configure models for openai and anthropic

agent/src/index.ts
No issue found for this.
Fixes a typo `intialize`->`initialize`
Typo fix
Fixing a simply typo. No related issues observed this.
=> fix: typo initialize

docs/community/Streams/12-2024/2024-12-10.md
Documentation update for community stream notes
Low - This is a documentation-only change adding new stream notes.
Adds detailed stream notes for the AI Agent Dev School Part 4 session from December 10, 2024, covering:
- Part 1: Technical discussion on Trusted Execution Environments (TEEs) with Agent Joshua
- Part 2: Building a Domino's pizza ordering agent using the Eliza framework
Documentation (non-breaking change which adds documentation)
My changes are documentation changes and I have added them accordingly in the new file:
`docs/community/Streams/12-2024/2024-12-10.md`
Review the new markdown file below.
1. Verify the markdown formatting is correct
2. Check that all timestamps and YouTube links are working
3. Verify the summary sections accurately reflect the stream content
=> docs: "AI Agent Dev School Part 4" livestream notes

README.md, README_HE.md
[Add Hebrew (RTL) translation](https://github.com/ai16z/eliza/issues/1022)
Low - This is a documentation-only change adding a new translation file.
Adds Hebrew (RTL) translation of the main README.md file as README_HE.md, including:
- Full translation of all main sections
- RTL text direction support using HTML/CSS
- Proper Hebrew character rendering
- Maintained all links and functionality from original README
Improvements (adds new language support to existing documentation)
My changes are documentation changes themselves - adding a new translated README file.
1. Open README_HE.md in either VSCode/Cursor/github.dev's Markdown preview
2. Verify RTL formatting is correct
3. Check that all links are functional
4. Verify Hebrew text renders properly
As anon/reviewer, go to …
=> docs: Add Hebrew README Translation

README.md
This PR adds tutorial link to the README
=> feat: Add AI Agent Dev School Tutorial Link

packages/plugin-goat/package.json
Added Coingecko dependency to the plugin-goat (package.json) file.
=> chore: Update package.json

packages/plugin-node/src/services/image.ts
If someone uses a proxy such as redpill to access the model, the original code will not load the image correctly.
=> fix: load image from diff endpoints

docker-compose.yaml
New branch to fix Docker issue related to #815
=> fix: remove docker compose command since Docker file already runs

agent/src/index.ts
Low
Fixes direct-client behavior
To restore previous behavior
=> fix: fix direct-client ability to start agents

packages/plugin-multiversx/src/actions/createToken.ts
=> fix: Fix typo in multiversx plugin prompt for creating token

.gitpod.yml
Sometimes we can't fetch tags, so let's fetch tags before.
=> fix: gitpod cicd bug

packages/client-twitter/src/post.ts, packages/core/src/types.ts
Low
Adds more variance to tweet generation so the content feels less stale
=> fix: improve twitter post generation prompt

client/vite.config.ts
Low
It uses SERVER_PORT environment variable in the client app
Improvements for developer experience
Experienced this issue when developing and wanted to use another port then 3000
=> fix: Sync UI Client with server port env

agent/src/index.ts
related: https://github.com/ai16z/eliza/issues/1255
=> fix: unsupported model provider: claude_vertex

characters/trump.character.json, package.json
=> chore: clean up merged PR1168

.github/workflows/integrationTests.yaml
does what it says on the box - fix integrationtests, they should run correctly now
=> fix: integration tests fix

.github/workflows/integrationTests.yaml
=> fix: output checkable variable for conditional

agent/src/index.ts
Low.
Not sure why google is missing in the latest `develop` branch.
Add support for google model.
=> fix: support google model.

packages/client-twitter/src/post.ts
Low.
I believe it's a bug introduced in https://github.com/ai16z/eliza/pull/1007, we shouldn'd hardcode the number as users should be able to customize it with X premium for writing long tweets.
=> fix: use MAX_TWEET_LENGTH from setting

packages/adapter-postgres/schema.sql
Closes: https://github.com/ai16z/eliza/issues/1344
Low
Fixes creating the table
Bug Fix
No
Run the postgres adapter on a fresh postgres
=> fix: postgres adapter schema

.github/pull_request_template.md, CONTRIBUTING.md, README.md, README_DE.md, README_FR.md, README_HE.md, README_IT.md, README_KOR.md, README_RU.md, README_TH.md, README_TR.md, README_VI.md, SECURITY.md, docs/community/faq-and-support.md, docs/docs/contributing.md, docs/docs/quickstart.md, docs/docusaurus.config.js
=> chore: revert discord url

README.md
adding documentation for running chat client
=> Update README.md to instructions to start client for chatting with Agent

docs/community/Streams/12-2024/2024-12-03.md, docs/community/Streams/12-2024/2024-12-05.md, docs/community/Streams/12-2024/2024-12-06.md, docs/community/Streams/12-2024/2024-12-10.md, docs/community/Streams/12-2024/2024-12-13.md, docs/community/Streams/12-2024/2024-12-20.md
Documentation standardization effort
Low - This is a documentation-only change that standardizes formatting across December 2024 stream notes.
- Standardizes formatting for December stream documentation
- Updates timestamp formatting to use markdown links
- Improves readability with consistent bullet points and headers
- Adds new stream notes for "What Did You Get Done This Week? 6"
Improvements (standardization of existing documentation)
These changes are documentation changes themselves, no additional documentation updates required.
Review the following files for consistent formatting:
- docs/community/Streams/12-2024/2024-12-03.md
- docs/community/Streams/12-2024/2024-12-05.md
- docs/community/Streams/12-2024/2024-12-06.md
- docs/community/Streams/12-2024/2024-12-13.md
- …
=> docs: Add "What Did You Get Done This Week? #6" notes

packages/core/src/generation.ts, packages/core/src/types.ts, packages/plugin-image-generation/src/index.ts
Super simple PR to add the option to use venice's style presets on image generation as well as the ability to remove the default watermark. (Also added in seed field which I guess I missed)
As low as it gets!
adds the option to use venice's style presets on image generation as well as the ability to remove the default watermark.
No, I guess we could add details about using venices image generation system but I don't think we have provider specific details in docs currently.
Add the new options to character file and generate an image
=> feat: add venice style presets & option to remove watermark (image generation)

.github/workflows/pr.yaml
=> chore: allow scoped pr titles

packages/plugin-evm/src/templates/index.ts, packages/plugin-evm/src/types/index.ts
No specific issue or ticket related.
Low. This PR only adds types for AlienX, and it does not impact existing features or functionalities.
This PR introduces types for AlienX.
Features (non-breaking change which adds functionality).
The reviewer should start by checking the added file for correctness and compatibility with the existing setup.
=> feat: (plugin-evm) add alienx chain

packages/adapter-sqljs/src/types.ts, packages/client-twitter/src/utils.ts
=> chore: fix typos

packages/plugin-story/src/actions/attachTerms.ts, packages/plugin-story/src/actions/getAvailableLicenses.ts, packages/plugin-story/src/actions/getIPDetails.ts, packages/plugin-story/src/actions/licenseIP.ts, packages/plugin-story/src/actions/registerIP.ts, packages/plugin-story/src/index.ts, packages/plugin-story/src/providers/wallet.ts
#1030 
Low
Uniform import packages from `ElizaOS`.
Improvements 
We should unifying the import consistency between `plugin-xxx`.
=> fix: remove `type` when import from `elizaos`

scripts/clean.sh
=> chore: Revert "Clear `/cache/` in `clean.sh` script"

scripts/clean.sh
=> chore: remove cache in core

.env.example, packages/core/src/embedding.ts, packages/core/src/models.ts
Low
There are some scenarios that require the use of the custom OpenAI API endpoint
Support custom OpenAI API endpoint URL using OPENAI_API_URL in env
Added documentation for OPENAI_API_URL environment variable，
OPENAI_API_URL=                 # OpenAI API Endpoint (optional), Default: https://api.openai.com/v1
=> feat: use OPENAI_API_URL from env to support custom OpenAI API endpoint

packages/client-direct/src/index.ts
=> chore: remove unused vars

packages/client-twitter/src/environment.ts
Low
Fixes twitter username validation
=> fix: twitter usernames can start with numbers

docs/community/Streams/12-2024/2024-12-27.md
Documentation updates for community content
Low - This is a documentation-only change adding new community stream notes.
Adds detailed notes from the "What Did You Get Done This Week? 7" community stream, including:
- Full summary of the Twitter Space discussion
- Notable quotes from participants
- Timestamped breakdown of all speakers and topics
- Structured documentation of project updates and announcements
Documentation (adding new community content)
My changes are documentation changes themselves, no additional documentation updates required.
Review the new file at `docs/community/Streams/12-2024/2024-12-27.md`
1. Verify the markdown formatting is correct
2. Check that all timestamps link to the correct YouTube video segments
3. Validate that the summary accurately reflects the stream …
=> docs: Add "What Did You Get Done This Week? #7" notes

scripts/generatecharacter.js
Relates to the PR #1467 as a way to not introduce new changes to the core files of Eliza or Twitter client. This also does not need to be added and could be moved to a tools repo if needed.
Low, but we can consider to add a refactored version to character generation tools in ai16z. Maybe @HowieDuhzit can check out this script & use this in a more effective way.
There is a misconception that Character JSON files do not have dynamic templates. This PR shows how to do this with a script.
Update or generate a new character file with a script
Example more than anything. Does not need to be merged.
=> feat: (example) script to show how to add system prompt and templates to eliza with character file

packages/core/src/types.ts, packages/plugin-node/src/services/transcription.ts
related: https://discord.com/channels/1322160818908954684/1322795334715310230/1323347747759460383
=> feat: Select a transcription provider based on the character settings.

packages/plugin-story/Readme.md
This pr contains readme for plugin-story
=> feat: add docs for story plugin

packages/plugin-zksync-era/src/actions/transfer.ts
=> chore(zksync-era): rm not used imports

agent/package.json, agent/src/index.ts, pnpm-lock.yaml
Low
Adds echochambers to agent
Found it was missing and we need to make it easy
=> fix: add echochambers to agent

packages/adapter-postgres/schema.sql
=> Revert "fix(postgres): Handle vector extension creation properly (#1561)"

README.md
Remove a duplication in the readme
=> refactor: typo in readme

CONTRIBUTING.md, docs/docs/contributing.md
https://github.com/elizaOS/eliza/issues/1838
low
Fixes broken link to FAQ
bug fix (doc update)
I have updated documents
Follow the link ensure it goes back to original FAQ. Original FAQ can be found on branch 
0.1.4-alpha
=> Fix faq link on contributing.md

README.md
=> docs: Add DAO donation ask & dev discord

packages/plugin-node/scripts/postinstall.js, pnpm-lock.yaml
Low
Fixes develop's install-phase
`pnpm i` stopped working:
```
packages/plugin-node postinstall:     throw new ERR_MODULE_NOT_FOUND(
packages/plugin-node postinstall:           ^
packages/plugin-node postinstall: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/runner/work/eliza/eliza/packages/plugin-node/node_modules/@elizaos/core/dist/index.js' imported from /home/runner/work/eliza/eliza/packages/plugin-node/scripts/postinstall.js
```
=> fix: Fix postinstall script

agent/src/index.ts, docs/docs/packages/plugins.md, packages/plugin-tee/package.json, packages/plugin-tee/src/actions/remoteAttestation.rs, packages/plugin-tee/src/index.ts, packages/plugin-tee/src/providers/remoteAttestationProvider.ts, packages/plugin-tee/tsup.config.ts
Closing #1796 in favor of this to avoid conflicts.
TEE Plugin and Adding Remote Attestations to be uploaded to a RA Explorer, so users can easily access an Agent's RA and verify on the proof.t16z.com explorer.
Low
Add more verifiability to the Eliza TEE Agents
- Adds a Remote Attestation Action to the TEE Plugin
- Uploads the RA Quote to t16z Proof Explorer instead of printing out full attestation that is too long for messages or social media posts
Feature addition
Added to plugin-tee doc
Run TEE Simulator based on Eliza in TEE Docs then request a RA Quote
Ask on Discord for RA Quote:
proof . t16z .com
Logs:
=> feat: add remote attestation action

packages/client-direct/src/index.ts
Low
Add an hyperfi endpoint to client-direct
=> feat: hyperfy support

packages/client-discord/src/actions/summarize_conversation.ts
=> chore(client-discord): fix SUMMARIZE prompt 

packages/client-direct/src/api.ts
=> API route update

packages/client-discord/__tests__/discord-client.test.ts, packages/client-discord/package.json, packages/client-discord/vitest.config.ts
Not related to specific issue. Since we are improving packages structure, adding starting tests for discord-client.
Low: Adding tests.
This PR adds starting tests for discord client.
Tests
Navigate to packages/client-discord/__tests__ to see tests
Run pnpm install in root of the project
Navigate to packages/client-discord and run pnpm test
=> test: adding tests for discord-client

docs/docs/packages/plugins.md
There is only processAction in runtime instance. Update them correctly.
=> docs: it is processAction instead of triggerAction

docs/docs/packages/plugins.md
- Fixed a comment-uncomment typo at the end of the Allora Documentation.
- Added a link to more comprehensive documentation + examples at the bottom
- Fixes a comment-uncomment error at the bottom of the Allora Section of plugins.md
- Adds a link to more comprehensive documentation and examples.
Discord: kushwav
=> Update plugins.md -- Allora README Fix

packages/client-telegram/README.md, packages/client-telegram/src/messageManager.ts, packages/client-telegram/src/telegramClient.ts
Low
-Add client-telegram README.me file
-Update comments to messages
-comment await at line 195
Working with telegram bot messages and learning more about elizaos code.
None: Automated tests are acceptable.
=> update: Readme and Comments

agent/src/index.ts
Auto Client not working.
Low
Auto Client didn't work.
Makes auto client work.
bug fix, simple one
=> fix: Auto Client bug

.env.example, packages/plugin-near/README.md, packages/plugin-near/src/environment.ts, packages/plugin-near/src/providers/wallet.ts
Low
makes near plugin use separate `NEAR_SLIPPAGE` env instead of conflicting with `SLIPPAGE` which is used by solana
=> fix: remove near-solana slippage env conflict

packages/plugin-anyone/src/actions/startAnyone.ts, packages/plugin-letzai/src/index.ts, packages/plugin-letzai/tsconfig.json, packages/plugin-letzai/tsup.config.ts, pnpm-lock.yaml
Low
fixes broken `develop` branch
=> fix: letzAi build issues

.env.example
Very low
The .env.example file has become really hectic and this is my attempt to help organize this. We could add having your env variable in the appropriate section to the PR requirements and this should stay more organized.
Separates the .env file into 
- Server & DB Configurations
- Client Configurations
- Model Provider Configurations
- Crypto Plugin Configurations
- Misc Plugin Configurations
An update. It wasn't broken but this is an improvement
None
=> fix: Categorize & Format .env.example

packages/plugin-near/src/providers/wallet.ts, packages/plugin-rabbi-trader/readme.md, packages/plugin-rabbi-trader/src/index.ts, packages/plugin-rabbi-trader/src/wallet.ts, packages/plugin-solana/src/actions/fomo.ts, packages/plugin-solana/src/actions/pumpfun.ts
1. replace RPC_URL to SOLANA_RPC_URL
2. replace RPC_URL to NEAR_RPC_URL
=> Fix: more specific rpc urls

packages/client-discord/src/messages.ts, packages/core/src/knowledge.ts
Reverts elizaOS/Eliza#2048
until further review
=> revert: #2048

packages/plugin-autonome/package.json, packages/plugin-autonome/src/actions/launchAgent.ts, packages/plugin-autonome/tsup.config.ts, pnpm-lock.yaml
syntax issue on autonome plugin and lock file update
=> fix: syntax issue on autonome plugin and lock file update

packages/adapter-postgres/src/__tests__/vector-extension.test.ts, packages/adapter-sqljs/src/index.ts, packages/client-direct/src/api.ts, packages/client-direct/src/index.ts, packages/client-slack/src/actions/chat_with_attachments.ts, packages/client-slack/src/actions/summarize_conversation.ts, packages/client-twitter/src/plugins/SttTtsSpacesPlugin.ts, packages/client-twitter/src/utils.ts, packages/core/src/generation.ts, packages/core/src/ragknowledge.ts, packages/core/src/runtime.ts, packages/plugin-anyone/src/actions/startAnyone.ts, packages/plugin-autonome/src/actions/launchAgent.ts, packages/plugin-avail/src/actions/submitData.ts, packages/plugin-avail/src/actions/transfer.ts, packages/plugin-cosmos/src/shared/helpers/cosmos-assets.ts, packages/plugin-depin/src/actions/sentientai.ts, packages/plugin-goplus/src/lib/GoPlusManage.ts, packages/plugin-irys/src/services/irysService.ts, packages/plugin-letzai/src/index.ts, packages/plugin-movement/src/tests/transfer.test.ts, packages/plugin-nft-generation/src/utils/deployEVMContract.ts, packages/plugin-solana-agentkit/src/actions/createToken.ts, packages/plugin-spheron/src/actions/escrow.ts, packages/plugin-tee-marlin/src/actions/remoteAttestation.ts, pnpm-lock.yaml
Fixing develop, bad PR was merged
=> fix: update lockfile and fix lint findings

packages/plugin-akash/src/actions/closeDeployment.ts, packages/plugin-akash/src/actions/createDeployment.ts, packages/plugin-akash/src/actions/getDeploymentApi.ts, packages/plugin-akash/src/actions/getDeploymentStatus.ts, packages/plugin-akash/src/actions/getGPUPricing.ts, packages/plugin-akash/src/actions/getManifest.ts, packages/plugin-akash/src/actions/getProvidersList.ts, packages/plugin-akash/src/error/error.ts, packages/plugin-akash/src/index.ts, packages/plugin-akash/src/providers/wallet.ts, packages/plugin-akash/src/types.ts, packages/plugin-akash/src/utils/paths.ts
- Fixed ESLint warnings in multiple action files by addressing unused parameters
- Changed `options` to `_options` in affected files to satisfy ESLint rules
- Updated `@ts-ignore` to `@ts-expect-error` with improved documentation
- Maintained existing functionality while fixing linting issues
- `src/actions/closeDeployment.ts`
- `src/actions/createDeployment.ts`
- `src/actions/getDeploymentApi.ts`
- `src/actions/getDeploymentStatus.ts`
- `src/actions/getGPUPricing.ts`
- `src/actions/getManifest.ts`
- `src/actions/getProvidersList.ts`
- `src/types.ts`
- `src/index.ts`
- `src/utils/paths.ts`
- `src/providers/wallet.ts`
- `src/error/error.ts`
- All modified files have been tested to ensure functionality remains intact
- Verified that ESLint passes without errors
- Confirmed that type …
=> fix: eslint-fix-full-test-again

packages/core/src/types.ts
Adding the github to the `Clients` enumeration due to error when trying to run. `Invalid enum value'
Low risk
Since the github client is live 0.1.7 it cant be used when adding to a character because its not part of the Client enum
Adds `GITHUB` to the client enum
=> add github to client enumerations

packages/core/__tests__/uuid.test.ts
Moving uuid.tests.ts to correct tests directory
Low: moving tests
This PR moves tests to new __tests__directory to follow new project structure
Structure of packages
None
=> test: moving uuid.tests to correct __tests__ directory

packages/plugin-coinbase/__tests__/commerce.test.ts, packages/plugin-coinbase/__tests__/utils.test.ts, packages/plugin-coinbase/package.json
https://github.com/elizaOS/eliza/issues/2169
Low: adding tests for plugin
https://github.com/elizaOS/eliza/issues/2169
tests/feature
https://github.com/elizaOS/eliza/issues/2169
None
packages/coinbase-plugin/__tests__
Navigate to desired directory to see tests. Run pnpm install --no-frozen-lockfile in the root, and navigate to desired directory and run pnpm test
=> tests: coinbase plugin - adding tests for coinbase plugin

packages/client-coinbase/src/index.ts, packages/client-direct/package.json, packages/client-direct/src/api.ts, pnpm-lock.yaml
=> feat: add external router path and new tweet generation

packages/core/src/models.ts
https://github.com/elizaOS/eliza/issues/2172
Low.
Replaces the together medium model with a valid one.
Bug fix.
- Try using the medium model of together ai
- Go to https://api.together.ai/models and check for the valid models.
=> Fix: replace invalid toghether ai medium model

packages/plugin-tts/package.json
Low
insert missing langdetect on plugin-tts package.json
Tasks:    87 successful, 87 total
Cached:    48 cached, 87 total
Time:    4m59.249s 
packages/plugin-tss/package.json
pnpm install
pnpm build
git pull origin develop
pnpm install
pnpm build
=> fix: insert missing langdetect on plugin-tts package.json

.github/workflows/greetings.yml
N/A
Low. This is a straightforward renaming change across the project. No core logic or functionality is altered. Risks are limited to potential missed references or inconsistencies in documentation or codebase.
This PR renames all instances of `ai16z` in the project to `elizaOS`. This includes updates to:
- Code variables, constants, and file names.
- Documentation references.
- Comments and inline notes.
Updates (non-breaking change which standardizes naming).
My changes require a change to the project documentation.  
- I have updated documentation files to replace `ai16z` with `elizaOS` where applicable.
1. Begin by reviewing the changes in the main code files where the rename occurs (e.g., `core/main.py`, `settings/config.yaml`).
2. Check updated documentation files.
1. Clone the …
=> chore: rename ai16z -> elizaOS

packages/plugin-whatsapp/__tests__/client.test.ts, packages/plugin-whatsapp/__tests__/handlers/message.handler.test.ts, packages/plugin-whatsapp/__tests__/handlers/webhook.handler.test.ts, packages/plugin-whatsapp/package.json
https://github.com/elizaOS/eliza/issues/2212
Low: adding tests for plugin
This PR adds test coverage for WhatsApp plugin.
The test coverage includes:
Text message sending
Template message sending
Error handling
Webhook verification
Message event handling
Status update handling
Empty event handling
Feature/Test
packages/plugin-whatsapp
Navigate to directory
See tests
Run pnpm install && pnpm test
=> feature: adding tests for whatsapp plugin

docs/community/Streams/01-2025/2025-01-03.md, docs/community/Streams/01-2025/2025-01-10.md
Documentation organization and new content addition
Low - This is a documentation-only change affecting sidebar positioning and adding new content.
1. Changes the sidebar position of "2025-01-03.md" from 8 to 1
2. Adds a new documentation file "2025-01-10.md" with comprehensive meeting notes from the latest community stream
- Improvements (organization of existing documentation)
- Features (addition of new documentation content)
My changes are documentation changes themselves, adding new content and reorganizing existing documentation.
1. Check the sidebar ordering in the documentation to ensure "2025-01-03.md" appears first
2. Review the new "2025-01-10.md" file for:
- Correct formatting
- Accurate content structure
- Working links and timestamps
- Proper markdown syntax
1. Navigate to …
=> docs: Add "What Did You Get Done This Week? #9" notes

CHANGELOG.md
Fix Minor Typo in `CHANGELOG.md`
This pull request fixes a minor typo in the `CHANGELOG.md` file, ensuring better readability and accuracy.
> Abstracts Eliza into a Package to **enble** publishing onto NPM along with plugin system
> Abstracts Eliza into a Package to **enable** publishing onto NPM along with plugin system
- Corrected the typo: `enble` → `enable`.
=> Minor typo in CHANGELOG.md

packages/_examples/plugin/src/plugins/samplePlugin.ts, packages/_examples/plugin/src/services/sampleService.ts
Adding sample service implementation
Low - This PR adds example code that:
- Implements a basic service pattern
- Has no direct impact on production systems
- Contains isolated example code
- Adds a new `SampleService` implementation demonstrating the service pattern for the Eliza platform
- Integrates the service with the sample plugin architecture
- Implements periodic task execution with proper initialization/cleanup
- Provides example of service type extension and runtime integration
- Includes basic logging and error handling patterns
My changes do not require a change to the project documentation as this is an example implementation included in the _examples directory.
1. Review the …
=> feat: Add an example service

packages/client-farcaster/src/actions.ts, packages/client-farcaster/src/interactions.ts, packages/client-farcaster/src/memory.ts, packages/client-farcaster/src/post.ts
=> fix: farcaster memory

.env.example, packages/core/src/generation.ts
Low
Transform any Eliza agents into unstoppable Solidity smart contracts deployed on 10+ blockchains
More flexible than with env and support for eternalai provider can get onchain system prompt
Eliza agents are currently offchain programs. The Eternal AI team is implementing an Onchain Agent Transformer that takes any Eliza agent and turn it into a fully onchain EVM smart contract.
After being tranformed, Eliza agents will live forever on the blockchain. Currently, Eternal AI is supporting 14+ different blockchains.
Because transformed Eliza agents are onchain, they are unstoppable, censorship-resistant, tamper-proof, and permissionless accessible by anyone.
Reviewers start from .env.example
Run pnpm start …
=> feat: Onchain Agent Transformer - transform any Eliza agents into unstoppable Solidity smart contracts deployed on 10+ blockchains

packages/client-github/README.md
=> Fix github client README.md

docs/README_FR.md
Finishing the translation and fixing a few typos
=> docs: Update README_FR.md

packages/plugin-tee/src/actions/remoteAttestation.ts
Fix the Remote Attestation Action to prevent hallucination in Twitter and Discord clients when publishing the Remote Attestation to the t16z proof explorer
=> fix: esure RA Action reply does not hallucinate

agent/package.json, agent/src/index.ts, packages/plugin-tron/README.md, packages/plugin-tron/package.json, packages/plugin-tron/src/actions/bridge.ts, packages/plugin-tron/src/actions/swap.ts, packages/plugin-tron/src/templates/index.ts, packages/plugin-tron/src/test/wallet.test.ts, pnpm-lock.yaml
Relates to
#2275
Risks
Low: this PR including only update for tests and examples
Background
Update the package name
Improve the prompt template
Update the examples
Update README
Bug fixes and Improvements
to fix failed tests
Documentation changes needed?
Testing
Run the following tests:
pnpm run smokeTests
pnpm run integrationTests
=> sequel to pr/2275

packages/plugin-tee-log/src/services/teeLogManager.ts, packages/plugin-tee-log/src/services/teeLogService.ts
#2405 
Medium: not sure if the condition causing the bug was made on purpose
- Fix the error about TEE configuration being invalid when TEE log is enabled
- Fix error telling 'Cannot open database because the directory does not exist'
- Fix error telling 'Invalid TEE_MODE: undefined. Must be one of: LOCAL, DOCKER, PRODUCTION' at start up
Bug fix
Starting an agent with tee-log enabled using TDX_DSSTACK
As a developer, 
- configure the agent to use tee-log with TDX_DSSTACK by editing the .env file as follows
```env
TEE_MODE=LOCAL
WALLET_SECRET_SALT=your_wallet_secret_salt             
ENABLE_TEE_LOG=true 
```
- start TEE simulator as described in https://elizaos.github.io/eliza/docs/advanced/eliza-in-tee/#environment-setup …
=> fix TEE Log plugin errors at agent startup

agent/src/index.ts
=> fix: missing import 

agent/src/index.ts, packages/core/src/defaultCharacter.ts
chore: set openai as default character's provider
=> chore: set openai as default character's provider

i18n/readme/README_DE.md
=> chore: edited the link to the banner

packages/plugin-depin/src/actions/sentientai.ts
=> fix(plugin-depin): sentientAI description

package.json
previous pr was clobbered.  fixes #2684
=> fix debug targets to show elizalogger debug messages

packages/core/src/types.ts, pnpm-lock.yaml
fixes missing `};` before simsai profile inteface
=> chore: fix types syntax issue

packages/client-twitter/src/post.ts
related: https://github.com/elizaOS/eliza/issues/2423
The issue occurred due to a JSON.parse error, which caused the raw text to be used as output:
https://github.com/elizaOS/eliza/blob/ff12944138dae4c1437cdf3e1ee24980a4e0fc8f/packages/client-twitter/src/post.ts#L658
Solution Implemented in This PR
- Replaced the existing JSON parsing logic with the `parseJSONObjectFromText` function which provides better parsing capabilities compared to JSON.parse.
- Found that line breaks in the response were also causing parsing errors, so this PR removes line breaks from the response to ensure correct parsing.
=> fix: Unexpected JSON Metadata in Twitter Bot Replies

packages/client-twitter/src/plugins/SttTtsSpacesPlugin.ts
Just remove one line logger since it may potentially cause the app to crash:
https://github.com/elizaOS/eliza/issues/2206#issuecomment-2585840351
https://github.com/elizaOS/eliza/issues/2206#issuecomment-2607519795
=> Remove the log as it may potentially cause the app to crash

agent/package.json, agent/src/index.ts, packages/plugin-holdstation/.npmignore, packages/plugin-holdstation/README.md, packages/plugin-holdstation/eslint.config.mjs, packages/plugin-holdstation/package.json, packages/plugin-holdstation/src/actions/swapAction.ts, packages/plugin-holdstation/src/constants/index.ts, packages/plugin-holdstation/src/environment.ts, packages/plugin-holdstation/src/hooks/index.ts, packages/plugin-holdstation/src/hooks/useGetAccount.ts, packages/plugin-holdstation/src/hooks/useGetWalletClient.ts, packages/plugin-holdstation/src/index.ts, packages/plugin-holdstation/src/providers/walletProvider.ts, packages/plugin-holdstation/src/templates/index.ts, packages/plugin-holdstation/src/templates/swapTemplate.ts, packages/plugin-holdstation/src/types/index.ts, packages/plugin-holdstation/tsconfig.json, packages/plugin-holdstation/tsup.config.ts, pnpm-lock.yaml
No specific issue or ticket is linked to this PR.
Low: This PR is for create a plugin that is not effecting the core functionality of the application.
This PR creates a plugin that allows users integrate with Holdstation Wallet on now on Zksync Era and Berachain coming soon. including the following features:
- Token swapping on Hold.so (Holdstation swap)
Review the new plugin from src/index.ts, actions/_ providers/_
Please refer to the README.md for detailed testing steps.
=> feat(plugin-holdstation): add plugin holdstation swap

packages/plugin-ton/src/providers/wallet.ts, pnpm-lock.yaml
fixes minor issue with `plugin-ton`
=> fix: ton plugin build issue

.env.example, agent/package.json, agent/src/index.ts, packages/plugin-imgflip/.npmignore, packages/plugin-imgflip/README.md, packages/plugin-imgflip/eslint.config.mjs, packages/plugin-imgflip/package.json, packages/plugin-imgflip/src/actions/generate-meme.ts, packages/plugin-imgflip/src/actions/index.ts, packages/plugin-imgflip/src/index.ts, packages/plugin-imgflip/tsconfig.json, packages/plugin-imgflip/tsup.config.ts, pnpm-lock.yaml
Adding a new feature
Low
This pull request adds the imgflip plugin. This plugin provides a GENERATE_MEME action that can be used to generate memes using the imgflip.com API based on the user's message.
I am working on an agent that generates meme's based on different inputs. I think this is a cool feature that others can use too.
You can find all the related code in `packages/plugin-imgflip`
1. Register at imgflip.com
2. Set the `IMGFLIP_USERNAME` and `IMGFLIP_PASSWORD` environment variables in `.env`
3. Add the plugin to an agent
4. Send a message to the agent asking to generate a meme based on some topic. Ex. "Generame a meme for debugging a race condition in a …
=> feat(new-plugin): adding Imgflip plugin for generating memes using the imgflip.com API

.github/workflows/minimal-merge-queue.yml
merge queue
shouldn't be any, added simple workflow
resolves the 'invisible check' that was holding up the merge queue
improvement
testing should happen right when i submit this pr lol
=> feat: minimal workflow to resolve ephemeral check

packages/plugin-coinbase/src/plugins/tokenContract.ts
=> chore(plugin-coinbase): Update tokenContract.ts

packages/core/src/runtime.ts
Fixed a bug.
Discord: jay.is.more
=> fix: topics formatting bug at composeState

packages/plugin-0g/__tests__/actions/upload.test.ts, packages/plugin-0g/package.json, packages/plugin-0g/vitest.config.ts
https://github.com/elizaOS/eliza/issues/2804
Low: adding tests
https://github.com/elizaOS/eliza/issues/2804
Features/tests
https://github.com/elizaOS/eliza/issues/2804
None
=> chore: plugin-0g test configuration and test coverage

packages/plugin-0x/__tests__/actions/getIndicativePrice.test.ts, packages/plugin-0x/package.json, packages/plugin-0x/vitest.config.ts
https://github.com/elizaOS/eliza/issues/2806
Low: adding test config and coverage
https://github.com/elizaOS/eliza/issues/2806
Features/tests
https://github.com/elizaOS/eliza/issues/2806
None
=> test: plugin-0x test configuration and coverage

.gitignore, packages/plugin-akash/src/index.ts
- Updated splash screen design for Akash plugin
- Enhanced visual presentation of the interface
- Improved user experience with better layout
- Modified: `packages/plugin-akash/src/index.ts`
- Updated splash screen components
- Aligned with ElizaOS design guidelines
- Verified splash screen renders correctly
- Tested responsive behavior
=> fix: akash splash 

packages/client-discord/readme.md
Adding basic instructions. Will look to expand this with some common issues and solutions as I come across them.
LOW
Next to nil. It's just documentation.
Just adds some basic instructions that fits the conventions of all the other client plugins, but is lacking in this probably one of the more popular clients.
Just documentation.
To improve usability for new devs
These are the documentation changes
I read it. I was able to read it.
Read it. If it is readable, it's good.
=> docs: Create client-discord readme.md

packages/client-telegram/README.md
Just corrected some formatting issues, and added details about configuration of advanced features via character.json files.
n/a
None.. just updating the readme.
updates some documentation.
=> docs: Update client-telegram README.md

docs/docs/advanced/infrastructure.md
None
Low, its documentation 
Updates the documentation to reflect `embed` moving from `runtime` to its own function
Documentation
So the documentation is up to date/works
This is a documentation change 
Look at the diff
rubinovitz
=> docs: update embedding function

packages/plugin-tts/src/index.ts
Fixed non-critical issues highlighted by strict biome linting:
- Updated imports to use `node:` prefix
- Changed bracket notation to dot notation for object access
- Added explicit type for `target_voice`
- Simplified environment variable assignment
- Improved type definition for `_options` parameter
=> fix: plugin-tts 

packages/plugin-twitter/src/actions/post.ts, packages/plugin-twitter/src/types.ts
- Simplified tweet posting logic by removing redundant `else` clauses
- Renamed unused parameters with underscore prefix
- Changed type annotation from `any` to `unknown` in `isTweetContent` function
- No functional changes
- Enhanced code maintainability
- Improved type safety in Twitter content validation
=> fix: plugin-twitter

packages/plugin-video-generation/src/index.ts
- Changed `any` type to `Record<string, unknown>` for options parameter in handler
- Added proper type definitions for ZerionProvider interface
- Removed `any` type usage in provider implementation
- Updated fs import to use Node.js protocol (`node:fs`)
- Changed string concatenation to template literals for error messages
- Added type guard for PortfolioData vs PositionData differentiation
- All changes maintain backward compatibility
- No functional changes to core logic
- Improved type safety without breaking changes
- Better error message formatting
- No test changes required
- Existing functionality preserved
- Type safety improvements are compile-time only
=> fix: plugin-video-generation Fixed multiple non criticla issues.

packages/plugin-zerion/src/actions/getWalletPortfolio/index.ts, packages/plugin-zerion/src/actions/getWalletPositions/index.ts, packages/plugin-zerion/src/providers/index.ts
- Added proper type definitions for ZerionProvider interface
- Removed 'any' type usage in provider implementation
- Added type guard for PortfolioData vs PositionData differentiation
- Improved type safety in data handling without changing core functionality
- Maintained existing API response structure and error handling
=> fix: plugin-zerion 

packages/plugin-3d-generation/__tests__/actions/generate3d.test.ts, packages/plugin-3d-generation/package.json, packages/plugin-3d-generation/vitest.config.ts
https://github.com/elizaOS/eliza/issues/2849
Low: test config and test coverage
https://github.com/elizaOS/eliza/issues/2849
Features/tests
https://github.com/elizaOS/eliza/issues/2849
None
=> chore(add-tests): plugin 3d generation: test config and test coverage

packages/plugin-apro/README.MD, packages/plugin-apro/package.json, packages/plugin-apro/src/actions/attpsPriceQuery.ts, packages/plugin-apro/src/actions/createAndRegisterAgent.ts, packages/plugin-apro/src/actions/priceQuery.ts, packages/plugin-apro/src/actions/verifyData.ts, packages/plugin-apro/src/index.ts, packages/plugin-apro/src/templates.ts, packages/plugin-apro/src/types.ts, packages/plugin-apro/tsconfig.json, packages/plugin-apro/tsup.config.ts
#2793
Low. This change only merge the new plugin from APRO.
Just merge the new plugin: plugin-apro
This PR adds support for Eliza to interact with apro, enabling users to:
- Query current price of coin, for example: BTC/USD.
- Create and register an agent with APRO. User must provide agent settings.
- Verify data with APRO. User must provide data to verify.
Spin up an agent with the apro plugin.
Follow the testing steps outlined in the README.md file of this plugin.
Please refer to the README.md file in this plugin for detailed testing instructions.
=> feat(new-plugin): support apro plugin

packages/client-discord/src/attachments.ts, packages/client-discord/src/utils.ts, packages/client-slack/src/attachments.ts, packages/client-twitter/src/post.ts, packages/plugin-node/src/services/browser.ts
just adding null check so that it wont get error 
`parsedResponse?.title`
=> fix: null check

packages/core/src/logger.ts
Low
Fix json output when it's set to "false"
=> fix: LOG_JSON_FORMAT env var setting

packages/plugin-abstract/package.json, pnpm-lock.yaml
Low
removes build warning
Sick of seeing it
=> fix: fix abstract package.json

.env.example, client/src/lib/api.ts, client/vite.config.ts
related: https://github.com/elizaOS/eliza/issues/2726
=> fix: client server port

packages/plugin-intiface/intiface-engine/README.md, packages/plugin-mind-network/README.md, packages/plugin-mind-network/src/actions/submitVoteAction.ts, packages/plugin-multiversx/src/actions/createToken.ts, packages/plugin-opacity/README.md
1. **`README.md`** in `intiface-engine` package:
- Corrected "pacakges" to "packages".
2. **`README.md`** in `plugin-mind-network` package:
- Fixed "Depedency" to "Dependency".
- Corrected "collabration" to "collaboration".
3. **`submitVoteAction.ts`**:
- Fixed "sumitted" to "submitted".
4. **`createToken.ts`**:
- Fixed "Succesfully" to "Successfully".
5. **`README.md`** in `plugin-opacity` package:
- Corrected "accomdate" to "accommodate".
Low. Changes are limited to spelling corrections and do not affect functional logic or implementation.
=> chore: fix spell errors

scripts/update-package-access.js
This ensures all packages that are not marked private are properly scoped and can be published to npm registry.
=> feat: add public access to packages.

packages/plugin-near/src/actions/swap.ts, packages/plugin-near/src/actions/transfer.ts, packages/plugin-near/src/providers/wallet.ts
=> fix: plugin-near

packages/client-twitter/src/post.ts
related: https://github.com/elizaOS/eliza/issues/2927
=> fix: {{maxTweetLength}} doesn't work in tweet post template 

packages/client-twitter/src/interactions.ts, packages/client-twitter/src/utils.ts
related: https://github.com/elizaOS/eliza/issues/2891
result:
=> fix: ensure action tweet replies to agent's initial tweet

packages/plugin-intiface/src/index.ts, packages/plugin-intiface/src/utils.ts
=> fix(lint): plugin-intiface

packages/plugin-iq6900/src/functions/bringIQData.ts
=> fix(lint): plugin-iq6900

packages/plugin-irys/src/services/irysService_bk.ts, packages/plugin-lens-network/src/actions/transfer.ts
=> fix: plugin-irys

packages/plugin-injective/src/action/base.ts
Fixed all the issues but 2 any that mess up all the other files.
=> fix(lint): plugin-injective

packages/plugin-initia/src/actions/transfer.ts, packages/plugin-initia/src/providers/wallet.ts
=> fix: plugin-initia 

packages/plugin-imgflip/src/actions/generate-meme.ts
=> fix(lint): plugin-imgflip

packages/plugin-arbitrage/__tests__/actions/arbitrageAction.test.ts, packages/plugin-arbitrage/__tests__/core/Arbitrage.test.ts, packages/plugin-arbitrage/__tests__/index.test.ts, packages/plugin-arbitrage/__tests__/services/ArbitrageService.test.ts, packages/plugin-arbitrage/__tests__/setup.ts, packages/plugin-arbitrage/__tests__/utils/TestMarket.ts, packages/plugin-arbitrage/package.json, packages/plugin-arbitrage/vitest.config.ts
https://github.com/elizaOS/eliza/issues/2981
Low: adding tests
https://github.com/elizaOS/eliza/issues/2981
feature/tests
https://github.com/elizaOS/eliza/issues/2981
None
=> feat(chore): plugin-arbitrage test config and coverage

packages/plugin-apro/__tests__/actions/attpsPriceQuery.test.ts, packages/plugin-apro/__tests__/actions/createAndRegisterAgent.test.ts, packages/plugin-apro/__tests__/actions/verifyData.test.ts, packages/plugin-apro/__tests__/index.test.ts, packages/plugin-apro/vitest.config.ts
https://github.com/elizaOS/eliza/issues/2979
Low: adding tests
https://github.com/elizaOS/eliza/issues/2979
Featurestests
https://github.com/elizaOS/eliza/issues/2979
=> feat(chore): plugin-apro -> test coverage and test config

.env.example
Issue: OpenAI embeddings error when running character without OpenAI API key configured in .env file. 
https://github.com/elizaOS/eliza/issues/3001#issuecomment-2622857063
Low 
change .env example OpenAI embedding configuration to DEFAULT 
Fix OpenAI embedding API error when loading character without OpenAI API key. 
=> fix: OpenAI embedding issue

packages/plugin-node/src/services/transcription.ts
=> fix: deepgram transcription null check

packages/core/src/parsing.ts
related: https://github.com/elizaOS/eliza/issues/2907
This PR also includes changes from [#3014](https://github.com/elizaOS/eliza/pull/3014) due to an accidental merge.
=> fix: llava model parsing Issue 

packages/core/src/generation.ts
=> fix: handle unsupported image provider

packages/plugin-sui/package.json, packages/plugin-sui/src/actions/swap.ts, packages/plugin-sui/src/actions/transfer.ts, packages/plugin-sui/src/index.ts, packages/plugin-sui/src/providers/wallet.ts, packages/plugin-sui/src/services/sui.ts, packages/plugin-sui/src/tokens.ts, packages/plugin-sui/src/utils.ts
Mainly changed list: 
- add basic sui service support some tools
- add swap action use Aggregator cetus
- other fix
=> feat: use Aggregator swap sui tokens

packages/plugin-cronos/biome.json, packages/plugin-cronos/package.json, packages/plugin-cronos/src/actions/balance.ts, packages/plugin-cronos/src/actions/transfer.ts, packages/plugin-cronos/src/providers/wallet.ts
=> fix: plugin-cronos lint

packages/plugin-multiversx/src/actions/createToken.ts, packages/plugin-multiversx/src/actions/swap.ts, packages/plugin-multiversx/src/actions/transfer.ts, packages/plugin-multiversx/src/environment.ts
No need for an issues I guess but can create one if necessary
That underdevelopment pull request that would import this file will have to adapt their pull requests
fixing a typo in a file name
file name changed and the 3 imports using it
Fixe formatting in the new file
=> fix: Rename file with typo in MVX plugin

packages/plugin-avalanche/biome.json, packages/plugin-avalanche/package.json, packages/plugin-avalanche/src/actions/tokenMillCreate.ts, packages/plugin-avalanche/src/actions/transfer.ts, packages/plugin-avalanche/src/actions/yakStrategy.ts, packages/plugin-avalanche/src/actions/yakSwap.ts, packages/plugin-avalanche/src/providers/wallet.ts, packages/plugin-avalanche/src/utils/tokenMill.ts
=> fix: plugin-avalanche lint

docs/docs/packages/adapters.md, docs/docs/packages/clients.md, docs/docs/packages/plugins.md
Navigate links to specified resources
Documentation links
=> docs(packages/adapters): navigate section links

packages/plugin-email-automation/src/services/emailAutomationService.ts
the build was failing due to a type issue for this plugin-email-automation
This PR aims to resolve the build error
=> fix: fixed build error in plugin-email-automation 

packages/plugin-autonome/biome.json, packages/plugin-autonome/package.json, packages/plugin-autonome/src/actions/launchAgent.ts, packages/plugin-autonome/src/index.ts
=> fix: plugin-autonome-v1

packages/plugin-arthera/biome.json, packages/plugin-arthera/package.json, packages/plugin-arthera/src/actions/transfer.ts, packages/plugin-arthera/src/providers/wallet.ts
=> fix: plugin-arthera-biome

packages/plugin-aptos/biome.json, packages/plugin-aptos/package.json, packages/plugin-aptos/src/actions/transfer.ts, packages/plugin-aptos/src/providers/wallet.ts
Fixed all the issues and added Biome.
=> fix: plugin-aptos

packages/plugin-chainbase/package.json
This PR fix a Chainbase plugin problem, the missing comma stops the pnpm install
I just added the missing comma
akuma9640
-->
=> fix:chore(plugin-chainbase): add missing comma in package.json

packages/client-twitter/src/utils.ts
Adding proper image URL handling for Twitter client memory system
Low
- Memory storage: Ensures consistent image URL handling in both directions
- Data consistency: Maintains image context through conversation threads
This PR ensures proper handling of image URLs in the Twitter client's memory system:
1. Inbound (interactions.ts - already handled):
- Processes incoming tweet images into memory
- Stores image URLs from received tweets
- Maintains image context in conversation threads
2. Outbound (utils.ts - our changes):
- Ensures image URLs are stored in memories for tweets we send
- Maintains image context for bot's own tweets
- Preserves image data for future reference
Improvement (enhancing existing image handling functionality)
My changes do not require a change to the project …
=> feat: save imageUrls for outbound tweets/messages

packages/core/src/generation.ts
Response from Venice model.
```
<think>
args
</think>
```
Low
Some Venice models as deepseek return a <think></think> tag that can be removed from generated text.
Improvements
packages/core/src/generation.ts
=> fix: think tag from venice

.env.example, .gitignore, packages/plugin-ton/src/actions/getCollectionData.ts, packages/plugin-ton/src/actions/mintNFT.ts, packages/plugin-ton/src/actions/transfer.ts, packages/plugin-ton/src/actions/transferNFT.ts, packages/plugin-ton/src/actions/updateNFTMetadata.ts, packages/plugin-ton/src/util.ts, packages/plugin-ton/src/utils/NFTCollection.ts, packages/plugin-ton/src/utils/NFTItem.ts, packages/plugin-ton/src/utils/util.ts
https://github.com/elizaOS/eliza/issues/2962
TON Plugin
- Action for NFT collection creation
- Action for NFT item creation
- Action for NFT metadata update
- Action for NFT transfer
`.env.example` updated with explanations
=> feat: TON Plugin: NFT collection, item creation, metadata change and transfer actions

docs/community/Discord/development/dev-vc/chat_2024-11-17.md
CONTRIBUTION.MD - CONTRIBUTING.md
=> docs: rename chat_2024-11-17.md

.env.example, packages/client-twitter/src/environment.ts, packages/client-twitter/src/post.ts
Introduced ENABLE_TWITTER_POST_GENERATION config to control automatic tweet generation.
=> feat: Add configuration for enabling/disabling Twitter post generation

packages/plugin-conflux/__tests__/actions/bridgeTransfer.test.ts, packages/plugin-conflux/__tests__/actions/transfer.test.ts, packages/plugin-conflux/__tests__/setup.ts, packages/plugin-conflux/package.json, packages/plugin-conflux/vitest.config.ts
https://github.com/elizaOS/eliza/issues/3246
Low: test config and coverage
https://github.com/elizaOS/eliza/issues/3246
features/tests
https://github.com/elizaOS/eliza/issues/3246
None
=> feat (chore) plugin conflux: test config and coverage

packages/client-discord/src/messages.ts
Low
When actions had the suppressInitialMessage flag, it would not work on other clients.
Added ability back so actions can properly suppress the initial response if enabled.
Implement changes, trigger an action and watch for suppression of initial message.
=> fix: discord - add actions suppress action ability.

packages/client-telegram/src/messageManager.ts
Low
When actions had the suppressInitialMessage flag, it would not work on other clients.
Added ability back so actions can properly suppress the initial response if enabled.
Implement changes, trigger an action and watch for suppression of initial message.
=> fix: telegram- add actions suppress action ability.

packages/client-telegram/src/telegramClient.ts
allow plugins to interact w messangerManager to post on tg
this allow to call the tg bot and generate messages
twitter client has a similar behaviour where you can access to post tweets
=> feat: allow plugins to interact w messangerManager to post on telegram

agent/.gitignore, agent/src/defaultCharacter.ts
=> fix: fix default character

package.json, packages/cli/src/index.ts, tsconfig.json
=> fix: cli build and init command

.env.example
- Connected to merged plugin implementation: [elizaos-plugins/registry#43](https://github.com/elizaos-plugins/registry/pull/43)
- Requires: Environment variable configurations for the plugin system merged in  [elizaos-plugins/registry#43](https://github.com/elizaos-plugins/registry/pull/43)
Low: This PR only adds environment variable declarations without modifying core logic
Potential impact areas:
- Plugin initialization (if variables are missing in runtime environments)
Adds required environment variables (DATA_API_KEY, DATA_AUTH_TOKEN) for the plugin system implemented in [elizaos-plugins/registry#43](https://github.com/elizaos-plugins/registry/pull/43)
Improvements (supplemental configuration for existing feature)
=> chore: commit d.a.t.a env configurations

README.md
https://github.com/elizaOS/eliza/issues/3387
Low
Update readme to clarify eliza-starter is separate repo with its own readme and instructions.
Documentation update
The change is a doc update
N/A
-->
=> Update readme to clarify difference between eliza-starter and eliza repos

i18n/readme/README_KOR.md
closes #3479 
Low – This PR only updates documentation and does not affect any functionality or code execution.
- Fixes incorrect image paths in the Korean documentation.
- Ensures that images are properly displayed by updating the file paths.
Bug fix (non-breaking change that fixes an issue in documentation)
- My changes require a change to the project documentation.
- I have updated the affected documentation accordingly.
- Review the file i18n/readme/README_KOR.md
- Check the corrected image path and verify that they match the actual file locations.
1. Open i18n/readme/README_KOR.md in a markdown viewer.
2. Ensure that the images now load correctly.
gkfyr
=> docs: fix incorrect image paths in Korean documentation

packages/docs/package.json
The client is currently broken, and I'm facing this issue:
Upgrading React in the docs resolves the issue
=> fix: client UI

docs/docs/guides/remote-deployment.md
Documentation
Adds a new guide for deployment to a remote server
Low, just adds a markdown file
Adds a single file to docs/docs/guides
Docs only
Very Regular FAQ is how to deploy
N/A
Look at the content, see if it's ok
@bealers
=> docs: New remote deployment guide

packages/core/src/generation.ts
This pull request includes a change to the `generateText` function in the `packages/core/src/generation.ts` file to improve the handling of responses from the Ollama model.
* [`packages/core/src/generation.ts`](diffhunk://#diff-b68254579d690900478f82405c1f5e9eab387a8637ffddaacbfadb2ca31369daL956-R956): The response from the Ollama model is now processed to remove any `<think>` tags and their content before being assigned to the `response` variable.
=> chore: Trim <think> block from Ollama response

.env.example, packages/core/src/types.ts
Low
This PR integrates the [`plugin-nkn`](https://github.com/nknorg/eliza-plugin-nkn) plugin into the `Eliza` project. It includes the following changes:
- **Modifies the `.env` file** to add new environment variables for NKN configuration.
- **Updates `ServiceType`** to include `NKN_CLIENT_SERVICE`.
My changes do not require test
=> feat: Modify the configuration for the plugin-nkn

README.md
This commit improves the README.md file by:
- Adding detailed system requirements section
- Including project structure overview
- Adding comprehensive contribution guidelines
- Improving documentation organization
- Making the project more accessible for new contributors
=> docs: enhance README with detailed requirements and contribution guidelines

i18n/readme/README_AR.md, i18n/readme/README_CN.md, i18n/readme/README_DE.md, i18n/readme/README_ES.md, i18n/readme/README_FA.md, i18n/readme/README_FR.md, i18n/readme/README_GR.md, i18n/readme/README_HE.md, i18n/readme/README_HU.md, i18n/readme/README_IT.md, i18n/readme/README_JA.md, i18n/readme/README_KOR.md, i18n/readme/README_NL.md, i18n/readme/README_PL.md, i18n/readme/README_PTBR.md, i18n/readme/README_RO.md, i18n/readme/README_RS.md, i18n/readme/README_RU.md, i18n/readme/README_TG.md, i18n/readme/README_TH.md, i18n/readme/README_TR.md, i18n/readme/README_UA.md, i18n/readme/README_VI.md
Fixed broken img links in README.md of i18n for all languages
=> docs: Fix broken links

agent/src/index.ts
Low
Support GAIANET API KEY
Features 
=> feat: gaianet support set api key

packages/plugin-discord/src/actions/chatWithAttachments.ts, packages/plugin-discord/src/actions/dm.ts, packages/plugin-discord/src/actions/joinvoice.ts, packages/plugin-discord/src/actions/leavevoice.ts, packages/plugin-discord/src/actions/summarizeConversation.ts, packages/plugin-discord/src/index.ts, packages/plugin-discord/src/messages.ts, packages/plugin-node/src/services/video.ts
This PR fixes the Discord actions and makes all of them work, except for the download media plugin. I couldn't get `ytdl` to work on my end, so I have temporarily commented out this plugin for now.
@odilitime would check the ytdl issue with another pr
=> fix: discord actions

agent/src/index.ts
https://github.com/elizaOS/eliza/issues/3610
Low
Fixes plugin importing for plugins from plugin registry: https://github.com/elizaos-plugins/registry
Tested it by making our plugin work
See the related issue
=> FIX: importing plugins from registry

packages/agent/package.json, packages/agent/src/plugins.test.ts, packages/plugin-elevenlabs/src/index.ts
Enhance the plugin test logger by improving color formatting for better readability. Also, ensure the test process properly terminates after execution.
=> feat: improve test plugin

.github/pull_request_template.md
Update discord link to elizaOS
=> update discord link

packages/plugin-bootstrap/src/providers/facts.ts
For some reason this was commented out. It looks like a great feature to include. Fetching relevant facts in addition to most recent facts is a good idea. I un-commented the code and renamed _embedding to embedding.
=> feat: Enable fetching relevant facts in the facts provider.

docs/docs/packages/plugins.md
Fixed a formatting issue in the `docs/packages/plugin.md` to improve readability.
=> docs: Fix plugins.md formatting

packages/core/src/runtime.ts
=> fix: set up dimension before starting client

docs/docs/contributing.md, docs/docs/core/characterfile.md
This pull request addresses minor typographical errors in the documentation files. 
Specifically, it corrects the wording in the contributing guidelines and ensures consistency in the character file format.
**Changes made:**
- Updated the term `updates or improvements` to maintain clarity in the contributing guidelines.
- Corrected the formatting of the `name` field in the character file to ensure proper JSON structure.
These changes enhance the readability and accuracy of the documentation, making it easier for contributors to understand the guidelines and the character file structure.
=> Fix Typographical Errors in Documentation

packages/cli/index.js
fixes issue introduced in #3660
=> fix: fix CLI install

packages/plugin-twitter/src/base.ts, packages/plugin-twitter/src/interactions.ts
The Twitter app fails to start due to this line: https://github.com/elizaOS/eliza/blob/5c1b5899cfb3bb5ec78ffecf8530a9ba19f29a35/packages/core/src/runtime.ts#L936
Fix:
This PR prevents the agent from connecting to itself, resolving the issue.
=> fix: twitter crash issue

packages/core/src/runtime.ts, packages/core/src/types.ts, packages/plugin-discord/src/actions/voiceJoin.ts, packages/plugin-discord/src/actions/voiceLeave.ts, packages/plugin-discord/src/messages.ts
Currently, the actions in Discord are broken. This PR aims to fix the voiceJoin and voiceLeave actions.
The voiceJoin and voiceLeave actions were not working due to minor typos and undefined variables. This PR fixes these issues. Additionally, I used voiceManager to handle voice join/leave actions, allowing us to track the current connection status  in the manager: https://github.com/elizaOS/eliza/blob/5f154c305fac51743cc32ee9fea798701c752bb8/packages/plugin-discord/src/voice.ts#L297
=> fix: discord voiceJoin/voiceLeave action

packages/agent/src/server/helper.ts, packages/agent/src/swarm/settings.ts, packages/core/src/actions/roles.ts, packages/core/src/bootstrap.ts, packages/core/src/generation.ts, packages/core/src/providers/roles.ts, packages/core/src/runtime.ts, packages/core/src/types.ts, packages/plugin-discord/src/index.ts, packages/plugin-discord/src/messages.ts, packages/plugin-telegram/src/messageManager.ts
This PR contains several improvements to the application:
Reduces response latency by optimizing the shouldRespondHandler
Adds debouncing to the message receive handler to prevent excessive processing
Refactors name and username fields to be stored in metadata[source]
Improves code formatting for better readability
Fixes a bug in role state initialization where the owner wasn't properly set as owner, and corrects role state ID mapping
=> feat: Performance Improvements and Metadata Refactoring

packages/core/src/types.ts
Character config in file ts
medium
update knowledge in type Character
=> fix: character knowledge add directory

packages/cli/index.js
Low
- makes install/add on par with remove, not requiring `@elizaos-plugins/` prefix
- skips pnpm adding to agent's package.json if it's already a dependency
=> feat: CLI install improvements

agent/package.json, agent/src/index.ts, packages/core/src/settings.ts, packages/core/src/types.ts, pnpm-lock.yaml
Low
- convert character to json5 (allows comments and new lines, more human friendly format)
- better error handling of plugins loading
- logging updates
=> feat: better plugin loading error handling / json5 support for character file

packages/agent/src/server/api/agent.ts
1. `GET /`
- Purpose: List all available agents
- Returns: List of all agents in the system
2. `GET /:agentId`
- Purpose: Get details of a specific agent
- Returns: Agent information including ID, enabled status, and character details
3. `POST /`
- Purpose: Create a new agent
- Accepts: characterPath, characterJson, or remotePath
- Returns: Created agent details with status
4. `PUT /:agentId`
- Purpose: Update an existing agent
- Accepts: Updated character configuration
- Returns: Updated agent details
5. `DELETE /:agentId`
- Purpose: Delete/remove an agent
- Returns: 204 on success
6. `PATCH /:agentId/status`
- Purpose: Update agent's operational status
- Accepts: status ('active' or 'inactive')
- Returns: Updated agent status and details
7. `POST /:agentId/messages`
- Purpose: Send a …
=> update agent endpoints

packages/agent/src/server/api/agent.ts, packages/agent/src/server/index.ts, packages/cli/src/commands/agent.ts, packages/cli/src/commands/character.ts, packages/cli/src/utils/helpers.ts, packages/client/tsconfig.node.tsbuildinfo, packages/core/src/database.ts, packages/core/src/runtime.ts, packages/core/src/types.ts, packages/plugin-sql/src/base.ts
=> fix server apis and server

packages/agent/src/index.ts, packages/client/tsconfig.node.tsbuildinfo, packages/plugin-sql/drizzle/migrations/20250302132443_init.sql, packages/plugin-sql/drizzle/migrations/meta/20250302132443_snapshot.json, packages/plugin-sql/src/base.ts, packages/plugin-sql/src/schema/cache.ts, packages/plugin-sql/src/schema/component.ts, packages/plugin-sql/src/schema/entity.ts, packages/plugin-sql/src/schema/goal.ts, packages/plugin-sql/src/schema/memory.ts, packages/plugin-sql/src/schema/participant.ts, packages/plugin-sql/src/schema/relationship.ts, packages/plugin-sql/src/schema/room.ts, packages/plugin-sql/src/schema/worldTable.ts
fixes delete issues for agents
=> fix-delete issues

packages/plugin-sql/src/base.ts, packages/plugin-sql/src/pg/adapter.ts, packages/plugin-sql/src/pg/manager.ts
This PR addresses issues with PostgreSQL connection handling by implementing proper connection acquisition and release patterns. The previous implementation was using the entire connection pool object directly, rather than acquiring individual client connections for operations, which could lead to connection leaks and eventual pool exhaustion.
- Modified PostgresConnectionManager to provide methods for proper client connection handling
- Implemented a proper connection lifecycle in PgDatabaseAdapter.withDatabase() method to:
- Acquire a dedicated client connection from the pool
- Execute the database operation
- Release the connection back to the pool when finished (even in error scenarios)
- Removed debugging code (console.trace)
- Ensured connections are properly released in all cases, …
=> fix: properly acquire and release connection

packages/core/src/generation.ts, packages/core/src/knowledge.ts, packages/core/src/memory.ts, packages/core/src/runtime.ts, packages/core/src/types.ts, pnpm-lock.yaml, tests/testLibrary.mjs
start by attempting to fix lock file on develop again, CI had a time out problem, attempting to fix discovered additional bugs in splitText.
=> fix: splitText fix & processCharacterKnowledge optimization

packages/core/src/evaluators/reflection.ts, packages/core/src/providers.ts, packages/core/src/providers/facts.ts, turbo.json
Low
- fix reflection guard when generateObject doesn't make proper JSON
- allow passing LOG_LEVEL through turbo to callees
- optimize facts provider to do retrieval in parallel
- more informative logging on provider profiling
Just quality of life improvements
=> feat: optimize fact retrivael, env fix, reflection guard

packages/client/src/components/app-sidebar.tsx, packages/client/src/components/profile-card.tsx, packages/client/src/routes/home.tsx
Added buttons for navigating to the Home and Chat pages. UI/UX design improvements can be considered later.
=> feat: add button for directing to home/chat page

docs/docs/quickstart.md
Added TWITTER 2FA secret in the values to config in the env to avoid X preventing the login
=> docs: Update quickstart with twitter configs.md

CONTRIBUTING.md, SECURITY.md, docs/docs/faq.md
LINK TO ISSUE OR TICKET
confusing the readers
=> docs: fixed some outdated links

docs/docs/intro.md
=> docs: Update intro.md - Fix missing space

packages/core/src/parsing.ts
=> fix: address issue #3779

Dockerfile
Fixes Dockerfile build for main branch
=> fix: fix main docker errors

i18n/readme/README_TR.md
Low risk. There might be grammer errors
I've commited before just to fix Turkish readme
Fix the grammer errors in Turkish readme
Readme fix
Turkish readme was wrong and there are deficiencies so I fixed it
azriel_the_hellrazor
=> chore: Turkish readme update

packages/plugin-discord/tsup.config.ts
=> fix: discord plugin error

packages/the-org/src/communityManager/index.ts, packages/the-org/src/devRel/index.ts, packages/the-org/src/investmentManager/index.ts, packages/the-org/src/liaison/index.ts, packages/the-org/src/projectManager/index.ts, packages/the-org/src/socialMediaManager/index.ts
Initialize the avatar for the org character as requested by @wtfsayo .
=> feat: set avatar from assets folder

.github/workflows/integrationTests.yaml, .github/workflows/tauri-ci.yml, packages/cli/src/characters/eliza.ts
if no keys, we can fallback to local-ai
also fixes CI for:
- integrationTest
- native app
=> fix: add back in local-ai + CI fixes

packages/client/src/lib/api.ts
uses a relative URL for fetch
this way
http://localhost:3000/
http://192.168.x.x:3000
or if you throw a hostname on it, they all work work
=> fix: fix client fetch URL

packages/core/src/bootstrap.ts, packages/core/src/runtime.ts, packages/the-org/src/devRel/index.ts
This PR fixes the RAG knowledge loading, which wants generating embeddings
Currently its sequential and very slow, we may want to parallelize the RAG processing
=> fix: Fix RAG Knowledge loading

packages/plugin-sql/src/base.ts
=> fix: delete memory

packages/client/src/components/chat.tsx
issue:
https://github.com/user-attachments/assets/a38b4596-d049-4651-a39f-95029e4ee042
=> fix: aiwriter rerender issue

packages/plugin-sql/src/pg/manager.ts, packages/plugin-sql/src/pglite/manager.ts
Add drizzle migration table to public schema
=> chore: add drizzle table to  public schemaD

packages/client/src/components/avatar-panel.tsx, packages/client/src/components/character-form.tsx, packages/client/src/components/group-panel.tsx, packages/client/src/constants.ts, packages/client/src/lib/utils.ts
Related Issue: #2
This issue occurred because the avatar image is too large:
=> fix: reduce payload size to prevent db update failure

packages/docs/docs/intro.md
The Quickstart Guide docs
Low
Just changes the instructions so that the code runs smoothly
=> Update intro.md documentation

packages/cli/src/commands/create.ts, packages/cli/src/commands/start.ts, packages/cli/src/utils/get-config.ts
Fix after merge conflits. 
Enhance validation for postgres url and UX.
=> fix: UX issue with start and create

bun.lock, packages/client/package.json, packages/client/src/components/app-sidebar.tsx, packages/client/src/components/group-panel.tsx, packages/client/src/components/ui/dropdown-menu.tsx, packages/client/src/routes/home.tsx
Added create button in left for easy access
=> feat: added create button; home page layout improvements

packages/client/src/components/agent-sidebar.tsx, packages/client/src/components/memory-viewer.tsx, packages/client/src/routes/chat.tsx
=> feat: better memory viewer

packages/client/src/components/secret-panel.tsx
related: https://github.com/elizaOS/eliza/issues/3936
=> feat: add drag & drop option for env uploading

packages/plugin-discord/src/service.ts, packages/plugin-discord/src/voice.ts
sub pr: https://github.com/elizaOS/eliza/pull/4035
Noticed that Discord voice wasn't working. Since the voice code was recently refactored, I made a quick fix to get it working again.
=> fix: discord voice

packages/docs/docs/quickstart.md
fixed add plugin command quickstart.md
N/A
LOW
Updates the documentation with the correct add plugin command.
Update
The documentation was incorrect
This IS a document update
None: Automated tests are acceptable.
$4n7m4n
=> fixed add plugin command quickstart.md

packages/cli/src/server/api/agent.ts, packages/core/src/settings.ts
Fix encryption when adding/updating secrets from GUI.
=> chore: encrypt character secrets from GUI

bun.lock, packages/cli/src/commands/agent.ts, packages/cli/src/commands/create.ts, packages/cli/src/commands/dev.ts, packages/cli/src/commands/env.ts, packages/cli/src/commands/start.ts, packages/cli/src/displayBanner.ts, packages/cli/src/index.ts, packages/cli/src/utils/handle-error.ts, packages/cli/src/utils/helpers.ts
- improved cli error display for when server not running
- fixed display banner fn causing cli errors
=> fix: cli related 

packages/client/src/components/group-panel.tsx
related: https://github.com/elizaOS/eliza/issues/4070
=> fix: handle whitespace issue in GUI name field

packages/client/src/components/app-sidebar.tsx
related: https://github.com/elizaOS/eliza/issues/4069
=> fix: room status

packages/client/src/components/chat.tsx, packages/client/src/components/room.tsx, packages/client/src/components/ui/chat/chat-message-list.tsx
Also fix typo "flex-column" -> "flex-col".
=> Fix excessive gap between chat messages.

packages/cli/src/server/api/index.ts, packages/client/src/components/chat.tsx, packages/client/src/lib/socketio-manager.ts, packages/core/src/bootstrap.ts, packages/core/src/types.ts
related: https://linear.app/eliza-labs/issue/ELI2-154/ui-fix-reliably-mute-send-message-button-during-agent-processing-to
result:
https://github.com/user-attachments/assets/dccd2324-c227-4cb2-9be9-486e016ef373
=> feat: prevent message overlap

packages/cli/src/commands/env.ts, packages/cli/src/server/api/env.ts, packages/cli/src/server/api/index.ts, packages/client/src/App.tsx, packages/client/src/components/env-settings.tsx, packages/client/src/lib/api.ts
related: https://linear.app/eliza-labs/issue/ELI2-136/improve-environment-variables-management-in-web-ui
This PR adds a new Settings route that allows users to view and manage their local and global environment variables directly from the Web UI.
=> feat: env settings gui

packages/core/src/prompts.ts, packages/plugin-discord/src/service.ts, packages/the-org/src/communityManager/index.ts, packages/the-org/src/communityManager/plugins/communityManager/actions/discord-timeout.ts, packages/the-org/src/communityManager/plugins/communityManager/communityService.ts, packages/the-org/src/communityManager/plugins/communityManager/index.ts, packages/the-org/src/communityManager/plugins/communityManager/providers/timeout.ts, packages/the-org/src/communityManager/plugins/communityManager/types.ts
This PR enables Discord community manager to automatically greet users when a new user joins. It also adds a new action/provider that allows agents to timeout users
telegram would be added after the onboarding issue is resolved: 
https://github.com/elizaOS/eliza/pull/4091
https://github.com/elizaOS/eliza/pull/4098
=> feat: community manager

packages/plugin-twitter/src/post.ts
fixes- #4086 
Caused by sending same tweet content consecutively- ref: https://stackoverflow.com/questions/36971860/duplicate-status-error-when-tweeting-using-twitter-api
=> fix: duplicate tweet (twitter error 187)

packages/cli/src/commands/install.ts, packages/cli/src/index.ts
=> feat: add monorepo command to cli

packages/docs/blog/reintroduction.mdx, packages/docs/blog/taming_info.mdx, packages/plugin-groq/src/index.ts
- removed un-necessary commented out code from groq plugin
- fixed retry mechanism + error handling
=> fix: Groq plugin handle retry gracefully

Dockerfile
1. Reduced Installed Packages with `--no-install-recommends`:                                                                                                                                          
- In both stages (builder and final image), the apt-get install command now includes the `--no-install-recommends` flag. This ensures that only the explicitly specified packages are installed,   
avoiding unnecessary dependencies and reducing the image size.                                                                                                                                         
2. Removed Redundant Packages:                                                                                                                                                                       
- The …
=> fix: reduce docker image size

packages/core/src/types.ts, packages/plugin-openai/README.md, packages/plugin-openai/src/index.ts, packages/plugin-sql/src/schema/embedding.ts
Adding ability to set the embedding model to the openAI plugin
Low, just adds the ability to add your own openai compatible embedding model
I am using openAI compatible LLM provider for all my LLM calls as well as embedding, I see that in the plugin we can provide the custom endpoint, api key and the LLM models but not embedding models
I want to use the openAI api compatible embedding model which has its own name and different dimensions as well.
Add the ability to specify your own `OPENAI_EMBEDDING_MODEL` and `OPENAI_EMBEDDING_DIMENSIONS`
as well as move the `VECTOR_DIMS` constant to core for better reusability
- Improvement
I want to use an OpenAI api compatible embedding model which has its own name and different dimensions as well, I cant right now as the embedding model and …
=> Add ability to choose embedding model in OpenAI plugin

scripts/generatecharacter.js
I noticed a inconsistency in the `twitterPostTemplate` where `{{agentName}}` was used instead of `{{AGENT_NAME}}`. This caused the `replaceAgentValues` function to miss replacing the placeholder, as it specifically looks for `{{AGENT_NAME}}`.  
I’ve updated the template to use `{{AGENT_NAME}}` to ensure the variable is correctly replaced.
This change aligns with the existing logic in `replaceAgentValues` and fixes the issue.
=> fix: Fix template variable inconsistency in `twitterPostTemplate`

packages/plugin-evm/src/tests/wallet.test.ts
PR #4130  
**Low** – Minor refactoring to use a constant variable. No functionality change.  
Fixes the test file by incorporating the suggested changes from PR #4130. Specifically, it extracts a repeatedly used string into a constant variable for better maintainability.  
- ✅ Bug fixes (non-breaking change which fixes an issue)  
- ✅ Improvements (misc. changes to existing features)  
- ❌ My changes do not require a change to the project documentation.  
Review the modified test file, particularly the extracted constant variable.  
- Run the test suite to ensure all tests pass.  
- Verify that the refactoring does not change the test logic.
=> tests: fixed test file according to the comments in the PR #4130 

bun.lock, packages/cli/src/commands/start.ts
fixes- (sample) project plugin attaching first; imp for first time DX
=> fix: project plugin loading first, related to starter project

bun.lock, packages/client/package.json, packages/client/src/components/chat.tsx, packages/client/src/components/room.tsx, packages/client/src/lib/socketio-manager.ts
replaces 'eventEmitter3' with 'evt' (more typesafe, works in more runtimes)
https://www.evt.land/
=> feat: use Evt instead of eventEmitter3

packages/plugin-sql/src/migrate.ts
**Medium** – Fixing the `pglite` migration issue due to inconsistent usage of `Datadir`. Could impact database migrations if not handled correctly.  
Fixes the `pglite` migration issue that was occurring due to inconsistent usage of `Datadir`. Ensures proper handling of `Datadir` across migrations.  
- ✅ Bug fixes (non-breaking change which fixes an issue)  
- ❌ My changes do not require a change to the project documentation.  
Review the migration changes and `Datadir` usage consistency.  
- Run database migrations and verify they complete successfully.  
- Ensure no data corruption or unexpected behavior occurs.  
- Check that rollback functionality works as expected.
=> fixed: Pglite Migration issue

packages/plugin-twitter/src/interactions.ts
I don't think we need to call shouldRespond here. bootstrap already handles that for us.
=> fix: twitter interaction

packages/plugin-telegram/src/service.ts
- Telegram integration stability
- Forum topics support / rooms in ElizaOS system
- Medium
The Telegram service implementation requires refactoring to better handle large groups and forum topics.
Previously, we only emitted the WORLD_JOINED event for connection which caused synchronization issues.
Now we sync Telegram directly by calling `ensureWorldExist` -> `syncTelegramWorld`, `ensureRoomExist` -> `syncTelegramRoom` and lastly `ensureConnection` methods.
This PR refactors the Telegram service implementation to improve reliability, maintainability, and performance when handling Telegram chats, especially forum topics. The changes focus on optimizing middleware flow, standardizing entity synchronization, and properly managing chat discovery.
With emphasis on correctly handling …
=> fix: telegram to elizaos data model sync

docs/api/classes/AgentRuntime.md
Noticed an unnecessary `~` in the code, which could potentially cause issues.
Removed it to keep things clean.
=> docs: removed an extra `~`

packages/client/src/components/agent-sidebar.tsx, packages/client/src/components/knowledge-manager.tsx
Knowledge tab scroll functionality issue
Low - Only affects UI rendering of the knowledge tab
Fixes an issue with the scrolling functionality in the Knowledge tab where content was not scrollable or loading properly. The fixes ensure that users can view and load more knowledge documents as they scroll.
Check the Knowledge tab in the agent sidebar with multiple documents.
- Navigate to an agent with multiple knowledge documents
- Open the Knowledge tab
- Verify scrollbar appears correctly
- Scroll down to load more items and confirm they load properly
0xbbjoker
=> fix: knowledge manager scroll issue

bun.lock, packages/cli/src/commands/update-cli.ts, packages/cli/src/utils/install-plugin.ts, packages/cli/src/utils/package-manager.ts
This PR enhances the ElizaOS CLI update and plugin installation mechanisms with more robust functionality:
- Added a centralized `executeInstallation()` function to standardize package installation across the codebase
- Added detection for npx/bunx running environments to prevent unnecessary installations
- Improved version and tag handling for package installations
- Refactored `update-cli` to use the new centralized installation system
- Added proper validation to prevent updates when running via npx/bunx
- Extracted core update logic to a separate `performCliUpdate()` function
- Improved error handling and logging
- Added better version compatibility checking
- Completely reworked plugin installation with a more reliable multi-attempt strategy:
1. Try local installation first …
=> feat: better plugin install management

bun.lock, packages/cli/src/commands/start.ts, packages/cli/src/utils/install-plugin.ts, packages/cli/src/utils/load-plugin.ts, packages/plugin-local-ai/src/index.ts
- enhances plugin install logic
=> chore: enhance plugin install strategy and code

packages/plugin-openai/src/index.ts
Bug fix for JSON parsing in OpenAI object generation
Low - This is a focused fix that improves error handling for JSON parsing in the OpenAI plugin.
This PR improves the OpenAI plugin by:
1. Adding support for JSON parse error handling
2. Refactoring the object generation code into a shared helper function
3. Adding a repair function that cleans code fence markers from JSON text
Review the new helper functions in `packages/plugin-openai/src/index.ts`:
- `generateObjectByModelType`
- `getJsonRepairFunction`
- Test the `OBJECT_SMALL` and `OBJECT_LARGE` model functions with prompts that include JSON code blocks
- Verify that the JSON parsing error handling correctly removes …
=> fix openai object json parse error

packages/plugin-telegram/README.md
Updated the documentation for the the follwoing issue.
https://linear.app/eliza-labs/issue/ELI2-191/ui-bug-talk-to-agent-edit-settings-try-to-talk-to-agent-again-error
=> docs: Update README.md for telegram plugin

packages/plugin-twitter/src/interactions.ts
related: https://github.com/elizaOS/eliza/issues/4225
=> fix: Duplicate Provider Section in Prompt

packages/plugin-twitter/src/interactions.ts
related: https://github.com/elizaOS/eliza/issues/4226
=> fix: Failed to Replies to Tweet in Interaction

packages/cli/src/server/api/agent.ts
This PR resolves the issue where TTS was not functioning properly in the GUI
=> fix: gui tts

bun.lock, packages/cli/src/commands/agent.ts, packages/cli/src/commands/dev.ts, packages/cli/src/commands/plugin.ts, packages/cli/src/commands/project.ts, packages/cli/src/commands/publish.ts, packages/cli/src/commands/start.ts, packages/cli/src/index.ts, packages/cli/src/utils/install-plugin.ts, packages/cli/src/utils/package-manager.ts, packages/client/src/lib/api.ts, packages/core/src/logger.ts, packages/docs/docs/cli/projects.md
This PR implements significant code cleanup and improvements across the CLI components of the Eliza project. Key changes include:
Refactored the start command with improved plugin loading logic and error handling
Enhanced package manager detection and installation utilities with better support for npm/bun environments
Streamlined project management functionality and plugin installation workflows
Added comprehensive documentation and comments throughout the codebase
=> chore: improve cli and start code

packages/plugin-openai/src/index.ts
related: https://github.com/elizaOS/eliza/issues/4210
=> fix: replace deprecated vision model

packages/plugin-openai/src/index.ts
=> feat: openai tts

packages/client/src/components/character-form.tsx, packages/client/src/components/plugins-panel.tsx, packages/client/src/config/voice-models.ts, packages/client/src/hooks/use-elevenlabs-voices.ts
https://linear.app/eliza-labs/issue/ELI2-195/ui-replace-text-input-with-dropdown-for-voice-model-selection
Low. The changes modify the voice model selection logic and plugin management, but use existing components and follow established patterns. The changes are isolated to the voice model selection flow and don't affect core functionality.
This PR improves the voice model selection by enhancing how plugins are managed when changing between voice model providers. Specifically:
1. Makes voice model to plugin mapping configurable in voice-models.ts
2. Ensures only one voice-related plugin is active at a time (removes previous provider's plugin when switching)
3. Improves the UI to clearly indicate which plugins are required by the selected voice model
4. Prevents users from removing plugins …
=>  Replace Text Input with Dropdown for Voice Model Selection

packages/client/src/components/character-form.tsx, packages/client/src/hooks/use-agent-update.ts, packages/client/src/hooks/use-partial-update.ts
Allow users to import JSON for agent creation and updates
=> feat: gui- support for importing JSON to create or update agents

bun.lock, packages/cli/src/commands/agent.ts, packages/cli/src/commands/start.ts, packages/cli/src/server/api/agent.ts, packages/core/src/runtime.ts, packages/docs/archive/notes/agent.md
[ELI2-189: UI Bug - Advanced Agent Creation Fails with TypeError (Same as Basic)](https://linear.app/eliza-labs/issue/ELI2-189/ui-bug-advanced-agent-creation-fails-with-typeerror-same-as-basic)
Low - This fix addresses a specific issue with agent initialization where default plugins are not being properly included. The changes are focused on ensuring that required plugins are always included during agent initialization, which should not affect other functionality.
This PR fixes an issue where agent creation fails with a TypeError when using advanced configuration options. The error occurs because the agent is initialized without the required default plugins, specifically the SQL plugin. The fix ensures that the default plugins (`@elizaos/plugin-sql` and `@elizaos/plugin-local-ai`) are …
=> Starting Agent Fix 

packages/client/src/components/agent-creator.tsx, packages/client/src/components/agent-settings.tsx, packages/client/src/components/avatar-panel.tsx, packages/client/src/components/character-form.tsx
- https://linear.app/eliza-labs/issue/ELI2-222/uiux-clarify-terminology-and-required-fields-in-agent-settings
- https://linear.app/eliza-labs/issue/ELI2-239/bug-uiux-avatar-preview-overlaps-uploadaction-area
Low - This PR only affects UI elements and text labels. No functional changes to data structure or processing logic.
This PR makes several UI/UX improvements to the agent configuration interface:
1. Terminology and Field Requirements (ELI2-222):
- Makes terminology consistent by changing all user-facing text from "Character" to "Agent"
- Adds a clear visual system for distinguishing between required, suggested, and optional fields
- Implements tooltips for all fields to explain their purpose and importance
- Creates a more elegant legend for requirement levels
- Refines field …
=> Clarify Terminology and Required Fields in Agent Settings

packages/plugin-twitter/src/constants.ts, packages/plugin-twitter/src/interactions.ts, packages/plugin-twitter/src/post.ts, packages/plugin-twitter/src/utils.ts
This PR removes unused code in the Twutter plugin and adds support for posting and replying with long tweets for premium accounts
=> feat: twitter plugin - Cleanup Unused Code and Support Long Tweets for Premium Accounts

packages/plugin-twitter/src/post.ts
fix: use config TWITTER_POST_INTERVAL_MIN and TWITTER_POST_INTERVAL_MAX instead of TWITTER_POST_INTERVAL)
=> fix: use correct twitter post interval config in plugin-twitter package

packages/client/src/components/agent-settings.tsx, packages/client/src/components/character-form.tsx, packages/client/src/components/profile-overlay.tsx, packages/client/src/components/stop-agent-button.tsx
[ELI2-198: Implement "Stop Agent" Feature in Web UI](https://linear.app/eliza-labs/issue/ELI2-198/implement-stop-agent-feature-in-web-ui)
Low - This PR implements a new UI control using existing backend functionality. The stop functionality already existed in the API and was being used in the ProfileOverlay component. This PR adds the same functionality to the agent settings page.
This PR adds a "Stop Agent" button to the agent settings page for running agents. When clicked, the button shows a confirmation dialog and, if confirmed, stops the agent and redirects the user to the home page. The button is only visible when an agent is active, and it shows a loading state during the stopping process.
My changes do not require a change to …
=> Added Stop agent button in agent settings

packages/plugin-openai/tsup.config.ts
Additional note for testing: 
- `bun i`
- `bun run build` 
- cd out from the project
- `node ../ai-agents/new-eliza/eliza/packages/cli/dist/index.js start`
=> fix: external depn issue

packages/client/src/components/character-form.tsx
Fixes missing requirement indicator and tooltips caused by a merge conflict
=> fix: GUI Missing Requirement Indicator and Tooltips After Merge Conflict

docs/api/type-aliases/Character.md
Description: 
This pull request corrects a typographical error in the `Character.md` file. The word "Optional" was previously misspelled as "Optinal" and has been corrected. This change ensures consistency and clarity in the documentation.
=> fix: Typographical Error in Character.md

docs/docs/changelog.md
**Description:**
This pull request addresses several minor issues in the changelog documentation:
- Corrected typos such as "toghether" to "together" and "misstype" to "mistype".
- Improved consistency by using strict types to avoid errors, as referenced in issue #2164.
- Updated links and references to ensure they point to the correct pull requests and issues.
- Enhanced readability and clarity of the changelog entries.
These changes aim to improve the overall quality and accuracy of the documentation.
=> Fix Typos and Improve Documentation in Changelog

.github/workflows/cli-tests.yml, packages/cli/__test_scripts__/test_agent.bats, packages/cli/__test_scripts__/test_dev.bats, packages/cli/__test_scripts__/test_env.bats, packages/cli/__test_scripts__/test_plugins.bats, packages/cli/__test_scripts__/test_publish.bats, packages/cli/__test_scripts__/test_start.bats, packages/cli/__test_scripts__/test_test.bats, packages/cli/__test_scripts__/test_update.bats, packages/cli/src/commands/start.ts, packages/cli/src/server/index.ts, packages/cli/src/server/loader.ts
This PR implements support for loading character configurations using paths that are relative to the current working directory. It also includes several test improvements and adds helpful logging messages.
- Added support for relative character paths in `loader.ts`
- Improved test isolation with unique temp directory names
- Added new test for character loading from relative paths
- Enhanced logging for .env file resolution and server startup
- Updated CI workflow to include core and plugin-bootstrap paths
=> feat: support relative char path + other issues

bun.lock, packages/cli/src/commands/start.ts, packages/cli/src/server/index.ts, packages/client/vite.config.ts, packages/core/src/entities.ts, packages/core/src/prompts.ts, packages/core/src/runtime.ts, packages/plugin-bootstrap/src/index.ts, packages/plugin-bootstrap/src/providers/character.ts, packages/plugin-bootstrap/src/services/task.ts, packages/plugin-discord/src/messages.ts, packages/plugin-solana/src/providers/wallet.ts, packages/plugin-solana/src/service.ts, packages/plugin-twitter/src/base.ts, packages/plugin-twitter/src/interactions.ts
Medium
- general logging clean up
- cli: fix how plugins are loaded so org-level plugins can be loaded after plugin-sql so we can start tasks in a plugin's init
- client: fix cloudflare:socket stopping it from build
- core: include quotes around entity names (to clarify when they have spaces in them
- core: stop html encoding everything in the prompt
- core: include source/entity in posts
- bootstrap: character don't include adjective twice, properly use topic/adjective
- bootstrap: tasks now support immediate tag and prevent repeating tasks from stacking
- bootstrap: post engine support dynamic providers/don't repeat self/don't post when we get moderated
- discord: include names in metadata
- solana: handle when public key isn't set yet in service
- solana: update wallet provider/set …
=> feat: V2 QoL improvements

packages/cli/src/commands/agent.ts
Currently, when a file path is provided to start an agent with cli, the agent gets created but doesn't automatically start.
=> fix: cli start agent

packages/docs/blog/openai-plugin-envs.md
- **Expanded Provider Coverage:**  
Added a new section for LM Studio, a popular local LLM desktop app, with clear instructions and example `.env` configuration for using its OpenAI-compatible API.
- **Embedding Model Requirement:**  
Added a prominent reminder that an embedding model is required for full plugin functionality, and recommended pairing with the Local AI plugin, OpenAI API key, or a provider that supports embeddings.
- **Formatting & Clarity Improvements:**  
- Improved table formatting for environment variables for better readability.
- Minor formatting tweaks for consistency (e.g., spacing, bullet points).
- **Link Updates:**  
- Added a link to the official LM Studio OpenAI Compatibility API docs in the “More Links” section.
- **General Verification:**  
- All provider …
=> chore: add-any-provider-blog

packages/plugin-anthropic/__tests__/index.test.ts, packages/plugin-anthropic/__tests__/utils.test.ts, packages/plugin-anthropic/package.json
Low
This PR contains:
* Unit tests for the plugin-anthropic package
* 14 test cases across two test files:
* utils.test.ts: 8 tests for JSON extraction and reflection property handling
* index.test.ts: 6 tests for the plugin's core functionality
Coverage includes:
* JSON parsing, repairing, and extraction functionality in utils.ts
* Plugin configuration and initialization
* Text generation with small and large models
* Object generation with reflection schema handling
* Error handling for invalid JSON responses
The tests run within the package directory using pnpm and vitest, following the project's established testing patterns.
feat(chore)
None
packages/plugin-anthropic
pnpm install && pnpm test
=> (chore)plugin anthropic - test coverage and setup

packages/plugin-sql/drizzle/migrations/0001_third_tyger_tiger.sql, packages/plugin-sql/drizzle/migrations/meta/0001_snapshot.json, packages/plugin-sql/drizzle/migrations/meta/_journal.json, packages/plugin-sql/package.json, packages/plugin-sql/src/schema/memory.ts
=> update memory.ts to use the new schema

packages/docs/docs/intro.md, packages/docs/docs/quickstart.md
Doc updation
None
Some docs were stale that can confuse the end user
=> docs: updated quick start and intro cli commands

packages/plugin-anthropic/src/index.ts
related: https://github.com/elizaOS/eliza/issues/4346
this pr add API key validation for Anthropic models
=> fix: Add API Key Validation for Anthropic Plugin Model Calls

packages/project-starter/.env.example
Added .env.example in project-template as some users were facing confusion while setting up keys for project
None 
Added .env.example in project-template as some users were facing confusion while setting up keys for project
This PR just added a .env.example whenever user setups cli and create a new project he just gets a .env.example along with it so he can fill out the .env files to avoid confusions.
I have tested this by setting up a new project using cli. it's loading the .env.example file
=> feat: added .env.example in project-starter

packages/cli/src/utils/handle-error.ts
My Macbook didn't have space yesterday, so I was getting these errors but wasn't aware for a while.
This PR will notify the user in red when their disk space is full
None
This PR introduces a visual notification to alert the user when their disk space is critically low. Specifically, it will display a red warning message indicating that the disk is full.
=> fix : error handling for no space left in disk to users

packages/cli/src/server/index.ts
it's made in initializeServer
Low
Small fix I saw
between:
=> fix: Don't make unneeded express object

packages/plugin-bootstrap/src/actions/reply.ts
Currently reply is using large model but replies end up being very slow. Small model is appropriate for most functionality.
=> feat: Reply uses small model

packages/plugin-twitter/src/templates.ts
Added character bio and postDirections to the quote/reply template prompt
=> fix: small template fix

packages/cli/src/server/api/agent.ts
Low
Makes a plugin's routes available in /api/agents/AGENT_UUID_OR_NAME/plugins/PLUGIN_NAME/ROUTE_FROM_PLUGIN
=> fix: make plugin.routes work

packages/plugin-bootstrap/package.json, packages/plugin-bootstrap/tsconfig.build.json, packages/plugin-bootstrap/tsup.config.ts, packages/plugin-openai/package.json, packages/plugin-openai/tsconfig.build.json, packages/plugin-openai/tsup.config.ts, packages/plugin-sql/package.json, packages/plugin-sql/tsconfig.build.json, packages/plugin-sql/tsconfig.json, packages/plugin-sql/tsup.config.ts
=> Revert "Fix ESM type generation in packages: SQL, Boostrap & OpenAI"

packages/core/package.json, packages/core/tsconfig.build.json, packages/core/tsup.config.ts
=> Revert "Fix ESM type declarations in Core"

packages/plugin-telegram/src/messageManager.ts, packages/plugin-telegram/src/utils.ts
Enhance message handling and text escaping by adding null checks. 
Updated MessageManager to handle empty messages and modified utility functions to return empty strings for null inputs, ensuring robustness in message processing.
=> Enhance message handling and text escaping by adding null checks. 

docs/packages/plugins/solana-v2.md
remove redundant word in solana-v2.md
=> docs: remove redundant word in solana-v2.md

packages/plugin-sql/src/index.ts, packages/plugin-sql/src/migrate.ts
=> fix: pglite migrations again

.github/workflows/tee-build-deploy.yml, tee-docker-compose.yaml
Low
Set up a repo with all the environment variables listed:
```
APP_NAME: ${{ vars.APP_NAME || secrets.APP_NAME }}
APP_ID: ${{ vars.APP_ID || secrets.APP_ID }}
DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME || secrets.DOCKER_USERNAME }}
DOCKER_IMAGE: ${{ vars.DOCKER_IMAGE || secrets.DOCKER_IMAGE }}
DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY || secrets.DOCKER_REGISTRY || 'docker.io' }}
DOCKER_REGISTRY_USERNAME: ${{ vars.DOCKER_REGISTRY_USERNAME || secrets.DOCKER_REGISTRY_USERNAME }}
DOCKER_REGISTRY_PASSWORD: ${{ vars.DOCKER_REGISTRY_PASSWORD || secrets.DOCKER_REGISTRY_PASSWORD }}
PHALA_CLOUD_API_KEY: ${{ vars.PHALA_CLOUD_API_KEY || secrets.PHALA_CLOUD_API_KEY }}
OPENAI_API_KEY: ${{ vars.OPENAI_API_KEY || secrets.OPENAI_API_KEY }}
ANTHROPIC_API_KEY: ${{ vars.ANTHROPIC_API_KEY || …
```
=> fix: TEE update for CI

bun.lock, packages/client/vite.config.ts
=> chore: remove log spam during client build

bun.lock, packages/cli/src/characters/eliza.ts, packages/project-starter/src/index.ts
- additional fix for default character used for quick start 
- fix for character used in project starter
=> fix: additional fix for topics project starter & def character

.github/workflows/docs-publish.yml
This runs Github Action if anything inside `packages/docs` folder changes and auto deploys to `docs.eliza.how`.
=> ci: Docs auto deployer.

packages/plugin-bootstrap/src/actions/reply.ts
This PR removes the skipping logic in the reply action. Previously, if a dynamic provider was added, it wouldn't be processed because the reply action would skip it.
=> fix: reply action skipping dynamic providers

docs/api/type-aliases/Plugin.md, packages/cli/index.js, packages/core-plugin-v1/src/types.ts, packages/core/src/runtime.ts, packages/core/src/types.ts
=> chore: fix some typos in comment

packages/plugin-jupiter/src/index.ts, packages/plugin-solana/src/index.ts, packages/plugin-solana/src/service.ts, packages/plugin-trader/src/strategies/strategy_llm.ts, packages/plugin-trader/src/tasks/tsk_twitter.ts, packages/the-org/src/investmentManager/plugins/degen-intel/tasks.ts, packages/the-org/src/investmentManager/plugins/degen-intel/tasks/twitter.ts, packages/the-org/src/investmentManager/plugins/plugin-autofun/providers/autofun.ts, packages/the-org/src/investmentManager/plugins/plugin-autofun/providers/sentiment.ts, packages/the-org/src/investmentManager/plugins/plugin-autofun/tasks.ts
Just minor tweaks I've made so far
=> [Spartan] Minor tweaks

packages/cli/src/server/index.ts
My heart isn't going to break if this is not merged, merely a suggestion
=> feat: Lower web server logging (no 404 or ping logging)

packages/cli/src/commands/plugins.ts
Changed text from eliza -> elizaos was making few users confuse when using cli
=> fix: updated text from eliza -> elizaos

.github/workflows/deploy-cli.yml
github action to auto deploy the CLI package on changes and version bump
=> ops: deploy CLI action

i18n/readme/README_MY.md
=> Add file TRANSLATION

.github/workflows/integrationTests.yaml
fixes integration CI complaining in bun install because of Sharp deps
=> fix: add libvips-dev to integration test CI

packages/cli/src/commands/create.ts, packages/cli/src/commands/publish.ts, packages/cli/src/utils/copy-template.ts, packages/cli/src/utils/publisher.ts, packages/cli/src/utils/registry/index.ts, packages/plugin-starter/.gitignore, packages/plugin-starter/package.json
**Key Features Added**
1. NPM Authentication Integration (getNpmUsername())
- Added required NPM authentication for registry compliance
- Interactive prompts to use existing NPM login or switch accounts
- Automatic fallback to npm login when not authenticated
- Ensures package names match potential NPM package requirements
2. Plugin Validation System (validatePluginRequirements())
- Hard validation: Plugin naming convention enforcement (plugin-* format)
- Soft warnings: Missing required assets with bypass option
- Default description detection (${PLUGINDESCRIPTION} or auto-generated)
- Missing logo.jpg (400x400px, max 500KB) in images/ directory
- Missing banner.jpg (1280x640px, max 1MB) in images/ directory
- User-friendly error handling with clear next steps
3. Enhanced Package.json …
=> feat: enhance plugin publishing with NPM authentication and validation

packages/docs/blog/twitter-agent-guide.mdx
Update Twitter agent blog post.
=> chore: update twitter setup blog

bun.lock, packages/cli/src/characters/eliza.ts, packages/plugin-polygon/package.json, packages/plugin-polygon/src/actions/bridgeDeposit.ts, packages/plugin-polygon/src/actions/delegateL1.ts, packages/plugin-polygon/src/actions/getBalanceInfo.ts, packages/plugin-polygon/src/actions/getBlockInfo.ts, packages/plugin-polygon/src/actions/getCheckpointStatus.ts, packages/plugin-polygon/src/actions/getDelegatorInfo.ts, packages/plugin-polygon/src/actions/getL2BlockNumber.ts, packages/plugin-polygon/src/actions/getMaticBalance.ts, packages/plugin-polygon/src/actions/getPolygonBlockDetails.ts, packages/plugin-polygon/src/actions/getPolygonGasEstimates.ts, packages/plugin-polygon/src/actions/getValidatorInfo.ts, packages/plugin-polygon/src/actions/heimdallSubmitProposalAction.ts, packages/plugin-polygon/src/actions/heimdallVoteAction.ts, packages/plugin-polygon/src/actions/isL2BlockCheckpointed.ts, packages/plugin-polygon/src/contracts/RootChainManagerABI.json, packages/plugin-polygon/src/contracts/StakeManagerABI.json, packages/plugin-polygon/src/index.ts, packages/plugin-polygon/src/providers/PolygonWalletProvider.ts, packages/plugin-polygon/src/services/ConfigService.ts, packages/plugin-polygon/src/services/GasService.ts, packages/plugin-polygon/src/services/HeimdallService.ts, packages/plugin-polygon/src/services/PolygonRpcService.ts, packages/plugin-polygon/src/templates/index.ts, packages/plugin-polygon/tests/services/GasService.test.ts, tsconfig.json
=> Updated polygon plugin

packages/cli/src/utils/get-config.ts
In server hosting environments, the secrets were being ignored since CLI creates a new .env file and only loads from that, now secrets will be merged in from process.env.
Updates the .env file creation and population logic to merge variables from `process.env` with example variables from the template. This ensures that existing environment variables are prioritized, while falling back to the template for missing values.
- Enhances the `.env` setup to prioritize `process.env` variables when creating or populating the file.
- Improves developer experience by automatically incorporating existing environment configurations.
=> feat: Merge process.env variables into .env file

packages/cli/README.md, packages/docs/docs/cli/agent.md, packages/docs/docs/cli/create.md, packages/docs/docs/cli/dev.md, packages/docs/docs/cli/env.md, packages/docs/docs/cli/overview.md, packages/docs/docs/cli/plugins.md, packages/docs/docs/cli/publish.md, packages/docs/docs/cli/setup-monorepo.md, packages/docs/docs/cli/start.md, packages/docs/docs/cli/stop.md, packages/docs/docs/cli/test.md, packages/docs/docs/cli/update.md, packages/docs/docs/quickstart.md
**Problem:**
CLI documentation across all commands contained critical inaccuracies and inconsistencies:
Command descriptions didn't match actual CLI help output
Incorrect aliases and missing options throughout
Non-existent commands referenced in quickstart guide
Inconsistent formatting and missing comprehensive examples
Command ordering didn't match CLI structure
JSON examples used unprofessional notation ("etc...")
**Solution:**
Systematically verified and standardized ALL CLI documentation against actual CLI help output:
✅ CLI Verification: Retrieved help output for every command and subcommand
✅ Complete Accuracy: All descriptions, options, and aliases now match CLI exactly
✅ Comprehensive Examples: Added detailed usage examples with realistic names
✅ Consistent Structure: Applied …
=> docs: comprehensive CLI docs standardization, updates, and accuracy fixes

CHANGELOG.md, docs/docs/changelog.md, docs/news/2024-11-10.md, docs/notes/changelog.md, docs/packages/plugins/cosmos.md, docs/packages/plugins/flow-advanced.md, docs/packages/plugins/gitcoin-passport.md, docs/packages/plugins/injective.md, docs/packages/plugins/irys.md, docs/packages/plugins/multiversx.md, packages/cli/index.js
=> chore: fix typos across codebase

bun.lock, packages/core/src/database.ts, packages/core/src/runtime.ts, packages/core/src/types.ts, packages/plugin-sql/__tests__/integration/agent.test.ts, packages/plugin-sql/src/base.ts
=> Revert "feat: update agent configuration on restart and move ensureAgentExist…"

packages/docs/archive/injection/example.md
Since we have a top 1% repo we want to have a space in our docs for adding stuff that can be trained into the model
=> Add example of prompt injection for future LLM trainings

bun.lock, package.json, packages/cli/__test_scripts__/test_plugins.bats, packages/cli/__test_scripts__/test_publish.bats, packages/cli/__test_scripts__/test_start.bats, packages/cli/__test_scripts__/test_update.bats, packages/cli/src/commands/agent.ts, packages/cli/src/server/api/agent.ts, packages/cli/src/utils/directory-detection.ts
Fix multiple failing test suites to achieve 100% test success rate. These comprehensive fixes address test expectation mismatches, improve error handling, and ensure CI pipeline stability.
- **Problem**: Test expected "available plugins" but CLI shows "Available v1.x plugins"
- **Solution**: Updated test to check for both "Available" and "plugins" text
- **Result**: `plugins list aliases (l, ls) work correctly` ✅
- **Problem**: Tests expected "must be run from a plugin directory" but CLI shows "No package.json found"
- **Solution**: Updated tests to match actual CLI error messages
- **Results**:
- `publish command validates basic directory structure` ✅
- `publish fails outside plugin directory` ✅
- **Problem**: Multiple test failures due to outdated expectations and missing error handling …
=> fix: failing CLI CI test suites

packages/cli/src/commands/start.ts
fixes forceful telegram, discord plugins etc
=> fix: elizaos start for plugins

packages/project-starter/package.json
make it easier for users to start (less log spam, gets installed during auto installation during create command)
=> chore: add bootstrap to package.json

packages/client/src/components/ChatMessageListComponent.tsx, packages/client/src/components/chat.tsx, packages/client/src/components/retry-button.tsx
Adds a retry button to user messages in chat bubbles, allowing users to easily resend previous messages without manually copying and pasting text. This addresses the frustration of having to retype messages after reboots or downtime.
Fixes #4926 - Users previously had to manually copy and paste previous chat messages to resend them, which was slow and tedious, especially after system reboots or downtime.
- **🔄 Retry Button**: New button with RotateCcw icon for user messages
- **🤖 Auto-Send**: Automatically populates input field and submits message
- **🎨 Visual Consistency**: Matches existing delete button styling
- **🎯 Smart Display**: Only appears on completed user messages (not agent messages or loading states)
- **RetryButton**: Reusable component with tooltip and consistent styling
- …
=> feat: Add retry button for user messages in chat

packages/client/src/components/agent-memory-viewer.tsx, packages/client/src/components/agent-sidebar.tsx, packages/client/src/components/character-form.tsx, packages/client/src/components/chat.tsx, packages/client/src/components/profile-overlay.tsx, packages/client/src/components/stop-agent-button.tsx
This PR introduces comprehensive responsive design improvements and UI enhancements across multiple client components, focusing on better space utilization, improved user experience, and consistent design patterns.
- **Container-aware responsiveness**: Replaced viewport-based breakpoints with actual container width detection
- **Dynamic button labels**: Button text shows/hides based on available space (640px threshold)
- **ResizeObserver integration**: Uses modern browser API for real-time container width monitoring
- **Comprehensive tooltips**: All form buttons now include helpful tooltips for better accessibility
- **Improved UX**: Buttons adapt to their actual context rather than just viewport size
- **Floating online status**: Moved agent status indicator to bottom-right corner of …
=> feat: 🎨 UI/UX Improvements: Responsive Character Form + Chat Interface Enhancements

packages/plugin-bootstrap/src/e2e/scenarios.ts, packages/plugin-bootstrap/src/e2e/test-utils.ts, packages/plugin-bootstrap/src/index.ts
This demonstrates a live interaction between a test and an agent to verify that the agent said what we expected. We can build on this to validate that actions, providers, etc are giving us the correct information and performing as expected, and we can create more and more detailed and complicated test scenarios.
=> feat: Add scenario test to bootstrap to check for "hello world"

.github/workflows/ci.yaml, .github/workflows/cli-tests.yml, .github/workflows/integrationTests.yaml, .github/workflows/tauri-ci.yml
This pull request refactors several GitHub Actions workflows to optimize job execution by introducing setup jobs for dependency installation and caching, and by restructuring workflows to enable parallel execution of tasks. The changes focus on improving efficiency and maintainability across CI, CLI tests, integration tests, and Tauri CI workflows.
* Introduced setup jobs in `.github/workflows/ci.yaml`, `.github/workflows/integrationTests.yaml`, and `.github/workflows/tauri-ci.yml` to centralize dependency installation and build artifact caching. These setup jobs are shared across subsequent workflow jobs to reduce redundant steps. [[1]](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL8-L19) [[2]](diffhunk://#diff-40e5e841155651e834bcd8287c765008aeda5f7195 …
=> chore: Parallelize CI actions.

packages/cli/src/commands/start/actions/server-start.ts, packages/cli/src/commands/start/index.ts
- Enables automatic loading of project agents when no `--character` flag is provided to the start command
- Adds support for `ProjectAgent` type with initialization functions and plugins
- Improves agent discovery by checking project configuration first
=> Fix: Enable loading project agents when no character files specified

scripts/dev-watch.js
- update health check URL
- node => bun
Low
makes `bun run dev` work
To fix the build
=> fix: fix `bun run dev`

README.md
- Replace starter-focused instructions with CLI-first approach for better user experience
- Add comprehensive CLI installation guide with step-by-step instructions
- Include complete command reference with examples and advanced usage
- Improve environment configuration with clear examples and best practices
- Add debugging and development workflow guidance
- Remove outdated OpenTelemetry documentation section
- Streamline manual installation section while keeping it available for advanced users
- **CLI Installation**: Clear step-by-step installation process
- **Project Creation**: Interactive and non-interactive options with recommendations
- **Configuration**: Essential environment variables with examples
- **Development Workflow**: Build, test, and restart processes
- **Advanced …
=> chore: Update README with comprehensive CLI documentation

packages/cli/src/utils/registry/index.ts
Small fix to normalize plugin names for consistency.
Bug fix (non-breaking change which fixes an issue)
=> fix: normalize plugin name

.github/workflows/cli-tests.yml, packages/cli/package.json, packages/cli/src/commands/plugins/actions/install.ts, packages/cli/src/commands/plugins/index.ts, packages/cli/src/commands/plugins/types.ts, packages/cli/src/utils/copy-template.ts, packages/cli/src/utils/install-plugin.ts, packages/cli/src/utils/user-environment.ts, packages/cli/tests/commands/plugins.test.ts
=> chore: optimize CLI performance for create and plugins commands

packages/cli/src/server/services/message.ts
Stores central message bus responses to memory for better message tracking and context persistence across agent communications.
=> chore: store central msg bus response to memory

bun.lock, packages/client/package.json, packages/client/src/components/ChatMessageListComponent.tsx, packages/client/src/components/agent-log-viewer.tsx, packages/client/src/components/chat.tsx, packages/client/src/components/ui/chat/animated-markdown.tsx, packages/client/src/components/ui/chat/chat-bubble.tsx, packages/client/src/components/ui/chat/chat-container.tsx, packages/client/src/components/ui/chat/chat-message-list.tsx, packages/client/src/components/ui/chat/code-block.tsx, packages/client/src/components/ui/chat/hooks/useAutoScroll.ts, packages/client/src/components/ui/chat/markdown.tsx, packages/client/src/index.css
- Add new animated markdown component with smooth rendering and improved user experience
- Implement chat container with better layout structure and responsive design
- Add enhanced code block component with syntax highlighting using Shiki
- Update chat bubble styling with improved animations and visual feedback
- Enhance message list with better scrolling behavior and auto-scroll functionality
- Add new markdown parser with support for line breaks and remark plugins
- Update dependencies to support better rendering capabilities (shiki, remark-breaks, use-stick-to-bottom)
=> feat: Enhance chat UI with improved styling and components

packages/cli/src/server/api/messaging/channels.ts, packages/client/src/lib/api.ts
Added API endpoints for managing agents across channels.
=> feat: add API points to manage channels

eliza.postman.json
Updated the Postman collection to include all missing API endpoints discovered through comprehensive codebase analysis.
- **Enhanced Agent Logs**: Added query parameters for filtering (roomId, type, count, offset, excludeTypes)
- **Channel Agent Management**: Added 3 new endpoints for managing agents in channels
- **Room Management**: Updated room creation with proper request body parameters  
- **Media Upload**: Fixed endpoint path from `/upload` to `/upload-media`
- **TEE Logs**: Updated to query-based format with pagination support
- Analyzed all router files in `/packages/cli/src/server/api/` 
- Cross-referenced with existing Postman collection to identify gaps
- Added proper request examples and variable definitions
- Maintained consistent naming and structure with existing endpoints …
=> chore: Update Postman collection with missing API endpoints

packages/docs/static/packages/plugins/flow-advanced.md, packages/docs/static/packages/plugins/multiversx.md
Description:  
This pull request corrects minor typographical errors in the documentation files for the Flow and MultiversX plugins:
- Fixed the spelling of "Registration" in the Flow plugin documentation.
- Corrected the spelling of "management" in the MultiversX plugin documentation.
=> Fix Typos in Plugin Documentation for Flow and MultiversX

CLAUDE.md
- Add comprehensive CLAUDE.md file to guide AI assistants working in this repository
- Documents project architecture, development workflow, and critical rules
- Covers monorepo structure, component system, and testing requirements
- Bun-only development requirements
- Agent-centric architecture patterns  
- Package dependencies and structure
- Testing and build workflows
- Environment setup and configuration
This file will help AI assistants understand the codebase structure and follow proper development practices when contributing to ElizaOS.
=> docs: add CLAUDE.md for AI assistant guidance

packages/client/src/components/media-content.tsx
Fix media content color contrast, text truncation, and padding adjustments
=> fix: tweak media content

packages/docs/docs/core/database.md, packages/docs/docs/core/entities.md, packages/docs/docs/core/knowledge.md, packages/docs/docs/core/plugins.md, packages/docs/docs/core/project.md, packages/docs/docs/core/rooms.md, packages/docs/docs/core/services.md, packages/docs/docs/core/tasks.md, packages/docs/docs/core/worlds.md, packages/docs/docs/faq.md, packages/docs/docs/quickstart.md
Updates core documentation files including FAQ, quickstart guide, and core documentation to improve clarity and accuracy.
- Updated FAQ documentation with latest information  
- Refreshed quickstart guide with current setup instructions
- Enhanced core documentation for better developer experience
- Improved onboarding experience for new users
- More accurate and up-to-date documentation
- Better alignment with current codebase and features
**Files changed:** +2,503 additions, -974 deletions across documentation files
=> chore: update faq, quickstart, core docs

packages/client/src/App.tsx, packages/client/src/components/agent-card.tsx, packages/client/src/components/agent-settings.tsx, packages/client/src/components/agent-sidebar.tsx, packages/client/src/components/profile-overlay.tsx, packages/client/src/components/ui/split-button.tsx, packages/client/src/routes/agent-settings.tsx, packages/client/src/routes/chat.tsx
Agent configuration and user experience improvements for ElizaOS platform
**Medium Risk**
- UI changes may affect existing workflows
- Potential integration issues with current configuration system
- Database schema changes (if applicable) require careful migration
This PR introduces a comprehensive **agent settings feature** that provides a user-friendly interface for configuring AI agents within the ElizaOS platform. Instead of manually editing JSON configuration files, users can now manage their agent settings through an intuitive web interface.
Key additions include:
- **Visual Configuration Interface**: Settings panels and forms for agent parameters
- **Real-time Configuration**: Live updates to agent settings without requiring restarts
- **Enhanced User Experience**: Streamlined …
=> feat: add agent settings

packages/client/src/components/app-sidebar.tsx
- Update FooterLink component to detect external URLs
- Add target='_blank' and rel='noopener noreferrer' for external links
- Documentation link now opens in new tab for better UX
=> feat: open documentation links in new tab

packages/client/src/components/env-settings.tsx
Previously, changes to environment settings could not be saved.
This PR adds the save handler to persist environment variable updates.
=> fix: env settings saving

packages/plugin-sql/src/custom-migrator.ts
Follow up to this issue
https://github.com/elizaOS/eliza/pull/5196
=> fix: throw precise error on problems with DB connection

packages/docs/archive/injection/example.md, packages/plugin-starter/src/index.ts
This pull request addresses minor typographical errors found in the project's documentation and code comments.
**Changes:**
*   Corrected a typo in `packages/docs/archive/injection/example.md`.
*   Fixed a typo in a comment in `packages/plugin-starter/src/index.ts`.
These changes improve the quality and clarity of the codebase without affecting any functionality.
=> Fix: Correct typos in documentation and comments

packages/docs/archive/injection/example.md, packages/docs/blog/taming_info.mdx
Spotted and fixed a few wording hiccups:
`satsified` - `satisfied`
`succesful` - `successful`
=> polishing docs: error fixes for clarity

packages/plugin-bootstrap/src/index.ts
This PR adds support for user-uploaded plain text (.txt) files in the GUI.
=> feat: process plain text file

bun.lock, packages/cli/src/commands/create/actions/creators.ts, packages/cli/src/commands/create/actions/setup.ts, packages/cli/src/commands/create/index.ts, packages/cli/src/commands/create/utils/selection.ts, packages/cli/src/utils/get-config.ts, packages/project-starter/src/character.ts
Relates to
Enhancement of model provider support in ElizaOS
Improving model selection flexibility for both language models and embedding models
Community requests for OpenRouter integration (related to deployment issues on platforms like Railway where users need reliable OpenRouter model selection)
Risks
Low risk: Adding new model provider option without breaking existing functionality
Configuration complexity may increase with additional model selection options
Potential API rate limiting or cost implications for users switching to OpenRouter models
Need to ensure backward compatibility with existing character configurations
Background
ElizaOS currently has limited model provider options, and users have been requesting better support for OpenRouter as a model provider. OpenRouter …
=> feat: add openrouter to model selection & selection for embedding models

packages/api-client/src/__tests__/services/agents.test.ts
Fixes test functionality for the agents panel component.
=> fix: get agents panel test

packages/cli/src/commands/plugins/actions/install.ts, packages/cli/src/commands/plugins/types.ts, packages/cli/src/commands/plugins/utils/env-vars.ts
This pull request introduces significant improvements to the plugin installation process in the CLI, with a focus on enhancing user experience during environment variable configuration. Key changes include replacing `readline` prompts with the `clack` library for better interactivity, adding support for optional and default values in environment variable configurations, and improving logging and messaging for clarity. Additionally, enhancements were made to streamline the handling of environment variables during plugin setup.
* **Enhanced Prompting for Environment Variables**: Replaced `readline` with `clack` for interactive prompts, enabling better formatting, validation, and support for sensitive inputs. Introduced default values and optional configurations for environment variables. …
=> feat: nicer env prompt experience

bun.lock, packages/cli/src/utils/copy-template.ts
https://github.com/elizaOS/eliza/issues/5292
This pull request includes a small enhancement to the `copyTemplate` function in `packages/cli/src/utils/copy-template.ts`. The change ensures that the `package.json` file is updated with the correct project name based on the target directory, improving consistency between the project name and its directory structure.
=> Set package name in package.json to match target directory

Dockerfile
Low
Fix an error when building docker image
It was failing because `bun run install` resulted with calling `postinstall` hook causing the execution of `scripts/init-submodules.sh`, but the later requires the docker folder to be a git repo which is not the case resulting with the error:
```
Error: Failed to initialize git submodules
```
The script allows to set `SKIP_POSTINSTALL=1` so that it skips that step,
The changes in this PR adds `SKIP_POSTINSTALL=1` before `bun run install` to skip this step resulting of a successful building of the docker image.
```
((HEAD detached at v1.0.13))$ docker build -t eliza .
[+] Building 43.6s (15/24) …
```
=> fix(docker): skip post-install hook during bun install

packages/project-starter/src/plugin.ts
This pull request includes a small change to the `helloWorldAction` in `packages/project-starter/src/plugin.ts`. The change modifies the return value of the function to `true` instead of returning `responseContent`.
=> fix: hello world plugin not returning response

README.md, packages/docs/docs/core/plugins.md, packages/docs/docs/faq.md, packages/docs/docs/quickstart.md
Enhances documentation to clearly communicate that plugin-bootstrap is mandatory for communication and basic agent functionality unless doing heavy customizations.
- **FAQ Section**: Enhanced the "Can I skip the bootstrap plugin?" section to emphasize it's mandatory for communication
- **README.md**: Updated plugin-bootstrap description to highlight it as "Essential communication core" and "Required for basic agent functionality"
- **Core Plugins Documentation**: Added clear warnings about bootstrap plugin requirement and what happens without it
- **Quickstart Guide**: Added important note about plugin-bootstrap being essential for communication
- Clarifies that plugin-bootstrap is **mandatory for communication** unless building custom event handling
- Explains what functionality breaks …
=> docs: enhance plugin-bootstrap requirements documentation

packages/docs/community/Streams/12-2024/2024-12-27.md, packages/docs/packages/plugins/flow-advanced.md, packages/docs/packages/plugins/multiversx.md, packages/docs/static/llms-community.txt
No risk.
fix some minor issues in the comments
=> chore: fix some minor issues in the comments

packages/cli/src/characters/eliza.ts
=> fix: issue with load from dirname

packages/cli/src/commands/start/actions/agent-start.ts, packages/cli/src/commands/start/utils/config-utils.ts
Add automatic synchronization of secrets from local `.env` file for characters that don't have secrets configured.
When characters are stored in the database or loaded from files, they often lack secrets for security reasons. However, agents need these secrets (API keys, tokens, etc.) to function properly. This change implements an automatic fallback mechanism.
- Characters stored without secrets fail to run properly
- Manual secret configuration was required for each character
- No standardized way to handle missing secrets
Implemented automatic secret synchronization that:
1. Checks if character has secrets configured
2. If not, loads secrets from local `.env` file
3. Applies them to character before runtime initialization
- `hasCharacterSecrets(character)` - Validates if secrets exist …
=> chore: update agent secrets when they are empty with local vars

packages/client/src/components/agent-settings.tsx, packages/client/src/components/array-input.tsx, packages/client/src/components/character-form.tsx, packages/client/src/components/plugins-panel.tsx, packages/client/src/components/secret-panel.tsx, packages/client/src/components/ui/input.tsx, packages/client/src/components/ui/label.cy.tsx, packages/client/src/components/ui/label.tsx, packages/client/src/components/ui/select.tsx, packages/client/src/components/ui/tabs.tsx, packages/client/src/components/ui/textarea.cy.tsx, packages/client/src/components/ui/textarea.tsx, packages/client/src/hooks/use-elevenlabs-voices.ts, packages/client/src/hooks/use-server-version.tsx, packages/client/src/index.css, packages/client/src/routes/agent-settings.tsx
- Updated dark theme colors for better contrast and visual consistency
- Fixed form field styling with proper border radius (4px) and increased spacing
- Restructured form element order to follow design pattern: label → input → description
- Increased input height to 48px with proper padding for improved UX
- Removed Card wrapper component for a cleaner, flatter design
- Added consistent spacing between form sections
- Updated typography with lighter label colors and proper font weights
- Modified dark theme CSS variables in 
- Updated Input, Textarea, and Select components with consistent styling
- Refactored CharacterForm component to properly structure form fields
- Adjusted Label component with muted foreground color
- Fixed spacing and layout issues throughout the form
The form now …
=> feat: update agent settings UI to match design specifications

packages/client/src/components/add-agent-card.tsx, packages/client/src/components/agent-card.tsx, packages/client/src/routes/home.tsx
This PR fixes all TypeScript type issues in the home.tsx file to ensure complete type safety.
- Use  enum instead of string literals for status comparison
- Add proper type imports for  and 
- Add explicit type annotations for  and  hooks
- Fix  to accept  parameter
- Add  to  memoized component
- Properly type  group prop with type assertion
- Ensure all map functions have explicit type annotations
- All TypeScript errors have been resolved
- No functionality changes, only type safety improvements
- Verified with  tool - no errors or warnings
Improves type safety as part of ongoing client improvements.
=> fix(client): resolve all type issues in home.tsx for complete type safety

packages/client/src/components/ChatMessageListComponent.tsx, packages/client/src/components/chat.tsx, packages/client/src/components/retry-button.tsx, packages/client/src/components/ui/button.cy.tsx, packages/client/src/components/ui/button.tsx, packages/client/src/components/ui/chat/chat-bubble.tsx, packages/client/src/components/ui/chat/chat-message-list.tsx, packages/client/src/components/ui/chat/chat-tts-button.tsx
This PR refactors the Chat component, including the chat bubble and chat view, to align with the new Figma design. Please note that the group chat design is not finalized yet and will be refactored in a separate PR once the design is complete.
=> feat: chat refactor

packages/client/src/routes/home.tsx
This PR improves the visual styling of the tabs component used for switching between group and DM views.
before:
after:
https://github.com/user-attachments/assets/0bdf2c1b-de68-4277-91c4-727e4055a708
=> feat: update tabs

packages/client/src/components/ChatMessageListComponent.tsx, packages/client/src/routes/home.tsx
This PR reduces the gap between the plus icon and the text as requested by @borisudovicic.
It also reduces the avatar size in group chats as requested by @wtfsayo.
=> feat: tweak ui

packages/client/src/components/app-sidebar.tsx
This PR updates the Sidebar component to align with the new Figma design, improving structure, consistency, and visual clarity.
Updated Agent and Group list sections with consistent headers and new button placements.
Added "Create New" dropdown button for creating agents and groups.
Improved GroupRow layout to display participant avatars with overflow indicators (+N), aligning with the new sidebar aesthetic.
Adjusted padding, hover states, and icon placements to match design specs.
result:
https://github.com/user-attachments/assets/2a9453fa-cc54-493a-b5cf-58cc1479d6db
=> feat: side bar

packages/client/src/components/ui/select.tsx
This PR updates the border radius of the select component from 'rounded' to 'rounded-xl' for a more modern appearance.
=> chore: Update select component border radius

packages/client/src/components/agent-sidebar.tsx
This PR updates the label for the actions tab in the agent sidebar from 'Actions' to 'Model Calls' for better clarity and user understanding.
- Updated the tab label in 
- Changed from 'Actions' to 'Model Calls' to better reflect the actual functionality
N/A - This is a simple text label change in the UI.
=> feat: update actions tab label to 'Model Calls' in agent sidebar

packages/client/src/components/agent-card.tsx, packages/client/src/components/app-sidebar.tsx, packages/client/src/components/connection-status.tsx
This PR improves the UI avatar handling and styling consistency across the client components.
- **Agent Card Component**: Added  utility function for consistent avatar handling
- **App Sidebar Component**: 
- Replaced custom avatar rendering with consistent Avatar component usage
- Improved avatar display in sidebar groups with proper fallbacks
- Enhanced group avatar display with better spacing and border styling
- Removed unused icon imports and cleaned up component structure
- **Connection Status Component**: Updated button styling for consistency
- **Styling Improvements**: Updated styling to use consistent rounded corners throughout
- More consistent avatar rendering across all components
- Better fallback handling for missing avatars
- Improved visual consistency with rounded …
=> feat: improve UI avatar handling and styling consistency

packages/client/src/components/agent-settings.tsx
Replace the local delete function in agent-settings with the existing agentDelete hook.
This improves reusability and keeps the code DRY.
No functional changes; only internal cleanup.
=> fix: use delete hook

packages/docs/versioned_docs/version-0.25.9/changelog.md
Standardized text formatting and corrected spelling inconsistencies
`initital` - `initial`
`enble` - `enable`
=> fix textual inconsistencies in files

packages/client/src/components/media-content.tsx, packages/plugin-bootstrap/src/actions/imageGeneration.ts, packages/plugin-bootstrap/src/actions/index.ts, packages/plugin-bootstrap/src/index.ts
This PR adds a new generateImageAction to the agent pipeline, enabling the agent to generate images based on conversational context using ModelType.IMAGE.
Additionally, this PR removes crossOrigin="anonymous" from the MediaContent component's <img> tag to fix CORS display issues with DALL·E Azure Blob URLs
result:
https://github.com/user-attachments/assets/5bb860cd-d75c-4509-b7c3-22cc9663d4a5
=> feat: image gen action

.github/workflows/release.yaml, bun.lock
=> chore: 1.1.2

bun.lock, lerna.json
This PR merges the latest changes from develop into main.
- Fix: Add bun.lock to .gitignore
- Fix: Improve client path resolution for global installations
=> chore: 1.1.3

bun.lock, lerna.json, packages/client/src/components/chat.tsx
This PR merges the latest changes from develop into main for the v1.1.3 release.
- Bump package versions to 1.1.3 and minor formatting
- Fix: SPA routing fallback and nested button hydration error
- Various bug fixes and improvements
Please see the detailed release notes in the changelog.
=> Release v1.1.4: Merge develop to main

bun.lock, lerna.json, packages/client/cypress/e2e/03-spa-routing.cy.ts, packages/client/src/components/chat.tsx
This PR merges the latest changes from develop into main.
=> Merge develop into main

packages/plugin-forms/src/actions/cancel-form.ts, packages/plugin-forms/src/actions/create-form.ts, packages/plugin-forms/src/actions/update-form.ts, packages/plugin-forms/src/services/forms-service.ts
This PR addresses all critical issues identified by Claude Code in PR #5487:
- ✅ **Form value extraction bug** - Fixed logic to properly handle falsy values (false, 0, empty strings)
- ✅ **Missing return statement** - Added proper ActionResult return in update-form.ts handler
- ✅ **Memory leak** - Fixed cleanup of persistence timer in stop() method
- ✅ **Duplicate cleanup logic** - Consolidated cleanup() and cleanupOldForms() methods
- ✅ **Secret field encryption** - Implemented encryption for secret fields using core crypto utilities
- ✅ **LLM response validation** - Added robust JSON parsing validation to prevent injection attacks
- ✅ **Type validation** - Added proper validation for extracted values against field types
- ✅ **Optimized lookups** - Improved form lookup methods to avoid …
=> fix: address critical issues in forms plugin

packages/core/src/prompts.ts
=> fix typo in prompts.ts

.github/workflows/daily-code-quality-analysis.yml, docs/code-quality-analysis.md, knip.config.ts, scripts/analyze-code-quality.sh, scripts/check-docs-consistency.sh
This PR introduces comprehensive code quality analysis tools and documentation consistency checks to improve the maintainability and quality of the ElizaOS codebase.
- Added daily GitHub Actions workflow for automated code quality checks
- Integrated Knip for dependency analysis (unused exports, dependencies, files)
- Created comprehensive code quality analysis script that runs:
- ESLint for code linting
- TypeScript compilation checks
- Knip for dependency analysis
- Prettier for code formatting validation
- License header validation
- Added documentation consistency check script
- Validates markdown files for proper formatting and structure
- Added `knip.config.ts` with ElizaOS-specific configuration
- Configured to ignore test files and known entry points
- Automated daily code quality …
=> feat: add code quality analysis and documentation consistency tools

.github/workflows/daily-code-quality-analysis.yml
This PR implements a simple workaround for the Claude GitHub Action's limitation where it doesn't support `schedule` or `workflow_dispatch` events.
The Claude action fails with:
- `Unsupported event type: schedule` for scheduled runs  
- `Unsupported event type: workflow_dispatch` for manual runs
According to the [Claude action documentation](https://github.com/anthropics/claude-code-action#supported-github-events), it only supports:
- `pull_request`
- `issue_comment`
- `pull_request_comment`
- `issues` (opened, assigned, labeled)
- `pull_request_review`
- `pull_request_review_comment`
The `schedule` and `workflow_dispatch` events are listed as "coming soon".
Create an issue at the end of manual workflow runs that mentions @claude:
1. **Daily Analysis Runs** - Either scheduled (no issue) …
=> fix: workaround Claude action limitations with issue-based approach

.github/workflows/daily-code-quality-analysis.yml
This PR enhances the daily code quality analysis workflow to enable full automation with Claude, including verbose logging and specific instructions for issue creation.
- Use `GH_PAT` instead of `GITHUB_TOKEN` for issue creation
- Issues are now created by a real user (PAT owner) instead of github-actions[bot]
- Claude will automatically respond since it's not a bot-created issue
- Added `::group::` sections for organized log output
- Descriptive progress messages for each analysis step
- Console output of all statistics and findings
- Total issue count calculation
- Specific prompt to create exactly 5 GitHub issues
- Detailed instructions to check workflow run logs thoroughly
- Structured issue format with example template
- Priority-based issue creation (CRITICAL → HIGH → MEDIUM)
- …
=> feat: enhance code quality workflow with Claude automation

.github/workflows/daily-code-quality-analysis.yml
This PR contains critical fixes for the daily code quality analysis workflow that were discovered after the initial PR was merged.
- Fixed missing file redirection for test framework check output
- The 'None found' message was going to stdout instead of the report file
- Now properly appends to `analysis-results/repo-standards.md`
- Fixed SyntaxError in issue creation step caused by unescaped backticks
- Backticks in code examples within the template literal are now properly escaped
- Prevents 'Invalid or unexpected token' error during workflow execution
- Both fixes have been identified during workflow runs
- File redirection fix was caught by Cursor bot in PR review
- Syntax error was discovered in workflow run: https://github.com/elizaOS/eliza/actions/runs/16222994806/job/45807977437 …
=> fix: critical fixes for code quality workflow

packages/cli/tests/commands/start.test.ts
```
N/A
Low. This PR only modifies test files, improving the accuracy and coverage of existing tests without affecting production code.
This PR fixes the auto-build functionality tests in `packages/cli/tests/commands/start.test.ts`. Previously, these tests incorrectly used the `--help` flag, which caused the `start` command to exit early without executing the main action logic where the auto-build occurs. This PR updates the tests to properly invoke the `start` command, mock the `buildProject` function, and assert on its calls (or lack thereof) under various conditions.
The original auto-build tests were misleading. By using the `--help` flag, they only validated the help text output and never actually tested the core auto-build …
```
=> Fix auto-build test flag usage

packages/plugin-quick-starter/src/plugin.ts
Hi Devs, fixed typo in packages/plugin-quick-starter/src/plugin.ts
dependecies - dependencies
=> fix typo in plugin.ts

packages/cli/src/characters/eliza.ts, packages/docs/packages/plugins/twitter.md, packages/docs/static/packages/plugins/twitter.md
Without this, twitter posting doesn't run.
=> feat: add post examples to default eliza char

.github/workflows/pre-release.yml, .github/workflows/release.yaml, package.json, packages/core/src/utils.ts
This PR contains two main improvements:
- Updated GitHub workflows (pre-release.yml and release.yaml) to use `bunx` instead of `npx` for lerna commands
- Updated package.json clean script to use `bunx` for consistency with the rest of the project
- Refactored `parseKeyValueXml()` function in `packages/core/src/utils.ts`
- Replaced regex-based approach with a safer linear scan implementation
- **Benefits:**
- Avoids potentially expensive regex backtracking with nested XML
- Correctly handles nested tags with the same name
- Improved performance and safety for XML parsing
- Better handling of edge cases like self-closing tags and unbalanced tags
- `.github/workflows/pre-release.yml`: Replace npx with bunx for lerna commands
- `.github/workflows/release.yaml`: Replace npx with bunx for lerna …
=> feat: migrate from npx to bunx and improve XML parser

src/index.ts, tsconfig.json
This PR adds TypeScript path aliases configuration to improve import statements throughout the project.
- ✅ Added `baseUrl` and `paths` configuration to `tsconfig.json`
- ✅ Updated import in `src/index.ts` to use `@` alias instead of relative path
- ✅ Enables cleaner, shorter import paths across the project
- Cleaner and more maintainable import statements
- Easier refactoring when moving files
- Consistent import style throughout the codebase
- Better developer experience with shorter paths
=> feat: Add TypeScript path aliases configuration

packages/server/src/api/messaging/__tests__/sessions.test.ts, packages/server/src/api/messaging/channels.ts, packages/server/src/api/messaging/errors/SessionErrors.ts, packages/server/src/api/messaging/sessions.ts, packages/server/src/index.ts, packages/server/src/types/sessions.ts
This PR significantly enhances the sessions API with comprehensive timeout management, auto-renewal capabilities, and robust error handling. The changes transform the basic session management into an enterprise-ready system with configurable lifecycles, warning states, and graceful cleanup mechanisms.
**Before:** Simple fixed timeout (`SESSION_TIMEOUT_MS`)
**After:** Multi-layered timeout configuration with:
- Configurable timeout minutes (5-1440 min range)
- Auto-renewal capabilities
- Maximum session duration limits
- Warning threshold notifications
- Agent-specific timeout settings
- Session-specific overrides
**Before:** Basic `errorResponse` function with generic error messages
**After:** Comprehensive error system with:
- 11 custom error classes (`SessionNotFoundError`, …
=> feat: Sessions API ++

.gitignore, packages/core/build.ts, packages/core/package.json, packages/core/src/entities.ts, packages/core/src/logger.ts, packages/core/src/roles.ts
This PR fixes issues with the browser build of the core package and improves type definitions.
- **Package.json exports**: Updated to use `.node.js` and `.browser.js` suffixes for better clarity
- **Deno support**: Added `deno` export condition for improved Deno compatibility
- **Type definitions**: Fixed to re-export from source modules instead of compiled output
- **Fallback declarations**: Added fallback declaration files for both node and browser builds
- **entities.ts**: Added explicit type annotation to `results` array
- **logger.ts**: Added explicit type annotation for `stream` variable
- **roles.ts**: Added explicit type annotation to `ownerWorlds` array
- Added `standalone.ts` to `.gitignore`
- Minor formatting improvements
1. **Browser builds were not properly resolving types** …
=> fix: Improve browser build exports and type definitions

standalone.ts
This PR adds comprehensive documentation to the  file to improve developer experience and understanding.
- **Added detailed JSDoc header** explaining the purpose and use cases of the standalone agent runner
- **Documented key differences** from the full ElizaOS CLI/server setup
- **Included clear prerequisites** (OPENAI_API_KEY, optional database configs)
- **Provided usage examples** for different configurations
- **Outlined architecture flow** of the 5-step initialization process
The  file is an important entry point for developers who want to:
- Learn ElizaOS core architecture without server overhead
- Test agent behaviors in isolation
- Integrate ElizaOS agents into custom applications
- Debug agent functionality during development
Previously, this file lacked any contextual …
=> feat: add comprehensive documentation to standalone agent runner

packages/project-tee-starter/README.md
=> docs: fix broken path

packages/plugin-bootstrap/src/index.ts
related: https://github.com/elizaOS/eliza/pull/5865#discussion_r2317180747
=> fix: Unhandled Promise in Action Update

standalone-cli-chat.ts, standalone.ts
- Add new standalone CLI chat interface (`standalone-cli-chat.ts`)
- Enhanced interactive chat experience with improved UX
- Version alignment to 1.5.8-alpha.1 across all packages
- Updated TypeScript configuration
- Interactive command-line chat interface using ElizaOS agents
- Similar to AI SDK's streamText but using ElizaOS runtime and plugins
- Support for LOG_LEVEL and OPENAI_API_KEY configuration
- Clean exit commands (quit/exit)
- Proper text wrapping and formatting
- 19 files modified (primarily version updates and new chat interface)
- 431 insertions, 39 deletions
- Standalone chat interface tested with OpenAI integration
- All existing functionality preserved
=> feat: Add standalone CLI chat interface with improved UX

packages/client/vite.config.cypress.ts, packages/client/vite.config.ts
Enhances debugging capabilities by enabling sourcemaps and preserving function names for better stack traces.
Ensures a single React instance to prevent version conflicts and related errors.
=> feat: Improves client debugging and React version handling

packages/server/src/index.ts
This PR introduces Sentry's Vercel AI integration to improve monitoring and error tracking for deployments on Vercel. It also includes minor code formatting changes.
=> feat: Add Sentry Vercel AI integration

packages/cli/src/commands/scenario/docs/README.md
=> docs: fix typo
