elizaOS/eliza

- README.md
The original command produces this: 
The documentation shows the correct command is `npx --no node-llama-cpp source download --gpu cuda`
> corrected node-llama-cpp command

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
resolves #61
This add 2 ew issue templates so that when users create a new issue for us, they have some guidance.
> adding github issue templates

- .github/workflows/generate-changelog.yml
Adding a github action for generating a CHANGELOG.md file automatically when a new tag is created.
Closes #181
low
Add a github action that create a CHANGELOG.md file
1. create a new tag
2. verify that a changelog was added to the repo
> 181  generate changelog

- core/.env.example
- core/src/core/generation.ts
- core/src/core/models.ts
- core/src/core/types.ts
Adding Groq API support to expand model provider options
Low - This is an additive change that doesn't modify existing provider functionality
Adds support for Groq (https://groq.com/) as a model provider, allowing use of Groq's API for text generation. 
My changes require a change to the project documentation to document Groq as a supported provider.
1. Check the Groq implementation in `core/src/core/generation.ts`
2. Review the model configuration for Groq
3. Test text generation using Groq provider
1. Set up environment with Groq API key
2. Configure character to use ModelProvider.GROQ
3. Test text generation:
```typescript
const runtime = new AgentRuntime({
modelProvider: ModelProvider.GROQ,
// other config...
});
const response = …
```
> Groq api integration

- docs/docs/guides/basic-usage.md
- docs/docs/guides/configuration.md
- docs/docs/intro.md
Low risk, just updating docs.
This PR is to update the Eliza documentation for ai16z.
Updates documentation around Eliza.
Additional Documentation
To improve documentation.
They are seen in the PR
N/A
Intro, Basic-Usage, and Configuration
n/a
-->
Merge to main
> Updated documentation

- core/src/services/llama.ts
Lazy loads llama from llama.ts so we don't try to install it immediately.
> lazy load llama

- core/.env.example
- core/package.json
- core/src/core/embedding.ts
- core/src/core/generation.ts
- core/src/core/models.ts
- core/src/core/types.ts
- core/src/services/LlamaCppService.ts
- core/src/services/OllamaService.ts
- core/src/services/llama.ts
(https://github.com/ai16z/eliza/issues/69)
OLLAMA Provider parts low risk
medium risk how the dependency ollama-ai-provider was added
llama.ts delegating to LlamaCppService or OllamaService high risk (because it was was crashing nodemon so wip but still a change that might be good to look at) 
All documentation needed is in the .env file. Did not update the readme. but i can if needed
run with a OLLAMA_MODEL defined to something & the OLLAMA_EMBEDDING_MODEL set to something
> Add OLLAMA as Model Provider 

- .env.example
- README.md
- packages/core/src/generation.ts
- packages/core/src/models.ts
- packages/core/src/runtime.ts
- packages/core/src/types.ts
- pnpm-lock.yaml
No issue for ticket for this yet.
Low risk.
This PR adds support for the Google models, which are represented in the types but not implemented in the generation file.  Adds env ket to example env file and main readme env example.
Just need Google models to work.
Switch the character to use ModelProviderName.GOOGLE and ensure you have the API key for Gemini in your env:
GOOGLE_GENERATIVE_AI_API_KEY= # Gemini API key
Things should continue to run.
> Support google models in generation

- packages/adapter-postgres/src/index.ts
PG Adapter wasn't working properly due to case insensitivity on calls
Low
Adding proper quotes around column names in SQL queries
Fixing JSONB field access syntax in cached embeddings query
Adding fuzzystrmatch extension for text similarity searches
Adding additional performance indexes
Improving error handling and logging
None, automtated tests are fine.
> Working PostGres Adapter

- .env.example
- packages/core/src/embedding.ts
.env variable for setting to use openai embedding
added this flag into embeddings.ts logic
> use openai embeddings setting

- packages/adapter-postgres/seed.sql
- packages/core/src/embedding.ts
decouple calls to create embedding from runtime 
made embed function use these
fixed the seed.sql for postgres
> refactor embeddings 

- packages/core/src/embedding.ts
if using openai embeddings is true always use the endpoint
embedding model from the provider being used still. That needs to be set to an openai model when openai is set to true. most of the modelprovider classes have the openai embedding model set as there embedding model already so it works
> embedding set to use openai endpoint when using openai embeddings

- packages/core/src/generation.ts
- packages/core/src/logger.ts
Let's add verbose with logger config.
Most log output will use logger.debug write infomation , with the verbose = true.
When developer want quite , they can change the verbose = false.
> add verbose config with logger

- docs/src/components/HomepageFeatures/index.js
No Relation
None
It fixes the fucked up font in the Docs / GitHub pages when using Darkmode.
No rocket science.
Styling improvements:
* Changed the card background color to use the CSS variable `--ifm-card-background-color` instead of a fixed RGBA value.
* Added a CSS variable `--ifm-font-color-base` for the card text color.
* Updated the heading color to use the CSS variable `--ifm-heading-color`.
Check out locally, cd into docs, run dev and looky looky
> fix: docs features darkmode color

- packages/agent/src/index.ts
If settings is empty this blows up looking for the WALLET_PUBLIC_KEY, let's not do that
"settings": {
"secrets": {
"WALLET_PUBLIC_KEY": "DM1fSD9KfdJ2jaSmR9NGpPPVcDzBwsYg1STttYc5Bvay"
}
},
> Don't blow up if the wallet is missing

- README.md
- docs/README.md
- docs/docs/api/index.md
- docs/docs/community/faq.md
- pnpm-lock.yaml
Add python as a prerequisite
Low: installation fails on pnpm install {reproduced on windows}. It's fixed after installing python and adding path to the env variables,
add python as a prerequisite to the documentation (needed for node-gyp)
> fix docs: add python as a prerequisite (needed for node-gyp)

- .gitignore
- packages/agent/src/index.ts
#295
**Low:** This change is low risk, as it only introduces a new case for an additional model provider in an existing switch statement. 
This PR adds initialization for the `GROK` model provider key in the `getTokenForProvider` function. Previously, the function did not handle the `GROK` model provider, potentially leading to issues if the provider was selected without a corresponding key.
- **Feature:** This is a non-breaking change that adds functionality by supporting a new model provider (`GROK`).
Yes
The review should focus on the `getTokenForProvider` function in the relevant file, ensuring that the added `GROK` case aligns with the structure of other model provider cases.
- Confirm that selecting `ModelProviderName.GROK` successfully returns the appropriate API key from …
> Added missing GROK model provider key initialization

- packages/plugin-solana/src/actions/transfer.ts
- packages/plugin-solana/src/index.ts
This allows the agent to send tokens if action is enable on the solana plugin
There is no verification logic set but examples is commented out that would required Admin User Ids
Whatever is good logic for trust & approval will need to be thought out
Action is not enabled by default
> Added Transfer / Send Token Action

- .env.example
- packages/client-discord/src/index.ts
- packages/client-telegram/src/index.ts
- packages/plugin-image-generation/src/index.ts
image gen does not return caption or description anymore (not really needed)
it generates image & returns the path to image in context
this will allow discord to poast image
other clients need updated handle & sends
-tg _shouldRespond & action context adding never even called
-tg agent wasnt even starting (fixed this on main)
-will look into twitter client as well
> image gen saves file & returns format for clients; discord image poasting just works

- .gitignore
- README_CN.md
- docs/README_CN.md
- docs/docs/api/_media/README_CN.md
- docs/docs/guides/local-development.md
- docs/docs/quickstart.md
- packages/agent/package.json
- packages/agent/src/index.ts
- packages/core/package.json
- packages/plugin-solana/src/actions/transfer.ts
- packages/plugin-solana/src/index.ts
- pnpm-lock.yaml
replace ts-node with tsx on @ai16z/agent
[Issue #288](https://github.com/ai16z/eliza/issues/288)
Low – This change impacts only the TypeScript execution environment by replacing `ts-node` with `tsx`, improving compatibility without affecting core functionality.
- Replaces `ts-node` with `tsx` to provide better support for handling `.ts` files within the Node.js environment.
- Bug fixes (non-breaking change that fixes an issue).
Replacing `ts-node` with `tsx` resolves an issue with `pnpm start` failing due to `.ts` file handling issues in this environment setup.
- My changes require a change to the project documentation.
- I have updated the documentation accordingly.
Start by verifying the setup instructions and running `pnpm start` to confirm the fix.
1. Install dependencies with `pnpm …
> replace ts-node with tsx on @ai16z/agent - fix #288

- README.md
- README_PTBR.md
None
Add Portuguese README
Translation
> docs: add a new Portuguese README version

- docs/docs/quickstart.md
#298 
> pnpm run shell not valid
Medium. I'm not 100% on the updates but asked the community on anything I'm unsure about
Updates Quickstart post-refactor
- be specific about tag/node version
- add helpful links
- be specific about the characters directory
- remove top mention of optional sharp since it's installed by default now (left in Common Issues just in-case)
- run shell => start
My change is a documentation change
> Update Quickstart Guide

- scripts/build.sh
- Builds the core package: @ai16z/eliza first
- Excluded the "agent" package from the build process with a specific message.
- Enhanced readability with formatted output for better user experience.
> fix: Build error for packages requiring @ai16z/eliza

- README.md
#317 getting the tests working
None
Improves README documentation about how to run tests and how docker works
Dev-facing documentation improvement
> Docs: README.md improvements: clarify testing, add additional docker information

- docs/docs/quickstart.md
#298 
Low to none
Improve quickstart:
- break up step by step command into individual blocks so copy&paste functions integrates easier with user's needs
- improves some visual formatting in source and render
- improves accuracy of character section, including being explicit which character when starting to reduce confusion
- also clarify common issues and add a bit more help to last item
Documentation update
no, it is a doc change
> Docs: additional Quickstart clarification and improvements

- packages/client-discord/src/messages.ts
- packages/client-telegram/src/messageManager.ts
- packages/core/src/types.ts
Low to none
Adds clientConfig to Character type and handle ignore DM and ignore bots logic in Telegram & Discord clients
An improvement to prevent abuse
Bots keep draining each other's credits in #the-arena. On Telegram, they are also affected by buy bots etc. I think "ignoreBots" configuration option is needed. DMs are also a concern because it's easy to purchase Telegram/Discord accounts and drain anyone's credits. The "[IGNORE]" feature alone is not a sufficient solution. 
Add
`"clientConfig": {
"discord": {
"shouldIgnoreBotMessages": true,
"shouldIgnoreDirectMessages": true
},
"telegram": {
"shouldIgnoreBotMessages": true,
"shouldIgnoreDirectMessages": true
}
}` to character.json file. All fields are optional.
> added clientConfig to optionally ignore bots and DMs

- packages/client-twitter/src/post.ts
Adjusts existing randomized posting interval from 1-4 hours to 90-180 minutes (1.5-3 hours) to help with account restrictions until better solution is implemented.
- Modified existing interval in `generateNewTweetLoop` from 1-4 hours to 90-180 minutes
- Updated interval calculation: `(Math.floor(Math.random() * (180 - 90 + 1)) + 90) * 60 * 1000`
- Changes posting range from 6-24 to 8-16 posts per day
This adjustment helps better align with Twitter's usage patterns and provides more consistent posting frequency. A more sophisticated system could be considered that:
- Could support configurable posting patterns (uniform, normal, life-cycle based)
- Could allow custom range settings
- Could include rate limit handling
- Could add more natural posting behaviors
- Verified interval generation …
> update tweet interval to 90-180 mins

- renovate.json
The Renovate file was removed somewhere along the lines which helps us do automated security scanning and package dependency updates. This adds it back into the dev branch.
Low
> feat: adding back the renovate file for automated security scanning

- packages/core/README-TESTS.md
- packages/core/jest.config.js
- packages/core/src/embedding.ts
- packages/core/src/tests/database.test.ts
- packages/core/src/tests/defaultCharacters.test.ts
- packages/core/src/tests/evaluators.test.ts
- packages/core/src/tests/goals.test.ts
- packages/core/src/tests/messages.test.ts
- packages/core/src/tests/models.test.ts
- packages/core/src/tests/posts.test.ts
- packages/core/src/tests/providers.test.ts
- packages/core/src/tests/relationships.test.ts
- packages/core/tsconfig.json
https://github.com/ai16z/eliza/issues/64
https://github.com/ai16z/eliza/issues/340
low - Only tests are affected
Unit tests as a starter
Includes tests for core package
Improvements/Features
Adding basic unit tests is a good starter for having good Testing/Quality Assurance process
Yes, but not in the main Documentation, README-TESTs.md is added for test documentation
Running the tests and making sure they are valid.
In packages/core 
Navigating to packages/core folder, runing pnpm install, pnpm test to run tests
> feat: Adding unit tests for start - Covering goals, defaultCharacters, relationships, evaulators, posts, database, messages

- packages/core/src/generation.ts
- packages/plugin-image-generation/src/index.ts
This PR enhances Heurist image generation by adding improved default parameters (guidance scale: 3, deadline: 60s, priority: 1) and implementing robust error handling. It also introduces dedicated Heurist image handling functionality with proper URL validation and API key checks.
> feat: Enhance Heurist Image Generation Settings and Image Handling

- packages/core/src/models.ts
Openrouter 70b model token limit is lower than what we want to send, which end up throwing errors from API.
Lowering token limit makes outputs less quality, instead we upgraded small model to 405b in model.ts
low
Upgraded openrouter small model to 405b
bug fix
set Modelprovider to openrouter in character.json
pnpm start
> fix: openrouter 70b don't support 128000, changed to 405b in model.ts

- packages/plugin-solana/src/providers/wallet.ts
The CA of BTC was fake/wrong one. Changed it to correct address 
Previous Address = https://birdeye.so/token/qfnqNqs3nCAHjnyCgLRDbBtq4p2MtHZxw8YjSyYhPoL?chain=solana
New Address = https://birdeye.so/token/3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh
High
Changed the CA
> fix: ca for btc was spam/fake

- README_ES.md
> feat: Create README_ES.md

- packages/core/src/runtime.ts
Low. This change introduces a new feature to register memory managers, which should not affect existing functionality.
This PR adds functionality to register memory managers if they are passed to the runtime. It iterates through the `managers` array in the `opts` object and calls `registerMemoryManager` for each manager.
The reviewer should start by examining the `AgentRuntime` class in the `packages/core/src/runtime.ts` file, focusing on the new code block that registers memory managers.
- Verify that the `AgentRuntime` class correctly initializes with the new code block.
- Test passing an array of memory managers to the runtime options and ensure they are properly …
> Register memory managers if passed to runtime

- README_FR.md
- docs/README_FR.md
Nothing in particular, just reading the specification and updating it.
None : documentation
Rewrites the French documentation in native French
Documentation change.
I have updated the documentation accordingly.
None required
> docs: Update README_FR.md

- packages/agent/src/index.ts
Low
adds Groq model provider to Agent getTokenForProvider
Bug fixes: Not loading Groq keys
> fix: adds Groq to getTokenForProvider

- packages/core/src/tests/videoGeneration.test.ts
- packages/plugin-video-generation/package.json
- packages/plugin-video-generation/src/constants.ts
- packages/plugin-video-generation/src/index.ts
- packages/plugin-video-generation/tsconfig.json
- packages/plugin-video-generation/tsup.config.ts
Relates to:
video generation
Risks
Low - Changes are contained within the video generation plugin and don't affect other functionality. Main risk is failed video generation or attachment, which is handled gracefully with error messages.
Background
Fixes video generation plugin to properly handle the Luma AI API response and correctly attach generated videos to Discord messages.
Plugin
Why are we doing this? Any context or related work?
adding video gen feature
Documentation changes needed?
Yes, adding LUMA LABS API to env.example
Testing
As a user, send a message to generate a video:
Send "Generate a video of a sunset"
Verify bot responds with "I'll generate a video based on your prompt"
Wait for video generation (about 1-2 minutes) …
> feat: video generation plugin

- README.md
- packages/agent/src/index.ts
- packages/client-direct/src/index.ts
- packages/client-discord/src/actions/download_media.ts
- packages/client-discord/src/attachments.ts
- packages/client-discord/src/index.ts
- packages/client-discord/src/messages.ts
- packages/client-discord/src/voice.ts
- packages/client-telegram/src/messageManager.ts
- packages/client-telegram/src/telegramClient.ts
- packages/client-twitter/src/base.ts
- packages/client-twitter/src/index.ts
- packages/client-twitter/src/interactions.ts
- packages/client-twitter/src/post.ts
- packages/client-twitter/src/search.ts
- packages/core/src/generation.ts
- packages/core/src/runtime.ts
- packages/core/src/tests/goals.test.ts
- packages/core/src/types.ts
- packages/plugin-node/src/index.ts
- packages/plugin-node/src/services/image.ts
- packages/plugin-node/src/services/index.ts
- packages/plugin-node/src/services/llama.ts
- packages/plugin-node/src/services/pdf.ts
- packages/plugin-node/src/services/speech.ts
- packages/plugin-node/src/services/transcription.ts
- packages/plugin-node/src/services/video.ts
- pnpm-lock.yaml
There was a bug within the services singelton pattern that cause the incorrect serivce to be called when multiple ones were used.
This changes the architecture so this doesn't happen.
> feat: services

- docs/docs/packages/adapters.md
I found I needed these schemas (ported from the supabase migration) in order to successfully run an agent with the discord client
> fix: Update adapters.md psql schema

- packages/agent/src/index.ts
Low
If you specify a file to load, don't just load default and continue if you can't find it
UX clean up, should reduce confusion and reduce support issues
I tested on stable-11-17 branch
> fix: don't continue to load if a specified file is not found

- docs/docs/community/contributing.md
No specific issue linked. Adding PR templates as part of process improvements.
Low: Adding templates and updating documentation does not impact code or production systems.
This PR updates the `CONTRIBUTING.md` file to include details about the new PR templates. It informs contributors about the location of the templates and how to use them when creating a pull request.
- Documentation update (non-breaking change).
To improve contributor onboarding and ensure a standardized process for submitting pull requests.
My changes require a change to the project documentation.  
I have updated the `CONTRIBUTING.md` file to reflect the new templates.
Review the changes made to the `CONTRIBUTING.md` file. Check that the instructions are clear and accurate.
1. Navigate to the `CONTRIBUTING.md` file. …
> docs: Update contributing.md to incorporate Contribution Guidelines

- README_IT.md
- agent/src/index.ts
- docs/docs/core/agents.md
- docs/docs/core/evaluators.md
- packages/core/src/runtime.ts
- packages/core/src/test_resources/createRuntime.ts
- packages/core/src/test_resources/testSetup.ts
- packages/core/src/tests/env.test.ts
- packages/core/src/tests/goals.test.ts
- packages/core/src/tests/messages.test.ts
- packages/core/src/tests/models.test.ts
- packages/core/src/tests/relationships.test.ts
- packages/core/src/tests/token.test.ts
- packages/core/src/tests/videoGeneration.test.ts
- packages/core/vitest.config.ts
- packages/plugin-video-generation/src/constants.ts
- packages/plugin-video-generation/src/index.ts
- packages/plugin-video-generation/tsup.config.ts
- pnpm-lock.yaml
> fix: linting and imports ready for npm

- README.md
- packages/core/src/settings.ts
Medium, haven't discussed this widely
Removes the requirement for .env to exists
Improvement
Large multiagent instances will have to rely on character.json to have all the settings and secrets for that agent. Have a default .env in these instances to set defaults might be helpful but also hurtful. This allows the admin to choose if they want any defaults across all their agents or nots.
Ran against stable-11-17 branch without issue
> feat: don't require .env to exist

- agent/src/index.ts
Medium, may affect npm packaging
fixes
`Error loading character from ../../characters/trump.character.json: Error: ENOENT: no such file or directory, open '../../characters/trump.character.json'`
when running it like
`pnpm start --characters="characters/trump.character.json" from the repo on 0.1.1`
Loaf asked
I ran a quick test
> fix: since agent is moved out of packages, adjust default path

- packages/core/src/embedding.ts
- packages/core/src/generation.ts
- packages/core/src/parsing.ts
- packages/core/src/test_resources/createRuntime.ts
- packages/core/src/tests/goals.test.ts
*No specific issue linked - appears to be a code quality improvement PR*
Low - Changes are purely related to code style and import organization with no functional changes.
This PR addresses linting issues in the codebase by:
1. Reorganizing and consolidating imports
2. Removing unused imports
3. Removing empty catch variable declarations
4. Fixing import ordering
5. Removing extra blank lines
Review the changes in the following files:
- packages/core/src/embedding.ts
- packages/core/src/generation.ts  
- packages/core/src/parsing.ts
No, automated tests are fine. These changes are purely syntactic and don't affect functionality.
The changes include:
1. Import reorganization
2. …
> fix: Fix linter issues

- packages/core/src/runtime.ts
the character style should always be followed,
because the use expects this when designing their character and also this will reduce slop content more than anything
if the user puts "no slop" as a style instruction for prompting, there was a %50 chance that would get picked up
this is a modification that for style it should be all of the characters style added for each post or message
additional ideas in the issues/features:
https://github.com/ai16z/eliza/issues/438
> feat:  add all the style guidelines to the context

- packages/client-discord/src/actions/joinvoice.ts
- packages/client-discord/src/voice.ts
(No linked issue provided in the diff)
Low - Changes only affect voice channel behavior for the Discord bot, specifically its deafened/muted state when joining channels.
This PR fixes an issue where the Discord bot was joining voice channels in a deafened state by default. The changes include:
1. Explicitly setting the bot to undeafened and unmuted when joining voice channels
2. Improved voice connection cleanup by clearing streams and monitors when destroying old connections
3. Added error handling for voice connections
4. Refactored voice channel join logic to use VoiceManager instead of direct joinVoiceChannel calls
Bug fix (non-breaking change which fixes an issue)
1. Review the changes in …
> fix: The bot is by default deafened and we don't want that

- .prettierignore
- README.md
- packages/client-discord/src/actions/joinvoice.ts
- packages/core/src/generation.ts
- packages/core/src/runtime.ts
- packages/core/src/test_resources/createRuntime.ts
> feat: readme and linting

- packages/create-eliza-app/README.md
- packages/create-eliza-app/package.json
- packages/create-eliza-app/registry/eliza.json
- packages/create-eliza-app/src/index.ts
- packages/create-eliza-app/tsconfig.json
- pnpm-lock.yaml
This PR adds a cli tool `create-eliza-app` and a registry folder for it.
It's currently pointed to the eliza-starter repo's main branch.
> feat: create-eliza-app

- packages/core/src/generation.ts
https://github.com/ai16z/eliza/issues/443
Low: almost none, just switching to the correct logger.
Using ollama appeared chattier than other providers which is why the bug was reported, but that seems to be just because the wrong logger was used accidentally
switch to elizaLogger
No
Ran against my ollama to repro bug
```
modelClass small
Initializing Ollama model.
****** MODEL
llama3.2
Received response from Ollama model.
Initializing Ollama model.
****** MODEL
llama3.2
Received response from Ollama model.
Initializing Ollama model.
****** MODEL
llama3.2
Received response from Ollama model.
Initializing Ollama model.
****** MODEL
llama3.2
Received response from Ollama model.
```
changed offending lines in …
> ollama generate case was using console.debug. 

- packages/client-twitter/src/base.ts
- packages/client-twitter/src/index.ts
- packages/client-twitter/src/interactions.ts
- packages/client-twitter/src/post.ts
- packages/client-twitter/src/search.ts
- packages/client-twitter/src/utils.ts
- packages/core/src/generation.ts
- packages/core/src/memory.ts
- packages/core/src/runtime.ts
> feat: Twitter Refactor

- packages/core/src/generation.ts
This PR fixes the issue of OpenAi object initialization which ignores the `modelEndpointOverride` optioin of the character
> fix: ignored modelEndpointOverride in generation

- agent/src/index.ts
> fix: agent loadCharacters file resolver

- packages/adapter-postgres/tsup.config.ts
- packages/adapter-sqlite/tsup.config.ts
- packages/adapter-supabase/tsup.config.ts
- packages/client-auto/tsup.config.ts
- packages/plugin-image-generation/tsup.config.ts
- packages/plugin-node/tsup.config.ts
- packages/plugin-starknet/tsup.config.ts
preparing the project with `sh scripts/start.sh`
LOW
I don't foresee any risks
When I run `sh scripts/start.sh`, I get errors about some packages not being able to be resolved, this seems to be the solution.
Adds the missing packages to tsup confgs' externals so that they can be resolved.
Bug fix
Issue with starting to work with the codebase
I ran `sh scripts/start.sh` until it didn't produce errors in the building stage.
This is pretty small and manageable.
None, automtated tests are fine.
massivefermion
> fix: added missing packages to tsup configs' externals

- docs/docs/community/best-practices.md
- package.json
- packages/plugin-starknet/package.json
- packages/plugin-trustdb/package.json
- scripts/test.sh
Eliza community’s best practices documentation
Low risk. This PR focuses on updating documentation to reflect the latest best practices for submitting pull requests, including pre-review with AI and template usage. No functional code changes are involved.
This PR updates the contributing guidelines to include new best practices for pull request submissions. It adds a recommendation for conducting pre-reviews using AI tools, elaborates on the use of PR templates, and emphasizes the importance of squashing commits.
- **Documentation**: This PR add the best practices documentation to streamline the contribution process and make it more consistent for all team members.
My changes require an update to the project documentation. The best practices guidelines have been added to include …
> docs: Create best-practices.md documentation

- docs/docs/quickstart.md
For the Twitter-related `.env` file, `TWITTER_COOKIES` requires a specific JSON format with relevant information. Without an example, new developers may have difficulty configuring the Twitter environment.
Added an example for `TWITTER_COOKIES`.
> feat: Added TWITTER_COOKIE example on quickstart.md

- packages/client-discord/src/actions/summarize_conversation.ts
- packages/client-discord/src/messages.ts
- packages/client-github/src/index.ts
- packages/core/src/generation.ts
- packages/core/src/index.ts
- packages/core/src/knowledge.ts
- packages/core/src/runtime.ts
- packages/core/src/types.ts
- packages/plugin-bootstrap/src/evaluators/fact.ts
- packages/plugin-bootstrap/src/index.ts
Improves knowledge content normalization, improves chunking bleed logic, extracts some knowledge methods to their own module.
Previously knowledge would use the embedding match fragment directly, this changes the behavior to fetch the full knowledge document for the context, allowing us to improve embedding lookup performance by reducing fragment sizes
> feat: Improve knowledge embeddings

- packages/core/src/types.ts
- packages/plugin-node/src/services/browser.ts
- packages/plugin-node/src/services/image.ts
- packages/plugin-node/src/services/pdf.ts
- packages/plugin-node/src/services/speech.ts
- packages/plugin-node/src/services/transcription.ts
- packages/plugin-node/src/services/video.ts
- implements improved interface saftey
> feat: improve type saftey

- .github/workflows/pre-release.yml
- agent/src/index.ts
- packages/adapter-postgres/src/index.ts
- packages/client-discord/src/actions/summarize_conversation.ts
- packages/core/package.json
- packages/core/src/embedding.ts
- packages/core/src/generation.ts
- packages/core/src/knowledge.ts
- packages/core/src/memory.ts
- packages/core/src/types.ts
- packages/plugin-bootstrap/src/providers/facts.ts
- packages/plugin-node/src/services/transcription.ts
- packages/plugin-node/src/services/video.ts
- pnpm-lock.yaml
- fixes types
- improves split chunks
> fix: improve embeddings

- docs/docs/guides/template-configuration.md
This PR adds comprehensive documentation for template and client configurations, helping users better understand and customize their character's behavior across different platforms.
- Add new template and client configuration guide
- Document all available template override options
- Add client configuration settings for bot and DM handling
- Include JSON examples for both templates and client configs
- Add best practices section for configuration management
- Verified all JSON examples are valid
- Checked documentation formatting and structure
- Ensured consistency with existing docs
This documentation aims to make it easier for users to:
- Override default prompt templates
- Configure platform-specific behaviors
> docs: add template and client configuration guide

- packages/core/src/embedding.ts
Non node.js environments may have issues building because of some packages and how they are imported.
##To Reproduce
Make a worker, include eliza/core and attempt to build. It will throw an error similar to
✘ [ERROR] No loader is configured for ".node" files:
node_modules/@anush008/tokenizers-darwin-universal/tokenizers.darwin-universal.node
node_modules/@anush008/tokenizers/index.js:116:32:
116 │ ... nativeBinding = require('@anush008/tokenizers-darwin-universal')
Expected behavior
This PR wraps the import in try catch to gracefully fail and allow the build.
> Wrap `fastembed` in try catch to allow non node environments to build

- SECURITY.md
- packages/plugin-node/src/services/llama.ts
github actions failed with a lint error for llama.ts for unused variable
security.md failed to pass the commit call out - had to do reformatting
> fix: Ollama fix

- agent/src/index.ts
- packages/adapter-postgres/src/index.ts
- packages/client-telegram/src/index.ts
- packages/client-telegram/src/messageManager.ts
- packages/client-telegram/src/telegramClient.ts
- packages/plugin-node/src/services/llama.ts
- fixes telegram image service
- fixes ollama init
> fix: Fix/telegram

- packages/client-twitter/src/base.ts
- packages/client-twitter/src/interactions.ts
Tweet IDs are ranging beyond JS integer support
Low. Should be a straight bug fix.
Replaces the usage of `number` by `biting` to store the `lastCheckedTweetId` in the twitter client.
Bug fix
Tweet IDs are in the range of 2^60, which is more than Javascript can safely handle.
Running a twitter client will work but the numbers get silently rounded.
Steps:
- Run an agent with the twitter client. Log the values of `lastCheckedTweetId`.
> fix: Use BigInt for tweet IDs in client-twitter

- packages/core/src/generation.ts
> fix: generateText format consistency

- docs/docs/quickstart.md
https://github.com/ai16z/eliza/issues/558
Low
Faced auth issues trying to setup a twitter client with cookies
Changes the docs to the correct cookies format.
Also added a (not really important) line about other env variables when using cookies.
Documentation
Documentation misleading, causes error when trying to use it
If a docs change is needed: I have updated the documentation accordingly.
Just try to setup a twitter client using the format provided in the docs.
Cheers, thanks for the amazing work
> Improved Twitter Documentation

- packages/adapter-sqlite/src/index.ts
Low
got this error on startup after updating main:
```
Error handling message: SqliteError: near "type": syntax error
at Database.prepare (/eliza/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
at SqliteDatabaseAdapter.searchMemoriesByEmbedding (/eliza/packages/adapter-sqlite/dist/index.js:332:30)
at SqliteDatabaseAdapter.createMemory (/eliza/packages/adapter-sqlite/dist/index.js:250:42)
at MemoryManager.createMemory (/eliza/packages/core/dist/index.js:2322:40)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async MessageManager.handleMessage (/eliza/packages/client-discord/dist/index.js:1953:9) {
code: 'SQLITE_ERROR'
}
```
Fixes SQL for searching memories from:
```
SELECT *, vec_distance_L2(embedding, ?) AS similarity
FROM memories
WHERE …
```
> fix: sql command

- packages/plugin-coinbase/package.json
The plugin from coinbase doesnt use playwright this was probably copied from plugin-node
> fix: remove postinstall script from plugin-coinbase

- agent/src/index.ts
- packages/adapter-postgres/src/index.ts
- packages/client-discord/src/voice.ts
- fixes type issue with postgres
> fix: postgres

- packages/plugin-solana/src/providers/token.ts
- packages/plugin-starknet/src/providers/token.ts
#467
Fixes bug in getHighestLiquidityPair token providers
Bug Fix
> fix: Token provider getHighestLiquidityPair

- .github/workflows/ci.yaml
- packages/core/src/defaultCharacter.ts
- packages/core/src/tests/goals.test.ts
Low
Enables running tests as part of CI
Improvement
We need to make sure no breaking changes (regressions) are introduced with new PRs
locally run tests
tests run in CI
None, automtated tests are fine.
piotrg5517
> fix: enable test run in CI for core package

- packages/client-direct/src/index.ts
Better downloaded file messages and handling
> Download updates

- packages/client-discord/src/messages.ts
- canSendMessage guard
- don't call it twice in handleMessage
Low
Fixes
```
Error handling message: TypeError: Cannot read properties of null (reading 'type')
at canSendMessage (file:///root/edward/packages/client-discord/dist/index.js:1727:17)
at MessageManager.handleMessage (file:///root/edward/packages/client-discord/dist/index.js:1833:18)
node:events:485
throw er; // Unhandled 'error' event
^
TypeError: Cannot read properties of null (reading 'type')
at MessageManager.handleMessage (file:///root/edward/packages/client-discord/dist/index.js:1930:33)
Emitted 'error' event on Client instance at:
at emitUnhandledRejectionOrErr (node:events:390:10)
at process.processTicksAndRejections (node:internal/process/task_queues:92:21)
Node.js v23.1.0
[nodemon] app crashed - waiting for file changes …
```
> fix: discord crash on sending message to null channel

- packages/adapter-sqljs/src/index.ts
- packages/adapter-sqljs/tsconfig.json
> fix: db queries in sqljs database adapter not using agentId

- packages/core/src/tests/actions.test.ts
- packages/core/src/tests/defaultCharacters.test.ts
- packages/core/src/tests/generation.test.ts
- packages/core/src/tests/goals.test.ts
https://github.com/ai16z/eliza/issues/188
Low - adding tests
This PR adds tests for actions and generation.ts
Feature: Adding tests
None
Navigate to packages/core
Navigate to packages/core
run pnpm install
run pnpm test
> feat: Adding tests for actions and generation. Skiping test step in defaultCharacters

- agent/src/index.ts
- packages/plugin-node/src/index.ts
- packages/plugin-node/src/services/browser.ts
By making node plugin lazy loaded and the browser service initialize only when used the agent starts almost instantly
> feat: make node-plugin lazy-loaded for faster boot times

- packages/adapter-sqljs/src/index.ts
- packages/core/.eslintignore
- packages/core/eslint.config.mjs
- packages/plugin-bootstrap/src/providers/time.ts
This PR adds Conflux, lints and fixes a few small things
> fix: Update and add Conflux

- agent/.gitignore
- packages/core/src/knowledge.ts
- packages/core/src/runtime.ts
https://github.com/ai16z/eliza/issues/615
https://github.com/ai16z/eliza/issues/614
Low:
- Change a `break;` to `continue;`
- Use the correct object in a logging statement
- Update .gitignore so the `generatedImages` folder doesn't get added to source control
A couple of small changes:
1. Fix the issue where new knowledge entries in character profile don't get included in agents memory db.
2. Fix for memory fragment similarity score logging.
3. Updated gitignore in `/agent` to ignore generated images
To make changes to core knowledge work and log memory related search metrics correctly.
Screenshots and replication steps for 2 bugs described in the linked issues.
See linked …
> fix: memory similarity log & new knowledge ingestion

- scripts/docker.sh
Docker running error
Low, The scope of influence is the operation of docker
After the author moved the agent folder, docker could not map the agent directory in docker, so docker volumn mapping incorrectly. I re-mapped the agent directory
docker has the following error:
```
sudo docker compose -f docker-compose-waifu.yaml up
[+] Running 1/0
✔ Container waifu  Created                                                                                               0.0 s
Attaching to waifu
waifu  |
waifu  | &gt;  eliza@ start /app
waifu  | &gt;  pnpm --filter "@ai16z/agent" start --isRoot "--characters=characters/waifu.character.json"
waifu  |
waifu  | No projects matched the filters in "/app"
```
My changes do not require a change to the …
> bugfix: Modify docker run error after agent folder move

- packages/client-twitter/src/post.ts
- packages/client-twitter/src/utils.ts
Low
Fix
`["⛔ Error sending response tweet: TypeError: Cannot read properties of undefined (reading 'tweet_results')"]`
Better internal state validation to make system work as expected
> fix: handle when tweet_results is empty better

- agent/src/index.ts
N/A
Low,  just a refactor and adding SIGTERM handling
We catch SIGTERM and refactor a bit of code. In the future we can use the `gracefulExit` function to clean up DB and client resources as well.
Small process management improvements
Nope
Running an agent locally and exiting through an exit prompt or ctrl + c
> fix: small improvements to agent process exits

- packages/client-twitter/src/interactions.ts
Twitter interaction handling and response deduplication
Low - Adds defensive check to prevent duplicate responses to tweets. Does not modify core functionality.
This PR adds tweet response deduplication by:
1. Generating unique tweetId using stringToUuid combining tweet.id and agentId
2. Checking message history before responding to prevent duplicate responses
3. Improving logging for skipped tweets
4. Maintaining consistent ID generation across different interaction points
My changes do not require a change to the project documentation as this is an internal improvement.
1. Review the tweet response check in `packages/client-twitter/src/interactions.ts`
2. Focus on the tweetId generation and message history check implementation
1. Test …
> fix: Add Tweet Response Deduplication Check

- agent/src/index.ts
- docs/docs/packages/plugins.md
- packages/plugin-tee/README.md
- packages/plugin-tee/src/index.ts
- packages/plugin-tee/src/providers/deriveKeyProvider.ts
- packages/plugin-tee/src/providers/remoteAttestationProvider.ts
- packages/plugin-tee/src/providers/walletProvider.ts
Low, Adding docs and updating TEE Plugin to derive both solana ed25519 and evm ecdsa keypairs.
Improvements
I have updated the documentation accordingly.
> fix: Add docs, update providers for TEE Plugin

- packages/plugin-starknet/src/actions/subdomain.ts
- packages/plugin-starknet/src/actions/transfer.ts
- packages/plugin-starknet/src/index.ts
- packages/plugin-starknet/src/utils/starknetId.ts
Low. Only agents with this plugin enabled would be affected.
Adds support for transfers to .stark names in `transfer` action.
Adds a new action to create and send a subdomain for a domain owned by the agent's wallet. 
Improvement + feature
None that I'm aware of
> feat: support starkname

- agent/src/index.ts
- packages/adapter-postgres/src/index.ts
- packages/adapter-sqlite/src/index.ts
- packages/adapter-sqljs/src/index.ts
- packages/adapter-supabase/src/index.ts
- packages/core/src/database.ts
- packages/core/src/types.ts
Better closing of db connections to prevent dangling connections
Low
This PR adds code to gracefully close db connections. This will be useful when we allow clients to be stopped (right now only starting is supported)
Improvements
Ran tests locally, let me know if there's a better way to test this.
> refactor: better db connection handling

- packages/client-discord/src/messages.ts
- packages/core/src/runtime.ts
- packages/plugin-node/package.json
- packages/plugin-node/src/services/browser.ts
- pnpm-lock.yaml
Performance and security improvements with the browser service.
Low since the browser performance was already inconsistent
There are several changes I made to the browser service to make it better:
- More accurate and up to date user agent to reduce bot detection
- Remove redundant content summarization
- Remove queuing system since all fetches are blocking and it was leading to duplicate pages being loaded
- Run in headless mode to reduce cpu usage and latency
- Re-enable sandbox mode to isolate malicious browser behavior
- Prevent unwanted downloads of files
Improvements
None
Test by sending urls on discord
> feat: improve browser service

- .env.example
- packages/plugin-node/src/services/llama.ts
https://github.com/ai16z/eliza/issues/242
Low,
User can provide any path for llamalocal and the plugin will direct/load from that directory.
Currently if user tries `pnpm build`, the `node-plugin/dist` gets deleted where the downloaded models are stored.
and hence it tries download everytime the build command is executed.
This PR will introduce a `LLAMALOCAL_PATH ` environment variable, which can be used to point/download llama models
It will require to add a new environment variable and it's detail.
1. in the `defaultCharacter.ts` make sure it has `modelProvider: ModelProviderName.LLAMALOCAL`
2. now execute `pnpm build` it will download the …
> added support for LlamaLocal's path outside plugin-node/dist

- packages/adapter-sqlite/src/index.ts
- packages/client-discord/src/index.ts
- packages/client-discord/src/messages.ts
- packages/client-discord/src/voice.ts
- packages/client-farcaster/src/actions.ts
- packages/client-farcaster/src/interactions.ts
- packages/client-farcaster/src/memory.ts
- packages/client-farcaster/src/post.ts
- packages/client-telegram/src/messageManager.ts
- packages/client-twitter/src/base.ts
- packages/client-twitter/src/interactions.ts
- packages/client-twitter/src/post.ts
- packages/client-twitter/src/utils.ts
- packages/core/src/embedding.ts
- packages/core/src/knowledge.ts
- packages/core/src/memory.ts
Embedding search was broken when not using OpenAI models because our default zero embeddings are length 1536 (which is the length generated from remote embedding processing), but our locally generated embeddings are of length 384.
Low
Fixes the embedding mismatch issue by generating a zero embedding vector based on the given model being used.
Bug fix
Run locally against OpenAI model and non-openai models
> fix: embedding search for non-openai models

- docs/docs/quickstart.md
https://github.com/ai16z/eliza/issues/337
Low
**1. Add a "Build Local Libraries" Step:**
Included the `pnpm build` step in the quickstart guide to address an issue where running pnpm start would fail due to missing imported libraries. This ensures the project is properly built before starting.
**2. Improve better-sqlite3 Troubleshooting Instructions:**
Added `pnpm store prune` as a troubleshooting step for resolving issues with better-sqlite3.
Deleting the pnpm-lock.yaml file is unnecessary since the library versions remain consistent. The root cause is related to the `pnpm` cache retaining an incompatible version of the package, which occurs when using a different Node.js version during the initial installation.
Improve docs
Got stuck while following the quickstart, saw other people had …
> fix: add missing commands to quickstart

- packages/plugin-coinbase/src/plugins/commerce.ts
- packages/plugin-coinbase/src/plugins/massPayments.ts
- packages/plugin-coinbase/src/plugins/trade.ts
- packages/plugin-coinbase/src/utils.ts
---
Enhance Providers with Wallet History (Transactions and Balances)
Low.
- The new functionality fetches and formats wallet balances and transactions. 
- Possible risks include:
- Increased response time for providers due to the added API calls.
- Dependency on the Coinbase SDK for accurate data retrieval.
This PR enhances the `massPayoutProvider`, `tradeProvider`, and `chargeProvider` to include wallet balances and recent transactions in their responses. Additionally:
1. A reusable utility function `getWalletDetails` is introduced to:
- Fetch wallet balances.
- Retrieve recent wallet transactions.
- Format and return this data.
2. The `getAssetType` helper function is added to determine the asset type (e.g., ETH, USDC) for transactions.
**Feature (non-breaking change which adds …
> feat: Add wallet history (transactions, balances) to coinbase providers

- packages/client-discord/src/index.ts
- Set correct bot invite permissions
- Add duplicate reaction handling
- Add /joinchannel command improvements
fix #661
> fix: discord permissions and duplicate reactions, new /joinchannel command

- .env.example
- agent/src/index.ts
Low, risks are removed by making sure default env variable `WALLET_SECRET_SALT` is undefined.
Remove default salt in the `.env.example` file to remove launch agent errors with TEE Plugin. Add tee plugin back into agent startup file so users can launch a TEE agent with a character file.
- Remove agent launch errors that use TEE Plugin
- Adds logic for Agent to startup in a TEE Plugin with or without a simulator
Bug fixes
I created a short YouTube video to explain the steps.
https://youtu.be/RABERCv5FiA
- Add the env variable `WALLET_SECRET_SALT` with a value in the character config file.
> Example for env vars to test locally:
> `DSTACK_SIMULATOR_ENDPOINT=http://localhost:8090`
> `WALLET_SECRET_SALT=secretSalt`
- Build …
> fix: Make TEE Plugin available to launch agent & fix previous launch error

- packages/adapter-postgres/src/index.ts
- packages/client-discord/src/index.ts
- packages/client-discord/src/messages.ts
- packages/client-discord/src/voice.ts
- packages/client-farcaster/src/memory.ts
- packages/client-telegram/src/messageManager.ts
- packages/client-twitter/src/base.ts
- packages/client-twitter/src/interactions.ts
- packages/client-twitter/src/post.ts
- packages/client-twitter/src/utils.ts
- packages/core/src/knowledge.ts
- packages/core/src/memory.ts
#677 made some changes to `getEmbeddingZeroVector` which need to be adjusted in order to get builds working again
Low
Bug fix
> fix: getEmbeddingZeroVector calls

- .env.example
- packages/client-twitter/src/base.ts
- packages/client-twitter/src/interactions.ts
Right now it's a random value between 2-5 minutes. Instead, we should make it configurable so different agents can have different response times. This allows devs to adjust polling intervals to avoid rate limiting.
Low
> feat: make twitter client polling configurable

- packages/client-twitter/src/interactions.ts
- packages/client-twitter/src/utils.ts
- packages/plugin-bootstrap/src/providers/facts.ts
Twitter memories for agent generated tweets weren't being saved properly due to null created_at values
Low
Uses the actual timestamp value for a sent tweet
Bug fix
> fix: twitter recent interactions

- packages/client-twitter/src/base.ts
related: https://github.com/ai16z/eliza/issues/656
I think the issue arises because the Scraper instance is shared across different accounts, causing auth and authTrends to be overwritten when a new account is used: 
https://github.com/ai16z/agent-twitter-client/blob/e1d86267681c44529ba3dc4b5125e1dc965ed0fc/src/scraper.ts#L665
> refactor: ClientBase to use a map for managing multiple Twitter clients by account identifier

- packages/core/src/embedding.ts
In current state it looks like we had a bit of a regression importing `fastembed` at the top level again, which causes build failures in non-Node environments due to native dependencies (.node files) like Cloudflare Workers and other edge workers. 
This PR:
- Removes top-level import of `EmbeddingModel` from `fastembed`
- Dynamically imports fastembed package only when local embeddings are needed
- Ensures native modules are only loaded in Node.js environment
This allows the package to be built for both browser and Node.js environments while maintaining all existing functionality.
Testing:
- Confirm local embeddings still work in Node.js
- Verify builds succeed in browser/Cloudflare Worker environments (done!)
- Maintained original behavior for remote embedding fallbacks
> fix: move `fastembed` import to the isnode condition check

- packages/core/src/parsing.ts
Bug Fix
No risk, Actually reduces risk
Invalid json format was being passed to LLM which very regularly causing json parse error that too inside the infinite while loop resulting in huge consumption of  model provider's credits.
Minor change but important
Nope
> fix (core): message completion footer format

- packages/client-twitter/package.json
Package wasn't uptodate
low
Package wasn't uptodate
Package updated to latest agentclient repo 0.0.16 where sendTweet also support media sending.
> fix: packagejson updated to latest agent-client 0.0.16

- .gitignore
- docs/api/variables/messageCompletionFooter.md
- packages/client-twitter/src/enviroment.ts
- packages/client-twitter/src/interactions.ts
- packages/client-twitter/src/post.ts
- packages/core/src/providers.ts
- packages/plugin-solana/src/providers/wallet.ts
- pnpm-lock.yaml
This PR adds QoL updates on top of Cygaar's twitter fixes, should make setting up character a bit easier.
> Update environment, add twitter quality of life updates

- packages/client-twitter/src/interactions.ts
- packages/client-twitter/src/post.ts
- packages/core/src/providers.ts
Issues with duplicate twitter content being posted
Low
Reduces duplication of Twitter content and reduces tokens used for twitter post generation.
The two key changes were:
1) Removing previous posts from the generation prompt as this influenced the model into repeating previous content even though the prompt asked it not to. Previous posts do not provide value when generation posts. For tweet interactions we already include exists posts in the thread so including previous posts (timeline) is not necessary.
2) Improve the prompts to remove unused blank lines and to better organize the structure of the context. These changes should improve response quality.
Improvement
> fix: improve twitter post content quality

- packages/client-twitter/src/post.ts
related: https://github.com/ai16z/eliza/issues/679
PR Description:
**Unified Room ID Handling:** 
Ensures consistency by using the same room ID when creating and retrieving memories addressing an issue where {{recentPosts}} in post.ts/twitter was always empty.
**Added Missing timestamp Property for Tweets:** 
Introduced the missing timestamp property to tweets, enabling accurate retrieval of the creation date for recent posts.
> fix: recentPosts always empty

- docs/docs/packages/plugins.md
- packages/plugin-tee/README.md
> add simulator tutor for plugin-tee docs

- agent/src/index.ts
- package.json
- packages/adapter-postgres/src/index.ts
- packages/core/src/types.ts
- packages/plugin-node/src/enviroment.ts
- packages/plugin-node/src/services/speech.ts
- packages/plugin-node/src/vendor/vitsVoiceList.ts
- pnpm-lock.yaml
feat(voice): enhance character card voice configuration support
- Add comprehensive ElevenLabs configuration in character cards
- Make ElevenLabs settings optional with sensible defaults
- Implement configuration priority (character card > env vars > defaults)
- Update schema validation to support optional fields
- Add debug logging for voice selection process
- Maintain backward compatibility with existing setups
Example character card config:
```json
{
"settings": {
"voice": {
"model": "en_GB-alan-medium",
"elevenlabs": {
"voiceId": "your-voice-id",
"model": "eleven_monolingual_v1",
"stability": "0.5"
}
}
}
}
```
Closes https://github.com/ai16z/eliza/issues/694
> feat: (voice) enhance character card voice configuration support

- docs/api/functions/generateCaption.md
- docs/api/functions/generateImage.md
- docs/api/functions/generateMessageResponse.md
- docs/api/functions/generateObject.md
- docs/api/functions/generateObjectArray.md
- docs/api/functions/generateObjectV2.md
- docs/api/functions/generateShouldRespond.md
- docs/api/functions/generateTextArray.md
- docs/api/functions/generateTrueOrFalse.md
- docs/api/functions/generateWebSearch.md
- docs/api/functions/handleProvider.md
- docs/api/functions/splitChunks.md
- docs/api/interfaces/GenerationOptions.md
- docs/docs/packages/plugins.md
- packages/plugin-coinbase/src/plugins/massPayments.ts
- packages/plugin-coinbase/src/plugins/trade.ts
- packages/plugin-coinbase/src/plugins/trades.csv
- packages/plugin-coinbase/src/utils.ts
- pnpm-lock.yaml
This PR introduces a new feature that automatically donates 1% of all transactions executed on Coinbase to a designated charity. The charity addresses are static and network-specific. In the future, we aim to integrate with The Giving Block API to allow for dynamic and configurable donations.
- **Low**: Changes could minimally affect transaction execution if there is an error in the transfer or donation logic.
- **Impact**: Network-specific charity transfers are a new feature and might require careful testing to ensure funds are correctly allocated.
- Implements automatic donation of 1% from each transaction to a charity wallet address based on the network.
- Includes utility functions to determine the correct charity address for each network.
- Updates the transaction execution flow to …
> feat: donate 1% of coinbase transactions by default

- Dockerfile
Low, only pertains to docker users
Currently, the developer experience for using docker is bad. Build times can take up to 30 minutes and image size is at 6GB. Reducing this pain point is key for more developer adoption.
This PR accomplishes the following:
- Reduces the Docker image size from 6GB to 3.49GB
- Cuts the Docker build time in half
- Tested on a Intel TDX Server (188s to 70s)
- Mac M1 Max (688.9s to 327.4s) 
Improvements (refactor Dockerfile)
- (Build) On mac m series `docker buildx build --platform linux/amd64 -t eliza .`
- (Build) On linux/amd64 `docker build -t eliza .`
- (Build & Start) `pnpm docker`
> refactor: refactor dockerfile to reduce image and build time

- packages/core/src/uuid.ts
Low
For compatible about uuid input: string and number.
There are two options:
one is to delete `number` compatible and remove the number2string code snippet.
The other is my way, only to input a handler at input parameter to make number is also a feasible input.
string and number both ok for UUID.
Bug fixes
> fixs: uuid compatible for number

- README_KOR.md
Low, because no code and/or instructions have changed
Updates README_KOR.md to match the latest version of README.md, done by a Korean.  
Improvement
Language Quality Assurance
rokseo
> chore: update README_KOR.md to match latest README.md

- Dockerfile
- agent/src/index.ts
No linked issue.
**Risk Level**: Low  
Adding a new flag `non-interactive` that defaults to skipping `chat()` should not affect existing functionality unless explicitly enabled. The main risk is around unintended bypass of user input under edge cases.
This PR adds a `non-interactive` flag to prevent running the `chat()` function and avoid waiting for user input. This is particularly useful for environments such as Cloud platforms where interactive sessions are not feasible and can cause the application to hang.
Additionally, the `non-interactive` flag is added to the `CMD` in the Dockerfile as the default.
Running the application in a non-interactive environment such as Cloud platforms caused the process to hang due to waiting for …
> fix: Docker default non-interactive mode for Cloud instances

- packages/client-telegram/src/getOrCreateRecommenderInBe.ts
- packages/client-telegram/src/telegramClient.ts
- packages/plugin-solana/src/evaluators/trust.ts
- packages/plugin-solana/src/providers/simulationSellingService.ts
- packages/plugin-solana/src/providers/trustScoreProvider.ts
> fix: swap type error, create user trust on first message in telegram

- .github/workflows/release.yaml
Rather than creating a new tag/release from the release workflow, we should use this workflow to publish the latest github release. This process should be idempotent because npm will reject duplicate packages from being published.
In the future, we can look into automating the publishing process so it runs whenever a github release is created
> fix: update npm publication workflow

- packages/core/src/actions.ts
Improve the action samples random selection by ensuring a bigger variety of actions are represented in the selection (as long as there is enough place, at least one example per action should be added)
https://github.com/ai16z/eliza/issues/798
low, but it makes LLM sometimes not understand that they can trigger an action because they don't have any example corresponding
This PR changes the algorithm that selects the actions examples that are sent to the model
Improvements
not really testable except if you do console logs but the difference is there.
> refactor: Improve actions samples random selection

- .github/workflows/release.yaml
This should fix the release properly - the clean will run before the tag checkout
> fix: release workflow part 3

- packages/core/package.json
- packages/plugin-goat/package.json
- packages/plugin-solana/package.json
- packages/plugin-tee/package.json
- pnpm-lock.yaml
Going forward, all package dependencies must have a pinned version. This will help us prevent supply chain attacks like the one we saw here: https://x.com/anza_xyz/status/1864085236432134264.
This PR also updates the @solana/web3.js package to the latest safe version which doesn't include exploits.
Low
> fix: pin all node dependencies + update @solana/web3.js to safe version

- packages/client-twitter/src/base.ts
Low
The `expires` timestamp in client-twitter/base.ts was not properly calculated relative to the current time, causing all cache lookups to miss.
> fix: twitter cache expires

- agent/src/index.ts
- docs/docs/packages/plugins.md
- packages/plugin-coinbase/src/index.ts
- packages/plugin-coinbase/src/plugins/tokenContract.ts
- packages/plugin-coinbase/src/templates.ts
- packages/plugin-coinbase/src/types.ts
- packages/plugin-coinbase/src/utils.ts
N/A - New feature implementation
Low - This PR adds new functionality without modifying existing features. The token contract plugin is only enabled when proper Coinbase credentials are present.
This PR adds a new Coinbase token contract plugin that enables:
1. Deployment of ERC20, ERC721, and ERC1155 token contracts
2. Interaction with deployed smart contracts through method invocation
3. Automatic logging of contract deployments and interactions to CSV files
4. Integration with existing Coinbase wallet management system
- Adds new token contract deployment capabilities
- Adds contract interaction functionality
- Extends existing Coinbase plugin suite
- Added comprehensive …
> feat: add coinbase  ERC20, ERC721, and ERC1155 tokenContract deployment / invokement plugin

- packages/plugin-node/package.json
No specific ticket linked - package configuration improvement
Low - Adding explicit files list to package.json for more controlled npm package contents
```bash
.../node_modules/@ai16z/plugin-node postinstall$ node scripts/postinstall.js
│ node:internal/modules/cjs/loader:1246
│   throw err;
│   ^
│ Error: Cannot find module '/Users/martincik/Projects/ai/access-ai-poc/echo2/node_modules/.pnpm/@ai16z+plugin-node@0.1.5-alpha.3_@google-cloud+vertexai@1.9.0_@langchain+cor…
│     at Function._resolveFilename (node:internal/modules/cjs/loader:1243:15)
│     at Function._load (node:internal/modules/cjs/loader:1068:27)
│     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
│     at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
│     at Function.executeUserEntryPoint [as …
```
> fix: Include scripts/postinstall.js in the final NPM package

- .env.example
- agent/package.json
- agent/src/index.ts
- packages/plugin-aptos/.npmignore
- packages/plugin-aptos/eslint.config.mjs
- packages/plugin-aptos/package.json
- packages/plugin-aptos/src/actions/transfer.ts
- packages/plugin-aptos/src/constants.ts
- packages/plugin-aptos/src/enviroment.ts
- packages/plugin-aptos/src/index.ts
- packages/plugin-aptos/src/providers/wallet.ts
- packages/plugin-aptos/src/tests/wallet.test.ts
- packages/plugin-aptos/tsconfig.json
- packages/plugin-aptos/tsup.config.ts
- pnpm-lock.yaml
Introducing new plugin for agent to manage an Aptos wallet.
Now agent can manage an Aptos wallet and send APT token to others.
Go to the aptos-plugin directory. To keep things simple, I only support transferring APT at the moment. Will add more functionalities later.
Enable the aptos-plugin in the test agent, set the aptos wallet private key and network in .env.
For unit test, run `pnpm test` in plugin-aptos directory.
For end to end test, [replace default character at this line](https://github.com/ai16z/eliza/blob/6735003d4119d7e57f1355600a95cf432f53e42c/agent/src/index.ts#L463) with this custom character that enables aptos.
```
const character = defaultCharacter;
let customAptosPlugin = aptosPlugin;
let customTransferAptToken = TransferAptosToken;
customTransferAptToken.validate = async …
```
> feat: add Aptos plugin

- packages/client-discord/src/messages.ts
- packages/client-farcaster/src/interactions.ts
- packages/client-telegram/src/messageManager.ts
- packages/plugin-0g/src/actions/upload.ts
- packages/plugin-bootstrap/src/actions/continue.ts
- packages/plugin-bootstrap/src/actions/followRoom.ts
- packages/plugin-bootstrap/src/actions/muteRoom.ts
- packages/plugin-bootstrap/src/actions/unfollowRoom.ts
- packages/plugin-bootstrap/src/actions/unmuteRoom.ts
- packages/plugin-bootstrap/src/evaluators/fact.ts
- packages/plugin-bootstrap/src/evaluators/goal.ts
- packages/plugin-coinbase/src/plugins/commerce.ts
- packages/plugin-coinbase/src/plugins/massPayments.ts
- packages/plugin-coinbase/src/plugins/tokenContract.ts
- packages/plugin-coinbase/src/plugins/trade.ts
- packages/plugin-conflux/src/actions/bridgeTransfer.ts
- packages/plugin-goat/src/actions.ts
- packages/plugin-icp/src/actions/createToken.ts
- packages/plugin-solana/src/actions/takeOrder.ts
- packages/plugin-solana/src/actions/transfer.ts
- packages/plugin-starknet/src/actions/takeOrder.ts
This PR makes the small models big. Apparently we've been using small models for interactions and message responses, but this is wrong.
> fix: Use LARGE models for responses

- docs/docs/quickstart.md
Issue Found
N/A
Low, only may affect some users while setting up the initial environment.
While trying to run the project I encountered an issue. There was no specification on the pnpm version and even though I had all the other versions correctly, I was getting the same constant error. 
The project requires specific versions of pnpm (9+?) as defined in the package.json, but when trying to install dependencies, I kept getting ERR_PNPM_META_FETCH_FAIL errors and broken lockfile warnings.
The root cause was a mismatch between my system's pnpm version and the one specified in the project.
This is a simple change in the documentation to add the specific versions needed for pnpm, npm, etc. And also a better git checkout to get the latest version of the repo.
This is a documentation change
Set …
> Updated quickstart.md to contemplate common issue

- packages/core/src/tests/environment.test.ts
- packages/core/src/tests/knowledge.test.ts
Not tied to particular issue. Contributing with more tests, environment.ts and knowledge.ts
Low, adding tests.
This pr adds tests for environment.ts and knowledge.ts
Adding tests.
None
packages/core/
Navigate to packages/core and run pnpm install & pnpm test
> test: adding environment and knowledge tests

- .github/workflows/ci.yaml
Continuous Integration workflow improvements
Low - Changes to CI workflow configuration only. Main risk would be potential CI pipeline failures if any configuration is incorrect.
Updates the GitHub Actions CI workflow configuration with the following changes:
- Adds code coverage reporting to Codecov
- Enhances the existing CI pipeline with better package management and test coverage reporting
1. Review the .github/workflows/ci.yaml file
2. Check the workflow runs on both push to main and pull requests
3. Verify all job steps are properly configured
1. Create a test PR to verify the workflow triggers correctly
2. Ensure all steps complete successfully:
- PNPM installation
- …
> fix: re-enable coverage report upload to Codecov in CI workflow

- packages/client-twitter/src/interactions.ts
- packages/core/src/parsing.ts
Right now the call to `parseJsonArrayFromText` in `evaluate` fails at times because the result passed in looks like:
````
```json
[
'EXTRACT_RECOMMENDATIONS'
]
```
````
In order to fix this, we need to fix the parsing function to convert the single quotes to double quotes.
Low
> fix: evaluation json parsing

- .env.example
- packages/core/src/models.ts
Introduce four environment variables for groq so users can configure its models through `.env`.
> feat: allow users to configure models for groq

- packages/core/src/generation.ts
- packages/plugin-aptos/src/actions/transfer.ts
- packages/plugin-flow/src/actions/transfer.ts
- packages/plugin-icp/src/actions/createToken.ts
- packages/plugin-solana/src/actions/pumpfun.ts
- packages/plugin-solana/src/actions/swap.ts
- packages/plugin-solana/src/actions/transfer.ts
- packages/plugin-starknet/src/actions/subdomain.ts
- packages/plugin-starknet/src/actions/swap.ts
- packages/plugin-starknet/src/actions/transfer.ts
- packages/plugin-starknet/src/actions/unruggable.ts
N/A prevent future folks from using the untyped version generateObject so folks use generateObjectV2 which is typesafe. Just a rename for now to reduce risk of regression. We will clean up old usages separately.
**Low**  
- Existing functionality will continue to work but will display a deprecation warning.  
- No impact on downstream systems expected.  
- Risk is isolated to developers relying on raw text-based JSON generation.
This PR deprecates the text-based way of generating JSON objects using LLMs and so folks use generatedObjectV2 with typesafe structured outputs. Method isn't removed yet it is deprecated.
- **Improvements**: Transitioning to a more robust way of handling JSON outputs.  
- **Chore**: Deprecation of legacy behavior.  
Text-based generation of JSON using LLMs is …
> chore: deprecate text based way of generating JSON

- .env.example
- packages/client-farcaster/src/client.ts
- packages/client-farcaster/src/interactions.ts
- packages/client-farcaster/src/post.ts
- packages/client-farcaster/src/prompts.ts
Low
- Code cleanup originally provided by @monilpat in #557
- Adds config to match the twitter client
- fixes the response logic so agents can disengage from threads
Updated the .env.example to reflect the new config options added
> fix: Farcater client cleanup and fixed response logic

- packages/client-twitter/src/environment.ts
- packages/client-twitter/src/post.ts
add MAX_TWEET_LENGTH env variable to .env file
start the agent with Twitter Client
check the limit is equal to MAX_TWEET_LENGTH value
> MAX_TWEET_LENGTH env implementation

- scripts/dev.sh
This setup is crucial for development because:
1. The agent depends on the packages listed in WORKING_FOLDERS
2. When you make changes to any of these packages, they get compiled to their respective dist directories
3. The agent needs to restart with the new changes for them to take effect
4. This automation saves developers from having to manually restart the agent every time they make changes to dependent packages
> feat: add dynamic watch paths for agent development

- packages/core/src/models.ts
Low: If the user had previously set these env vars to any value, these will now be used where previously they would be ignored.
This PR will make the previously defined Heurist model env vars actually take effect.
Bug fix
Because the env vars are already defined, and it makes sense to use them.
The change should be pretty straight forward.
> fix: use of Heurist model env vars

- packages/plugin-coinbase/src/constants.ts
- packages/plugin-coinbase/src/plugins/tokenContract.ts
- packages/plugin-coinbase/src/templates.ts
- packages/plugin-coinbase/src/types.ts
- Introduced `readContractAction` for reading data from deployed smart contracts
- Added `ReadContractContent` interface and `ReadContractSchema` for input validation
- Integrated `readContractTemplate` to guide users in extracting necessary details for read operations
- Enhanced existing contract interaction capabilities in `tokenContractPlugin` with `invokeContractAction` now relying on `networkId`, `amount` as a string, and required `assetId`
```typescript
interface ReadContractContent {
contractAddress: `0x${string}`;
method: string;
networkId: string; // Network now identified by networkId (e.g. "ethereum-mainnet")
args?: Record<string, any>;
abi?: any[];
}
```
- `ReadContractSchema` added for validating read operations:
- Validates `contractAddress`, `method`, `networkId`, `args`, …
> feat: add readContract / invokeContract functionality to Coinbase plugin

- .env.example
- packages/core/src/models.ts
Low
Config eternalai model from env
More flexible than with env
Currently, Eliza supports only OpenAI. However, centralized AI providers limit user control, pose trust issues, and create single points of failure with high costs and restricted access. Decentralized AI offers a more transparent, accessible, and resilient alternative, empowering users with greater autonomy.
Learn more about our decentralized inference AI: https://eternalai.org/api
Reviewers start from .env.example
Run pnpm start --characters="path/to/your/characters/eternal.character.json"
No change
Change .env by adding more
ETERNALAI_MODEL=#require
> feat: Config eternalai model from env

- docs/docs/wsl.md
AI Agent Dev School Video 1 : https://www.youtube.com/watch?v=ArptLpQiKfI
Low 
Shaw suggests using WSL to code with Eliza but there are some steps missing from the instructions in order for installation to work. 
Fixes pnpm installation error when using WSL for the first time. 
Documentation 
- Verified all commands work in a fresh WSL installation
- Confirmed formatting matches existing documentation
Video: 
https://www.youtube.com/watch?v=ArptLpQiKfI
none
> docs: add WSL installation guide

- packages/client-farcaster/src/interactions.ts
Fix the bug where Farcaster client does NOT fire any actions
Low
Only fixes action handling in existing functionality
No structural changes to the codebase
No database schema changes
1. Fixes the bug where Farcaster client does not fire any actions
2. Adds cast hash to message memory for later use in action handler
Currently, when the Farcaster client generates responses that should trigger actions (like following a user or reacting to a cast), these actions are not being executed. This happens because:
1. The action information is being lost during the response chain
2. The cast hash, which is necessary for some actions, is not properly stored in the message memory
3. The action handlers don't receive the complete context they need …
> Fix farcaster client process action issue

- agent/src/index.ts
Bug fix for EVM plugin activation logic
Low 
Fixes a logic bug in the EVM plugin activation condition where it was incorrectly checking for wallet addresses that do NOT start with '0x'. 
Bug fixes
Review the change in `agent/src/index.ts` where the EVM plugin activation condition is modified.
Code change:
```
// Before
getSecret(character, "EVM_PRIVATE_KEY") ||
(getSecret(character, "WALLET_PUBLIC_KEY") &&
!getSecret(character, "WALLET_PUBLIC_KEY")?.startsWith("0x"))
? evmPlugin
: null,
// After
getSecret(character, "EVM_PRIVATE_KEY") ||
(getSecret(character, "WALLET_PUBLIC_KEY") &&
getSecret(character, "WALLET_PUBLIC_KEY")?.startsWith("0x"))
? evmPlugin
: null,
```
> fix(agent): correct EVM plugin activation condition

- packages/client-twitter/src/environment.ts
- packages/client-twitter/src/utils.ts
A follow-up PR of https://github.com/ai16z/eliza/pull/912 where some code weren't updated.
> fix: use MAX_TWEET_LENGTH from setting

- .env.example
- packages/core/src/types.ts
- packages/plugin-node/package.json
- packages/plugin-node/src/index.ts
- packages/plugin-node/src/services/awsS3.ts
- packages/plugin-node/src/services/index.ts
- pnpm-lock.yaml
N/A (Internal feature implementation)
Low - This is an isolated service addition to plugin-node for S3 file upload functionality. Main risks:
1. AWS credentials security
2. File upload limits and validation
3. S3 bucket permissions configuration
Adds a new service to plugin-node that enables file uploads to AWS S3 storage. This includes:
New S3 service implementation
File upload handling
AWS SDK integration
Configuration for S3 bucket and credentials
After AI-generated NFT, need to upload the file to a network storage service.
1. Review the S3 service implementation
2. Check AWS configuration setup
3. Verify file upload functionality
4. Review error handling and …
> feat: Supports upload files to AWS S3.

- docs/docs/faq.md
Fix package name in faq.md, `eliza` package isn't same as `@ai16z/eliza`.
> fix: update package name in faq

- packages/core/src/runtime.ts
Currently the runtime is only processing the first memory response, this allows for multiple actions to be processed from all the responses.
> feat: process all responses actions

- .env.example
- packages/core/src/models.ts
Low
This PR adds more environment variables to override the model used for hyperbolic. This PR creates env variables for a default hyperbolic model (HYPERBOLIC_MODEL) and variables for each model class (SMALL_HYPERBOLIC_MODEL, MEDIUM_HYPERBOLIC_MODEL, LARGE_HYPERBOLIC_MODEL, and IMAGE_HYPERBOLIC_MODEL). These changes follow the same variable pattern that ollama, redpill, google, and other model providers use on Eliza.
> feat: Add hyperbolic env vars to override model class

- packages/core/src/models.ts
Low: not sure if LlamaCloud has updated their URL recently
reverts this seeming typo:
https://github.com/ai16z/eliza/commit/f3ca29902a9797eb991e4f7c07f69f5bd2914848#diff-126a0b18ab66588de8b33f8e6dc451651eb9fb5f7ab6d0c961a989b76f40be57L90
LlamaCloud probably should not be using together.ai's api endpoint
A step in the right direction to fix llamacloud
> fix: revert llamacloud endpoint change

- packages/core/src/runtime.ts
- packages/core/src/types.ts
This allows to pass down the callback handler from clients to evaluators allowing them to respond. The callback handler was already in the evaluator interface just not implemented in the runtime.
> feat: add callback handler to runtime evaluate method

- Dockerfile
- package.json
Low
Fixes `pnpm docker` by adding a custom action for build for docker `block-docker`
Changed the `Dockerfile` to use this new action, which gets around the docs package not found when filtering.
This was the error
```
101.0 
101.0 > eliza@ build /app
101.0 > turbo run build --filter=!eliza-docs
101.0 
101.3 
101.3 Attention:
101.3 Turborepo now collects completely anonymous telemetry regarding usage.
101.3 This information is used to shape the Turborepo roadmap and prioritize features.
101.3 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
101.3 https://turbo.build/repo/docs/telemetry
101.3 
101.3 turbo 2.3.3
101.3 
101.8   x No package found with name 'eliza-docs' in workspace
101.8 
101.8 …
```
> fix: docker trying to filter out missing docs package

- packages/core/src/generation.ts
Low
Allowed overriding of models for use on OpenRouter
I may have multiple agents that I want to use different models to customize their personality
My changes may a change to the project documentation: We need to describe this is available
> feat: allow character.json settings models for open router

- packages/client-linkedin/README.md
- packages/client-linkedin/package.json
- packages/client-linkedin/src/base.ts
- packages/client-linkedin/src/environment.ts
- packages/client-linkedin/src/index.ts
- packages/client-linkedin/src/interactions.ts
- packages/client-linkedin/src/post.ts
- packages/client-linkedin/tsconfig.json
Medium - Rate Limiting  - Dependent on adhering to rate limits which we have tried to help developers with via defaults
Medium - I've done minimal testing so far, please halp!
New client for supporting Eliza integrating with LinkedIn
I include a README but maybe some mention in the main Eliza README would be nice
I minimally tested but would love more help testing further.
yourfriendbrett
> LinkedIn Client

- agent/src/index.ts
- packages/plugin-node/src/environment.ts
- packages/plugin-node/src/services/awsS3.ts
https://github.com/ai16z/eliza/pull/941 and https://github.com/ai16z/eliza/pull/898
Errors when running agent were:
`TypeError: Cannot read properties of null (reading 'getChain')`
```
["✓ Service video initialized successfully"] 
Initializing AwsS3Service
⛔ ERRORS
Failed to initialize service aws_s3: 
{} 
⛔ ERRORS
Error starting agent for character trump: 
{} 
Error: Missing required AWS credentials in environment variables
at _AwsS3Service.initialize (file:///home/jnaulty/github.com/ai16z/eliza/packages/plugin-node/dist/index.js:1890:19)
at AgentRuntime.initialize (file:///home/jnaulty/github.com/ai16z/eliza/packages/core/dist/index.js:3245:31)
at async startAgent (file:///home/jnaulty/github.com/ai16z/eliza/agent/src/index.ts:344:9)
at async startAgents …
```
> fix: Goat Plugin + AWS S3 Service error when env vars absent

- docs/docs/guides/wsl.md
- docs/sidebars.js
AI Agent Dev School video 1: https://www.youtube.com/watch?v=ArptLpQiKfI 
Low 
Shaw suggests using WSL to code with Eliza but there are some steps missing from the instructions in order for installation to work.
Fixes pnpm installation error when using WSL for the first time. 
Creates a WSL setup guide that will help windows users code with Eliza in a Linux environment. 
Added installation guide to "Guides" section in docs. 
Documentation
Verified all commands work in a fresh WSL installation
Confirmed formatting matches existing documentation
Previewed page and tested links 
Video:
https://www.youtube.com/watch?v=ArptLpQiKfI
> docs: add WSL Setup Guide to documentation 

- packages/core/src/tests/parsing.test.ts
No particular issue now. Adding tests for parsing.ts
Low, adding tests.
This PR adds unit tests for parsing.ts
Adding new tests
None
packages/core/src/tests
navigate to packages/core
run pnpm install && pnpm test
> test: adding parsing tests. changed files parsing.test.ts

- packages/client-farcaster/src/interactions.ts
Adds callback to action in farcaster client
Low
Only adds callback parameter to action handling
No structural changes to the codebase
No database schema changes
Adds callback parameter implement in Farcaster client action handler to enable:
1. Proper action chaining
2. Response tracking for actions
3. Memory updates after action execution
The Farcaster client's action system needs to support callbacks for several reasons:
1. Actions often need to trigger follow-up responses
2. We need to track and store the results of actions
3. Some actions require updating the conversation memory
4. Complex action chains require proper state management
This improvement enables features such as:
- Multi-step action sequences
- Better error handling for …
> fix: add callback to action in farcaster client

- docs/docs/core/characterfile.md
No linked issue.
Low - Documentation changes only; no functional changes to the codebase.
Adds documentation for the templates object in the project, including a list of available templates and an example of usage.
Improvements - docs
Review the added `templates` documentation in `docs\core\characterfile.md`
None, as this is a documentation-only change.
0xspit
> docs: Add templates documentation to the project

- .env.example
- packages/client-twitter/src/base.ts
- packages/client-twitter/src/post.ts
- packages/core/src/generation.ts
- packages/core/src/parsing.ts
- packages/core/src/types.ts
Low - This PR primarily adds functionality to handle tweet generation and processing with proper error handling and rate limiting in place. Main risks:
- Potential rate limiting from Twitter API if intervals not properly configured
- Memory usage from caching tweets and processing actions
Implements a Twitter post client that:
- Generates and posts new tweets on configurable intervals
- Processes tweet actions (likes, retweets, quotes, replies) based on agent personality
- Handles proper truncation of tweets to fit character limits
- Implements caching and rate limiting
- Provides error handling and logging
- Adds new TwitterPostClient class
- Implements tweet generation and action processing
- Adds caching and rate limiting controls …
> feat: improve Twitter client with action processing

- lerna.json
- packages/_examples/plugin/.npmignore
- packages/_examples/plugin/README.md
- packages/_examples/plugin/eslint.config.mjs
- packages/_examples/plugin/package.json
- packages/_examples/plugin/src/actions/sampleAction.ts
- packages/_examples/plugin/src/evaluators/sampleEvalutor.ts
- packages/_examples/plugin/src/index.ts
- packages/_examples/plugin/src/plugins/samplePlugin.ts
- packages/_examples/plugin/src/providers/sampleProvider.ts
- packages/_examples/plugin/src/templates.ts
- packages/_examples/plugin/src/types.ts
- packages/_examples/plugin/tsconfig.json
- packages/_examples/plugin/tsup.config.ts
- pnpm-lock.yaml
Initial setup of example plugin structure, to come examples of adapters, clients, services, etc. This will make it easier to standardize development, best practices, code review, and ultimately quality of the repo.
Low - This is an example plugin that serves as a template/reference implementation
Creates an example plugin folder with a sample implementation including:
- Basic plugin structure
- Sample actions, providers, and evaluators
- TypeScript configuration
- Build setup with tsup
- NPM package configuration
My changes do require a change to the project documentation which is included. Will update the global readme once all examples are added.
1. Review the plugin structure in `packages/_examples/plugin/`
2. Key files to review: …
> feat: create example folder with example plugin

- packages/client-discord/src/constants.ts
- packages/client-discord/src/messages.ts
- packages/client-discord/src/utils.ts
- packages/core/src/types.ts
[PR 957](https://github.com/ai16z/eliza/pull/957)
Low: Additional settings to character.json types are low level changes, and should not break any core functionality. Additionally discord messages.ts and file additions are specific to the new team settings, so risk is low.
Enhances the Discord bot's message handling to support:
1. Team-based agent interactions - allowing multiple agents to coexist and coordinate responses
2. More natural conversation flow in team contexts
3. Improved interest management for multi-agent scenarios
Add documentation for team-based interaction features
1. Review changes in messages.ts (Discord) …
> feat: Add Discord Team features

- .github/workflows/integrationTests.yaml
https://github.com/ai16z/eliza/pull/993/files#r1883351009 
https://discord.com/channels/1253563208833433701/1308960830670377070/1317011277155012631
Medium
* OpenAI API Key would be accessible to github actions running integration tests for pull requests from forked repos
There are potential risks with exposing this secret (see: https://nathandavison.com/blog/github-actions-and-the-threat-of-malicious-pull-requests )
Response + Mitigations were provided by GitHub here: https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
I'd recommend a 'spend limit' on the OpenAI API in question. As well as a plan to quickly revoke the api key if required.
Allows OpenAI API Secret Value to be used by pull requests that come from forked repos
Bug fixes
Allows testing of new code …
> fix: use pull_request_target for integration tests

- agent/src/index.ts
- packages/client-discord/src/index.ts
- packages/core/src/runtime.ts
- packages/core/src/types.ts
- pnpm-lock.yaml
Low
implements discord websocket disconnect
make character settings optional
implement runtime.clients as a dict
disable client in characters client
Preparation for hot reloading
My changes should not require a change to the project documentation.
> feat: client-discord stop implementation / agent improvements

- packages/client-twitter/src/post.ts
Low
Re-enables generateNewTweetLoop
Tweet actions PR, assumingly, removed it by accident
> fix: re-enable generateNewTweetLoop / lint fixes

- agent/src/index.ts
- packages/client-direct/src/api.ts
- packages/client-direct/src/index.ts
Low
Add the ability to add an agent or change a running agent
No restarting needed to work on character development. Increases iteration speed
> feat: add/change change through REST api (client-direct)

- packages/client-discord/src/messages.ts
- packages/client-discord/src/voice.ts
The latest CI build fails due to incorrect interface definitions and unused variables. I also auto-linted these files.
> fix: discord client ci issues

- packages/client-twitter/src/interactions.ts
- packages/client-twitter/src/utils.ts
- packages/core/src/types.ts
- packages/plugin-image-generation/src/index.ts
related: https://github.com/ai16z/eliza/issues/970
> fix: Allow bot to post tweets with images generated by the imageGenerationPlugin

- .env.example
- agent/src/index.ts
- packages/core/src/generation.ts
- packages/core/src/models.ts
- packages/plugin-image-generation/src/environment.ts
- packages/plugin-image-generation/src/index.ts
Second portion of Venice.ai model provider api: adding image generation.
Very low, just adds the ability to use the imageGeneration plugin with the venice api
Venice.ai is a private AI platform that offers uncensored interactions, storing user data only in the browser. It supports document uploads, including PDFs, and features an image generation mode available to all users, allowing them to create images.
Adds the ability to use the Venice AI API for image generation.
These changes don't require updates to the documentation. If there is a section that lists the available providers for image generation I will find and submit a PR adding it.
Add venice API key. Load a character with images enabled (add imageSettings section). Load …
> feat: add venice.ai image generation

- packages/client-twitter/src/base.ts
fix: optimize Twitter login with cookie validation and retry mechanism
- Check for existing cookies or logged-in status before attempting login.
- Add a retry mechanism with a limit of 5 attempts to avoid infinite loops.
- Log meaningful errors and outcomes for easier debugging.
- Reduce unnecessary API calls to improve efficiency and prevent rate limits.
#855 
Low
•	Changes are limited to the Twitter login flow.
•	Potential risks involve improper handling of cookies or failure to recognize logged-in status, which could prevent login.
•	Checks for existing cookies or logged-in status before attempting a login to reduce unnecessary API calls.
•	Adds a retry mechanism with a maximum of 5 attempts to prevent infinite loops.
•	Improves logging for better error tracing …
> feat: improve X/Twitter login with cookie validation and retry mechanism

- docs/README.md
- docs/README_TH.md
- Low
- adds Thai translation and helps the Thai community further improve and contribute to eliza 
- created a README translations for the Thai language
> feat: add README_TH.md in docs directory

- .env.example
- agent/package.json
- agent/src/index.ts
- packages/plugin-ton/package.json
- packages/plugin-ton/src/actions/transfer.ts
- packages/plugin-ton/src/enviroment.ts
- packages/plugin-ton/src/index.ts
- packages/plugin-ton/src/providers/wallet.ts
- packages/plugin-ton/src/tests/wallet.test.ts
- packages/plugin-ton/tsconfig.json
- packages/plugin-ton/tsup.config.ts
- pnpm-lock.yaml
Low
Introduces Agent Plugin to manage a Ton Wallet.
Add the ability for Eliza agents to interface with the Ton Blockchain.
- Goto `packages/plugin-ton` directory
- Run `pnpm i`
- Run `pnpm test`
```text
stdout | src/tests/wallet.test.ts > Wallet provider > Wallet Integration > should check wallet address
Cache miss for fetchPortfolioValue
Cache miss for fetchPrices
stdout | src/tests/wallet.test.ts > Wallet provider > Wallet Integration > should check wallet address
Fetched portfolio: { totalUsd: '0', totalNativeToken: '0' }
Cache miss for fetchPrices
✓ src/tests/wallet.test.ts (1) 1267ms
✓ Wallet provider (1) 1267ms
✓ Wallet Integration (1) 986ms
✓ should check wallet address 985ms
Test Files  1 passed (1)
Tests  1 passed (1)
Start …
```
> feat: add plugin-ton

- packages/plugin-evm/README.md
#1009 
No
Add README.md explaining how the plugin works.
nikita_zhou
> docs: add README.md to plugin-evm

- .env.example
- packages/core/src/models.ts
Low.
1. Update grok model to the latest
2. Allow customization in `.env`
> feat: allow users to configure models for grok

- packages/core/src/tests/actions.test.ts
- packages/core/src/tests/messages.test.ts
- packages/core/src/tests/models.test.ts
No particular issue, adding more coverage and more tests for actions.test.ts, messages.test.ts, models.test.ts to cover more functionalities.
Low, adding tests.
This PR adds more tests to already existing test suites.
packages/core/src/tests/
navigate to packages/core and run pnpm install and pnpm test
> test: adding tests. changed files actions.test.ts, messages.test.ts, models.test.ts

- docs/docs/packages/plugins.md
- Plugin list numbering was broken. Fixed that.
- There were higher level titles inside some plugins' details. Gave them lesser hierarchy.
Documentation
It was bugging me while reading the docs.
calmbro
> Documentation: Plugin list numbering and titles

- .env.example
- agent/package.json
- agent/src/index.ts
- packages/plugin-sui/.npmignore
- packages/plugin-sui/eslint.config.mjs
- packages/plugin-sui/package.json
- packages/plugin-sui/src/actions/transfer.ts
- packages/plugin-sui/src/enviroment.ts
- packages/plugin-sui/src/index.ts
- packages/plugin-sui/src/providers/wallet.ts
- packages/plugin-sui/src/tests/wallet.test.ts
- packages/plugin-sui/tsconfig.json
- packages/plugin-sui/tsup.config.ts
- pnpm-lock.yaml
#868 
* no new risks presented
Introduce new Eliza Agent Plugin to manage a Sui Wallet
Add the ability for Eliza agents to interface with the Sui Blockchain.
* Goto `packages/plugin-sui` directory
* Run `pnpm i`
* Run `pnpm test`
```
stdout | src/tests/wallet.test.ts > WalletProvider > Wallet Integration > should check wallet address
Cache miss for fetchPortfolioValue
Cache miss for fetchPrices
stdout | src/tests/wallet.test.ts > WalletProvider > Wallet Integration > should check wallet address
Fetched portfolio: { totalUsd: '0.90126', totalSui: '0.9' }
Cache miss for fetchPrices
✓ src/tests/wallet.test.ts (1) 778ms
✓ WalletProvider (1) 777ms
✓ Wallet Integration (1) 777ms
✓ should check wallet address 776ms
Test Files  1 passed (1) …
```
> feat: add plugin-sui

- .gitignore
- characters/3cpo.character.json
- characters/dobby.character.json
While doing a lot of tests with Tate and Trump to fire some plugin actions I found out they were not ideal chars to do that, sometimes they are just arrogant and don't want to do things like actions. So I think we should have 2 more helpful and nicer chars to use for testing and development out of the box. 
So I give you Dobby and 3CPO
> fix: add more heplful default agents (Dobby and 3CPO)

- packages/client-discord/src/messages.ts
N/A
Low - Removing duplicate function.
Bug fix - Removing duplicate _isMessageForMe private function in Discord messages.ts file.
N/A
Review messages.ts in discord-client to confirm only 1 private _isMessageForMe now exists with same functionality to avoid issues.
N/A
N/A
N/A
N/A
> fix: discord client duplicate function removal

- docs/docs/api/functions/composeContext.md
- packages/core/package.json
- packages/core/src/context.ts
- packages/core/src/tests/context.test.ts
- pnpm-lock.yaml
Added support for the Handlebars templating engine in the composeContext function, allowing for advanced template processing in addition to the existing simple string replacement.
- Existing functionality for simple string replacement remains unchanged.
- Handlebars is an optional addition and is only used when specified, minimizing potential impact on existing use cases.
This PR enhances the composeContext function by integrating Handlebars as an optional templating engine. Users can now choose between simple key replacement or advanced template features provided by Handlebars, such as conditionals and loops.
- Feature: Adds a new functionality to support Handlebars templating engine.
- Yes: Update documentation to include examples of using the Handlebars templating engine with …
> feat: add support for handlebars templating engine as an option

- packages/client-twitter/src/post.ts
New tweet being created with `\n` text instead of new line
No risks
Improves tweet creation script. Make sure none `\n` are inside newly published tweet.
**Improvement.** This logic is already there inside `generateTweetContent` however it's not included inside `generateNewTweet`. It could use a little more refactor but right now I'm just posting this as an easy fix.
I'm playing around with eliza and my twitter account and saw that it posted tweet with `\n \n` inside which I don't think is what AI beneath intended :)
I looked at the logs and inserted the cleanup function right before it's submitted to twitter. I'm attaching screenshot from logs to see my reasoning 
Quite simple change
elowielo
> clean newlines for new tweet

- packages/client-telegram/src/messageManager.ts
N/A
Low - Removing duplicate function.
Bug fix - Removing duplicate _isMessageForMe private function in Telegram messages.ts file.
N/A
Review messageManager.ts in telegram-client to confirm only 1 private _isMessageForMe now exists with same functionality to avoid issues.
N/A
N/A
N/A
N/A
> fix: telegram client duplicate function removal

- packages/plugin-solana/package.json
- packages/plugin-solana/src/actions/fomo.ts
- packages/plugin-solana/src/index.ts
New create token action in plugin-solana for FOMO.fund
Low - this is a new action, it only adds code and 1 new dependency (FOMO sdk)
This allows an agent to create a token on FOMO.fund's bonding curve. Buy and Sell functions built in as well.
This adds a new action to plugin-solana for creating tokens on FOMO.fund
This adds another place agents can launch tokens using a launchpad other than pump.fun, FOMO.fund is a launchpad being built for agents.
ineedtendies
> feat: allow agents to create/buy/sell tokens on FOMO.fund's bonding curve in plugin-solana

- packages/plugin-solana/src/actions/fomo.ts
- packages/plugin-solana/src/actions/pumpfun.ts
- packages/plugin-solana/src/index.ts
Low
enables fomo action
improve code quality instead of removing fomo
> fix: improve fomo integration

- packages/plugin-solana/src/actions/fomo.ts
- packages/plugin-solana/src/index.ts
ShakkerNerd said to directly commit
> chore: fix PR #1147

- packages/client-discord/src/voice.ts
related: https://github.com/ai16z/eliza/issues/1145
reference: 
https://github.com/discordjs/voice/issues/206#issuecomment-924551194
https://stackoverflow.com/questions/71446777/how-do-i-manage-voice-connections-from-multiple-bots-in-one-code
> fix: Enable multiple bots to join Discord voice channels

- scripts/start.sh
> feat: make script dash compatible

- docs/docs/contributing.md
> docs: fixed CONTRIBUTING.md file Issue: 1048

- packages/core/README-TESTS.md
- packages/core/src/tests/runtime.test.ts
https://github.com/ai16z/eliza/issues/187
Low: adding tests for runtime.ts
This PR adds tests for runtime.ts
Adding new tests.
Contributing to have stable and good SDEC.
Minimal: Edited tests README file since we switched to vitests from jest.
packages/core/
navigate to directory and run pnpm install and pnpm test
> test: adding tests for runtime.ts. Modified README since we switched to vitest

- packages/client-telegram/src/messageManager.ts
- packages/client-twitter/src/utils.ts
- packages/plugin-image-generation/src/index.ts
related: 
https://github.com/ai16z/eliza/issues/970
https://github.com/ai16z/eliza/pull/1040
> fix: Allow the bot to post messages with images generated by the imageGenerationPlugin on Telegram.

- agent/src/index.ts
Low
fix scary start up warnings for firing it up out of the box
```
["◎ DirectClient constructor"] 
["⛔ Failed to get token - unsupported model provider: llama_local"] 
⛔ ERRORS
Error starting agent for character Eliza: 
{} 
["⛔ Error: Failed to get token - unsupported model provider: llama_local"] 
⛔ ERRORS
Error starting agents: 
{} 
["◎ Run `pnpm start:client` to start the client and visit the outputted URL (http://localhost:5173) to chat with your agents"] 
```
Improved new developer experience, reduce confusion
> fix: Fix local_llama key warning

- docs/docs/quickstart.md
Add a brief notice about the required Twitter "Automated" label setup in the quickstart guide to prevent accounts from being flagged.
Fixes #1253 
Multiple users have reported their agents being flagged when not properly labeled as automated accounts.
Add a single line notice about enabling the "Automated" label via Developer Portal:
```bash
**Important:** Log in to the [Twitter Developer Portal](https://developer.twitter.com) and enable the "Automated" label for your account to avoid being flagged as inauthentic.
> doc: add Twitter automation label notice (#1253)

- .env.example
- packages/core/src/generation.ts
- packages/plugin-web-search/src/index.ts
relates to tavily #518
Low
Constrain the maximum output of per web search from Tavily, while allows more input parameters that can be controlled by the developers or users.
Improvements & Features 
No
Yes, I have fulfilled the test by test this part independently and then assemble this to the core.
Could start with the test just like normally use Tavily.
> feat: upgrade Tavily API with comprehensive input and constrain the token consumption

- packages/adapter-redis/.npmignore
- packages/adapter-redis/eslint.config.mjs
- packages/adapter-redis/package.json
- packages/adapter-redis/src/index.ts
- packages/adapter-redis/tsconfig.json
- packages/adapter-redis/tsup.config.ts
- pnpm-lock.yaml
This PR introduces a Redis cache implementation. The implementation provides a reusable and scalable solution for caching data in the application by also implementing the IDatabaseCacheAdapter interface.
**Implemented Features:**
- `getCache`: Retrieves cached data for a given `agentId` and `key`.
- `setCache`: Caches data with a unique key constructed using `agentId` and `key`.
- `deleteCache`: Removes cached data for the specified `agentId` and `key`.
- Proper error handling and logging for all Redis operations.
- Integration with the `IDatabaseCacheAdapter` interface.
**Code Highlights:**
- A new `RedisClient` class implements the IDatabaseCacheAdapter interface.
- The `buildKey` method ensures unique Redis keys for each agent and operation.
- `ioredis` is used for efficient Redis …
> feat: Redis Cache Implementation

- .env.example
- agent/package.json
- agent/src/index.ts
- packages/core/src/types.ts
- pnpm-lock.yaml
This PR implements a flexible caching mechanism into the agent that supports Redis, Database, and File System as configurable options.
**Notes:**
- Requires `CACHE_STORE` environment variable. Support values are `redis`, `database`, `filesystem`.
- Requires `REDIS_URL` environment variable for Redis caching.
> feat: Add caching support for Redis

- agent/src/index.ts
update getting tokens to reflect no key needed for gaianet. Don't throw an error here.
getTokenForProvider function. 
Low risk, simply does not throw an error for gaianet anymore. 
Bug fix
We are doing this so that gaianet is supported here. 
> no token needed for gaianet

- turbo.json
Low.
I'm getting 'cannot find package' error like below with the latest develop branch:
> Error: Cannot find package '/Users/oxSaturn/eliza/agent/node_modules/@ai16z/plugin-nft-generation/' imported from /Users/oxSaturn/eliza/agent/src/index.ts
And seems someone ran into it as well in discord:
Setting `"outputs": ["dist/**"],` in `turbo.json` seems to fix the problem for me.
> fix: update turbo to fix "cannot find package" error

- agent/src/index.ts
Low.
Seems we introduced this new `CACHE_STORE` recently, but users with old `.env` could be missing it, and the error is kind of unclear:
```
throw new Error(
`Invalid cache store: ${cacheStore} or required configuration missing.`
);
```
Set a default value for cacheStore so we won't break the agents with old `.env` file.
> fix: set default value for cache store

- agent/src/index.ts
No risks
This pull request includes a small change to the `agent/src/index.ts` file. The change adds a new case for the `OLLAMA` model provider to the `getTokenForProvider` function, returning an empty string for this provider.
[`agent/src/index.ts`](diffhunk://#diff-935219608f7b5ca6c8b8548cfdce88c7d3cdb6bb6d9f9d8df644b364f6557e4eR220-R221): Added a case for `ModelProviderName.OLLAMA` in the `getTokenForProvider` function to return an empty string.
> fix: Add OLLAMA model to the getTokenForProvider class

- packages/client-farcaster/src/post.ts
- packages/client-farcaster/src/utils.ts
Medium risk: I don't know if neynar's APIs support long casts with 1024 length without any additional flags as I couldn't find the limit documented or if there are any other parameters except for `text` in their publishCast function. I don't have an account to test it. The value takes into consideration the byte length of the cast, so maybe unicode characters of 1024 length will fail.
The cast limit for farcaster client has been modified to match the [protocol's spec](https://github.com/farcasterxyz/protocol/blob/main/docs/SPECIFICATION.md#24-casts)
I wanted it to match the spec instead of the currently incorrectly defined limit
I don't think there's any documentation for the Farcaster client at the moment
If you have a neynar account try posting a cast with a message size of 1024 bytes
> Update farcaster client max cast length

- packages/plugin-0g/readme.md
chore: Document Missing Plugin Documentation and Examples #1200
Low 
Adds sample plugin documentation to 0G plugin. Uploading for review and comments. If this is satisfactory I will create docs for all other plugins.
> docs: sample plugin documentation

- packages/client-twitter/src/post.ts
Replace YES/NO with true/false for boolean variables in .env file. Ensure consistency across the codebase by removing the need for parseBooleanFromText.
Relates to:
#1391 - Standardize boolean values and fix pattern for .env file
Background
This PR replaces the "YES" and "NO" values used in the .env file for boolean variables with true and false to ensure consistency across the codebase. It removes the need for the parseBooleanFromText function, simplifying the parsing logic.
Testing
Where should a reviewer start?
The reviewer should begin by checking the .env file to ensure that all boolean variables are now using true or false instead of "YES" or "NO".
Detailed testing steps
Check the .env file and verify that all boolean variables …
> Standardize boolean values and update .env file pattern

- packages/client-twitter/src/post.ts
- Resolved an issue where `generateNewTweetLoop` was called twice in the `start` method of /packages/client-twitter/src/post.ts.
- The method was invoked at line 174 and line 190 without any conditional checks, leading to two independent tweet scheduling loops being created.
- Move second `generateNewTweetLoop()` inside the `if (enableActionProcessing)`
Fixes #1395
Issue #1395
Low: Removing the redundant call ensures only one scheduling loop, minimal impact on other functionalities.
This PR fixes an issue where `generateNewTweetLoop` was called twice, leading multiple tweets to be posted. It ensures only a single scheduling loop is initialized by removing the redundant call.
My changes do not require a change to the project …
> fix: duplicate tweet log

- packages/adapter-postgres/src/index.ts
- packages/core/src/embedding.ts
> fix: postgres adapter settings not being applied

- packages/plugin-bootstrap/src/evaluators/goal.ts
Low
Remove code duplication in  getGoals to avoid performance penalty
> fix: Remove code duplication in  getGoals call

- packages/core/src/generation.ts
modelConfiguration was not optional resulting in the core module crashing during answer generation
Low
modelConfiguration was not optional resulting in the core module crashing during answer generation
> fix(core) make modelConfiguration optional

- packages/client-twitter/src/post.ts
I'm not entirely sure if this would resolve the issue: https://github.com/elizaOS/eliza/pull/1396#issuecomment-2559249056.
From reviewing the code logic, it seems that enabling ENABLE_ACTION_PROCESSING might result in generating two TweetLoop instances. Is this the intended behavior?
@samarth30, could you kindly clarify this when you have a moment? Thank you so much!
related: https://github.com/elizaOS/eliza/issues/1395
> fix: duplicate twitter post

- packages/plugin-ton/Readme.md
this pr contains readme for ton plugin
> feat: add readme for ton plugin

- packages/plugin-web-search/Readme.md
This pr contains the readme for websearch plugin
> feat: add readme for websearch plugin

- docs/docs/advanced/fine-tuning.md
I noticed a syntax issue in the `ModelClass` enum where a comma was missing after the `EMBEDDING` value. This would have caused a compilation error or unexpected behavior. I've added the necessary comma so the code functions as intended.
Here’s the fix I applied:
Before:
```typescript
enum ModelClass {
SMALL,    // Fast, efficient for simple tasks
MEDIUM,   // Balanced performance and capability
LARGE,    // Most capable but slower/more expensive
EMBEDDING // Specialized for vector embeddings
IMAGE     // Image generation capabilities
}
```
After:
```typescript
enum ModelClass {
SMALL,    // Fast, efficient for simple tasks
MEDIUM,   // Balanced performance and capability
LARGE,    // Most capable but slower/more expensive
EMBEDDING, // Specialized for vector embeddings
IMAGE     // Image …
```
> docs: Fixed a small syntax issue in the ModelClass Update fine-tuning.md

- packages/client-twitter/src/post.ts
- Added proper boolean parsing for dry run configuration
- Improved configuration logging on startup
- Prevented tweet generation and action loops in dry run mode
- Added more descriptive dry run messages
- Fixed duplicate loop execution
Improves Twitter client functionality by enhancing dry run mode and configuration logging
Low - Changes are isolated to Twitter client's dry run functionality and logging
- Improves Twitter client's dry run mode implementation
- Enhances configuration logging for better visibility
- Prevents unnecessary API calls in dry run mode
- Fixes duplicate loop execution issues
- Makes configuration values more human-readable in logs
- Fixes rate limit errors in dry run mode
- Fixes duplicate loop execution
My …
> fix: improve Twitter client dry run mode and configuration logging

- packages/core/src/parsing.ts
- Added support for "ENABLE" and "DISABLE" as affirmative and negative cases respectively.
- Ensured consistent handling of null, undefined, and unrecognized inputs.
> feat: extend parseBooleanFromText function with additional boolean values

- packages/plugin-evm/src/actions/bridge.ts
- packages/plugin-evm/src/actions/swap.ts
- packages/plugin-evm/src/templates/index.ts
- #1251 
Low
The inputs of swap and bridge actions are not right.
This PR implements the missing swap and bridge functionalities in the plugin-evm.
> fix: swap and bridge actions of plugin-evm

- .env.example
- agent/src/index.ts
- docs/api/enumerations/ModelProviderName.md
- docs/api/type-aliases/Models.md
- docs/docs/api/enumerations/ModelProviderName.md
- docs/docs/api/type-aliases/Models.md
- docs/docs/guides/configuration.md
- docs/docs/quickstart.md
- packages/core/src/generation.ts
- packages/core/src/models.ts
- packages/core/src/types.ts
- packages/plugin-image-generation/src/index.ts
Low, only effects users using the new Livepeer provider.
Adds Livepeer as a model provider for image generation.
In a separate PR we will be adding the LLM generation for Livepeer provider as well, this is a clean separation with for image gen for now.
Feature that adds functionality, non-breaking.
Yes, I have a commit with doc changes ready. Will push them after this PR for correct API doc links.
1) Install and build from scratch to ensure no build errors. There are no new packages added with Livepeer.
2) Add a free gateway into the .env under `LIVEPEER_GATEWAY_URL=`
Here is one for testing `https://gateway.livepeer-eliza.com`
3) Set `IMAGE_GEN=` to `TRUE` in the .env
4) Add `"imageModelProvider": "livepeer"` to your character file.
5) Run start your character and open up the dialog box …
> feat: Add Livepeer Image Provider

- packages/client-telegram/src/messageManager.ts
- packages/client-telegram/src/utils.ts
[PR 1229](https://github.com/elizaOS/eliza/pull/1229)
Low: Fixes TG message handling with markdown, introduced with [PR 1229](https://github.com/elizaOS/eliza/pull/1229)
Bug fixes (non-breaking change which fixes an issue):
Fixes TG messages "Bad Request: can't parse entities"
And still keeps markdown functionality for regular messages.
N/A
Added escapeMarkdown function within /utils.ts, imported to messageManager, and passing through TG messages.
N/A
N/A
ninja_dev
> fix: Telegram Bad Request: can't parse entities

- packages/adapter-postgres/schema.sql
- packages/adapter-postgres/src/index.ts
- packages/adapter-supabase/schema.sql
- packages/core/src/embedding.ts
Low
Initialize the resources required for gaianet embedding like any other embedding model
If a docs change is needed: I have updated the documentation accordingly.
``` .env
...
GAIANET_MODEL=llama3b
GAIANET_SERVER_URL=https://llama3b.gaia.domains/v1
GAIANET_EMBEDDING_MODEL=nomic-embed
USE_GAIANET_EMBEDDING=TRUE
...
```
And chat with a agent.
> fix: init 768 dimension in database for gaianet

- packages/core/src/generation.ts
- packages/core/src/types.ts
add experimental telemetry model option
> feat: add experimental telemetry model option

- packages/core/src/settings.ts
- packages/core/tsup.config.ts
- scripts/clean.sh
- turbo.json
Finally found the cause of the error.
It was a literally caused by not adding a CommonJS module to external modules so as not to bundle it.
Rubbish!
> fix: breath taking error

- packages/core/src/generation.ts
Low
This PR fixes an issue where the GOOGLE_GENERATIVE_AI_API_KEY is not being passed through if set in the character file.
We are fixing a bug.
N/A
<!--
Set the GOOGLE_GENERATIVE_AI_API_KEY in the .env file and generation works, than remove it from .env file and set it in character secrets, and generation will fail stating missing API key.
ninja_dev
> fix: Google API Key not passing from character file

- packages/plugin-bootstrap/src/actions/continue.ts
Low
This PR fixes a double response issue that was caused by the CONTINUE action in the plugin-bootstrap. The agent would respond to the same message multiple time due to the continue trigger.
N/A
Test sending a message, watch logs for CONTINUE message to be triggered, watch logs as agent logs that a response has already been sent to an existing message or not responding further.
The double response was seen as triggered in a CONTINUE action whe the agent would ask/frame response a certain way back to the user. Which on subsequent messages, would trigger the callback to respond to the same message multiple times.
Where the continue action is meant for a natural flow of thoughts to keep generating, on normal back and forth convo's it …
> fix: Double Responses from Continue Action

- packages/plugin-evm/package.json
- packages/plugin-goat/package.json
- pnpm-lock.yaml
https://github.com/elizaOS/eliza/issues/1635
Low
update the version of viem to 2.21.58 in plugin-evm and plugin-goat.
Updates
just installing to confirm it starts with the new version.
bertux.celo
> chore: update viem dependency version in plugin-evm and plugin-goat

- .github/workflows/integrationTests.yaml
- package.json
- packages/client-lens/package.json
- packages/plugin-abstract/package.json
- packages/plugin-avalanche/package.json
- packages/plugin-evm/package.json
- packages/plugin-goat/package.json
- packages/plugin-story/package.json
- packages/plugin-tee/package.json
- pnpm-lock.yaml
- scripts/clean.sh
Trunk being broken
Low. This change updates the `pnpm-lock.yaml` file, which could affect dependency resolutions. Potential risks include:
- **Dependency Resolution Changes:** Updates might lead to different versions of dependencies being installed, which could introduce unforeseen issues.
- **Build or Runtime Errors:** If updated dependencies have breaking changes, they might cause build failures or runtime errors.
This pull request updates the `pnpm-lock.yaml` file by running `pnpm install -r --no-frozen-lockfile`. This command installs dependencies recursively across all workspaces and refreshes the lockfile to reflect any changes in dependencies.
- **Updates:** This is a non-breaking change that updates the lockfile to ensure it accurately represents the current state of dependencies. …
> fix: lockfile wasn't updated after dependency + bring viem to root level package.json

- packages/plugin-near/src/actions/swap.ts
- packages/plugin-near/src/actions/transfer.ts
- packages/plugin-near/src/providers/wallet.ts
> feat(plugin-near): replace console.log to eliza logger

- docker-compose.yaml
3000 is listening on the docker image
Low - This change affects the Docker container configuration. It may require updates to documentation and environment configurations where the container is deployed.
---
This pull request updates the Dockerfile and related Docker configuration to expose port 3000 instead of port 80. This change is necessary to align with our application's configuration and avoid conflicts with other services running on port 80.
N/A (Issue linked provides context)
---
My changes require a change to the project documentation. I have updated the documentation accordingly.
---
Start by reviewing the changes in the Dockerfile and docker-compose.yml files.
1. Pull the latest changes from the repository.
2. Build the …
> fix: bugfix. the port 80 is not listening use 3000

- packages/plugin-image-generation/src/index.ts
https://github.com/elizaOS/eliza/issues/917
https://github.com/elizaOS/eliza/issues/1118
Low. It adds a default export. 
After adding the plugin to the character file and running `pnpm start` you get an `can't access property "actions" of undefined"`. That's because the plugin loader uses the default export after importing a plugin. See [here](https://github.com/elizaos/eliza/blob/6759187b4e629304381cfdcba6d8634a3044d5f6/agent/src/index.ts#L214).
It adds the default export to the `plugin-image-generation` so the plugin can be used in `character.json` files.
Bug Fix
> fix: add default export to plugin-image-generation

- packages/plugin-bootstrap/src/index.ts
Relates to:
Plugin export collisions in character files
Risks
Low - This is a minor bug fix that ensures proper module exports
Background
Ensures the bootstrap plugin has a proper default export at the bottom to avoid collisions when used in the actions module in character files. This maintains consistency with other plugins in the codebase that follow the same pattern (like the EVM plugin).
Documentation changes needed?
Testing
Where should a reviewer start?
Check packages/plugin-bootstrap/src/index.ts to verify the proper export structure Verify that the plugin can be properly imported in character files without …
> chore: update bootstrap plugin export

- CONTRIBUTING.md
- docs/docs/contributing.md
This pull request includes a small change to the `CONTRIBUTING.md` and `docs/docs/contributing.md` files. The change corrects the link to the FAQ page to point to the correct location.
* [`CONTRIBUTING.md`](diffhunk://#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055L82-R82): Updated the FAQ link from `docs/community/faq.md` to `docs/docs/faq.md`.
* [`docs/docs/contributing.md`](diffhunk://#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055L82-R82): Updated the FAQ link from `docs/community/faq.md` to `docs/docs/faq.md`.
https://github.com/elizaOS/eliza/issues/1838
Low - docs change
Read the contributing docs, they were broken, submitting a PR
fixes the docs
Includes documentation change
Check …
> correct faq docs link in both contribution md files

- .env.example
- agent/src/index.ts
- packages/core/generation.ts
- packages/core/models.ts
- packages/core/types.ts
N/A
N/A
This PR introduces an additional inference provider for Eliza, enabling agents to be powered by models hosted on Infera. Additionally, Infera is currently free, further making Eliza more accessible to developers.
Feature (non-breaking change which adds new functionality)
We want to contribute to Eliza project in a way that allows for developers to easily use a versatile inference provider. Currently Infera is free for all users and our goal at Infera is to further lower the barrier for developers to work on AI agents.
`.env.example` has been updated with Infera settings.
Reviewer should focus on eliza/packages/core/src/generations.ts , eliza/packages/core/src/models.ts, eliza/packages/core/src/types.ts and eliza/agent/src/index.ts
Option 1:
Add an Infera API key to your .env file …
> Feat: add infera as an inference provide

- packages/plugin-solana/src/providers/simulationSellingService.ts
- packages/plugin-solana/src/providers/token.ts
Executing trades
low
I was unable to execute a trade unless I made these changes
Awaits cached data because the function returns a promise. If we don't await, then the results are always not null and the logic is incorrect and likely fails downstream.
It's a bug fix
None
- Start the app with a character and a valid wallet address and private key
- Start the UI
- Use the following prompt: "buy 0.001 sol of GOAT CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump"
> fix(solana token provider): await cached data

- packages/plugin-node/scripts/postinstall.js
Low
Add more playwright support for various debian distros.
because it said I wasn't debian and I was like what?
> chore: support more debians distros

- docs/docs/guides/local-development.md
fixed broken API Documentation in local-development.md
it's not a lot, but it's honest work.
> Fixed broken API Documentation URL

- packages/client-twitter/src/utils.ts
fix twitter result obj undefined properties
> fix: twitter result obj undefined properties

- packages/core/src/runtime.ts
Low
Makes sure evaluators isn't null in the runtime evaluators handler loop.
> fix(core): check evaluators for null

- packages/client-twitter/src/base.ts
- packages/client-twitter/src/post.ts
Related Issue
https://github.com/elizaOS/agent-twitter-client/issues/43
Problem
The count parameter is currently not functioning. Based on testing, it appears to be ignored on the server side. This is problematic, as the default behavior fetches a large number of timelines:
fetchHomeTimeline: ~30–40 timelines per request
fetchFollowingTimeline: ~100 timelines per request
For users with the action processing feature enabled, this results in excessive LLM API calls (Reference: https://github.com/elizaOS/eliza/pull/1824 introduced a new environment variable to enable user interactions with following timelines.). In this PR, I used a workaround by slicing the timelines before processing to reduce the number of processed items.
> fix: Limit the number of timelines fetched

- .env.example
- README_CN.md
- README_ES.md
- README_JA.md
- README_PTBR.md
- README_RO.md
- README_RS.md
- README_RU.md
- docker-compose.yaml
- docs/README_CN.md
- docs/docs/guides/local-development.md
Low
Removes the unused X_SERVER_URL that appears to be a relic of legacy code.
Improvement
I noticed this doesn't appear to be used in the code anymore. I also noticed that the XAI_API_KEY is only used for loading the Together API but it has it's own API key var now (which can be used to load the provider). Should I go ahead and remove it as well? I feel like most people think these vars are related to X/Twitter or xAI and may be confused by them.
A lot of the documentation does need to be updated to reflect the changes to selecting providers and models. Many may be trying to use this unworking and unused variable. I removed it from the Readme's on here in this PR though.
@proteanx (same as on here)
> fix: rm unused variable X_SERVER_URL

- .env.example
- packages/core/src/generation.ts
Low
Config eternalai can extra request body with chain_id from env, this PR will replace for PR #1903
More flexible than with env
Currently, Eliza supports only OpenAI. However, centralized AI providers limit user control, pose trust issues, and create single points of failure with high costs and restricted access. Decentralized AI offers a more transparent, accessible, and resilient alternative, empowering users with greater autonomy.
Learn more about our decentralized inference AI: https://eternalai.org/api
Reviewers start from .env.example
Run pnpm start --characters="path/to/your/characters/eternal.character.json"
No change
Change .env by adding more
ETERNALAI_CHAIN_ID=45762 #Default: "45762"
> feat: support for eternalai provider can make request with chain_id extra data in body

- characters/c3po.character.json
- packages/core/src/environment.ts
- Resolved an array in the c3po character file where the messageExamples were an object rather an 2D array.
- Character validation handling has been improved
Before:
After:
Hopefully this resolves the following issues: https://github.com/elizaOS/eliza/issues/1946 https://github.com/elizaOS/eliza/issues/1929
It seems users were copying C3PO as it's the first one on the list and then altering it.
> fix: fixed error in C3PO and improved error handling feedback

- packages/adapter-sqlite/src/index.ts
Prevents the sqlite database from getting corrupted.
Tried to just NULL as a solution first, but it would error as well.
Seems the best solution is to just store an empty array with the defined default length of 384.
> fix: SQLITE ERROR, zero-lenght vectors not supported

- packages/client-telegram/src/messageManager.ts
https://github.com/elizaOS/eliza/issues/1972
Low
Solves Telegram context, as explained with an example in issue #1972.
- change {{agent}} to {{agentName}} for consistency
- remove variables from the template that didn't exist in the state
- fix markdown
- remove prepended explanation text for variables that already had it in the state
- make it more clear to the AI agent that he's replying on Telegram because when asked, he didn't even know he was on Telegram
First cherry-pick my other pull request that makes Eliza show context for each agent reply #1980. Then talk with the AI agent on Telegram.
None: Automated tests are acceptable.
laurwin
> fix: many fixes to the Telegram templates

- .env.example
- packages/client-twitter/package.json
- packages/client-twitter/src/post.ts
Low Risk- Works only If enabled
This PR introduces a new feature in the Twitter client that implements an approval workflow before publishing tweets on Twitter. This feature is particularly useful for organizations using Eliza to manage their Twitter accounts, as it provides an additional layer of control by requiring approval before any content goes live.
The approval mechanism is being introduced to address the needs of organizations and teams that require greater control over the content being published via their Twitter accounts. By adding this feature, we enable a structured review process to ensure that tweets align with brand guidelines, organizational policies, and quality standards before they are made public.
- Use Case in …
> feat: Add approval mechanism for Twitter posts via Discord bot

- packages/adapter-postgres/package.json
Fixes #2009  - @elizaos/adapter-postgres package does not bundle together schema.sql
Low - Adding missing SQL files to package bundling. Only affects package distribution, not functionality.
Adds schema.sql and seed.sql files to the package.json "files" array to ensure they are properly bundled with the npm package when published.
1. Review the package.json changes in packages/adapter-postgres/package.json
2. Verify the added files: schema.sql and seed.sql are included
1. Run `pnpm install @elizaos/adapter-postgres`
2. Instantiate PostgresDatabaseAdapter
3. Call db.init()
4. Verify no "no such file or directory" errors occur
5. Verify migrations run successfully
After …
> fix: include schema.sql and seed.sql in package files

- agent/src/index.ts
- packages/plugin-lensNetwork/src/index.ts
wrong export name: https://github.com/elizaOS/eliza/blob/bcad0c4485d58b058553a813a9ab3fcd4993e01c/agent/src/index.ts#L66
and fixed duplicated import
> fix: lens export name and duplicate imports

- packages/plugin-starknet/package.json
- packages/plugin-starknet/src/providers/portfolioProvider.ts
- packages/plugin-starknet/src/providers/token.ts
- packages/plugin-starknet/src/providers/trustScoreProvider.ts
- pnpm-lock.yaml
https://github.com/elizaOS/eliza/issues/2028
Low risk, just fixing something that use to be broken so that people now can begin to use the starknet plugin.
Fixes the starknet plugin by updating some broken references.
Bug fixes
- Clone the eliza-starter repo
- replace the starknet plugin dependency in package.json with "@elizaos/plugin-starknet": "file:./plugin-starknet", where plugin-starknet is the path to the plugin-starknet folder of the plugin that was changed here.
- cd into the plugin folder, build the plugin with pnpm build
- install the plugin in eliza-starter with pnpm i
- add the plugin in your character plugins
- run the project with pnpm start, it should include the starknet actions and run without issues.
> Fix: fix starknet plugin by replacing walletProvider with portfolio provider

- packages/client-discord/src/actions/joinvoice.ts
related: https://github.com/elizaOS/eliza/issues/2147
https://github.com/user-attachments/assets/afc11430-8d3a-45f8-958c-7485cf55e86c
> fix: fix client-discord join voice action

- .vscode/settings.json
None
Low
Make the project workspace cleaner
Folding the related files of \*.md, Dockerfile, and package.json
Features
no
> feat: 🎈 perf(vscode): Set file nesting for md and DockerFile

- agent/src/index.ts
https://github.com/elizaOS/eliza/pull/2067
Low
DeepSeek is a leading AI model provider offering high-performance language models with OpenAI-compatible API format. And the model support was introduced (but incomplete) in the issue above.
Complete the deepseek api support.
1. agent/src/index.ts - Add deepseek in getTokenForProvider
- Set DEEPSEEK_API_KEY in .env
- Configure a character to use "deepseek" as modelProvider
- Start the agent and verify chat completion works
- Verify different model classes (SMALL, MEDIUM, LARGE) work correctly
New environment variables needed:
- DEEPSEEK_API_KEY
- DEEPSEEK_API_URL (optional)
- SMALL_DEEPSEEK_MODEL (optional)
- …
> fix: deepseek support in getTokenForProvider

- packages/core/src/types.ts
Adds missing LETZAI enum value to ModelProviderName to fix type errors in agent/src/index.ts.
In @elizaos/packages/core, add to ModelProviderName enum:
1. Build core package
2. Verify agent/src/index.ts compiles without errors 
3. Verify LETZAI provider works with getTokenForProvider()
- Simple enum addition
- Only affects type system
- No runtime behavior changes
1. Add enum value
2. Run `pnpm build` in core package
3. Run `pnpm build` in agent package
4. Verify no TypeScript errors in agent/src/index.ts
No documentation changes needed as this is an internal enum update.
> fix: Missing LETZAI model

- README.md
- README_GR.md
Relates to
This pull request relates to issue https://github.com/elizaOS/eliza/issues/2197.
Risks
Low: This PR only adds a Greek translation for the README file and updates the main README to include a link to the new translation. No functionality or core code is affected.
Background
This PR adds a new README_GR.md file containing a Greek translation of the README. It also updates the main README.md file to include a link to the Greek version under the translations section.
Documentation: This is a documentation change, adding a new translation and improving accessibility for Greek-speaking users.
Documentation changes needed?
I have updated the main README file to include a link …
> Add Greek translation for README_GR

- packages/plugin-node/scripts/postinstall.js
Low
Currently pnpm install on linux (and probably mac etc) is doing a ```npx playwright install-deps``` for the post postinstall script on plugin-node. This forces a super user login for root access which is a huge red flag and generally a bad practice.
Removes the root privileged command and in the rare case the user does not have the required dependencies prints a console message on how to fix. This way users aren't blindly trusting what calls are being made with super user privileges.  
Bug fix
None
> fix: don't force root for install

- packages/plugin-evm/src/templates/index.ts
- packages/plugin-evm/src/types/index.ts
No specific issue related.
Low. This PR only adds gravity to templates and types.
- Updated `fromChain` and `toChain` types in `templates/index.ts` to include "gravity".
- Added "gravity" to the `EvmPluginConfig` interface in `types/index.ts`.
This enhancement allows the EVM plugin to handle transactions involving the ["gravity" chain.](https://docs.gravity.xyz/network/using-gravity-alpha-mainnet-l2)
> feat: add support for gravity chain in EVM plugin

- packages/plugin-abstract/package.json
- packages/plugin-abstract/src/actions/transferAction.ts
- packages/plugin-tts/package.json
- pnpm-lock.yaml
Gives eliza agents their own abstract global wallets so they can use Abstract similar to how real users will use the chain
Low
> feat: Add AGW support to the Abstract plugin

- packages/plugin-stargaze/README.md
Corrected a typo:
- Replaced `publically` with `publicly` in the README file.
---
This PR is ready for review. 🚀
> docs: Typo fix README.md

- client/package.json
Fixes #2223
#2223 
Windows users are experiencing an issue with the `extract-version` script in package.json. The current configuration works differently on Windows vs Unix-based systems:
- Windows requires: `"extract-version": "version.sh"`
- Unix requires: `"extract-version": "./version.sh"`
This is causing the script to fail on Windows systems due to path resolution differences between operating systems.
Solution
The most cross-platform compatible solution is to use the `sh` command explicitly in the script
> fix: resolve Windows path issue in pnpm build client

- .env.example
- agent/package.json
- agent/src/index.ts
- packages/plugin-gitcoin-passport/README.md
- packages/plugin-gitcoin-passport/eslint.config.mjs
- packages/plugin-gitcoin-passport/package.json
- packages/plugin-gitcoin-passport/src/actions/getScore.ts
- packages/plugin-gitcoin-passport/src/index.ts
- packages/plugin-gitcoin-passport/tsconfig.json
- packages/plugin-gitcoin-passport/tsup.config.ts
- pnpm-lock.yaml
Include gitcoin passport integration so AI Agents can check the score of Ethereum addresses and their credibility.
It should help in making some kind of decisions and trust
> feat: Gitcoin passport

- docs/docs/advanced/eliza-in-tee.md
- docs/docs/packages/plugins.md
- packages/plugin-evm/src/providers/wallet.ts
- packages/plugin-solana/src/keypairUtils.ts
- packages/plugin-tee/package.json
- packages/plugin-tee/src/actions/remoteAttestation.ts
- packages/plugin-tee/src/providers/deriveKeyProvider.ts
- packages/plugin-tee/src/providers/remoteAttestationProvider.ts
- packages/plugin-tee/src/providers/walletProvider.ts
- packages/plugin-tee/src/tests/deriveKey.test.ts
- packages/plugin-tee/src/tests/remoteAttestation.test.ts
- packages/plugin-tee/src/tests/remoteAttestationAction.test.ts
- packages/plugin-tee/src/types/tee.ts
Re-implements #2039 and updates Remote Attestations to have more content to ensure older generated RA Quotes cannot be used to as a fake verifiable quote.  
Low
Currently, the derive key function will use the `WALLET_SECRET_SALT` to generate a key for the agent. This is okay for single agent deployments, but the subject field is used for the certificate chain and will not generate a new key if the `WALLET_SECRET_SALT` is changed during an upgrade. This change moves the `WALLET_SECRET_SALT` to the `path` parameter and uses the `subject` parameter to define the type of wallet (i.e solana, evm).
Another problem with the current remote attestations is that not enough content is added to the RA Quote `reportData` parameter. Currently, we only include the `agentId` and this will become …
> fix: fix derive key and update remote attestation

- agent/src/index.ts
LOW
set private runtime envs for each character, eg:  
```
character.settings.secrets = {...privateEnvs};
```
use openrouter as ModelProvider and set OPENROUTER_API_KEY as agent runtime secrects 
fix OPENROUTER_API_KEY env bug
Bug fixes
NO
use openrouter as ModelProvider and set OPENROUTER_API_KEY as agent runtime secrects 
runs correctly
> fix: correct OPENROUTER_API_KEY env in config

- packages/core/src/runtime.ts
- packages/plugin-node/src/services/image.ts
Action: DESCRIBE_IMAGE
Low
Modified the core/runtime.ts and plugin-node/service/image.ts files. 
As it is core files, maybe it can affect others plugins.
This PR includes the "class GroqImageProvider implements ImageProvider"
that is used to describe images using the llama-3.2-90b-vision-preview Model.
Improvements (now image description works with Groq)
This feature is to use an Vision Image Provider supported by Groq llama vision models that i`m working with.
configure Groq as Model provider
Send an image asking to agent describe it.
|Before new feature|After new feature|
|-|-|
|![groq-error-image-vision-provider](https://github.com/user-attachments/assets/0e417e2f-9a82-4a1d-9242-318d75bc680c)|![groq-success-image-visiion-p …
> feat: groq image vision provider

- packages/core/src/generation.ts
https://github.com/elizaOS/eliza/issues/2164
Medium
The key changes:
Added explicit return type Promise<Response> to the fetch function
Added explicit type RequestInit to the options object
Maintained proper ordering of URL | RequestInfo for the input parameter
Improvements
The key changes:
Added explicit return type Promise<Response> to the fetch function
Added explicit type RequestInit to the options object
Maintained proper ordering of URL | RequestInfo for the input parameter
Issue: https://github.com/elizaOS/eliza/issues/2164
core/src/generation.ts
run pnpm build
> improvement: using strict types to avoid erorrs like issue 2164

- README.md
Hey all! I saw strange formatting in the README.md and figured it was an extra three backticks ```
Sure enough, deleting those made the section render as intended. I also reworded one of the sentences that had three "and"s to make it a little more legible.
None? Small README tweak shouldn't break anything.
Small tweak to a specific section of the README to make it render as intended by the author.
Improvement to legibility of README.
The changes are to the documentation :)
Preview the file and lmk if you agree it's an improvement.
Before:
After:
Happy to get the role `@derrekwonders`, but not needed for something small like this.
> Fix formatting in Browser section of README.md

- packages/adapter-sqlite/src/index.ts
- packages/core/src/environment.ts
- packages/core/src/generation.ts
- packages/core/src/localembeddingManager.ts
- packages/core/src/ragknowledge.ts
- packages/core/src/runtime.ts
- packages/core/src/types.ts
- Added support for double-byte characters (e.g., Chinese) to ensure proper processing.
- Implemented cleanup of deleted knowledge files to maintain data integrity.
- Enabled loading knowledge from directories, simplifying configuration and management.
These improvements address performance and usability issues, facilitating better support for large knowledge sets.
Closes #2323
These are changes to ragKnowledge so should be low.
In your character card, set:
"ragKnowledge": true,
and configure your knowledge folders.  Direct files and strings are still supported, below is a sample:
```
"knowledge": [
{
"path": "hexagrams/harvardYenchingHexagrams.md"
},
{
"directory": "shared/warringstates",
"shared": true
},
"The art of war is of vital importance to the state. It is a matter of life and …
```
> feat: (ragKnowledge) Enhance RAG knowledge handling

- .env.example
- client/src/lib/api.ts
- client/vite.config.ts
Low
Currently, the client depends on the api (server) base url, which is hardcoded in `client/src/lib/api.ts`:
```
const BASE_URL = "http://localhost:3000";
```
If we would like to run the server on another port, we can modify the `SERVER_PORT` in `.env`, while we still need to update the `BASE_URL` in the `client/src/lib/api.ts`.
This PR will align the server port, so that we only need to update the `.env` if we need to run the server on a different port.
It also ensures the single source of credential.
Improvements
Run the project on a different port, and see if the client works as expected.
> fix: align base url in client if api runs on a different port

- packages/core/src/generation.ts
- packages/core/src/types.ts
- packages/plugin-image-generation/src/index.ts
- pnpm-lock.yaml
Very low
Venice has uncensored image generation which may create issues for agents running on platforms with strict terms of service related to nudity or graphic content.
Venice recently added safe_mode to automatically blur out graphic content made by one of their uncensored models. We added this as well as a missing param cfg_scale.
None required but I can add instructions for unique venice capabilities if wanted.
add imageSettings to character file like below
using the flux-dev-uncensored model (set w/ IMAGE_VENICE_MODEL) make a graphic content image prompt.
> feat: add safe_mode (& cfg_scale) for venice image generation

- .env.example
- agent/src/index.ts
[Issue #2252](https://github.com/elizaOS/eliza/issues/2252)
[Expands on PR #2281](https://github.com/elizaOS/eliza/pull/2281)
- Security risk using character URLs
Allows multiple remote character urls to be used whether in conjuction with `character(s)` param or not
- A user can start the server with OR without character(s) params and the remote character(s) will load
> feat: Enable Multiple remote character urls

- agent/src/index.ts
right now if the REMOTE_CHARACTER_URLS environment variable is not defined, the app would crash
The issue causing the app to crash when the REMOTE_CHARACTER_URLS environment variable is not defined originated from changes introduced in PR https://github.com/elizaOS/eliza/pull/2328
> Fix: Prevent app crash when REMOTE_CHARACTER_URLS is undefined

- agent/src/index.ts
- client/src/lib/info.json
No specific issue ticket.
Low - This is a minor validation improvement that makes the URL check more robust.
Character start fails due to lack of a env
Improves the URL validation check in the `hasValidRemoteUrls()` function to be more stable by ensuring URLs start with "http" rather than just checking for non-empty strings.
Look at the `hasValidRemoteUrls()` function in `agent/src/index.ts`:
```typescript:agent/src/index.ts
// Before:
const hasValidRemoteUrls = () =>
process.env.REMOTE_CHARACTER_URLS &&
process.env.REMOTE_CHARACTER_URLS !== "";
// After:
const hasValidRemoteUrls = () =>
process.env.REMOTE_CHARACTER_URLS &&
process.env.REMOTE_CHARACTER_URLS !== "" && …
```
> Startup Error: ENV misconfig

- .env.example
https://github.com/elizaOS/eliza/pull/1482
Low
Set a better default throttle interval for Squid Router
Improvement
> fix: set default Squid Router plugin throttle to 1000

- docs/docs/quickstart.md
> fix: quickstart.md conflicts

- packages/plugin-obsidian/README.md
Update documentation links in README.md
Changes:
- Updated documentation link in packages/plugin-obsidian/README.md from https://docs.elizaos.com to https://elizaos.github.io/eliza/
Why:
This update redirects users to the correct documentation URL on GitHub Pages, ensuring access to up-to-date documentation.
> Update documentation links 

- packages/adapter-supabase/seed.sql
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `last_messsage_read` to `last_message_read`
Please review the changes and let me know if any additional changes are needed.
> fix: typos in supabase seed file

- packages/plugin-0g/README.md
Update Zero Gravity (0G) link in README.md
Changes:
- Updated Zero Gravity link in packages/plugin-0g/README.md from https://0g.xyz to https://0g.ai
Why:
This update fixes the broken link to Zero Gravity's website by pointing to their current active domain, ensuring users can access the correct project information.
> fix: update zero Gravity (0G) link

- docs/api/classes/MemoryCacheAdapter.md
- docs/community/ai16z/degenai/index.md
Fix typos in docs
No related issues
Low - documentation changes only
- Fix "initalData" to "initialData" in MemoryCacheAdapter
- Unify "DegenSpartanAI" naming across docs
- Bug fixes (typo corrections)
Visually verified, typos fixed
Documentation has been updated
> Fix typos in docs

- .github/workflows/smoke-tests.yml
> revert: "refactor: dockerize smoke tests"

- .env.example
- agent/src/index.ts
- packages/core/src/defaultCharacter.ts
- packages/plugin-iq6900/src/functions/bringIQData.ts
- pnpm-lock.yaml
related: https://github.com/elizaOS/eliza/issues/2450
> fix: OPENAI provider being overwritten by LLAMA_LOCAL on pnpm start

- packages/plugin-squid-router/README.md
This pull request corrects a typo in the `README.md` file for the `@elizaos/squid-router` package. The word "beteen" was updated to "between" to enhance readability and accuracy.
- Corrected the typo in the following sentence:
```diff
- For now, only swaps beteen EVM chains are supported, but the plan is to add swaps from/to Solana and the Cosomos ecosystem.
+ For now, only swaps between EVM chains are supported, but the plan is to add swaps from/to Solana and the Cosmos ecosystem.
> Typo fix in read.me

- .github/workflows/smoke-tests.yml
> chore: add openai env to smokeTests

- packages/adapter-redis/__tests__/redis-adapter.test.ts
- packages/adapter-redis/package.json
- packages/adapter-redis/vitest.config.ts
https://github.com/elizaOS/eliza/issues/2469
Low: adding tests and test configuration.
https://github.com/elizaOS/eliza/issues/2469
Features/Tests
https://github.com/elizaOS/eliza/issues/2469
None
packages/adapter-redis
pnpm install in root of the directory
navigate to desired directory to see tests
run pnpm test to run tests
> test: adding test configuration and tests for redis adapter

- packages/adapter-sqlite/__tests__/sqlite-adapter.test.ts
- packages/adapter-sqlite/package.json
- packages/adapter-sqlite/vitest.config.ts
- packages/adapter-supabase/__tests__/supabase-adapter.test.ts
- packages/adapter-supabase/package.json
- packages/adapter-supabase/vitest.config.ts
https://github.com/elizaOS/eliza/issues/2467
Low: adding tests
https://github.com/elizaOS/eliza/issues/2467
features/tests
None
packages/adapter-sqlite
packages/adapter-supabase
pnpm install in root
navigate to desired directories to see tests
run pnpm test to run tests
> feat: tests for supabase and sqlite db adapters

- packages/plugin-sui/src/utils.ts
Low
Sui supports the secp256k1/secp256r1 algorithms. When the wallet is loaded, it needs to support both of these algorithms simultaneously.
docs: https://docs.sui.io/guides/developer/cryptography/signing
Features: Sui supports the secp256k1/secp256r1 algorithms
> feat: Sui supports the secp256k1/secp256r1 algorithms

- .env.example
- agent/package.json
- agent/src/index.ts
- packages/plugin-holdstation/.npmignore
- packages/plugin-holdstation/README.md
- packages/plugin-holdstation/eslint.config.mjs
- packages/plugin-holdstation/package.json
- packages/plugin-holdstation/src/actions/swapAction.ts
- packages/plugin-holdstation/src/constants/index.ts
- packages/plugin-holdstation/src/environment.ts
- packages/plugin-holdstation/src/hooks/index.ts
- packages/plugin-holdstation/src/hooks/useGetAccount.ts
- packages/plugin-holdstation/src/hooks/useGetWalletClient.ts
- packages/plugin-holdstation/src/index.ts
- packages/plugin-holdstation/src/providers/walletProvider.ts
- packages/plugin-holdstation/src/templates/index.ts
- packages/plugin-holdstation/src/templates/swapTemplate.ts
- packages/plugin-holdstation/src/types/index.ts
- packages/plugin-holdstation/tsconfig.json
- packages/plugin-holdstation/tsup.config.ts
No specific issue or ticket is linked to this PR.
Low: This PR is for create a plugin that is not effecting the core functionality of the application.
This PR creates a plugin that allows users integrate with Holdstation Wallet on now on Zksync Era and Berachain coming soon. including the following features:
- Token swapping on Hold.so (Holdstation swap)
Review the new plugin from src/index.ts, actions/_ providers/_
Please refer to the README.md for detailed testing steps.
> feat(plugin-holdstation): add plugin holdstation swap

- packages/plugin-node/src/environment.ts
- packages/plugin-node/src/services/awsS3.ts
https://github.com/elizaOS/eliza/issues/2174, and builds upon https://github.com/elizaOS/eliza/pull/2379
Low. This affects only the `plugin-node`, and it changes logic in a way that is backward compatible. 
This changes the `plugin-node` to, optionally, use the set `AWS_S3_ENDPOINT` when generating URLs. If the value is set (e.g., `http://localhost:8014`), it instead uses this custom URL when reading/writing data. Closes https://github.com/elizaOS/eliza/issues/2174.
Feature; improves the S3 plugin functionality. 
The S3 plugin lacked a small feature, which was still enforcing public AWS S3 URLs, even if you're using a local provider.
For reference, I'm building a web3 native object storage layer, which has S3 compatability—called Basin: https://basin.textile.io. We have an S3 adapter that …
> feat: custom s3 endpoint url for 'plugin-node'

- .env.example
- agent/package.json
- agent/src/index.ts
- packages/plugin-ethstorage/.npmignore
- packages/plugin-ethstorage/README.md
- packages/plugin-ethstorage/package.json
- packages/plugin-ethstorage/src/actions/submitData.ts
- packages/plugin-ethstorage/src/actions/transfer.ts
- packages/plugin-ethstorage/src/environment.ts
- packages/plugin-ethstorage/src/index.ts
- packages/plugin-ethstorage/src/utils/blobs.ts
- packages/plugin-ethstorage/src/utils/uploader.ts
- packages/plugin-ethstorage/tsconfig.json
- packages/plugin-ethstorage/tsup.config.ts
- pnpm-lock.yaml
The PR is not related to any issues.
Low risk, this PR is to add a new plugin, does not affect the core functionalities of Eliza.
There are existing tools that assist users in interacting with decentralized storage networks like EthStorage. These tools enable users to store and retrieve data in a decentralized manner, leveraging blockchain-based storage mechanisms. The EthStorage plugin allows for the transfer of QKC tokens and submission of arbitrary data to the EthStorage network, offering users a way to interact with decentralized storage easily. The plugin also provides a simple interface to interact with the EthStorage testnet and, once the mainnet is available, will enable mainnet interactions.
This PR adds the `plugin-ethstorage`, which interacts with the EthStorage decentralized …
> feat: Add plugin-ethstorage

- docs/docs/guides/configuration.md
Adding to `docs/guides/configuration.md`: 
```
If you don't want to have secrets in your character files because you would
like to utilize source control for collaborative development on multiple
characters, then you can put all character secrets in `.env` by prepending
`CHARACTER.NAME.` before the key name and value. For example:
```bash
CHARACTER.C3PO.DISCORD_APPLICATION_ID=abc
CHARACTER.C3PO.DISCORD_API_TOKEN=xyz
CHARACTER.DOBBY.DISCORD_APPLICATION_ID=123
CHARACTER.DOBBY.DISCORD_API_TOKEN=369
```
> docs: add docs on configuring secrets for multi agent workflows.

- packages/client-twitter/src/base.ts
Currently, using the API always returns name as undefined.
It should be retrieved from .core, like the username on the line below, but it is missing.
> fix: client-twitter homeTimeline name parse bug

- .gitignore
- Added `extra` folder to .gitignore to prevent conflicts during rebases
- This helps maintain a cleaner git history when working with local development folders
When rebasing against upstream, having local development folders like `extra` can cause unnecessary conflicts. This change makes the rebase process smoother by ignoring such folders.
- No impact on codebase functionality
- Improves developer experience during rebases
- Reduces merge conflicts with local development folders
> fix: adding exclusion for extra folder for faster future rebase

- .env.example
- packages/plugin-multiversx/src/actions/createToken.ts
- packages/plugin-multiversx/src/actions/swap.ts
- packages/plugin-multiversx/src/actions/transfer.ts
- packages/plugin-multiversx/src/utils/accessTokenManagement.ts
multiversx-plugin
- Add the possibility to limit token management to one user or all user
Improvements
- Add a user id in the .env under ACCESS_TOKEN_MANAGMENT_TO (line 522)
- Try creating, transfer or swap a token with the account linked to this id
- Try creating, transfer or swap a token with another account
> feat: Add Access Token Management to MultiversX Plugin

- packages/plugin-nvidia-nim/src/actions/actionGetTopic.ts
- packages/plugin-nvidia-nim/src/utils/validation.ts
- Fixed typo in environment variable names in `actionGetTopic.ts`:
- `NVIDIA_OFFTOPIC_SYSTEM`
- `NVIDIA_OFFTOPIC_USER`
- Modified: `packages/plugin-nvidia-nim/src/actions/actionGetTopic.ts`
- Corrected variable names to match environment configuration
- Ensures proper environment variable usage in off-topic detection
- Fixes potential environment variable mismatches
- Improves code consistency
- No functional changes, only typo correction
- Verified environment variables are correctly referenced
- Tested off-topic detection functionality
> fix: nvidia nim environment

- packages/plugin-zksync-era/src/actions/transferAction.ts
- packages/plugin-zksync-era/src/hooks/useGetAccount.ts
- Replace non-null assertion with fallback in useGetAccount
- Avoid parameter reassignment in transferAction handler
- Add explicit typing for hash variable
- Convert string concatenations to template literals
- Remove commented-out legacy code
PR was pretty old the new ones wil not present this issues.
> fix: plugin-zksync-era multiple errors and issues as documented

- packages/client-twitter/src/post.ts
- packages/client-twitter/src/types.ts
- packages/client-twitter/src/utils.ts
Adds support for media attachments in tweets and refactors tweet posting logic
- Introduces `MediaData` type for handling media attachments
- Extracts media handling logic into separate `fetchMediaData` utility function
- Renames variables for better clarity around tweet content handling
- Updates tweet posting methods to support media attachments
- Maintains existing approval workflow while adding media support
related: https://github.com/elizaOS/eliza/commit/0c13bfe6908f0d770f5c5eea7f720e9e9d3bc69b#commitcomment-151761396
> feat: twitter post media

- packages/plugin-udio/src/actions/extend.ts
- packages/plugin-udio/src/actions/generate.ts
- packages/plugin-udio/src/index.ts
- packages/plugin-udio/src/providers/udio.ts
- Fixed template literal usage in `extend.ts` where string interpolation wasn't needed
- Updated imports to use `import type` syntax in `udio.ts`
- Replaced `any` types with more specific `Record<string, unknown>` type
- Added proper return type for `get` method
- No functional changes
- Improved type safety and code quality
- Resolved Biome linting warnings
> fix: plugin-udio 

- packages/client-farcaster/src/interactions.ts
None
Keep running Farcaster client loop even if there's an error 
Bug fix
I had a memory get error and then the Farcaster client stopped checking for new messages
Use the Farcaster client 
Use the farcaster client, if an error happens, it'll still check your messages 
rubinovitz
> fix: still run Farcaster client loop if error

- packages/core/src/defaultCharacter.ts
Low
Change default character model provider back to the original default
openai was temporary to get someone's PR in
> fix: default character openai => llamalocal

- packages/plugin-movement/src/actions/transfer.ts
- packages/plugin-near/src/actions/transfer.ts
> fix: remove dead code

- packages/core/src/generation.ts
Issue: https://github.com/elizaOS/eliza/issues/3017
Low - This is a minor change to use a different object generation mode for Anthropic models only. The change is isolated and doesn't affect other providers.
Changes the default object generation mode from "json" to "auto" for Anthropic/Claude models since they don't support JSON mode. This fixes compatibility issues when using the Twitter plugin with Anthropic models.
1. Review the change in `packages/core/src/generation.ts`
2. Test Twitter plugin functionality with Anthropic/Claude models
1. Configure a character to use Anthropic/Claude as the model provider
2. Enable Twitter plugin
3. Trigger a tweet generation action …
> fix: change handleAnthropic default mode to auto

- packages/client-telegram/src/messageManager.ts
related: https://github.com/elizaOS/eliza/issues/2796
The issue is caused by the message ID being used to create a UUID for memory. Since the message ID could be the same in different Telegram channels, it leads to collisions in memory creation. In this PR, we use the channel ID to create the UUID instead.
> fix: Message id collision in Telegram Client

- packages/core/src/runtime.ts
The `imageVisionModelProvider` is used in the image description service, but its value is never applied at runtime. As a result, even if a user sets it in the character file, it has no effect. This PR ensures that the imageVisionModelProvider is correctly set at runtime.
> fix: ImageVisionModelProvider Not Applied in Runtime for Image Description Service

- biome.json
- packages/_examples/plugin-with-di/src/actions/sampleAction.ts
- packages/_examples/plugin-with-di/src/providers/sampleProvider.ts
- packages/_examples/plugin-with-di/src/services/sampleService.ts
- packages/_examples/plugin/src/services/sampleService.ts
- packages/plugin-di/src/actions/baseInjectableAction.ts
- packages/plugin-di/src/evaluators/baseInjectableEvaluator.ts
Incorrect biome lint in commit:
https://github.com/elizaOS/eliza/commit/4b9510d93e34436e6047dd0e3bbebeafb9326411
cc @wtfsayo 
Low
Because the parameter decorator configuration is not configured in the settings.
Doc: https://biomejs.dev/blog/biome-v1/#support-for-function-class-parameter-decorators 
so added this field in biome.json (and formatted the file)
```json
{
"javascript": {
"parser": {
"unsafeParameterDecoratorsEnabled": true
}
}
}
```
The decorator for the DI plugin was incorrectly changed.
At the same time, I noticed that the serviceType of sampleService needed to be revised in its writing, otherwise it would be undefined during actual runtime, so I fixed that as well.
Changes:
- fix erroneous corrections in di plugin caused by biome.
- add Parameter Decorators support in biome …
> fix: the unexpected corrections for plugin-di caused by biome lint

- packages/plugin-coingecko/src/actions/getMarkets.ts
- packages/plugin-coingecko/src/actions/getPrice.ts
https://github.com/elizaOS/eliza/issues/3049
Low: Coingecko might revoke demo access to these two api endpoints. Then, these two actions would break for users with only a demo api key. 
Add demo api access to coingecko plugin 
I would like to be able to use a demo key for these two actions in the coingecko plugin: GET_MARKETS and GET_PRICE.
The coingecko plugin defaults to using coingecko's pro api for these two actions, even though both endpoints are also available to demo users.
GET_TRENDING and GET_TOP_GAINERS_LOSERS already check for api configuration, and can use coingecko's demo endpoint.
> feat: 3049 add demo api access coingecko

- packages/plugin-multiversx/README.md
- packages/plugin-multiversx/src/actions/createLiquidityPool.ts
- packages/plugin-multiversx/src/constants.ts
- packages/plugin-multiversx/src/graphql/createLiquidityPoolQueries.ts
- packages/plugin-multiversx/src/models/inputToken.model.ts
- packages/plugin-multiversx/src/providers/wallet.ts
- packages/plugin-multiversx/src/utils/schemas.ts
MultiversX Plugin
It adds the CREATE_POOL feature witch trigger the following transactions on chain:
- wrapEgld (optionnal)
- createPair
- issueLpToken
- setLocalRoles
- addInitialLiquidity
- lockTokens
- setSwapEnabledByUser
I've add the necessary informations into the plugin README
> feat: Add CREATE_POOL action in MultiversX plugin

- packages/plugin-cronos/__tests__/actions/balance.test.ts
- packages/plugin-cronos/__tests__/actions/transfer.test.ts
- packages/plugin-cronos/__tests__/setup.ts
- packages/plugin-cronos/package.json
- packages/plugin-cronos/vitest.config.ts
https://github.com/elizaOS/eliza/issues/3249
low: tests
https://github.com/elizaOS/eliza/issues/3249
features/tests
None
> feat (chore): plugin-cronos test setup and coverage

- packages/plugin-solana-v2/package.json
fixes a JSON syntax issue in packages/plugin-solana-v2/package.json that caused the following error during pnpm i:
> fix: pnpm install

- packages/plugin-ton/tsup.config.ts
When running pnpm start, the following error occurred: (due to new change of this PR: https://github.com/elizaOS/eliza/pull/3211)
added @pinata/sdk to the external field in tsup.config.ts to ensure that the dependency is not bundled
> fix: Dynamic require of "http" is not supported error

- CONTRIBUTING.md
N/A (Fixing broken links in documentation)
Low – This only updates Markdown links and does not affect the application functionality.
This PR fixes two broken links in CONTRIBUTING.md
> Fix broken links on contributing.md

- packages/adapter-pglite/src/index.ts
- packages/adapter-postgres/src/index.ts
It fixes a minor bug in adapter-postgres adapter-pglite packages. There's a bug in SQL query in getCachedEmbeddings: `content->$2->>$3` part converts to `content->'content'->>'text'` and it searches in `{"content": {"text":""}}`  of **content** field of the table. But the text of the Memory is located in `{"text":""}` of **content** field.
No
> Fix PG query: Use only 'text' subfield name, field name is not needed here

- packages/client-twitter/src/interactions.ts
Low
When actions had the suppressInitialMessage flag, it would not work on other clients.
Added ability back so actions can properly suppress the initial response if enabled.
Implement changes, trigger an action and watch for suppression of initial message.
> fix: twitter - add actions suppress action ability.

- packages/plugin-quick-intel/src/actions/audit.ts
- packages/plugin-quick-intel/src/templates/index.ts
N/A
Low risk, just optimizations
add suppressInitialMessage flag on action
To suppress the initial response stating a scan is happening.
N/A
Run a scan and initial message will not be sent.
> fix: quick-intel plugin: optimize template/add suppress init msg

- agent/src/index.ts
- packages/core/src/generation.ts
- packages/core/src/runtime.ts
- packages/core/src/types.ts
This PR removes verifiable inference as a concept, use this as plugin providers, add runtime handler functionality if no dice
> feat: remove verifiable inference concept, will be plugin loaded

- package.json
This fixes `adapter-sqlite` not loading as the default adapter (occurs when no other plugins provide it).
https://github.com/elizaOS/eliza/blob/6f40883c7ae5bdb491a55753562785c40eaa7432/agent/src/index.ts#L678
Note `adapter-sqlite` is still present in `packages` for convenience. It can be externalized and installed from registry too, by changing the dep specifier to pull from npm/repo/whatever.
> Add adapter-sqlite to deps

- packages/agent/src/index.ts
To run an agent with a custom character you currently have to do (to escape a few layers of args parsing):
```
bun run agent -- -- --character=./characters/trump.character.json
```
However, this `yargs` parse slices off the argument:
```
ARGV: [
@elizaos/agent:start:       "/Users/a/.nvm/versions/node/v23.6.1/bin/node",
@elizaos/agent:start:       "/Users/a/eliza/packages/agent/src/index.ts",
@elizaos/agent:start:       "--character=./characters/trump.character.json"
@elizaos/agent:start:     ]
```
Note that yes, this command is still running the agent in `node`. That seems like a separate bug, or it could just be my env.
> Fix yargs slice in character loading

- packages/agent/src/index.ts
This allows the user to specify character paths relative to the repository root:
```
bun run agent -- -- --character=./characters/trump.character.json
```
We add `${cwd}../..` to the list of paths to try, to move up from `packages/agent` to the repo root.
> Try loading character path from repo root

- package.json
- packages/cli/index.js
- packages/cli/package.json
- pnpm-lock.yaml
Low, maybe it doesn't work for you
provides a little CLI utility for listing/adding plugins to an elizaos V1 repo:
`npx elizos`
get a list of available plugins
`npx elizos plugins list`
add a plugin
`npx elizos plugins add PLUGIN_NAME`
Help developers deal with the new plugin registry
> feat: v1 CLI utility

- .env.example
Update the  README to guide users to remember to add the "0x" prefix Infront their evm private keys. I experienced an "invalid private key" that was resolved by doing this. Thought this would save alot of people the hustle.
> docs: add note about 0x prefix needed for evm private key

- packages/core/src/runtime.ts
- packages/core/src/types.ts
When running multiple characters with the same plugin configuration, discovered a race condition where the `ensureEmbeddingDimension` method wasn't being properly executed before database operations. This caused inconsistent behavior across character instances.
1. Setup two characters with identical plugin configurations:
```json
"plugins": [
"@elizaos/plugin-openai",
"@elizaos/plugin-elevenlabs",
"@elizaos/plugin-discord",
"@elizaos/plugin-node",
"@elizaos/plugin-twitter"
]
```
2. Place character files in `packages/agent/characters/`
3. Run multiple characters:
```bash
cd packages/agent
bun run start -- --characters=nisa.character.json,lara.character.json
```
During investigation, I discovered a build dependency issue that required the following steps to get a clean state:
1. Remove all …
> fix: race condition

- docs/docs/contributing.md
The example uses a double hyphen (`--`) between the issue number and the description, which isn't standard practice.
I've updated it to use a single hyphen (`-`) to align with common Git conventions.  
This change ensures clarity and consistency for contributors when creating new branches.  
- Updated `9999--add-test-for-bug-123` to `9999-add-test-for-bug-123`.
> docs: fix branch naming example in CONTRIBUTING.md

- .npmrc
- agent/package.json
- client/src/lib/info.json
- packages/adapter-sqlite/package.json
- packages/client-direct/src/index.ts
- packages/core/package.json
- packages/plugin-bootstrap/package.json
- pnpm-lock.yaml
Might be related to: https://github.com/elizaOS/eliza/issues/3571
Low
- Use default [isolated](https://pnpm.io/npmrc#node-linker) pnpm node-linker setting.
- This allows to install the packages using symlinks and not only on the root `node_modules`.
- Bug fix with no breaking change
- When trying to install new packages from the [new registry](https://github.com/elizaos-plugins/registry) inside `agent/` folder, even tho it is shown in the `agent/package.json`, it will be installed in the root `node_modules`. This makes the agent unable to dynamically load the plugins since they are trying to be loaded from `agent/node_modules` and not root `node_modules`.
```
{
"name": "@elizaos/agent",
"version": "0.25.7",
"main": "src/index.ts",
"type": "module",
"scripts": {
"start": "node --loader …
```
> fix: installing packages from new registry

- agent/src/index.ts
None
Low
- Rollbacks some changed introduced on https://github.com/elizaOS/eliza/commit/3f66c9aa08829a794c4c52b064c4bc7b81c1049a#diff-6ccf35df0aad3b9693dad2ec6826b8742e506fa4197cf3e5fa2da7c74ca299c9
- Bug fix (non-breaking change). Fixes a bug where we can't re-initialize an agent through the client direct api on the `/agents/:agentId/set` route.
- To be able to continue using the client-direct api to restart agents.
None
- Install
- Build
- Run the agent
- Make a post request to `/agents/:agentId/set` make sure the restart works as expected.
- Same as own testing
@dtb0x
> fix: set agent from api

- .devcontainer/devcontainer.json
Fixed port mapping syntax
Old: "-p=3000:3000"
New: "-p 3000:3000"
Old: "-p=5173:5173"
New: "-p 5173:5173"
Reason: The correct syntax for port mapping in Docker is -p <host_port>:<container_port> (without =). Using = can lead to syntax errors or unexpected behavior.
> fix: Fix devcontainer.json Port Mapping Syntax and JSON Structure

- .env.example
**Relates to**
N/A
**Risks**
Low
**Background / What does this PR do?**
This PR updates the default RPC URLs for NEAR and Starknet to use Lava.
**What kind of change is this?**
Improvements (configuration changes)
**Documentation changes needed?**
**Discord username**
@rod_of_nim
**Email address**
[nimrod@magmadevs.com](mailto:nimrod@magmadevs.com)
<div align="center">
<h1>
<a href="https://lavanet.xyz">
Lava Network
</a>
</h1>
</div>
> configuration: Set Lava as the default RPC URL for NEAR and Starknet

- .env.example
- packages/core/src/generation.ts
- packages/core/src/models.ts
https://github.com/elizaOS/eliza/pull/3275
Low. This PR fixes a bug we encountered when testing with NEAR AI model provider. 
The PR https://github.com/elizaOS/eliza/pull/3275 has added NEAR AI as a model provider into Eliza, but it didn't include NEAR AI models into `generateObject` function for generating structured objects, which causes some actions fail to execute. 
In addition, we noticed that NEAR AI image models are not added and included in this PR.
Actions will throw `Unsupported model: nearai` since `handleNearAi` is not implemented. We met this issue when we're testing plugins with a demo agent: https://github.com/think-in-universe/near-eliza-starter/pull/1
- …
> fix: generate structured objects and images with NEAR AI

- packages/plugin-telegram/src/messageManager.ts
- packages/plugin-telegram/src/tests.ts
This PR fixes the E2E test for Telegram by adding the chat attribute to the mocked message.
Additionally, the Telegram agent isn't working in my group chat (chat.type = "group") due to an undefined issue at this [line](https://github.com/elizaOS/eliza/blob/5ff1eb8434a15a074d58e3c99290b6a1067d52e3/packages/plugin-telegram/src/messageManager.ts#L281), which is causing a database error. To resolve this, I set the default world name as a string.
here is the error message:
> fix: Telegram E2E Test and Group Chat Issue

- packages/core/src/knowledge.ts
No linked issue. This PR addresses a bug found in knowledge processing.
Low. Only affects how short text items are processed, with a small isolated change to prevent errors.
Fixes "Invalid array length" error when processing knowledge items by adding a length check before text chunking.
Problem:
- Knowledge processing fails with "Invalid array length" error for short text items
- Affects multiple character files (snoop.json, make.json, etc.)
- Error occurs in splitText() when trying to chunk small texts
Solution:
- Added length check before chunking in knowledge.set()
- Short texts (< chunkSize) are processed as single chunks
- Maintains existing chunking behavior for longer texts
My changes do not require a change to the project …
> fix: Handle short text items in knowledge processing

- packages/core/src/runtime.ts
- packages/core/src/types.ts
- packages/plugin-discord/src/messages.ts
1. Fix App Crash When Sending a PDF Message with No Text
Currently, sending a PDF message without any accompanying text causes the app to crash due to this line:
[packages/core/src/memory.ts#L100](https://github.com/elizaOS/eliza/blob/5f154c305fac51743cc32ee9fea798701c752bb8/packages/core/src/memory.ts#L100).
This PR ensures that messages containing only attachments (e.g., PDF files) default to an empty string instead of undefined, preventing the crash.
2. Fix getInstance Breaking All Services
Currently, all services are unusable due to a broken getInstance function. This PR fixes the issue.
Error message:
> fix: PDF Message Sending Failure & getInstance Bug

- packages/plugin-discord/src/actions/downloadMedia.ts
- packages/plugin-node/package.json
In the current branch, the video service fails due to a missing yt-dlp dependency in the youtube-dl-exec module. This happens because Bun does not install yt-dlp automatically unless you manually navigate to the youtube-dl-exec folder and run npm i.
To resolve this, this PR adds the trustedDependencies to plugin-node's package.json
This ensures that Bun installs youtube-dl-exec correctly, including its required dependencies.
Error Screenshot:
result:
> fix: media download action

- agent/src/index.ts
- packages/core/src/types.ts
n/a
Low
- Introduce `handlePostCharacterLoaded` method in agent startup process
- Add optional `postProcessors` and `handlePostCharacterLoaded` to Character and Plugin types
- Enable plugins to modify characters after initial loading
Sometimes we need to make some modifications to the dynamic data of Character.
Or, when there are multiple Characters, we need to perform unified post-processing on them through plugins. 
Currently, this can not be achieved. Therefore, a postProcesser mechanism for plugins and Character is introduced.
bt.wood
> feat: Add post-processing support for character loading

- .env.example
- packages/core/src/models.ts
Adds ANTHROPIC_API_URL to envs so can call other proxy AI endpoints.
odi edit/note:
Enables custom proxies for usage tracking/introspection
> feat: ANTHROPIC_API_URL env.

- .specstory/history/.what-is-this.md
- docs/docs/core/plugins.md
- packages/core/src/generation.ts
Plugin.md
No risks.
Added info on how to use custom plugins that are not in the official registry.
Improvement to plugins.md on how to use custom plugins in the new version.
I have a few custom plugins that I'm not allowed to share and wanted others to be updated on how to use custom plugins in new version as well.
Yes, plugins.md.
-->
> Update plugins.md for custom plugins not in registry

- docs/api/variables/stringArrayFooter.md
- packages/cli/index.js
- packages/client-direct/src/verifiable-log-api.ts
File: createVerifiableLogApiRouter.ts
Changed .pageQueryLogs(...) to ?.pageQueryLogs(...)
Prevents runtime errors in case pageQueryLogs is undefined or getService(...) returns null.
File: some_script.js (Logging Statements Fix)
Changed "only currently support github" to "currently only supports GitHub"
Fixed subject-verb agreement (singular "supports" for "this utility").
Moved "currently" for better readability.
File: packages/core/src/parsing.ts
Changed "formatted for markdown" to "formatted in markdown"
Corrected preposition usage for proper English grammar.
> fix: Grammar fix & createVerifiableLogApiRouter guard

- packages/core/src/knowledge.ts
https://github.com/elizaOS/eliza/pull/3652
https://github.com/elizaOS/eliza/pull/3653
Low
Revert's back to the original behavior since the change on https://github.com/elizaOS/eliza/pull/3652 where only needed if the splitText function misbehaves.
Because less code doing the same is better =)
packages/core/src/knowledge.ts - Check the deleted code.
Add a very short knowledge entry into a character (less than 15 characters and it should be enough) and then start the project with that character.
fcatena
> fix: Revert short knowledge items handling

- packages/agent/src/server/api/agent.ts
Currently, attempting certain operations (e.g., starting an agent, editing agent) results in the error: "Cannot read properties of undefined (reading 'databaseAdapter')". 
I noticed that we are trying to access the agent's runtime before it is actually created. If we are starting an agent, that means the runtime does not yet exist, so we shouldn't be attempting to access it beforehand.
Additionally, I removed some runtime checks that verified whether the runtime’s character name matched the agentId (maybe should check the character id instead?), when the runtime itself was not found. Instead of these repeated checks, maybe we should ensure that every runtime is properly registered, allowing us to reliably retrieve the agent with `agents.get(agentId)`.
> fix: api issues

- docs/community/Contributors/weekly-contributor-meeting/2025-02-18.md
- docs/community/Contributors/weekly-contributor-meeting/2025-02-25.md
Documentation updates for weekly contributor meetings
Low - This is a documentation-only change adding meeting notes.
Adds meeting notes for two weekly contributor meetings:
- February 18, 2025 covering plugin ecosystem discussions, Linea blockchain integration, and V2 plugin management
- February 25, 2025 covering ETH Denver updates and documentation improvements
Documentation (adding new meeting notes)
My changes are documentation changes themselves, no additional documentation updates needed.
Review the two new markdown files:
1. `docs/community/Contributors/weekly-contributor-meeting/2025-02-18.md`
2. `docs/community/Contributors/weekly-contributor-meeting/2025-02-25.md`
1. Verify markdown formatting is correct
2. Verify dates and titles are consistent with our documentation standards …
> docs: Add weekly contributor meeting notes (2025-02-18 + 2025-02-25)

- scripts/gettweets.mjs
This change fixes an issue where the `getTweets` method was not awaited, causing potential issues with handling the returned promise. The method is asynchronous, so I added `await` to properly wait for the promise to resolve.
- Bug fix
The method `scraper.getTweets` is asynchronous and returns a promise. Without using `await`, the code may continue execution before the promise is resolved, leading to unexpected results. This fix ensures the method completes before working with its response.
Tested by running the function and confirming that the correct list of tweets is returned after the promise is resolved.
> fix: Fixed issue with async handling in getTweets method

- README.md
- README_PTBR.md
Revamping README_PTBR.md for clearer and updated instructions Removed a redundancy on the README.md where it stated the supported models twice
> docs: Revamping README_PTBR.md for clearer and updated instructions (CONFLICTED)

- packages/core/tsup.config.ts
This enables index.d.ts to be built in /dist. I was seeing no types available errors on imports.
> Add core types.

- packages/the-org/vite.config.ts
> fix missing moment rollup external, the-org

- bun.lock
- packages/cli/src/server/index.ts
- packages/plugin-sql/drizzle.config.ts
- packages/plugin-sql/src/pg-lite/manager.ts
- packages/plugin-sql/src/pg/manager.ts
1. **Unified Migration Sources**
- Modified `drizzle.config.ts` to ensure that `npx drizzle-kit migrate` generates identical migrations as our code-based migrator
- This eliminates inconsistencies between static and runtime migration approaches
2. **Improved Migration Process**
- The CLI database initialization must now be awaited to ensure migrations run to completion
- All database client managers call `runMigrations()` which leverages Drizzle's built-in migration detection
3. **Smarter Migration Application**
- Instead of manually checking for applied migrations (which can confuse Drizzle), we now let Drizzle handle diff detection:
- If there's a difference between the database schema and migrations, Drizzle will apply them
- If migrations are already applied, Drizzle will skip them
- …
> fix: migration race condition

- packages/the-org/src/index.ts
- packages/the-org/src/init.ts
Added an environment control of the character file so the user can just comment out the .env and not touch the code to activate the agents. The code already control both Discord and Telegram but the main is still Discord.
> Fix: the org environment

- packages/core/src/logger.ts
- Synchronously load `pino-pretty` to prevent mixed JSON and formatted logs
- Refactored `createStream()` to remove async initialization issues
This ensures that logs always appear in a human-readable format without JSON noise.
> fix: logger not properly formatting.

- bun.lock
- package.json
- packages/the-org/src/index.ts
Upgrade pckg manager - bun. 
Test: 
1. `bun update`
2. `bun upgrade`
4. `bun i` 
5. `bun run build`
6. `bun run start` 
Upgrade bun for the monorepo.
Also changed the `preinstall` script to match this:
> feat: upgrade pckg manager

- scripts/gettweets.mjs
I noticed that the call to `scraper.getTweets("pmarca", 2000)` wasn’t using `await`, so the `tweets` variable was getting the promise instead of the actual tweet data. This caused an issue when trying to access the tweets.
I’ve added the missing `await`, so now everything should work as expected and load the tweet data correctly.
> chore: fix missing `await` for tweet scraping

- packages/cli/src/commands/create.ts
Fixes how Postgres connection URLs are handled during project creation:
- Adds proper validation for Postgres URL format with helpful error messages
- Stores URL in `~/.eliza/.env` for persistence
- Extracts Postgres URL handling to dedicated functions for better code organization
- Simplifies UI prompts for improved user experience
> fix: store postgres connection URL properly in global config

- scripts/smokeTests.sh
Noticed a mistake in the timeout comment—1200 tenths of a second is 120 seconds, not 60.
Fixed it to avoid confusion.
> chore: Fix incorrect timeout comment

- packages/client/src/components/chat.tsx
- packages/client/src/lib/api.ts
- packages/client/src/lib/socketio-manager.ts
- packages/client/src/lib/utils.ts
- packages/client/src/lib/world-manager.ts
- don't need localhost hardcoded
- fixes firefox since crypto.randomUUID is only available in https context and most users will be using http
> fix: Make client use relative URL & firefox fixes

- docs/api/classes/MemoryCacheAdapter.md
Fixed a typo in the parameter name from initalData → initialData for correct spelling.
> Fixed a typo

- packages/cli/src/commands/create.ts
- packages/cli/src/commands/start.ts
- packages/cli/src/utils/cli-prompts.ts
- packages/cli/src/utils/get-config.ts
This update refactors and improves the database configuration logic in the Eliza CLI commands. The changes enhance both the user experience and code maintainability.
- **Centralized database utilities**: Created shared database configuration functions in `get-config.ts`
- **Improved directory management**: PGLite database directory is now only created when the user selects PGLite
- **Consistent environment variable handling**: Environment variables are now properly handled in both file and memory
- **Reduced code duplication**: Eliminated duplicate functions in `start.ts` and `create.ts`
- **Simpler setup flow**: Clearer prompts and more intuitive database selection process
- **Minimized file system operations**: Only creates directories and files when necessary
- **Persistent …
> Enhance start cli cmd

- packages/cli/src/commands/create.ts
- packages/cli/src/commands/start.ts
- packages/cli/src/server/index.ts
- packages/cli/src/utils/env-prompt.ts
This PR includes several improvements to the CLI experience and fixes various bugs related to command execution and project setup.
* Standardized npx commands across the project, making them more consistent and easier to use
* Unified post-creation directions between projects and plugins for better consistency
* Simplified cd paths in setup instructions
* Fixed custom port display in dashboard URL (previously always showed port 3000)
* Fixed -t flag to properly pass project/plugin name
* Fixed -d flag functionality
* Added support for cloud URL pattern for PostgreSQL to prevent unnecessary warnings
* Fixed --configure flag and added missing imports
* Added support for cloud-hosted PostgreSQL URL patterns
* Enhanced error handling and configuration validation
* Standardized command output …
> Eli2 107/validate and test cli commands functionality

- packages/client/src/components/app-sidebar.tsx
- packages/client/src/routes/home.tsx
this pr also remove the thumbnail for group
https://github.com/user-attachments/assets/ef3d66a4-325b-467f-a1f7-b7f4a9b531ea
> feat: update agents status in group

- packages/plugin-openai/src/index.ts
Currently, OpenAI transcription is not working with the GUI and Discord. I'm not sure, but maybe something changed on OpenAI's end since I didn't see any related changes in our codebase. I changed it to use a file instead of a blob, and it now works with both the GUI and Discord as I tested.
> fix: openai stt

- packages/plugin-discord/package.json
related: https://github.com/elizaOS/eliza/issues/3955
Hi @jmikedupont2, could you provide the reproduction steps for the issue? I've noticed this error message when I try to use voice in Discord, so I’ve added the missing dependencies to the Discord package.json. Could you kindly test it on your end to see if it resolves the issue?
> fix: opus issue

- packages/cli/src/utils/github.ts
This PR fixes an issue where the CLI fails to create files in non-existent directories when using the GitHub API, specifically when test publishing a plugin. 
When running `npx elizaos plugin publish --test` on a fresh fork, the CLI tries to use the POST method to create files in non-existent directories, which fails with 404 errors. However, using PUT works successfully for the same operation.
Modified the `updateFile` function to always use the PUT method instead of conditionally using POST/PUT based on file existence. The GitHub API handles PUT requests more reliably when creating files in directories that don't exist yet.
Tested by:
1. Deleting my fork of the registry
2. Running `npx elizaos plugin publish --test` with the original code (fails)
3. Running with the modified code that …
> fix: Use PUT method for GitHub file operations to handle non-existent directories

- packages/core/src/prompts.ts
- packages/plugin-discord/src/service.ts
- packages/the-org/src/communityManager/index.ts
- packages/the-org/src/communityManager/plugins/communityManager/actions/discord-timeout.ts
- packages/the-org/src/communityManager/plugins/communityManager/communityService.ts
- packages/the-org/src/communityManager/plugins/communityManager/index.ts
- packages/the-org/src/communityManager/plugins/communityManager/types.ts
- packages/the-org/src/index.ts
sub pr: https://github.com/elizaOS/eliza/pull/4063
**Summary**
This PR enables Discord community manager to automatically greet users when a new user joins. It also adds a new action that allows agents to timeout users
**TODO**
In a future PR, we could allow agents to use a custom greeting prompt from metadata, so agent can have different greeting message.
We should adapt this behavior to support other platforms, like Telegram.
**Notes**
I updated recentMessages to include the full entity ID so we can retrieve the target Discord username for the timeout action. Let me know if this is acceptable or if we should trim it down.
result:
> feat: [discord] community manager greet + timeout user

- packages/core/src/actions/settings.ts
- packages/core/src/providers/settings.ts
related: https://linear.app/eliza-labs/issue/ELI2-150/hallucinations-in-actions-and-response-of-agents
Currently, I haven’t been able to get the onboarding settings to work due to a few issues:
1. The agent keeps selecting UPDATE_SETTINGS even when I haven’t said anything. It immediately replies with:
"I couldn't understand your settings update. Please try again with a clearer format."
**It also seems unaware of the current settings and ends up hallucinating them.**
2. After fixing the above issue, I still couldn’t apply settings because the result gets cleaned to an empty object if it’s not an array:
https://github.com/elizaOS/eliza/blob/e20bd81fec5c8fd7a7987930faa18f79ab22e775/packages/core/src/actions/settings.ts#L391
I also noticed that the LLM sometimes returns a different structure …
> fix: settings action

- docs/scripts/get-changelog.py
Noticed a missing comma in the `section_headers` list, which caused the last regex pattern to be concatenated incorrectly. This could lead to `New Contributors` headers not being processed as expected.  
Fixed by adding the missing comma to ensure proper separation of regex patterns.
> chore: Fix missing comma in section headers list

- scripts/bug_hunt/main.py
I noticed that the `json` module is imported twice in the code.
I removed the second import to clean up the code and improve readability.
> chore: removed duplicate JSON import

- .env.example
- agent/src/index.ts
- packages/core/package.json
- packages/core/src/generation.ts
- packages/core/src/models.ts
- packages/core/src/types.ts
N/A
Medium
Here's a more polished version of your PR description:  
---
This PR adds [Mem0](https://mem0.ai/) as a provider in the Vercel AI SDK. The Mem0 AI SDK Provider functions like any other provider in the AI SDK but introduces a separate memory layer for users. 
Mem0 is a self-improving memory layer for LLM applications.
1. **Memory Saving** – Stores relevant information based on user queries.  
2. **Personalized Search** – Retrieves stored memories to generate context-aware response
3. ** Retain Memory Across Agents and Conversations ** -  Mem0 also enables users to retain memory across different agents and conversations.
Integrating Mem0 into Eliza provides developers with a powerful memory layer for their AI applications, …
> feat: Add Mem0 as AI SDK Provider

- packages/plugin-sql/src/base.ts
Database connections getting stuck in "idle in transaction" state, causing unresponsiveness.
The `getWorld` method inside `createWorld` wasn't supposed to be merged. This combination caused transactions to hang without completion.
Removed the problematic code:
```diff
async createWorld(world: World): Promise<UUID> {
return this.withDatabase(async () => {
const newWorldId = world.id || v4();
-   // This check was causing the problem - created a transaction but didn't complete it
-   const existingWorld = await this.getWorld(newWorldId);
-   if (existingWorld) {
-     return existingWorld.id;
-   }
await this.db.insert(worldTable).values({
...world,
id: newWorldId,
});
return newWorldId;
});
}
```
Run PGlite and verify it's working without "idle in transaction" errors in logs.
> fix: resolve database transaction deadlock

- packages/plugin-starter/.gitignore
node_modules wasnt in the gitignore in plugin-starter template, resulting in trouble pushing the plugin repo to github. added it so it works well.
> add node_modules to .gitignore

- packages/plugin-twitter/src/base.ts
- packages/plugin-twitter/src/interactions.ts
related: https://github.com/elizaOS/eliza/issues/4181
This PR eliminates the duplicate fetchSearchTweets call previously used to retrieve Twitter interactions (likes, retweets, quotes). Instead, it reuses the already-fetched mentionCandidates from the original mention query and converts them into interaction payloads where applicable.
The MENTION_RECEIVED and REACTION_RECEIVED event emissions are currently commented out and marked with TODOs, as they require additional handling to be fully supported. These will be addressed in a follow-up PR.
> fix: twitter interaction

- packages/plugin-bootstrap/package.json
Low – This change only removes a `postscript` entry from the `plugin-bootstrap` package. Since the script it was referring to no longer exists, removing the reference reduces the chance of errors during post-installation. It does not affect runtime behavior.
This PR removes the `postscript` section from the `plugin-bootstrap` package's configuration. The script that was being called in this section does not exist anymore, making the entry redundant and potentially error-prone.
Start by reviewing the `plugin-bootstrap` package's configuration (likely `package.json` or similar) and confirm that the removed script reference was indeed pointing to a non-existent script.
- Run …
> fixed: bun installation issue for plugin-bootstrap

- packages/core/src/prompts.ts
- packages/plugin-bootstrap/src/actions/reply.ts
- packages/plugin-bootstrap/src/index.ts
1. Modified `reply.ts` to use pre-generated responses from the planning stage
- Now finds all responses with REPLY action and message
- Uses existing responses instead of generating new ones when available
- Only calls LLM if no suitable responses are found
2. Improved `replyTemplate` to be more focused
- Removed action selection since this is specifically for REPLY
> feat: Improve Reply Action to Use Pre-generated Responses

- packages/plugin-openai/src/index.ts
- packages/plugin-twitter/src/interactions.ts
This PR addresses an issue where transcription was no longer working in both the Discord and GUI. The issue appears to have been introduced in [#4169](https://github.com/elizaOS/eliza/pull/4169), which switched to using NodeFormData. Unfortunately, that change seems to have broken the transcription feature, as the API returned a 400 Bad Request.
To resolve this, I’ve reverted to using the form-data package along with node-fetch. I’ve tested this update, and transcription now works as expected in both Discord and the GUI.
> fix: transcription

- bun.lock
- packages/plugin-anthropic/package.json
- packages/plugin-anthropic/src/index.ts
- packages/plugin-anthropic/src/utils.ts
Low - This PR addresses an edge case in the JSON parsing logic for Anthropic responses containing code blocks. The changes improve the robustness of the existing error handling without changing the API.
This PR fixes an issue in the Anthropic plugin where responses containing code blocks with language identifiers (like `bash`) are causing JSON parsing errors. The specific issue occurs when the model returns valid JSON containing markdown code blocks in string values, but the parser fails to handle the content correctly.
Bug fix (non-breaking change which fixes an issue)
No documentation changes are required as this fixes an internal parsing mechanism.
The reviewer should start by examining the `extractAndParseJSON` function in `packages/plugin-anthropic/src/index.ts` to understand how the …
> Fix anthropic json parse issue

- packages/cli/src/utils/install-plugin.ts
- packages/cli/src/utils/package-manager.ts
- packages/cli/src/utils/registry/index.ts
**Issue:**
Users were unexpectedly prompted for GitHub authentication during normal CLI operations like elizaos start, while the same command run through npx elizaos start did not require authentication. This inconsistency created a confusing user experience and unnecessary friction.
**Root Cause:**
The CLI was using GitHub-authenticated API calls for routine operations like looking up plugin metadata and registry indexes, even when these operations could be performed without authentication. Specifically:
The plugin installation process (installPlugin) was using getPluginMetadata() which required GitHub authentication
The registry lookup functions were defaulting to authenticated GitHub API endpoints. When installing plugins, the CLI was *sometimes* preferring authentication-required …
> Fix GitHub Authentication Prompt During Start CLI Command

- packages/core/src/types.ts
- packages/plugin-telegram/README.md
- packages/plugin-telegram/src/messageManager.ts
- packages/plugin-telegram/src/types.ts
- packages/plugin-telegram/src/utils.ts
Low - The changes are focused on adding button support to the Telegram plugin, which is a non-breaking change. The main risk would be if the button conversion logic has any edge cases not covered by testing.
This PR adds support for interactive buttons in Telegram messages through the Eliza framework. It introduces a new Button type in the core package and implements the conversion of these buttons to Telegram's inline keyboard format.
If documentation change is needed: I have updated the documentation accordingly.
The reviewer should start by examining the new Button type in packages/core/src/types.ts and then look at how it's implemented in the Telegram plugin.
- Test …
> feat: Add message buttons

- packages/plugin-bootstrap/src/evaluators/reflection.ts
In group settings, agents were frequently asking each other "how are you doing?" during conversations. This was caused by a hardcoded reflection prompt in `reflectionEvaluator`:
> Generate a self-reflective thought on the conversation. How are you doing? You're not being annoying, are you?
The prompt encouraged agents to check in with others, leading to repetitive and unnatural group interactions.
- Rewrote the reflection prompt in `packages/plugin-bootstrap/src/evaluators/reflection.ts` to use neutral language that no longer encourages agents to ask others how they’re doing
- This stops the specific loop of agents checking in with each other, while preserving the overall reflection capability
- While this change removes the direct "how are you doing?" loop, agents in group settings can …
> ELI2-185/reflections-agent-asks-all-other-agents-deployed-how-its-doing

- packages/client/package.json
- packages/client/src/components/agent-creator.tsx
- packages/client/src/components/plugins-panel.tsx
https://linear.app/eliza-labs/issue/ELI2-242/default-sql-and-openai-plugins-for-new-characters-and-warn-on-removal
Low - This PR only affects the UI for new agent creation and plugin management. The changes are isolated to frontend components and don't impact core functionality or existing agents.
1. Adds essential plugins (@elizaos/plugin-sql and @elizaos/plugin-openai) by default when creating new agents
2. Implements warning confirmations when users attempt to remove essential plugins
3. Provides visual indicators to distinguish essential plugins in the UI
4. Preserves user choice after confirmation (plugins stay removed if confirmed)
1. Create a new agent via the UI …
> Improvement: Default SQL and OpenAI Plugins for New Character

- packages/plugin-telegram/src/messageManager.ts
low – this change adds a typing indicator (sendChatAction) to simulate a more humanlike interaction pattern.
adds a typing indicator to telegram bots to improve user experience and give feedback that the bot is “typing” while processing the response. this is done via telegram’s sendChatAction endpoint with the typing action. the goal is to make the interaction feel less abrupt and more natural, especially when responses have slight delays due to processing or API latency.
None
run an agent and message it on telegram. you should expect to see "typing..." underneath the bots username before it sends its response.
Currently, when the agent is processing a user message, this just shows a static status until the message comes through. …
> feat: add typing indicator to telegram

- packages/core/src/runtime.ts
Make sure `init` exist on plugin before we call it. 
error: 
```
[2025-04-13 14:10:02] WARN: Failed to load or prepare plugin specified by name: @elizaos/plugin-bootstrap
[2025-04-13 14:10:02] ERROR: An error occurred:
message: "(TypeError) Cannot read properties of undefined (reading 'init')"
stack: [
"TypeError: Cannot read properties of undefined (reading 'init')",
"at AgentRuntime.initialize (file:///Users/root1/.npm/_npx/594f2c2739bbbf45/node_modules/@elizaos/cli/dist/chunk-GFPVHNVN.js:46086:24)",
"at startAgent (file:///Users/root1/.npm/_npx/594f2c2739bbbf45/node_modules/@elizaos/cli/dist/chunk-U6NYC23Y.js:83211:17)",
"at process.processTicksAndRejections (node/process/task_queues:105:5)",
"at async startAgents (file:///Users/root1/.npm/_npx/594f2c2739bbbf45/node_modules/@elizaos/cli …
```
> fix: check if init exist before calling

- packages/cli/src/commands/start.ts
```
[2025-04-15 20:57:12] ERROR: An error occurred:
message: "(TypeError) Cannot read properties of undefined (reading 'some')"
stack: [
"TypeError: Cannot read properties of undefined (reading 'some')",
"at startAgents (file:///root/twitter/packages/cli/dist/chunk-V43JKZMH.js:83348:47)",
"at async _Command.<anonymous> (file:///root/twitter/packages/cli/dist/chunk-V43JKZMH.js:83482:5)",
"at async _Command.parseAsync (file:///root/twitter/packages/cli/dist/chunk-5LH7NKB4.js:1721:9)",
"at async main (file:///root/twitter/packages/cli/dist/index.js:117:3)"
```
> fix: ensure plugins

- packages/plugin-telegram/src/index.ts
low – this change only affects the type exports from the package. it makes more internal types publicly available for consumers but does not alter runtime behavior.
Exposed `messageManager` and `telegramService` from telegram package so users can import and use as needed in their agents, especially as types. 
One use case for this would be exposing a function you can call at the top level of the agent that allows you to send a message through telegram on command. This way you can send notifications through the agent.
There should be no changes that require testing. Automated tests are acceptable.
nickb0181
> fix: expose telegram types

- packages/plugin-bootstrap/src/actions/index.ts
- packages/plugin-bootstrap/src/actions/roles.ts
- packages/plugin-bootstrap/src/actions/settings.ts
- packages/plugin-bootstrap/src/evaluators/index.ts
- packages/plugin-bootstrap/src/index.ts
- packages/plugin-bootstrap/src/providers/index.ts
Exporting all providers, actions, and evaluators from the bootstrap plugin for a more controlled consumer experience.
No breaking changes for regular package consumers. For consistency, `updateRoleAction ` and `updateSettingsAction ` have been changed to named exports as the other actions.
@michavie
> chore: Export bootstrap plugin capabilities

- packages/client/src/components/onboarding-tour.tsx
related: https://github.com/elizaOS/eliza/issues/4316
Mark onboarding as complete when the tour is closed manually to prevent lingering blue beacon.
> fix: persistent beacon by handling tour close action

- packages/client/src/components/room.tsx
related: https://github.com/elizaOS/eliza/issues/4315
Fallback to a custom UUID generator for browsers that don't support crypto.randomUUID().
> fix: Use utils-based UUID for broader browser support

- packages/plugin-twitter/src/client/client.ts
- packages/plugin-twitter/src/client/tweets.test.ts
- packages/plugin-twitter/src/client/tweets.ts
- Request to add same changes as in https://github.com/elizaOS/agent-twitter-client from @tcm390 
- Low: No error if you try to accidentally delete a tweet which is not yours, simply nothing happens
- Add deleteTweet() function to tweets.ts
- Add deleteTweet() wrapping method for Client class
- Add test for deleteTweet() to tweet.tests.ts
Feature
@paoloanzn 
btw i'm in the development server but I can't join the other server as if I'm banned :(
> feat: Add deleteTweet()

- packages/client/src/components/secret-panel.tsx
Previously, envs was initialized only once from characterValue and did not update when characterValue changed. This caused the panel to display stale data unless manually rerendered.
> fix: gui - sync envs state with updated characterValue props

- packages/plugin-bootstrap/src/providers/recentMessages.ts
These PR fix the issue where agents were repeatedly sending the same canned response during ongoing conversations in group chat
> fix: Prevent repetitive agent replies

- packages/core/src/runtime.ts
- packages/plugin-sql/src/base.ts
This PR fixes an issue where starting an agent created via the GUI using the same agent name would result in an error: Agent does not exist in database after ensureAgentExists call.
The issue occurred because multiple agents with the same name but different IDs existed in the database. The ensureAgentExists call would return an agent (based on name), but subsequent logic that expected a specific agentId would fail to find it, causing the error.
This PR ensures the correct agentId is used, resolving the mismatch.
Additionally, this PR resolves merge conflicts between the following PRs:
https://github.com/elizaOS/eliza/pull/4223
https://github.com/elizaOS/eliza/pull/4261
> fix: agent not found error after GUI creation and resolve merge conflict

- packages/cli/src/utils/copy-template.ts
added this small change because .gitignore wasnt getting copied over on plugin-starter copying via the cli.
> added bc .gitignore wasnt getting copied from plugin-starter

- packages/cli/src/server/api/agent.ts
- packages/cli/src/utils/audioBuffer.ts
This PR addresses an issue where plugin-openai TTS wasn't working because it returns a Web ReadableStream. The fix properly handles all types of stream responses for TTS APIs
> fix: tts api

- packages/client/src/components/character-form.tsx
- packages/client/src/components/plugins-panel.tsx
This PR fixes several issues:
**1. Removed poor contrast background color for the voice required plugin label**
**2. Removed the white/blue background color from the "Voice Required" header and replaced it with a neutral color based on feedback from @wtfsayo.**
**3. Disabled the logic that automatically removes plugins based on voice model selection. For example, when switching to the ElevenLabs voice model, it would remove the OpenAI plugin even if it was still needed.**
**4. The warning message doesn't make sense when using the ElevenLabs voice model — it tells me to remove the OpenAI plugin even though it’s unrelated. So I’ve commented it out for now.**
> fix: small GUI fix

- packages/cli/src/server/index.ts
Update agent service management during unregistration
Low. This change improves resource management when unregistering agents by ensuring all services are properly stopped.
This PR enhances the `unregisterAgent` method by adding automatic shutdown of agent services before removing it from the active agents Map. This ensures that all resources are properly released when an agent is unregistered, preventing potential resource leaks or orphaned services that would continue running in the background.
Examine the changes made to the `unregisterAgent` method in the `eliza/packages/cli/src/server/index.ts` file.
1. Create an agent with active services (e.g., with a Telegram or …
> fix: agent unregistration process with service stop handling

- packages/cli/src/commands/create.ts
Updates the missing default for type in `elizaos create`
None.
Minor text update in CLI.
This should be included so the user knows what is the default value.
No.
> fix: add default project text to create cli

- docs/community/Discord/the_arena/price-talk-trenches/chat_2024-11-29.md
This pull request updates a broken Pump.fun link 
The old link was missing the /coin/ path, leading to a 404 error. The new link correctly directs to the intended resource.
> Fix: Correct broken Pump.fun link

- docs/README_CN.md
- docs/README_DE.md
- docs/README_FR.md
Replaced incorrect image paths that caused 404 errors in README_CN.md, README_DE.md, and README_FR.md.
Old path: ./docs/static/img/eliza_banner.jpg
New path: static/img/eliza_banner.jpg
This fixes broken banner images that were not displaying correctly in the translated documentation files.
> Fix broken image paths

- docs/README_JA.md
Old path: ./docs/static/img/eliza_banner.jpg
New path: static/img/eliza_banner.jpg
This fixes broken banner images that were not displaying correctly in the translated documentation files.
> Fix broken image paths 

- packages/core/src/settings.ts
Type error during decryption in MCP plugins
**Low**. This change adds an additional type check to prevent errors when executing cryptographic functions.
This PR fixes a `TypeError: value.split is not a function` that occurs on some calls by adding explicit type checking in the encryption and decryption functions.
Review the changes in `eliza/packages/core/src/settings.ts` where type checks have been added to the `encryptStringValue` and `decryptStringValue` functions.
- Verify in the logs that no "value.split is not a function" error appears
- Verify that the tool execution completes successfully
> fix(core): type check crypto values

- packages/plugin-sql/src/base.ts
Currently, we cannot delete an agent if they own worlds, because it causes a foreign key constraint error on the logs table (logs_roomId_rooms_id_fk).
This PR fixes the issue by first checking for an existing agent to reassign the worlds to.
- If another agent exists, the worlds are reassigned to that agent before deletion.
- If no other agent exists, the worlds are deleted before deleting the agent.
This ensures we can safely delete the agent without violating database constraints.
Error previously encountered:
```
[2025-04-29 09:40:06] DEBUG: [DB] Found 2 worlds to delete
[2025-04-29 09:40:06] ERROR: [DB] Error in transaction:
message: "(error) update or delete on table \"rooms\" violates foreign key constraint \"logs_roomId_rooms_id_fk\" on table \"logs\""
stack: [
"error: update or …
```
> fix: agent deletion

- packages/plugin-local-ai/src/index.ts
fixes local ai throwing
```
[2025-04-29 15:06:40] DEBUG: API request: GET /ping
[2025-04-29 15:06:40] DEBUG: API request: GET /agents/b850bc30-45f8-0041-a00a-83df46d8555d/logs
[2025-04-29 15:06:40] DEBUG: Skipping plugin handler for specific route: /agents/b850bc30-45f8-0041-a00a-83df46d8555d/logs
[2025-04-29 15:06:41] DEBUG: API request: GET /agents/b850bc30-45f8-0041-a00a-83df46d8555d/memories
[2025-04-29 15:06:41] DEBUG: Skipping plugin handler for specific route: /agents/b850bc30-45f8-0041-a00a-83df46d8555d/memories
2820 |       let response = await this.chatSession.prompt(params.prompt, {
2821 |         maxTokens: 8192,
2822 |         temperature: 0.7,
2823 |         topP: 0.9,
2824 |         repeatPenalty: {
2825 |           punishTokensFilter: () => …
```
> chore: fix local llm throwing undefined error

- packages/cli/src/commands/start.ts
This PR removes the forced adding of the bootstrap plugin to projects through the CLI. Projects *can* use the bootstrap plugin, but it isn't forced on them. Makes simple agents much easier.
> fix: remove forced bootstrap plugin add

- packages/docs/src/components/HomepageHeader/index.jsx
`eliza is apowerful AI agent framework for autonomy & personality` ---> `eliza is a powerful AI agent framework for autonomy & personality`
> docs: fix title spacing

- packages/client/src/App.tsx
- packages/client/src/components/action-viewer.tsx
- packages/client/src/components/agent-sidebar.tsx
- packages/client/src/components/connection-error-banner.tsx
- packages/client/src/components/ui/sidebar.tsx
- packages/client/src/components/ui/tabs.tsx
Scrollbars were doubled up in task list, also if hover side bar would get scroll weirdly, the main page also had a global scroll bloat.
Now it is much cleaner and fullscreen no scrolls.
> fix client scroll bars

- packages/core/src/parsing.ts
[Issue 3779](https://github.com/elizaOS/eliza/issues/3779)
Low.  The change modifies a regular expression used for JSON normalization.  The primary risk is that the updated regex could inadvertently fail to normalize certain valid JSON strings, or incorrectly normalize previously correct strings. The automated tests and new test cases should mitigate this risk.
This PR fixes a bug in the `normalizeJsonString` function that caused extra quotation marks to be added to nested JSON objects during normalization. Specifically, the existing regex pattern was incorrectly attempting to wrap the entire nested object in double quotes, resulting in invalid JSON.
Bug fix
<!--
I encountered this bug when trying to parse nested objects from an LLM response. The parsing was failing and using the …
> fix: fix json parse problem with nested objects

- packages/cli/src/utils/config-manager.ts
```bash
Version: 1.0.0-beta.48
[2025-05-07 22:26:45] WARN: Error loading configuration: TypeError: fs4.exists is not a function
[2025-05-07 22:26:45] INFO: First time setup. Let's configure your Eliza agent.
[2025-05-07 22:26:45] ERROR: Error saving configuration: TypeError: fs4.exists is not a function
```
Get these errors everytime run CLI... it's because `fs.exists()` is deprecated now and when compile to high version of node, it's getting dropped. 
https://nodejs.org/api/fs.html#fsexistspath-callback
This PR changes out for new version: `fs.access()`
> chore: fix type errors in CLI, fs.exists is deprecated

- packages/plugin-sql/src/schema/log.ts
[Linear](https://linear.app/eliza-labs/issue/ELIZA-271/if-agent-has-been-in-a-room-it-cant-be-deleted)
**Problem:**
Attempting to delete an agent resulted in a database error: `update or delete on table "rooms" violates foreign key constraint "logs_roomId_rooms_id_fk" on table "logs"`. This occurred because `rooms` associated with the agent were being deleted, but the `logs` table had a foreign key constraint (`logs_roomId_rooms_id_fk`) on `rooms.id` with `ON DELETE NO ACTION`. This prevented the deletion of `rooms` if any `logs` referenced them.
**Solution:**
**Schema Update:** Modified the Drizzle schema definition in [packages/plugin-sql/src/schema/log.ts](cci:7://file:///Users/studio/Documents/GitHub/eliza/packages/plugin-sql/src/schema/log.ts:0:0-0:0). The `roomId` column in …
> fix: delete agents that have been in room

- bun.lock
- packages/core/src/types.ts
- packages/plugin-bootstrap/src/actions/choice.ts
- packages/plugin-bootstrap/src/actions/followRoom.ts
- packages/plugin-bootstrap/src/actions/muteRoom.ts
- packages/plugin-bootstrap/src/actions/roles.ts
- packages/plugin-bootstrap/src/actions/sendMessage.ts
- packages/plugin-bootstrap/src/actions/settings.ts
- packages/plugin-bootstrap/src/actions/unfollowRoom.ts
- packages/plugin-bootstrap/src/actions/unmuteRoom.ts
- packages/plugin-bootstrap/src/actions/updateEntity.ts
- packages/plugin-bootstrap/src/evaluators/reflection.ts
- packages/plugin-bootstrap/src/index.ts
- packages/plugin-bootstrap/src/providers/anxiety.ts
- packages/plugin-bootstrap/src/providers/character.ts
- packages/plugin-bootstrap/src/providers/choice.ts
- packages/plugin-bootstrap/src/providers/evaluators.ts
- packages/plugin-bootstrap/src/providers/roles.ts
- packages/plugin-bootstrap/src/providers/settings.ts
- packages/plugin-bootstrap/src/providers/world.ts
- packages/plugin-bootstrap/src/services/scenario.ts
- packages/plugin-bootstrap/src/services/task.ts
- packages/plugin-bootstrap/tsconfig.json
- packages/plugin-bootstrap/tsup.config.ts
We cannot write stable code in Typescript, if do not generate types, and respect strict mode.
This PR fixes all red errors in plugin-bootstrap and generates a index.d.ts.
I don't see any sensible way to develop without moving to strict types in this project.
`If your code doesn't compile, fix it properly, do not just turn off types!` 
I believe my code does no logic changes, introduces some error throws for param checking, and found some events that do not make sense at all in types, I cast to any for now.
Works, builds, tested bun run start, seems no logical changes.
> chore: strict types, generate DTS, plugin-bootstrap

- docs/docs/changelog.md
Found a broken link to v0.25.6-alpha.1 release in docs/docs/changelog.md.
Replaced the markdown link with plain text to avoid 404.
Feel free to suggest a working link if available — happy to update!
> remove broken release link in changelog

- bun.lock
- packages/cli/src/commands/test.ts
- packages/cli/tsup.config.ts
- packages/core/src/database.ts
- packages/core/src/runtime.ts
- packages/core/src/types.ts
- packages/plugin-sql/src/base.ts
- packages/plugin-sql/src/pg/adapter.ts
- packages/plugin-sql/src/pglite/adapter.ts
- packages/plugin-sql/tsconfig.build.json
- packages/plugin-sql/tsup.config.ts
This PR:
- Turns on `dts: true` in both CLI and plugin-sql packages.
- This exposed missing: `connection` which was being used in tests but didn't actually exist.
- Implemented `getConnection()` for realsies in DB adapters to satisfy usage.
- Also found `deleteRoomsByServerId` and `removeWorld` not implemented in AgentRuntime. Added them.
> Enforce Typescript on /cli and  /plugin-sql, fix missing DB functions.

- packages/core/src/runtime.ts
This removes annoying instrumentation logs in startup.
`@elizaos/the-org:dev: [2025-05-11 19:24:33] WARN: [getTracer] Service instrumentation not found in runtime.`
Now it doesn't try and load the runtime, unless `process.env.INSTRUMENTATION_ENABLED` is set.
> Disable loading instrumentation if not enabled.

- packages/cli/src/commands/plugins.ts
**NO LOGIC OR FUNCTIONALITY CHANGES**
in order to keep the cli helper text ux uniform and consistent, i made these two minor changes:
- removed the displayBanner(), kinda random to show it in elizaos plugins -- this is mostly called during a more main action like updating cli, creating an agent/project/plugin, or starting a server or test server
- right now -h and --help are showing up on two lines but they are the same command and on every other cli command its on a single line
> minor fix: remove banner display + have -h, --help show on same line

- packages/cli/__test_scripts__/test_start.bats
- packages/client/src/components/app-sidebar.tsx
- packages/client/src/components/connection-error-banner.tsx
- packages/client/src/components/connection-status.tsx
- packages/client/src/context/ConnectionContext.tsx
- packages/client/src/lib/socketio-manager.ts
The /pings were kinda annoying log spam and were not perfectly realtime, like a 5 second lag on connect / reconnect.
We also didn't even have a proper /ping route, it was 404 and falling back to middleware btw.
This PR changes client frontend to rely on pure websocket connect / disconnect for server status changes.
This provides instant realtime feedback, with no /ping spam.
> Remove REST /ping for websocket status checks in client.

- .github/workflows/cli-tests.yml
Attempt to fix PRs in CLI tests randomly failing but passing on local and for pushes.
Adds SHA hash from github commit to bust cache better.
> fix: add commit sha to CLI cache action

- packages/plugin-bootstrap/src/index.ts
- packages/plugin-bootstrap/src/providers/recentMessages.ts
This PR addresses two issues:
1. **Bootstrap plugin response parsing**  
Previously, the LLM response was reduced to a fixed set of keys, which discarded useful custom fields like `emote` returned by custom templates. This change spreads all fields from `parsedXml` to preserve any additional values while maintaining defaults for core keys.
2. **recentMessagesProvider header handling**  
The `Received Message` and `Focus your response` headers were shown even when there was no actual user message. This update checks that the message content exists before including those headers, resulting in cleaner prompt formatting.
> fix: LLM response parsing to support custom fields and clean up empty message headers

- packages/plugin-bootstrap/src/index.ts
This PR ensures the onComplete callback is always executed, regardless of whether the message handler completes successfully, throws an error, or times out.
Key changes:
- Wrapped the entire messageReceivedHandler logic in a try-finally block
- Moved onComplete into finally to guarantee execution
- Removed redundant onComplete calls from try/catch blocks inside processingPromise
- Ensured timeout cleanup with clearTimeout in the same finally block
This prevents orphaned states or incomplete lifecycles when early errors occur during setup or long-running processes hit timeouts.
> fix: Guarantee onComplete is always called in messageReceivedHandler

- bun.lock
- packages/cli/src/utils/copy-template.ts
- packages/client/package.json
- packages/client/vite.config.ts
Fixes client error:
```
Uncaught TypeError: Failed to resolve module specifier "@elizaos/core". Relative references must start with either "/", "./", or "../".
```
Also adds vite-node-polyfills to supplement Buffer and process missing.
> fix: core not importable in client

- bun.lock
- packages/cli/src/utils/copy-template.ts
- packages/client/package.json
- packages/client/vite.config.ts
Fixes client error:
Uncaught TypeError: Failed to resolve module specifier "@elizaos/core". Relative references must start with either "/", "./", or "../".
Also adds vite-node-polyfills to supplement Buffer and process missing.
> fix: core not importable in client / vite polyfills.

- packages/cli/src/server/api/agent.ts
- packages/core/src/search.ts
- packages/docs/docs/rest/send-message.api.mdx
- Enhanced message processing with an event-driven, asynchronous flow for agent message handling
- Added support for new response scenarios where the agent may choose not to reply
- Corrected the audio message endpoint route for consistency
- Updated API documentation to clarify request and response schemas, including new required fields and response codes
- Improved descriptions and examples for API responses
Use Postman or curl for testing:
```bash
curl -X POST \
-H "Content-Type: application/json" \
-d '{
"entityId": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
"roomId": "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
"source": "curl-test",
"text": "How does rag knowledge works in elizaos",
"channelType": "API"
}' \
http://localhost:3000/api/agents/1ee9e4ad-f1a9-0946-8498-edce550b222c/message
```
> fix: send-message-api

- i18n/readme/README_PTBR.md
Hey team—noticed a dead link, replaced it with a working URL. Thanks!
https://ai16z.github.io/eliza/ -- old link
https://elizaos.github.io/eliza/ -- new link
> docs: fix broken link to ELIZA demo (ai16z → elizaos)

- packages/plugin-bootstrap/src/actions/reply.ts
Previously, the REPLY action was designed to skip the LLM call if an existing response with a REPLY action was found. However, recent changes to the message handler's template prompt caused the LLM to return the response with the `text` field instead of `message`.
This PR makes the reply field configurable (e.g., ['message', 'text']) to support both field formats. With this fix, we can correctly detect LLM responses even if the field name changes, and avoid unnecessary duplicate LLM calls in `messageReceivedHandler`.
> fix: reply action to skip LLM call if existing REPLY response is found

- packages/plugin-bootstrap/src/providers/recentMessages.ts
This PR fixes an issue where the senderName was often displayed as "Unknown" in the recentMessages provider. The update changes the logic to prioritize entitiesData for resolving the sender's name based on entityId. If no match is found, it falls back to metadata.entityName, and finally defaults to "Unknown User" if neither is available. This improves the accuracy of sender name display.
> fix: senderName is "Unknown" in recentMessages provider

- packages/cli/src/server/api/agent.ts
When using API calls and creating AGENT it very useful to have returned ID on first API call, so there are not needed subsequent calls after it just to find ID, which is crucial for other types of API calls.
So I added ID in return data so it can be used.
> API - return ID of newly created agent

- .github/workflows/docs-publish.yml
fixes npm cache since doesn't exist for docs package, removes PR runs, should only happen on pushes.
> fix: docs deploy workflow

- packages/cli/__test_scripts__/test_plugins.bats
- test plugin install modifies package.json with plugin-discord
- verify missing plugin fails with registry error
- `./run_all_bats.sh` *(fails: 'bats' not found in PATH)*
> chore: Add missing plugin failure test

- .env.example
- bun.lock
- package.json
- packages/core/README-automated.md
- packages/core/src/index.ts
- packages/core/src/logger.ts
- packages/core/src/sentry/instrument.ts
Initial Sentry hookup into core logger errors.
Has envs for custom Sentry setups, but defaults to ours.
> Add sentry logging to core logger errors.

- packages/cli/src/server/api/agent.ts
- packages/client/src/lib/api.ts
Currently we dont have API endpoint to create new rooms, so I added this feature in PR. 
Did some tests, rooms are created and IDs returned. Adding screenshots from tests
> feat: API endpoint for creating new rooms

- packages/core/src/logger.ts
- packages/core/src/sentry/instrument.ts
Since requires new ENV added, usually would always be not true, this turns off sentry only if user sets false. Even if env not added.
> default sentry better

- docs/notes/changelog.md
The old link led to a 404 error (page not found).
To avoid confusion and broken navigation for readers, the link has been temporarily cleared.
> docs: Fix outdated link in changelog.md

- packages/cli/src/commands/start.ts
- packages/cli/src/utils/load-plugin.ts
loading plugins just takes too much output and it's working fine now for the most part
- just lower output for debug channel
- move success to success channel
My heart isn't going to break if this is not merged, merely a suggestion
has improved my development log reading experience
> feat: Clean up plugin loading logging

- packages/plugin-starter/.gitignore
**Problem**
When publishing plugins to GitHub using elizaos publish, the CLI was accidentally including .env files in the initial commit. These files often contain sensitive GitHub credentials, leading to GitHub's push protection blocking the commits due to exposed tokens. This used to not occur because the .env was global (outside the repo getting pushed to gh)
**Solution**
Added .env to the default .gitignore file in the packages/plugin-starter template to ensure that:
New plugins created from this template automatically ignore environment files
GitHub tokens and other sensitive credentials are prevented from being committed
GitHub push protection doesn't block plugin publishing
This small but critical fix improves the developer experience because plugin publishing fails without it.
> add .env to plugin-starter's .gitignore file (publishing was failing due to key presence)

- packages/cli/src/utils/get-config.ts
`.env` file is empty on creation, this writes example envs for users to config better.
Also cleans up some functions and improves type safety and file handling.
> feat: write .env example, cleanup get-config functions

- packages/cli/src/commands/create.ts
this is a small pr to change a codeblock that checks for "plugin-" prefix and adds it if its not there. i am also adding some alphanumeric validation to the part that comes after "plugin-" so it's like this:
allowed:
plugin-abc
plugic-abc123
not allowed:
plugin--1
plugin-!@#%
> update plugin prefix check/add function to also validate "plugin-alpanumeric" naming conv

- packages/cli/src/commands/create.ts
- packages/cli/src/utils/publisher.ts
**Problem:**
publisher.ts was hardcoded to only handle @elizaos/ scoped packages, but it needed to work with any npm scope (like @yungalgo/, @username/, etc.).
**Specific Changes Made:**
Repository Name Extraction (Line ~298)
Test Branch Naming (Line ~178)
Simple Name Generation (Line ~193)
Package Name Without Scope (Line ~398)
Package Metadata Path (Line ~424)
**Impact:**
Fixed repository creation - now works with packages like @yungalgo/plugin-name
Fixed registry metadata - properly extracts package names from any scope
Fixed branch naming - creates correct branch names for any scoped package
Fixed file paths - generates correct registry file paths
> update name handling in publisher.ts so it doesnt expect "elizaos" anymore

- packages/core/src/utils.ts
**## Problem**
CLI commands fail with `ReferenceError: Can't find variable: DOMMatrix` when running in environments without DOM support (like Node.js/Bun).
**## Root Cause**  
`packages/core/src/utils.ts` imports `pdfjs-dist` at the top level but never uses it. This causes CLI bundling to include PDF.js dependencies that require DOM APIs.
**## Solution**
Remove the unused PDF.js imports from `core/src/utils.ts` since no functions in the file actually use PDF.js functionality.
**## Testing**
- ✅ CLI `create` command works without DOMMatrix errors
- ✅ Core package builds successfully 
- ✅ No functionality lost (PDF.js wasn't used)
Fixes CLI runtime errors like:
ReferenceError: Can't find variable: DOMMatrix
at /Users/.../node_modules/pdfjs-dist/legacy/build/pdf.mjs:12495:26
> fix: remove unused PDF.js imports causing CLI DOMMatrix runtime error

- packages/core/__tests__/entities-extra.test.ts
- packages/core/__tests__/instrumentation-index.test.ts
- packages/core/__tests__/instrumentation.test.ts
- packages/core/__tests__/roles.test.ts
- packages/core/__tests__/search.test.ts
- packages/core/__tests__/services.test.ts
- packages/core/__tests__/settings.test.ts
- packages/core/__tests__/utils-extra.test.ts
- packages/core/__tests__/utils-prompt.test.ts
- add utility tests verifying template upgrades, header addition, random name replacement, XML parsing, circular reference handling, and UUID validation
- implement settings tests covering encryption/decryption and value salting mechanics
- add service builder tests to ensure dynamically created services start and stop correctly
- add prompt utility tests for composing prompts, formatting posts, and trimming tokens
- `npx vitest run packages/core/__tests__ --coverage`
- `npm run lint`
> Add supplemental unit tests for core utilities

- packages/cli/src/commands/env.ts
- packages/cli/src/commands/start.ts
- packages/cli/src/utils/resolve-utils.ts
- packages/cli/src/utils/user-environment.ts
Any .envs upper from the project directory would get grabbed, even not inside monorepos... now this forces .env creation and respects the project folder.
> fix: .env hoisting in non-monorepo dirs

- .github/workflows/deploy-cli.yml
- packages/plugin-starter/package.json
- Fix E404 and E403 publishing errors in deploy-cli workflow
- Add lerna ignore flags for template packages that shouldn't be published
- Exclude both `create-eliza` and `plugin-starter` via workflow ignore flags
- Add `--ignore create-eliza --ignore plugin-starter` to lerna publish command
- Keep plugin-starter as a regular package but exclude it from publishing via workflow
> fix: resolve deploy-cli workflow publishing failures

- .github/workflows/deploy-cli.yml
- packages/cli/src/utils/copy-template.ts
- packages/create-eliza/package.json
- packages/plugin-starter/package.json
- Fix lerna publish command to properly exclude template packages from auto-publishing
- Resolves GitHub Actions failure: "lerna --ignore was renamed to --ignore-changes"
- Implements proper template exclusion while keeping templates usable by users
The original `--ignore` flags were deprecated, but simply replacing them with `--ignore-changes` doesn't prevent publishing - it only ignores file changes for version bumps.
- Added `"private": true` to `create-eliza` and `plugin-starter` package.json files
- These packages are now excluded from lerna publish via `--no-private` flag
- Updated `packages/cli/src/utils/copy-template.ts` to remove the `private` field when copying templates
- Users can now create projects from templates without private field restrictions
- Removed …
> feat: properly exclude template packages from lerna publish

- .github/workflows/deploy-cli.yml
- Converts deploy-cli workflow from automatic push trigger to manual workflow_dispatch
- Adds GH_PAT token for enhanced git operations and permissions
- Replaces manual version checking with lerna-managed prerelease versioning
- Uses direct lerna publish command with user-selected dist-tag (beta/alpha)
- Removes duplicate publish logic and always performs version bumps
- Change trigger from `push` to `workflow_dispatch` with dist-tag input
- Add `GH_PAT` token to checkout action for broader permissions
- Remove manual version bump detection logic
- Use single lerna publish command: `npx lerna publish prerelease --preid {dist_tag} --dist-tag {dist_tag} --no-private --force-publish --yes`
- Simplify workflow to single publish step with user-controlled dist-tag selection
- Manual control …
> refactor: convert deploy-cli workflow to manual trigger with dist-tag selection

- packages/core/src/index.ts
- packages/core/src/search.ts
- packages/core/src/types.ts
Low
- make strict typing pass
- don't export BM25 outside npm (we only use it in runtime)
improve what we have to lock down in specification and give core as much freedom as possible.
> feat: improving typing

- .github/workflows/cli-tests.yml
- bun.lock
- packages/cli/__test_scripts__/test_agent.bats
Fixes CI test failures due to missing OpenAI API key configuration.
**Low** - This change only affects test configuration and does not modify core application logic.
This PR adds the OpenAI API key configuration to CLI tests to ensure they can pass on the CI runner. The tests were failing on the CI runner because it couldn't authenticate with OpenAI services, while tests pass locally where the API key is available.
The CLI tests pass locally but fail on the CI runner due to missing OpenAI API key configuration. The CI environment wasn't configured with the necessary API key, causing test failures. This change ensures the tests can authenticate and run successfully in the CI pipeline.
My changes do not require a change to the project …
> fix: CLI tests add openai api-key

- packages/cli/src/utils/publisher.ts
Problem: 
- registry publishing logic was creating a package.json file for some reason in addition to updating the registry index.json
- Registry publishing was creating massive diffs by reordering the entire index.json file, used incorrect package name format with @elizaos-plugins/ prefix, and had indentation inconsistencies.
In general the logic was not in line with what the registry publishing should do which is basically just add an alphabetically-ordered mapping of the npm package org/package name to the github org / repo name.
Solution:
* Fixed package naming to use actual npm package name instead of @elizaos-plugins/ prefix
* Implemented line-by-line insertion to avoid massive diffs
* Added alphabetical positioning logic for clean registry updates
* Standardized indentation to 4 …
> fix: update and improve registry publishing logic and package naming

- packages/cli/src/commands/publish.ts
- packages/cli/src/utils/parse-registry.ts
Problem: 
The elizaos publish command only published to GitHub, requiring users to manually publish to npm separately. 
Ideally, elizaos publish does three things:
- publishes the github repo
- forks the registry, adds the line for the plugin, and submits a pr to elizaos-plugins/registry
- publishes to NPM
Additionally, parse-registry.ts couldn't access GITHUB_TOKEN from .env files, causing authentication failures.
Solution:
* Updated elizaos publish to publish to npm + GitHub + registry by default
* Added --ignore-scripts flag to prevent recursion when npm triggers the publish script
* Changed --npm flag to mean "npm only" (skip GitHub and registry)
* Added environment loading to parse-registry.ts with dotenv support
* Added success message with guidance for future updates using standard …
> feat: add npm publishing to default elizaos publish workflow

- packages/cli/README.md
- packages/docs/docs/cli/publish.md
- packages/plugin-starter/README.md
Problem: 
Documentation didn't reflect the new publish behavior where elizaos publish handles npm + GitHub + registry, and lacked guidance on continuous development workflows.
Solution:
* Updated CLI README and publish.md docs to reflect npm + GitHub + registry default behavior
* Added comprehensive continuous development section emphasizing standard npm/git workflows
* Updated plugin starter templates with detailed publishing guidance
* Clarified that elizaos publish is for initial publishing, while npm/git commands handle updates
* Enhanced testing workflow documentation throughout development lifecycle
Details:
* Emphasizes testing as part of proper development workflow
* Provides clear guidance on when to use elizaos publish vs standard npm/git commands
* Includes troubleshooting …
> docs: update publish workflow documentation for npm integration

- bun.lock
- packages/plugin-sql/src/base.ts
This PR fixes the issue where the API endpoint `/api/agents/:agentId/rooms` was returning an empty list despite agents being actively participating in rooms.
The root cause was that when rooms were created, the `agentId` was not being properly associated with the room record in the database. This meant that while agents could successfully:
- Create rooms (logs showed "Room [UUID] created successfully")
- Connect to rooms (logs showed "Successfully connected entity [agentId] in room [roomId]")  
- Send and receive messages in rooms
The `getRoomsForParticipant(agentId)` function could not retrieve rooms for a specific agent because the agent-room association was missing from the database.
Added the missing `agentId` field to the room creation process to ensure proper agent-room associations …
> fix: add missing agentId to create room

- packages/plugin-bootstrap/src/actions/choice.ts
Fixes a bug in CHOOSE_OPTION action validation where room.serverId could be null, causing a TypeError.
> fix: choice action null check

- packages/cli/src/utils/load-plugin.ts
- Implement smart strategy selection that checks file existence before attempting imports to find optimal path in one shot
- Reorder import strategies to prioritize most likely successful paths (package.json entry first, then common dist pattern)
- Make fallback strategy failures silent to reduce debug log noise while maintaining robust fallback system
During elizaOS startup, the plugin loading system generates excessive debug logs and errors as it tries multiple import strategies sequentially before finding the correct one. This creates log spam and slower startup times with messages like:
```
[2025-06-01 13:42:55] DEBUG: Import failed using direct path ('@elizaos/plugin-bootstrap'):
[2025-06-01 13:42:55] DEBUG: Import failed using local node_modules …
```
> chore: Optimize plugin loading to reduce startup log spam

- .gitmodules
Removes the plugin-specification submodule from the repository.
This change simplifies the project structure by removing an unused submodule.
> fix: Removes plugin-specification submodule

- bun.lock
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/tsconfig.build.json
- packages/core/tsup.config.ts
Refactors the core package's build process for improved modularity and maintainability.
- Adds dedicated entry points for different API versions.
- Updates the build configuration to use `tsup` for all build tasks.
- Enables declaration file generation for improved type safety.
- Excludes test files from the build output.
For npm modules, a single bundled index.js file is generally better for most use cases. Here's why:
1. Performance
Fewer HTTP requests when loading the module
Faster module resolution (Node.js only needs to load one file)
Better caching (single file to cache)
Reduced I/O operations
2. Bundle Size Optimization
Dead code elimination during bundling
Better minification across the entire module
Shared code is deduplicated automatically
Tree-shaking works more effectively
3. …
> chore: Enhances core package build process

- packages/cli/src/server/api/messages.ts
- packages/cli/src/server/index.ts
- packages/cli/src/server/socketio/index.ts
- packages/plugin-sql/src/base.ts
Chat messages were broken on send. channeld was not being passed through.
```
[2025-06-03 04:38:22] ERROR: [SocketIO -e53_zI1X1FYfB4MAAAF] Error during central submission for message: insert or update on table "central_messages" violates foreign key constraint "central_messages_channel_id_channels_id_fk"
message: "(error) insert or update on table \"central_messages\" violates foreign key constraint \"central_messages_channel_id_channels_id_fk\""
stack: [
"error: in
```
> fix: foreign key issue in chat messages

- package.json
Getting errors like:
```
[2025-06-03 16:47:43] ERROR: Failed to run database migrations (pglite):
message: "(RuntimeError) unreachable"
stack: [
"RuntimeError: unreachable",
"at wasm://wasm/01edd1ba:wasm-function[3611]:0x262a57",
"at wasm://wasm/01edd1ba:wasm-function[3610]:0x2627f9",
"at wasm://wasm/01edd1ba:wasm-function[7801]:0x3e3502",
"at wasm://wasm/01edd1ba:wasm-function[2533]:0x1c1034",
"at Module._pg_initdb (file:///Users/cjft/Documents/git/eliza/eliza/node_modules/@electric-sql/pglite/dist/index.js:3:124284)",
"at pe.qe (file:///Users/cjft/Documents/git/eliza/eliza/node_modules/@electric-sql/pglite/dist/index.js:3:243608)",
"at async pe._checkReady (file:///Users/cjft/Documents/git/eliza/eliza/node_modules/@electric-sql/pglite/dist/index.js:3:238920)",
"at async pe.query …
```
> chore: clean .elizadb and .eliza on bun run clean

- package.json
This PR fixes the bun install error caused by having `@elizaos/cli` listed as both a workspace package and a root dependency.
- Removed `@elizaos/cli` from root `package.json` dependencies since it's already available as a workspace package
This resolves the following error during `bun install`:
```
error: Duplicate package path
at bun.lock:908:5
InvalidPackageKey: failed to parse lockfile: 'bun.lock'
```
> fix: remove duplicate @elizaos/cli dependency from root package.json

- packages/cli/src/server/api/index.ts
The plugin route handler was incorrectly trying to handle standard agent API routes, causing debug messages like:
```
[2025-06-04 08:57:23] DEBUG: No valid agentId in query. Trying global match for path: /api/agents/b850bc30-45f8-0041-a00a-83df46d8555d/logs
[2025-06-04 08:57:23] DEBUG: No plugin route handled GET /api/agents/b850bc30-45f8-0041-a00a-83df46d8555d/logs, passing to next middleware.
```
The issue occurs in the `createPluginRouteHandler` function when:
1. A request comes in for `/api/agents/{uuid}/logs`
2. The plugin handler checks for `agentId` in query parameters (but agent routes use path parameters)
3. Since there's no `agentId` query param, it falls through to "global plugin route matching"
4. It tries to match the agent API route against plugin routes from all agents
5. …
> fix: plugin route handler intercepting agent API routes

- packages/cli/README.md
- packages/cli/src/index.ts
- packages/cli/src/utils/auto-install-bun.ts
- packages/cli/src/utils/user-environment.ts
This pull request introduces a new feature for the ElizaOS CLI: automatic installation of the Bun package manager if it is not already installed. Additionally, it adds new global options for enhanced user control and updates the CLI's internal logic to support these features.
* Added a mechanism to detect if Bun is missing and attempt automatic installation across Windows, macOS, and Linux. This includes updating the `PATH` environment variable for the current session and providing fallback manual installation instructions if the process fails. (`packages/cli/src/utils/auto-install-bun.ts`, [packages/cli/src/utils/auto-install-bun.tsR1-R101](diffhunk://#diff-4ff8b4129e7f36e6f88bfd288743b82c46872fee51fb4eb858511ba03e0cf512R1-R101))
* Integrated the auto-installation logic into the …
> chore: auto install bun in CLI

- package.json
- packages/client/vite.config.ts
This pull request introduces changes to the build and release process as well as enhancements to the versioning logic in the codebase. The most significant updates include modifying the `release` script in `package.json` to improve versioning and publishing workflows, and adding a fallback mechanism to retrieve the version from `package.json` if `lerna.json` is unavailable.
* **Updated `release` script in `package.json`:** The `release` script now uses `lerna version` with additional flags (`--no-push` and `--no-git-tag-version`) before building, linting, and publishing packages. This change ensures better control over versioning and avoids automatic pushing and tagging during the process.
* **Added fallback to `package.json` for version retrieval:** In the `vite.config.ts` file, the …
> fix: release versioning in client

- bun.lock
- packages/cli/package.json
- packages/plugin-bootstrap/package.json
- packages/project-tee-starter/package.json
This PR addresses critical dependency management issues in the monorepo that were causing build failures and CLI functionality problems.
- Unnecessary dependencies in the monorepo were causing version conflicts
- Old/outdated package versions were being installed, breaking compatibility
- CLI was not working properly due to dependency issues
- Several packages that should not be in the monorepo were included (elevenlabs, redpill)
- Removed unnecessary dependencies from monorepo root
- Cleaned up outdated package versions
- Removed `elevenlabs` package (should not be in monorepo)
- Removed `redpill` package (should not be in monorepo)
- Fixed CLI dependency conflicts
- Streamlined package.json dependencies
- CLI now works properly
- Eliminates version conflicts between packages
- Cleaner …
> dependencies cleanup

- bun.lock
- package.json
This pull request includes a minor update to the `clean` script in the `package.json` file. The order of operations in the script was adjusted to ensure that cleaning individual packages occurs before removing and reinstalling dependencies.
Error that was happening:
```
rm -rf dist .turbo node_modules .turbo-tsconfig.json tsconfig.tsbuildinfo bun.lock* .eliza .elizadb && turbo run clean --filter=./packages/* && bun install && bun run build
/bin/bash: turbo: command not found
error: script "clean" exited with code 127
```
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L19-R19): Updated the `clean` script to run `turbo run clean` for individual packages before executing the remaining cleanup commands.
> fix: clean command

- .github/workflows/release.yaml
When we tag a release, it doesnt save the version back to our code
This PR fixes our release (or should at least) so that versions are saved to the tag, pushed back to the main branch and a version update PR is made to develop. Or that's what is supposed to happen.
> feat:  push version back to main and make a pr to develop on release

- packages/docs/versioned_docs/version-0.25.9/changelog.md
packages/docs/versioned_docs/version-0.25.9/changelog.md
`promisses` - `promises`
`formating` - `formatting`
`evaulators` - `evaluators`
> minor docstring fixups

- packages/docs/packages/plugins/gitcoin-passport.md
packages/docs/packages/plugins/gitcoin-passport.md
`treshold` - `threshold`
`retrive` - `retrieve`
> fix typos gitcoin-passport.md

- .github/workflows/ci.yaml
- packages/cli/src/commands/test.ts
This pull request introduces changes to improve the handling of database directories during end-to-end (E2E) tests and updates the CI workflow configuration. The key changes include ensuring unique and clean database directories for each test run, adding cleanup logic after tests, and introducing a new environment variable in the CI workflow.
* Modified `runE2eTests` to create a unique database directory for each test run using the package name and a timestamp, preventing conflicts between test runs. (`packages/cli/src/commands/test.ts`, [packages/cli/src/commands/test.tsL167-R200](diffhunk://#diff-1e127a5e0035493241bed339c064acd5235272cf6841f1e539240118da2133eaL167-R200))
* Added logic to clean up existing database directories before initializing a new one to avoid potential corruption. …
> fix: cleanup DB in E2E tests, make fresh unique DB, PGLITE_WASM_MODE: node

- packages/core/src/types/primitives.ts
Low
add an optional target to Content type
So we have a clear way for plugin to describe when a response should be sent over DM
> feat: Add target to Content

- packages/plugin-dummy-services/.gitignore
- packages/plugin-dummy-services/package.json
- packages/plugin-dummy-services/src/e2e/scenarios.ts
- packages/plugin-dummy-services/src/e2e/test-utils.ts
- packages/plugin-dummy-services/src/index.ts
- packages/plugin-dummy-services/src/lp/__tests__/service.test.ts
- packages/plugin-dummy-services/src/lp/service.ts
- packages/plugin-dummy-services/src/tokenData/__tests__/service.test.ts
- packages/plugin-dummy-services/src/tokenData/service.ts
- packages/plugin-dummy-services/src/wallet/__tests__/service.test.ts
- packages/plugin-dummy-services/src/wallet/service.ts
- packages/plugin-dummy-services/tsconfig.build.json
- packages/plugin-dummy-services/tsconfig.json
- packages/plugin-dummy-services/tsup.config.ts
- packages/plugin-dummy-services/vitest.config.ts
This PR adds dummy services which can be depended on by other plugins
All shared service types should have a dummy implementation for use in testing
> feat: add dummy services

- packages/cli/src/server/api/index.ts
- packages/cli/src/server/api/shared/file-utils.ts
- packages/cli/src/server/index.ts
- packages/cli/src/server/loader.ts
- packages/cli/src/server/upload.ts
- packages/cli/src/utils/eliza-paths.ts
- packages/cli/src/utils/get-config.ts
- packages/cli/src/utils/resolve-utils.ts
- packages/plugin-sql/drizzle.config.ts
- packages/plugin-sql/src/index.ts
- packages/plugin-sql/src/utils.ts
This pull request introduces a significant refactor to centralize and standardize the directory structure for CLI-generated data under a hidden `.eliza` folder in the project root. Additionally, it includes instrumentation enhancements and legacy path migration logic to ensure backward compatibility. The most important changes are grouped into themes: directory structure updates, instrumentation improvements, and legacy path migration.
* Added utility functions in `packages/cli/src/utils/eliza-paths.ts` to centralize logic for resolving standard Eliza directories (`getElizaBaseDir`, `getElizaUploadsDir`, etc.). This eliminates scattered hard-coded paths throughout the codebase.
* Updated all references to CLI-generated data paths (e.g., uploads, characters, database) to use the new …
> chore: migrate all generated files into .eliza

- packages/docs/docs/cli/agent.md
The “Create Agent character” examples still used the deprecated short flag `-t`:
elizaos create -t agent eliza
Recent versions of the CLI reject that flag with:
error: unknown option '-t'
All examples now use the long-form flag:
elizaos create --type agent eliza
elizaos create --type project my-project
For reference, the current `elizaos create --help` output shows `--type` as the only valid option:
```bash
Usage: elizaos create [options] [name]
Create a new ElizaOS project, plugin, agent, or TEE project
Options:
--dir <dir>    directory to create the project in (default: ".")
--yes, -y      skip prompts and use defaults
--type <type>  type of project to create (project, plugin, agent, tee)
-h, --help     display help for command
```
This update brings the documentation in line with the …
> docs(agent): replace -t with --type in CLI examples

- packages/plugin-sql/src/custom-migrator.ts
This bug fixes a Postgresql migration issue:
If the first entry in the postgres search path is '\$user' (which it often is), it would wrongly return that entry due to wrong quotes.
The intention was to use 'public' or some other _valid_ custom schema.
This bugfix:
* correctly ignores values that _include_ '$user' (avoid exact matches that may or may not have quotes etc)
* will continue to iterate over the next values instead of directly using 'public'. 
E.g. previously if the search path was 
`"\$user", my_schema, public, extensions` , it would have wrongly returned "\$user"; and had it correctly recognized and ignored "\$user" it would have returned 'public', but should return my_schema.
This consistently happens on a fresh or existing supabase postgres database.
der.jogi
> Fix: Postgres migration schema selection

- packages/cli/src/commands/start/index.ts
Fix for envs not loading in bun run start with default character eliza.
This moves the loadEnvs function higher up since was only being called for project agents.
> fix: envs loading on default eliza

- packages/client/src/components/chat.tsx
fix the issue that when the last memory is removed or a new agent is created, two memory entries appear in the dropdown:
> fix: duplicate memory

- packages/core/src/actions.ts
Small update action examples are confusing as text and action fields are inline and agent does mistake when choosing action in XML format by adding it inline with text. 
Bad example: 
```
assistant: I'll help you transfer 1 ETH to 0x742d35Cc6634C0532925a3b844Bc454e4438f44e (action: EVM_TRANSFER_TOKENS)
user: Transfer 1 ETH to 0x742d35Cc6634C0532925a3b844Bc454e4438f44e (action: EVM_TRANSFER_TOKENS)
```
> fix: action text in example should not be inline with action field

- packages/cli/tests/commands/create.test.ts
- packages/cli/tests/commands/env.test.ts
- packages/cli/tests/commands/plugins.test.ts
- packages/cli/tests/commands/publish.test.ts
- packages/cli/tests/commands/start.test.ts
- packages/cli/tests/commands/test-utils.ts
- Fixes Windows test failures by replacing Unix-specific commands with cross-platform equivalents
- Creates .cmd files instead of bash scripts for Windows mock executables  
- Adds proper error handling for git operations and shell commands
- Use .cmd batch files for Windows instead of bash scripts with shebangs
- Skip chmod operations on Windows since .cmd files are executable by default
- Replace rm/mkdir with Windows-compatible rmdir/del commands where needed
- Add try-catch blocks around git operations for environments without git
- Handle platform-specific shell input methods for interactive command tests
Fixes the failing Windows tests identified in workflow run.
> fix: Windows compatibility for CLI tests

- packages/docs/sidebars.ts
This PR fixes the Next navigation button bug in the Core Concepts - Overview section which pointed to the same page instead of Core Concepts - Actions by removing the unnecessary link section.
> Remove link with duplicated id from sidebars

- packages/plugin-bootstrap/src/index.ts
Evaluator callbacks seem unhandled.
This PR forwards the callback handler to `runtime.evaluate()` in favor of passing an empty closure
> fix bootstrap evaluator callbacks

- packages/client/src/components/chat.tsx
- packages/server/src/api/messaging/core.ts
- packages/server/src/services/message.ts
Currently, if an agent chooses to ignore the user (either by selecting the IGNORE action or sending an empty text response), the chat UI gets stuck displaying "agent is thinking". This blocks the user from sending any further messages unless the page is refreshed.
This happens because the chat interface only unlocks when it receives the next agent message. However, in these cases, no message is sent—so the UI remains in a loading state indefinitely.
Changes in this PR:
Added a complete API endpoint that notifies the client when message processing is finished—even if the agent ignored the message or an error occurred.
Ensures the chat UI is unblocked and responsive even when no message is returned by the agent.
> fix: gui stuck issue

- packages/core/src/prompts.ts
None, I can open an issue if necessary and update this.
The default `messageHandler` prompt contains an entry for the AI to choose relevant evaluators to be run after handling the processed message. At the moment, however, even if the AI returns any evaluators in the response they are left unused, as the `runtime.evaluate` function simply runs through all available evaluators. Moreover it seems lie the AI is not given the list of evaluators to choose from (in contrast to the providers).
Might interfere with some client plugins (e.g. socials) if they rely on this default template but haven't encountered any such plugin yet. Even if they did it probably would not properly work anyway due to the missing evaluators list.
Removes obsolete evaluators entry in prompt which is unnecessary and may …
> fix: remove evaluators from messageHandler prompt

- packages/docs/partners/eliza/index.mdx
Replaced the outdated ElizaOS documentation link (https://elizaos.github.io/docs) with the current official documentation URL (https://eliza.how/docs/intro) in the Eliza partner page. This ensures users are directed to the latest and most accurate resources.
Reference: https://eliza.how/docs/intro
> fix(docs): update ElizaOS documentation link to new official URL

- packages/client/src/components/secret-panel.tsx
Currently, when importing a long list of environment variables into the secret panel, the user has to scroll all the way down to access the "Save" button.
This PR sets a maximum height and enables vertical scrolling to improve.
before: 
https://github.com/user-attachments/assets/edf205e7-4d8f-4399-8bd2-4acf0707a25c
after:
https://github.com/user-attachments/assets/3b7e8ac9-dec2-4bce-a2ab-7b79a7376540
> fix: scroll behavior on env panel

- packages/cli/src/utils/copy-template.ts
This PR fixes an issue where the `elizaos create` command was not properly copying templates due to missing `__dirname` in ES module context.
- Added `fileURLToPath` import from `node:url`
- Defined `__filename` and `__dirname` for ES module compatibility in `copy-template.ts`
The `elizaos create` command was failing to copy templates because `__dirname` is not available in ES modules by default.
This fix properly defines `__dirname` using the ES module-compatible approach with `import.meta.url`.
> fix: add __dirname for ES modules in copy-template utility

- packages/client/src/components/secret-panel.tsx
related: https://linear.app/eliza-labs/issue/ELIZA-452/unable-to-edit-agent-environment-variables-in-v109
Previously, adding or editing a secret would redirect to the main homepage without saving because it triggered the parent "Save Agent" button. This PR fixes the issue by adding preventDefault to prevent it
issue:
https://github.com/user-attachments/assets/2271d922-113d-49d6-b5eb-6ae403281f4f
> fix(secret-panel): allow editing and adding new secrets

- packages/cli/tests/commands/create.test.ts
This pull request updates the test suite for `ElizaOS Create Commands` to reflect changes in the available AI models. Specifically, it adjusts the expected number of models and removes assertions related to the `ollama` model's title and description.
Key changes to tests:
* [`packages/cli/tests/commands/create.test.ts`](diffhunk://#diff-42f8ccf9512d443a84058d5afd8607fe283748d0c81369cff38fa28c24f4ea1aL271-L278): Updated the `getAvailableAIModels` test to expect 5 models instead of 4 and removed checks for the `ollama` model's title and description.
> fix: create option test

- packages/cli/src/utils/registry/index.ts
- packages/cli/tests/commands/plugins.test.ts
This pull request refines the `normalizePluginName` function in `packages/cli/src/utils/registry/index.ts` by removing duplicate and incorrect namespace formats from the list of generated plugin name variations.
Key change:
* [`normalizePluginName`](diffhunk://#diff-ab81a7f856a44c5b61c0792337ded8ecfcf3960da121c0fcfd7fdb913a0625e1L390-L399): Removed redundant entries (`@elizaos/${baseName}`, `@elizaos/plugin-${baseName}`, `@elizaos-plugins/plugin-${baseName}`) from the list of possible plugin name formats, ensuring no duplicates or incorrect namespaces are included.
> fix: incorrecly scoped plugin name

- .github/workflows/integrationTests.yaml
CLI tests were running duplicate in both integration and cli workflows, not needed.
> chore: remove CLI tests from integration tests

- packages/cli/tests/unit/commands/test/e2e-tests.test.ts
- packages/cli/tests/unit/utils/build-project.test.ts
- packages/cli/tests/unit/utils/directory-detection.test.ts
This PR fixes broken tests that resulted from the directory detection centralization refactor. The tests were discovered to have commented-out assertions with "TODO:
Fix for bun test" - essentially fake tests that weren't validating anything. This PR restores real working tests using proper bun test APIs.
After the directory detection refactor, we ran the tests and discovered a critical issue:
- **Most assertions were commented out** with "TODO: Fix for bun test"
- **Tests were passing but not testing anything** - dangerous false security
- **Only 38 expect() calls** across test files that should have been validating behavior
- **Tests would not catch regressions** if code broke
The original tests had been "temporarily" commented out when migrating to bun test, but the real assertions …
> fix: (tests) restore working test assertions after directory detection centralization

- packages/core/src/utils.ts
This PR fixes a failing test in the core package by implementing intelligent attachment formatting in the `formatMessages` utility function that handles both simple and complex attachments correctly.
The test `Utils Comprehensive Tests > formatMessages > should handle attachments` was failing because it expected simple attachments to be formatted as a comma-separated list:
```
(Attachments: [att-1 - Image (http://example.com/img.jpg)], [att-2 - Document (http://example.com/doc.pdf)])
```
But the implementation was using newline separation for all attachments:
```
(Attachments: [att-1 - Image (http://example.com/img.jpg)]
[att-2 - Document (http://example.com/doc.pdf)])
```
The issue was more complex than initially apparent. Attachments can have additional `text` and `description` fields …
> fix: update attachment formatting to use comma-separated list

- packages/api-client/src/services/messaging.ts
- packages/client/src/components/chat.tsx
Fixes an issue with chat title generation. This was a regression introduced in [this PR](https://github.com/elizaOS/eliza/pull/5263), which I unfortunately missed during review and approval.
> fix: chat title

- packages/cli/tests/commands/create.test.ts
This PR improves the AI provider tests in `create.test.ts` to avoid the anti-pattern of needing to update tests every time a new AI provider is added.
1. **Removed hardcoded provider count**: Changed from `expect(models).toHaveLength(5)` to a range test (3-7 providers)
2. **Removed provider-specific tests**: Removed the ollama-specific test that was redundant
3. **Test only core providers**: Now only tests for essential providers (local, openai, claude, openrouter) 
4. **Added contract tests**: New test ensures all providers follow the expected structure regardless of count
5. **Better test organization**: Count test is now separate and clearly named
- ✅ No more test updates needed when adding new AI providers (up to 7 total)
- ✅ Tests focus on behavior and contracts rather than …
> fix: improve AI provider tests to avoid brittle patterns

- packages/core/package.json
When plugin developers try to use `bun test` instead of `vitest` for testing their plugins, they encounter a critical error:
```
error: Cannot find module '@elizaos/core' from '/path/to/plugin/test.ts'
```
This happens because:
- The published `@elizaos/core` npm package has `"bun": "./src/index.ts"` in its package.json
- Bun prioritizes this field and tries to load from `node_modules/@elizaos/core/src/index.ts`
- However, the npm package only contains compiled files in `dist/`, not the source files
- This makes it impossible for plugins to use `bun test` when importing from `@elizaos/core`
Update the "bun" fields in package.json to point to the compiled dist files:
- `"bun": "./src/index.ts"` → `"bun": "./dist/index.js"`
- **Minimal change**: Only updates two lines in package.json
- **No …
> fix(core): fix bun import error by pointing to dist files

- packages/cli/src/utils/copy-template.ts
- turbo.json
Recent deployments have been experiencing "Client UI not available" errors when accessing the frontend. This happens when the CLI package is built without the client package being built first, resulting in missing client dist files that the server needs to serve the UI.
The issue was introduced by commit 9f50fda322 which added dynamic client path resolution to the server. However, the build process didn't guarantee that client files would be available when the CLI tried to copy them.
- Added explicit dependency in `turbo.json` for `@elizaos/cli#build` to depend on `@elizaos/client#build`
- This ensures turbo automatically builds the client before building the CLI
- Made CLI build fail fast with clear error message if client files are missing
- Prevents silent failures that lead to missing …
> fix: ensure CLI build depends on client build to prevent 'Client UI not available' errors

- packages/client/src/components/plugins-panel.tsx
This PR marks @elizaos/plugin-bootstrap as an essential plugin within the PluginsPanel
related: https://linear.app/eliza-labs/issue/ELIZA-504/bootstrap-needs-to-be-marked-blue-in-gui
> feat: mark bootstrap plugin as essential

- packages/client/src/components/agent-card.tsx
- packages/client/src/components/ui/avatar.tsx
- packages/client/src/constants.ts
This PR includes the following improvements:
1. Increase avatar upload threshold to 1024
Per request by @borisudovicic, the allowed avatar upload size limit is now increased to 1024 to support higher-quality avatars.
2. Fix avatar image display with object-cover
Ensures avatar images maintain correct aspect ratio without stretching, providing a consistent and polished appearance.
before: 
after:
3. Fix header being covered by avatar image
Previously, when an avatar image was uploaded, it visually covered the header due to layering, which prevented users from clicking header buttons like Settings and Chat. This PR resolves the issue by switching the CardHeader and CardContent order, ensuring the header remains visible.
before:
after:
> fix: avatar

- packages/cli/src/utils/display-banner.ts
- packages/cli/tests/integration/version-display.test.ts
- packages/cli/tests/unit/utils/display-banner.test.ts
- Added logic to detect if CLI is running from node_modules
- Shows 'monorepo' when running from local dist (not properly installed)
- Shows actual version only when globally installed via bun/npm
- Added `isRunningFromNodeModules()` helper function to check installation method
- Modified `getVersion()` to return 'monorepo' for non-node_modules executions
- Updated unit tests to cover all version detection scenarios
- Added integration test for local dist behavior
> feat(cli): show 'monorepo' version for local dist builds

- packages/cli/src/utils/get-config.ts
- Remove automatic merging of process.env variables into .env file
- Use clean template without runtime environment pollution
- Prevent .env file from becoming cluttered with unrelated variables
The previous implementation was automatically merging all process.env variables into the generated .env file, which:
- Made the .env file messy and confusing with system/unrelated variables
- Added variables that weren't required by ElizaOS
- Created an unclear configuration experience for new users
This PR simplifies the .env file creation to only use the template content, providing:
- A clean, well-documented configuration file
- Only the variables actually needed by ElizaOS
- Clear structure for users to understand and modify
> fix: simplify .env file creation to use template only

- packages/client/src/components/agent-card.tsx
- packages/client/src/routes/home.tsx
This PR updates the UI based on @wtfsayo requirements:
- Updates the switch off button to gray color.
- Removes the message icon from the “New Chat” button.
- Adds background color to the tabs that switch between group chat and DM chat views.
Additionally, this PR fixes two issues:
- The agent card content now maintains consistent height across different cards.
- Fixes the issue where all agent cards were displaying the same bio for different agents. Previously, we were checking if the agent bio was a string, but the agent bio is actually an array, which caused it to always fall back to the default text.
> fix: tweak ui and fix agent card padding issue

- packages/client/src/components/character-form.tsx
This PR fixes the reversed import/export buttons in the character form dropdown menu.
1. **Fixed icon orientation**: 
- Export button now uses  (data flowing down from app to file)
- Import button now uses  (data flowing up from file to app)
2. **Reordered menu items**:
- Import button now appears first in the dropdown
- Export button now appears second in the dropdown
The previous implementation had:
- Reversed icons that didn't match the logical data flow direction
- Reversed button order where export came before import
This fix ensures:
- Icons correctly represent the direction of data flow
- Menu order follows logical user workflow (import first, then export)
-
> Fix import/export button order and icons in character form

- bun.lock
- eliza.postman.json
- lerna.json
- package.json
- packages/api-client/package.json
- packages/app/package.json
- packages/app/src-tauri/tauri.conf.json
- packages/autodoc/package.json
- packages/cli/package.json
- packages/client/package.json
- packages/core/package.json
- packages/create-eliza/package.json
- packages/docs/package.json
- packages/plugin-bootstrap/package.json
- packages/plugin-dummy-services/package.json
- packages/plugin-sql/package.json
- packages/plugin-starter/package.json
- packages/project-starter/package.json
- packages/project-tee-starter/package.json
- packages/server/examples/package.json
- packages/server/package.json
This PR updates the version across all packages from 1.0.15 to 1.0.16.
> chore: bump version to 1.0.16

- packages/client/src/components/agent-card.tsx
Previously, the bio handling logic assumed `agent.bio` was always an array, causing existing agents with string-based bios to fallback to the default description, hiding their actual bio.
This fix adds type checks to gracefully handle both string and array forms of `agent.bio`, preserving backward compatibility and ensuring existing agent bios are displayed correctly.
related:
https://github.com/elizaOS/eliza/pull/5385#pullrequestreview-2984281045
> fix: handle string and array types in bio for backward compatibility

- packages/client/src/components/audio-recorder.tsx
Issue:
The recording icon has no padding, causing it to appear cramped.
Fix:
Added padding to the recording icon to improve visual balance and alignment.
> fix: recording icon padding

- packages/client/src/components/chat.tsx
- packages/client/src/components/ui/split-button.tsx
This PR fixes a group chat crash issue
Additionally, it unifies the corner radius for the SplitButton component across the app by:
Adding mainButtonClassName and dropdownButtonClassName props to allow per-button styling control.
> fix: resolve group chat crash and unify SplitButton corner radius

- packages/client/src/components/chat.tsx
- packages/client/src/hooks/use-delete-agent.ts
This PR updates the header avatar action to match the new Figma design. Clicking the avatar in the header now opens a dropdown with options to export, delete, or stop the agent directly.
Additionally, this PR adds a reusable useDeleteAgent hook to handle agent deletion with consistent confirmation, error handling, and background processing across the app.
> feat: header dropdown

- packages/cli/src/commands/update/actions/cli-update.ts
- packages/cli/src/commands/update/index.ts
- packages/cli/tests/commands/update.test.ts
Fixes a critical bug where `elizaos update` creates unwanted project files (package.json, node_modules, etc.) when run outside of an ElizaOS project directory.
When running `elizaos update` in a non-project directory (e.g., ~/Documents):
- The command incorrectly used `executeInstallation()` which performs local package installation
- This created package.json, bun.lock, node_modules, and other project files in the current directory
- The global CLI was not actually updated
- Users ended up with project files scattered in random directories
The `performCliUpdate()` function was calling:
```typescript
await executeInstallation('@elizaos/cli', latestVersion, process.cwd());
```
This executes `bun add @elizaos/cli` locally instead of `bun add -g @elizaos/cli` globally.
- Replaced …
> fix: prevent CLI update from creating files in non-project directories

- packages/cli/src/characters/eliza.ts
- packages/project-starter/src/character.ts
PR Description:
This PR fixes the starter project’s missing Eliza avatar by replacing the previous local image bundling method with a direct hosted image approach.
✅ Created a dedicated repo ([elizaOS/eliza-avatars](https://github.com/elizaOS/eliza-avatars)) to host agent avatars publicly.
✅ Replaced the monorepo’s local fs-based avatar loading with a direct URL reference to the hosted Eliza avatar.
✅ Removes unnecessary copying of avatar images into dist during builds.
✅ Simplifies the code and ensures new projects always have the Eliza avatar available without extra setup or local bundling.
✅ Keeps consistent behavior across local development, deployment, and all environments.
This improves consistency across the starter, monorepo, and deployment workflows while reducing code …
> fix: starter avatar

- packages/core/src/runtime.ts
Summary
Currently, we have duplicated model logging during useModel runtime:
The first log (prompt:${modelKey}) captures the prompt but lacks detailed context.
The second log (useModel:${modelKey}) captures parameters and the response.
In practice, this results in two logs for each model call, adding unnecessary noise in the GUI while the first log does not add meaningful additional detail.
What this PR does
Merges the two logs into a single adapter.log call.
> fix: merge duplicate model logging into a single adapter.log call

- packages/client/src/components/chat.tsx
Problem:
Navigating to a chat with { state: { forceNew: true } } caused repeated DM channel creation on page refresh, as location.state persists across reloads in React Router.
What this PR does:
Adds navigate(location.pathname, { replace: true }) immediately after consuming the forceNew flag in the Chat component.
This clears the location.state to prevent repeated forced DM creation on refresh while preserving intended one-time forced behavior.
> fix: repeated DM creation on refresh by clearing forceNew state

- packages/cli/src/commands/create/actions/creators.ts
this updates the helper text to use elizaos commands and also gives more descript instructions about what to do after creating a plugin project or agent.
it also flashes a warning in case the plugin name gets augmented so the user isnt surprised
this doesnt change code, only logs and warnings.
> fix: update create command helper text + warning msg

- packages/client/src/components/chat.tsx
- Adds clear toast feedback when opening or reusing a fresh DM channel:
- Shows "Already in a fresh chat" if the user is already in the latest empty DM channel.
- Shows "Chat opened" if switching to a fresh empty DM channel automatically.
- Helps users understand chat state transitions without ambiguity.
- Keeps UX clean and warm without noisy or redundant toasts.
> chore: refine chat opening toasts for clarity

- packages/cli/tests/commands/plugins.test.ts
This PR removes the --skip-verification flag from all plugin test commands in the plugins.test.ts file. The flag appears to be no longer needed or recognized in the current version of the CLI.
> fix: remove skip-verification flag from plugin test commands

- packages/cli/src/characters/eliza.ts
This PR adds explicit boolean conversion using the `!!` operator for environment variable checks in the eliza character configuration.
- Added `!!` operator to convert environment variables to boolean values explicitly
- Affected environment variables:
- `ANTHROPIC_API_KEY`
- `OPENROUTER_API_KEY`
- `OPENAI_API_KEY`
- `OLLAMA_API_ENDPOINT`
- `GOOGLE_GENERATIVE_AI_API_KEY`
- Ensures consistent behavior across different environments
- Prevents potential issues with truthy/falsy values
- Makes the boolean conversion explicit and more readable
The changes are straightforward boolean conversions that maintain the existing logic while making it more explicit.
> fix: add explicit boolean conversion for environment variable checks

- .gitignore
- packages/server/src/index.ts
This PR adds `bun.lock` to the .gitignore file to prevent the Bun package manager lock file from being tracked in version control.
- Added `bun.lock` to .gitignore
Lock files for package managers should typically be ignored in git repositories to avoid merge conflicts and unnecessary version control tracking of dependency resolution states.
> fix: add bun.lock to .gitignore

- .gitignore
- packages/server/src/index.ts
Fixes 'Client application not found' error when running ElizaOS from global CLI installation.
When ElizaOS is installed globally via `bun install -g @elizaos/cli`, the server cannot find the client dist files because it only looks for them relative to the server package location, which doesn't work for global installations.
1. Added multiple path resolution strategies:
- First tries the development path (relative to server package)
- Falls back to using `require.resolve('@elizaos/cli/package.json')` to find the CLI package in global installations
2. Applied the same logic to both:
- Static file serving middleware
- SPA catch-all route handler
1. Install CLI globally: `bun install -g @elizaos/cli`
2. Run `elizaos` command
3. Navigate to http://localhost:3000/chat
4. Refresh the page - …
> fix: improve client path resolution for global CLI installations

- packages/client/src/components/chat.tsx
- packages/server/src/api/index.ts
This PR fixes critical UI hydration errors and SPA routing issues that were preventing proper client-side navigation and causing React warnings in production.
1. **React hydration error**: Invalid HTML structure with nested `<button>` elements causing "button cannot be a descendant of button" warnings
2. **SPA route handling failure**: Page reloads on client routes (e.g., `/chat/[id]`) returned 404 errors instead of serving the SPA
3. **Plugin middleware intercepting client routes**: The plugin route handler was returning error responses for non-API routes
1. **Fix nested button hydration error**:
- Removed inner `Button` component from dropdown menu trigger in chat header
- Replaced with direct `ChevronDown` icon element
- Maintains same visual appearance while producing valid HTML …
> fix: SPA routing fallback and nested button hydration error

- packages/cli/src/commands/start/actions/server-start.ts
- packages/server/src/__tests__/spa-routing-fix.test.ts
- packages/server/src/index.ts
- Enhanced debugging for SPA routing issues
- Improved client path resolution with file existence checks
- Better error messages to help diagnose path resolution problems
This PR builds on #5479 which was already merged but users are still experiencing SPA routing issues. This adds additional debugging and reliability improvements.
Users are still seeing errors like:
```
[STATIC] Failed to serve index.html: Not Found
```
Even after the initial fix was merged.
1. **Store clientPath as instance variable**: Ensures the resolved path is available to the SPA fallback handler
2. **Add file existence checks**: Verify index.html exists before attempting to serve it
3. **Enhanced error logging**: Log specific error codes and attempted paths
4. **Use Express recommended sendFile approach**: Use `{ …
> fix: enhance SPA routing debugging and reliability

- packages/client/src/components/ui/chat/animated-markdown.tsx
Summary
This PR refactors AnimatedMarkdown to replace the previous AIWriter + Markdown swap-based animation with a smooth, consistent, progressive reveal using Markdown alone, while capping animation duration for long texts.
Previous Implementation Recap:
Used:
<AIWriter> for animated typing effect.
Switched to <Markdown> after an estimated time (message length * 50ms, capped at 3000ms) via a setTimeout.
Issues:
Visible hiccup/jump when swapping from AIWriter to Markdown due to DOM replacement and different rendering structures.
Estimated duration was imprecise, relying on a fixed guess that could mismatch actual animation length.
For long messages, either animation ran too long or felt inconsistent, leading to delays in user reading.
Increased complexity with managing animationComplete …
> fix: Smooth progressive reveal with cap, remove AIWriter swap causing hiccups

- packages/cli/src/commands/create/actions/setup.ts
- packages/cli/src/utils/spinner-utils.ts
This PR fixes the Google Generative AI plugin installation during the `elizaos create` command.
When users select "Google Generative AI" during project creation:
1. The system was trying to install `@elizaos/plugin-google` instead of `@elizaos/plugin-google-genai`
2. A `ReferenceError: logger is not defined` error occurred in `spinner-utils.ts`
1. **Fixed plugin mapping**: Changed the mapping from `google` → `google` to `google` → `google-genai` in `resolveModelToPlugin()`
2. **Added missing import**: Added the missing `logger` import in `spinner-utils.ts`
- `packages/cli/src/commands/create/actions/setup.ts`: Updated plugin mapping
- `packages/cli/src/utils/spinner-utils.ts`: Added logger import
After this fix:
- Running `elizaos create` and selecting "Google Generative AI" will …
> fix: correct Google Generative AI plugin installation

- .github/workflows/daily-code-quality-analysis.yml
This PR fixes the failing Daily Code Quality Analysis workflow by addressing the Claude action's incompatibility with scheduled events.
The workflow was failing with error: `Unsupported event type: schedule` because the `anthropics/claude-code-action@beta` action doesn't support scheduled workflow runs.
1. **Fixed Claude Action**: Added proper event type checking so the Claude action only runs on `workflow_dispatch` events, not scheduled runs
2. **Added Informative Messages**: When Claude analysis is skipped during scheduled runs, users see a clear message explaining why and how to enable it
3. **Preserved Model Configuration**: Maintained the Claude Opus 4 model specification for comprehensive analysis
- Modified the Claude Analysis condition from:
```yaml
if: …
```
> fix: parallelize code quality workflow and fix Claude action for scheduled runs

- .github/workflows/daily-code-quality-analysis.yml
This PR fixes a critical issue that was discovered after the previous PR was merged. The daily code quality analysis workflow was failing because the generated issue body exceeded GitHub's 65,536 character limit.
The workflow failed with error:
```
Failed to create issue: Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}
```
This happened because the full analysis report can be very large, especially for large codebases.
Added truncation logic to the issue creation step:
1. **Smart Truncation**: If report exceeds 50,000 characters, truncate it
2. **Line Boundary Cutting**: Truncate at the nearest line boundary to maintain valid markdown
3. **User Notification**: Add a note when truncated, directing users to …
> fix: handle GitHub issue body character limit in code quality workflow

- packages/client/src/components/ChatInputArea.tsx
- packages/client/src/components/ui/chat/chat-input.tsx
- Adds **auto-resizing functionality** to the `ChatInput` component using `internalRef` and `resizeTextarea`.
- Dynamically adjusts the textarea height based on content while **capping at 160px (MAX_HEIGHT)** to prevent overflow.
- Improves the typing experience in chat by:
- Removing unnecessary scrollbars.
- Keeping multi-line messages fully visible while typing.
---
Currently, `ChatInput` has a **fixed height**, which:
- Makes it harder to view longer messages while composing.
- Forces users to scroll within a small textarea for multi-line inputs, degrading usability.
---
By adding auto-resizing with a max height cap, we:
✅ Improve user experience during message composition.  
✅ Maintain a clean, consistent chat layout without abrupt jumps.  
✅ Avoid overflow issues while supporting …
> feat: Auto-resize ChatInput textarea with max height for improved UX

- packages/plugin-sql/src/migration-service.ts
Low. This is a targeted bug fix correcting data access, unlikely to introduce regressions.
This PR fixes a bug in the `acquireAdvisoryLock` method where it incorrectly accessed the return format from `this.db.execute()`. Previously, it attempted to access `result[0]?.acquired`, but `this.db.execute()` returns an object with a `rows` property (e.g., `{ rows: [...] }`).
The previous incorrect access to the `execute()` result meant that the advisory lock acquisition always failed when using this path, potentially leading to unnecessary lock waiting or timeouts. This fix ensures the lock acquisition logic functions as intended.
`packages/plugin-sql/src/migration-service.ts` …
> Fix advisory lock acquisition bug

- packages/client/src/hooks/use-character-convert.ts
This PR maps the llama_local provider in v1 to @elizaos/plugin-ollama.
> chore: provider mapping

- .github/workflows/cli-tests.yml
- bun.lock
- packages/cli/package.json
- packages/cli/src/utils/bun-exec.ts
- packages/cli/tests/commands/README.md
- packages/cli/tests/commands/agent.test.ts
- packages/cli/tests/commands/create.test.ts
- packages/cli/tests/commands/dev.test.ts
- packages/cli/tests/commands/env.test.ts
- packages/cli/tests/commands/monorepo.test.ts
- packages/cli/tests/commands/plugins.test.ts
- packages/cli/tests/commands/publish.test.ts
- packages/cli/tests/commands/test-utils.ts
- packages/cli/tests/commands/test.test.ts
- packages/cli/tests/commands/update.test.ts
- packages/cli/tests/utils/bun-test-helpers.ts
This PR adds the Ollama plugin as a dependency to the ElizaOS CLI package and optimizes the CI/CD workflow for better performance.
- Added `@elizaos/plugin-ollama@1.2.1` as a dependency to the CLI package
- This enables Ollama LLM support directly in the CLI
- Updated `bun.lock` to include `ollama-ai-provider` and its dependencies
- **Removed redundant Node.js setup** from CLI tests workflow
- Bun already handles JavaScript/TypeScript execution natively
- Reduces CI complexity and setup time
- **Removed memory allocation override** from test command
- Removed `NODE_OPTIONS="--max-old-space-size=8192"` 
- Tests should run fine with default memory settings
- Simplifies test execution
- Various dependency version updates in `bun.lock`
- Includes updates to `@swc/core`, `@shikijs`, …
> feat: improve cli ci tests + migrate to bun native process spawn etc

- packages/cli/src/characters/eliza.ts
This pull request updates the `getElizaCharacter` function in `eliza.ts` to improve plugin configuration logic. The change ensures that the `@elizaos/plugin-ollama` plugin is only included as a fallback if no other large language model (LLM) providers are configured. Additionally, the `@elizaos/plugin-linear` plugin has been added to the list.
Key changes in plugin configuration:
* [`packages/cli/src/characters/eliza.ts`](diffhunk://#diff-b1cc9842b2ffbafc6920646d7fbabdd5aad44d2589f33703fff24ba62c7dc9c6L220-R228): Modified the logic to include `@elizaos/plugin-ollama` only when no LLM provider API keys are set (`ANTHROPIC_API_KEY`, `OPENROUTER_API_KEY`, `OPENAI_API_KEY`, or `GOOGLE_GENERATIVE_AI_API_KEY`).
* [`packages/cli/src/characters/eliza.ts`](diffhunk://#diff-b1cc9842b2ffbafc6920646d7 …
> fix: only fallback ollama if nothing else exists

- packages/plugin-sql/src/__tests__/integration/memory.test.ts
- packages/plugin-sql/src/base.ts
Great catch!  
The change that stringifies `content` and `metadata` before passing them to
```ts
sql`${...}::jsonb`
```
solves the root issue where raw objects were implicitly coerced to the string `"[object Object]"`.  
That coercion broke the `::jsonb` cast, triggered `Failed query` errors, and blocked service startup (most visibly with `plugin-twitter`).
1. **`createMemory`**
* Detects string vs. object and always stores a *JSON string*:
```ts
const contentToInsert  = typeof memory.content  === 'string'
? memory.content
: JSON.stringify(memory.content ?? {});
const metadataToInsert = typeof memory.metadata === 'string'
? memory.metadata
: JSON.stringify(memory.metadata ?? {});
```
* Uses those variables in the `INSERT`.
2. **`updateMemory`**
* Mirrors the same logic when updating …
> fix: JSON strings in sql base

- packages/cli/.npmignore
- packages/cli/package.json
- packages/cli/src/commands/create/actions/creators.ts
- packages/plugin-quick-starter/package.json
- packages/plugin-starter/package.json
When creating plugins with `elizaos create`, the .gitignore file was not included in the published npm package. This could lead to accidentally committing and pushing sensitive files like .env to GitHub.
- Added .gitignore to the files array in plugin template package.json files
- Created .npmignore for CLI to explicitly include template dot files
- Added security warning after plugin creation
- Created new plugin with updated CLI
- Verified .gitignore is included in npm package using `npm pack --dry-run`
- Confirmed sensitive files are properly excluded from version control
> fix: gitignores missing in plugin starter

- packages/core/src/__tests__/runtime.test.ts
- packages/core/src/runtime.ts
- packages/core/src/types/model.ts
Enhancement: Allow model parameters to be configured at the character level instead of hardcoded in plugins
**Low** - Changes are backward compatible. If no model settings are configured in character, behavior remains unchanged. Settings only apply as defaults and can still be overridden per call.
This PR adds support for configuring model parameters (temperature, maxTokens, frequencyPenalty, presencePenalty) at the character level. These settings are automatically passed as defaults to all `useModel()` calls, allowing consistent model behavior across all plugins without hardcoding values.
- Need to document the new MODEL_* settings in character configuration
- Need to update …
> feat: add character-based model configuration settings to runtime

- bun.lock
- packages/cli/src/commands/dev/actions/dev-server.ts
- packages/cli/src/commands/start/index.ts
- packages/cli/src/utils/__tests__/dependency-manager.integration.test.ts
- packages/cli/src/utils/__tests__/dependency-manager.test.ts
- packages/cli/src/utils/dependency-manager.ts
- packages/plugin-sql/src/__tests__/integration/memory.test.ts
Automatically adds `@elizaos/cli` as a dev dependency using **bun** when running `start` or `dev` commands in non-monorepo environments. This improves the development experience by ensuring developers always have access to the local CLI for better performance and consistency.
**Core Components:**
- **New utility:** `dependency-manager.ts` with smart auto-installation logic optimized for bun
- **Enhanced commands:** Integrated into both `start` and `dev` commands
- **Comprehensive testing:** 49 passing tests with 100% coverage for the new module
**Smart Detection Logic:**
- ✅ **Will install** when: Not in monorepo, has package.json, @elizaos/cli missing, auto-install enabled
- ❌ **Will skip** when: In monorepo, CI/test environments, CLI already present, or disabled via env vars
**Bun-Only …
> feat: auto-install @elizaos/cli as dev dependency for start/dev commands

- packages/cli/src/commands/update/utils/version-utils.ts
- packages/cli/tests/commands/update.test.ts
This PR fixes the failing CLI test `update --check works` that was failing in CI due to version handling in monorepo context.
The test was expecting a semantic version pattern (e.g., `1.2.0`) but was receiving `workspace:*` because the CLI's package.json in the monorepo uses workspace protocol.
- Updated `getVersion()` in `version-utils.ts` to detect monorepo context using the standard `detectDirectoryType` pattern
- Returns `'monorepo'` instead of `'workspace:*'` when running in monorepo context
- Updated the test regex to accept both `'monorepo'` and semantic versions
- Follows existing patterns used throughout the codebase (e.g., in `dev-server.ts`, `build-utils.ts`)
1. **packages/cli/src/commands/update/utils/version-utils.ts**
- Added import for `detectDirectoryType`
- Check for …
> fix(cli): handle monorepo version in update command

- packages/core/src/runtime.ts
- packages/core/src/settings.ts
- packages/core/src/types/runtime.ts
- packages/plugin-bootstrap/src/index.ts
- packages/plugin-sql/src/base.ts
- packages/test-utils/src/mocks/runtime.ts
Low
- add getServiceLoadPromise interface to runtime
- fix component queries in plugin-sql (was too easy for dates to get invalid, this is a more flexible set up, allowing the intended effect)
- remove bootstrap capabilities
- fixes ensureConnections large addPartipants, now does it in batches
- lower logging
removes the need for polling and timers when waiting for a service to be available in initialization
> feat: getServiceLoadPromise

- packages/core/src/__tests__/prompts.test.ts
- packages/core/src/prompts.ts
The actionNames block was appearing twice in the messageHandlerTemplate: once correctly inside the <providers> section and once redundantly after it. This PR removes the duplicated block after the </providers> tag to streamline the template and prevent confusion.
> fix: Remove duplicate actionNames block from message handler template

- packages/plugin-bootstrap/src/__tests__/actions.test.ts
- packages/plugin-bootstrap/src/actions/imageGeneration.ts
This PR updates `GENERATE_IMAGE` in `@elizaos/plugin-bootstrap` to return an `ActionResult` per core `Action` contract.\n\n- Changes limited to `packages/plugin-bootstrap/src/actions/imageGeneration.ts`\n- Excludes edits to `standalone.ts` and `package.json`\n- Resolves type incompatibility with `Plugin` by ensuring all action handlers conform\n\nPlease review.
> fix(plugin-bootstrap): return ActionResult in GENERATE_IMAGE handler

- packages/cli/src/commands/scenario/src/runtime-factory.ts
When running any ElizaOS CLI command (like `elizaos create`), users see confusing environment warnings:
```
[ENV] No .env file found in any of the expected locations
[ENV] ⚠️ OPENAI_API_KEY not found in process.env
[ENV] Safe env preview: {"NODE_ENV":"<missing>","OPENAI_API_KEY":"<missing>"}
```
These warnings appear even for commands that don't need environment variables, like `elizaos create` which is setting up a new project that doesn't have a `.env` file yet.
The issue was in `packages/cli/src/commands/scenario/src/runtime-factory.ts`:
- The module had a top-level call to `loadEnvironmentVariables()` that executed immediately when the module was imported
- The CLI's main entry point imports all commands at startup, including the scenario command
- The scenario command imports …
> fix: make environment loading lazy to prevent warnings during CLI startup

- packages/core/src/runtime.ts
Low
- creates an initPromise property
- ensures runtime is always in emitted events
Before any plugin init() can delete tasks, adapter has to be ready
> Feat: initPromise & always include runtime in emitted events

- packages/core/src/prompts.ts
- packages/plugin-bootstrap/src/index.ts
- **Fixed multi-step action result handling** to properly pass `values` between action steps
- Added `values?: Record<string, any>` to `MultiStepActionResult` interface
- Updated `runMultiStepCore` to include `values: result.values` when storing action results
- **Clarified task completion logic** in multi-step action prompts
- Added explicit instruction: "Do **not** mark the task as `isFinish: true` immediately after calling an action"
- Emphasized waiting for action completion before marking tasks as finished
The main issue was that multi-step actions weren't properly passing `values` between steps, which caused:
- **Image generation actions** to only return action text instead of the final image result
- **Data loss** between action steps in complex workflows
- **Incomplete results** …
> fix: Fix multi-step action result handling to properly pass values between steps

- CLAUDE.md
- README.md
- packages/cli/README.md
- packages/cli/src/commands/test/utils/project-utils.ts
- packages/cli/tests/commands/start.test.ts
- packages/project-starter/src/__tests__/character-plugin-ordering.test.ts
- packages/project-starter/src/__tests__/character.test.ts
- packages/project-tee-starter/src/__tests__/character.test.ts
- packages/project-tee-starter/src/__tests__/error-handling.test.ts
this is a tiny pr to fix some minor issues with the cli test command and default tests that come with project-starter and project-tee-starter.
1. when passing a test name with the --name flag, it was lowercasing the passed test name, but bun test runner is case sensitive, so it wasnt finding the test by name. solution is to remove the lower caseing. however it is case sensitive so we've added this to the relevant readmes.
2. in project-starter and project-tee-starter, once you change the name from Eliza/Mr. Tee respectively in character.ts, it fails character name validation. i switched it so it doesnt fail and now checks if its a valid string basically.
> fix: (cli) test command minor fixes

- bun.lock
- packages/core/build.ts
- packages/core/package.json
Point package.json to existing generated types instead of broken re-exports to src/
**Low** - This is a build configuration fix that corrects broken TypeScript declarations without changing any runtime behavior.
Fixes broken TypeScript imports in the published `@elizaos/core@1.5.0` npm package by:
1. Removing problematic `.d.ts` file creation that re-exports from missing `src/` directories
2. Pointing `package.json` to the existing, properly generated TypeScript declarations
3. Using the robust type definitions already created by the build system
**Bug fix** (non-breaking change which fixes an issue)
After PR #5832, consumers of the published npm package experience TypeScript compilation failures:
```typescript
error TS2305: Module '"@elizaos/core"' has no exported member 'IAgentRuntime'. …
```
> fix(core): fix TypeScript declarations in npm package

- bun.lock
- packages/core/build.ts
- packages/core/package.json
- packages/core/tsconfig.build.json
The deployed version of `@elizaos/core` on NPM was experiencing type export failures, causing TypeScript compilation errors when the package was used outside the monorepo. Users reported errors like:
```
Module '"@elizaos/core"' has no exported member 'Agent'
Module '"@elizaos/core"' has no exported member 'UUID'
... (174+ similar errors)
```
1. **Missing Source Files**: The published NPM package only included the `dist` folder, but the type declaration files referenced source files in `../src` that weren't included in the package
2. **Broken Type Generation**: The build process was attempting to generate TypeScript declarations using `npx tsc` which wasn't available in the build environment
3. **Incorrect Build Script**: The `build.ts` script created stub `.d.ts` files that pointed to …
> fix: core types output

- bun.lock
- packages/cli/build.ts
- packages/cli/package.json
- packages/cli/src/utils/copy-template.ts
- packages/cli/src/utils/display-banner.ts
- packages/cli/src/utils/user-environment.ts
- packages/core/build.ts
- packages/core/package.json
When the CLI is published to NPM and installed globally (e.g., `bun i -g @elizaos/cli`), it fails with the error:
```
Cannot find module '/home/runner/work/eliza/eliza/packages/cli/package.json'
```
This occurs because the build process in GitHub Actions CI/CD embeds absolute paths from the build machine, which don't exist on users' machines.
The CLI was using **build-time path resolution** with `require.resolve('@elizaos/cli/package.json')` which gets hardcoded to the GitHub Actions runner path during the build process.
Changed all path resolution to happen at **runtime** with multiple fallback strategies to handle different installation scenarios:
- ✅ Global NPM/Bun installations
- ✅ Local node_modules (as dependency)
- ✅ Monorepo development
- ✅ Various package manager locations
- …
> fix: CLI NPM Deployment Path Resolution Issue

- bun.lock
- packages/cli/.gitignore
- packages/cli/build.ts
- packages/cli/src/scripts/generate-version.ts
- packages/cli/src/utils/copy-template.ts
- packages/cli/src/utils/display-banner.ts
- packages/cli/src/utils/user-environment.ts
The published NPM package `@elizaos/cli@1.4.3-alpha.0` was failing with the following error when users tried to run `elizaos create` or `elizaos start`:
```
Error: Cannot find module '/home/runner/work/eliza/eliza/packages/cli/package.json' 
from '/home/cjft/.bun/install/global/node_modules/@elizaos/cli/dist/index.js'
```
This occurred because the CLI was attempting to read its own `package.json` at runtime using `import.meta.url` path resolution, which embedded the GitHub Actions build machine's absolute paths during the bundling process.
Three files were attempting to read `package.json` at runtime:
- `src/utils/user-environment.ts` - Used `import.meta.url` to resolve package.json path
- `src/utils/display-banner.ts` - Read package.json to display version
- `src/utils/copy-template.ts` …
> feat: Embeds CLI version into build output

- packages/core/src/__tests__/settings.test.ts
- packages/core/src/settings.ts
The application was logging 'SECRET_SALT is not set or using default value' error multiple times during startup, causing excessive log noise. This happens because:
1. The `getSalt()` function logs an error every time it's called when SECRET_SALT isn't configured
2. `getSetting()` in AgentRuntime calls `getSalt()` for every setting retrieval that needs decryption
3. During startup, multiple settings are retrieved, causing repeated error logs
Implemented a TTL-based caching mechanism for the salt value with the following features:
- **Cache with TTL**: Salt value is cached for 5 minutes to prevent repeated environment reads
- **One-time error logging**: Error is logged only once per application lifecycle
- **Cache invalidation**: Added `clearSaltCache()` function for tests and environment …
> fix: Prevent excessive SECRET_SALT error logging

- packages/core/src/settings.ts
The SECRET_SALT environment variable validation was logging an **error** when the default value was being used. This created confusion as error-level logs typically indicate critical failures that prevent the system from functioning properly.
The current implementation treats missing SECRET_SALT as an error, but the system continues to function normally using the default value. This is misleading for developers and operators monitoring logs.
Changed  to  for the SECRET_SALT default value message.
- **Appropriate Log Level**: A warning is more suitable since the system remains fully functional
- **Better UX**: Developers won't think something is broken when seeing this message
- **Semantic Correctness**: Errors should indicate actual failures, warnings for suboptimal configurations
- …
> fix: change SECRET_SALT log level from error to warning

- README.md
- packages/client/src/components/chat.tsx
result:
https://github.com/user-attachments/assets/7f1a502b-51f6-431f-be05-dc0dccf923e8
Implements URL synchronization for DM channels, allowing users to bookmark and share direct links to specific conversations while maintaining proper channel switching functionality.
- **URL Updates**: Automatically updates URL when users switch between DM channels
- **Direct Navigation**: Supports direct URL navigation (e.g., `/chat/{agentId}/{channelId}`)
- **Non-blocking Implementation**: Uses `window.history.replaceState()` to avoid component re-renders
- **Conflict Resolution**: Prevents URL navigation from interfering with normal channel selection
- Added `addChannelIdToUrl()` function for efficient URL updates without navigation
- Added `useEffect` to monitor `chatState.currentDmChannelId` …
> feat(client): Add URL synchronization for DM channel switching and direct navigation

- bun.lock
- packages/core/src/test_resources/constants.ts
- packages/plugin-sql/build.ts
- packages/plugin-sql/package.json
- packages/plugin-sql/src/__tests__/unit/index.browser.test.ts
- packages/plugin-sql/src/__tests__/unit/utils.browser.test.ts
- packages/plugin-sql/src/index.browser.ts
- packages/plugin-sql/src/index.node.ts
- packages/plugin-sql/src/index.ts
- packages/plugin-sql/src/utils.browser.ts
- packages/plugin-sql/src/utils.node.ts
- packages/plugin-sql/tsconfig.build.node.json
- packages/plugin-sql/types/index.d.ts
- tsconfig.json
- Add browser-safe build for `@elizaos/plugin-sql` using PGlite WASM.
- Dual entrypoints: `src/index.browser.ts` (PGlite-only) and `src/index.node.ts` (Postgres/PGlite).
- Conditional exports in `package.json` route browser to `dist/browser` and node to `dist/node`.
- Replace `global` with `globalThis` in `src/index.ts`.
Fix Next.js app-client bundling failure caused by Node builtins and server drivers leaking into the client bundle (“the chunking context does not support external modules (request: node:module)”). Enable in-browser Eliza with PGlite and embeddings.
- `packages/plugin-sql/src/index.browser.ts`: PGlite-only plugin entry.
- `packages/plugin-sql/src/index.node.ts`: Node entry with Postgres/PGlite.
- `packages/plugin-sql/src/utils.browser.ts`: No-op, browser-safe utils.
- …
> feat: Adds browser build with PGlite WASM support

- packages/cli/tests/commands/agent.test.ts
The Windows tests in the CI pipeline are failing due to incorrect handling of file paths with quotes. The issue was identified in the GitHub Actions run: https://github.com/elizaOS/eliza/actions/runs/17766711070/job/50491852008?pr=5980
On Windows, when file paths are wrapped in quotes within the command string, the quotes become part of the actual path value passed to the CLI, resulting in:
1. File not found errors with paths like: `"C:\Users\RUNNER~1\AppData\Local\Temp\eliza-test-agent-G1W52a\update_config.json"`
2. Malformed path concatenation: `D:\a\eliza\eliza\packages\cli\"C:\Users\RUNNER~1\AppData\Local\Temp\eliza-test-agent-G1W52a\output_ada.json".json`
Remove the unnecessary quotes around file path arguments in the test commands. The shell will handle path escaping appropriately …
> fix(cli): remove quotes from file paths in Windows tests

- .github/workflows/claude-code-review.yml
- Cancel previous Claude code review runs when new commits are pushed
- Prevents resource waste and ensures latest code is reviewed
- Matches concurrency behavior of other CI workflows
> feat(ci): add concurrency control to Claude code review workflow

- build-utils.ts
- bun.lock
- packages/cli/src/commands/dev/actions/dev-server.ts
- packages/cli/src/commands/dev/utils/file-watcher.ts
- packages/cli/src/commands/start/index.ts
- packages/cli/src/utils/copy-template.ts
- packages/server/build.ts
- packages/server/package.json
- turbo.json
Fixes client bundling, dev-loop restarts, and DB runtime mode; enforces TS type-check failures to stop builds. Improves build ordering so the web UI is always shipped with the server.
- Client UI bundling
- Server now bundles client assets reliably:
- Copies from `packages/client/dist` if present, else falls back to `node_modules/@elizaos/client/dist`.
- Files: `packages/server/build.ts`
- Build order enforced so client builds before server:
- Added task and dependency in `turbo.json`:
- `@elizaos/client#build` defined
- `@elizaos/server#build.dependsOn` includes `@elizaos/client#build`
- Dev stability (fix “death loop”)
- Debounce and watcher tuning to prevent rebuild storms:
- `packages/cli/src/commands/dev/utils/file-watcher.ts`
- Guard against concurrent rebuilds:
- …
> fix: release fixes

- packages/cli/src/commands/dev/actions/dev-server.ts
- packages/cli/tests/commands/start.test.ts
- packages/cli/tests/test-timeouts.ts
This fixes the dev mode port increment loop by waiting for the previous server port to be released before restarting.\n\n- Adds a small utility  using existing \n- Ensures we wait before starting the server after rebuild\n\nTested locally; the server no longer hops ports upon file change restarts.
> fix(cli): wait for port to be free before dev restart

- packages/cli/src/commands/dev/actions/__tests__/recursion-prevention.test.ts
- packages/cli/src/commands/dev/actions/dev-server.ts
Fixes infinite dev restart loop when client is missing by adding proper recursion prevention logic.
- Added check to prevent recursive execution when  would call itself
- Improved client directory detection logic in dev server
- Added safeguards to prevent infinite restart loops when client dependencies are missing
The CLI dev command was getting stuck in infinite restart loops when the client was missing or when running from directories with vite config that would cause recursive execution.
Added detection logic to:
1. Check if dev script would run  to prevent recursion  
2. Validate client directory existence before attempting to start client server
3. Skip client startup when it would cause infinite loops
Based on commits:
- 89ab5119c7 Merge branch 'fix/cli-dev-missing-client-loop' of …
> fix(cli): prevent infinite dev restart loop when client is missing

- bun.lock
- packages/cli/src/characters/eliza.ts
- packages/cli/src/commands/start/index.ts
Refines the logic for including Ollama as a fallback LLM provider,
ensuring it's only included when no other LLM providers are configured.
Enhances environment variable loading by using a monorepo-aware
resolver, falling back to the current working directory if resolution
fails. This ensures that the root .env file is found when running via
turbo.
> fix: .env not loading from mono, ollama always fallback

- bun.lock
- packages/server/src/managers/PluginInstaller.ts
- packages/server/src/managers/PluginLoader.ts
- packages/server/src/managers/__tests__/PluginInstaller.test.ts
This PR introduces safe, on-demand plugin auto-installation for the server PluginLoader.\n\nProblem\n- Missing server plugins cause runtime failures when a project references external plugins not pre-installed.\n- Operators often need to manually run `bun add <package>` after the runtime crashes.\n\nSolution\n- Add `PluginInstaller` which guards via environment checks (disabled in CI/test, opt-out via `ELIZA_NO_AUTO_INSTALL`, `ELIZA_NO_PLUGIN_AUTO_INSTALL`).\n- On import failure, attempt `bun add <plugin>` once per process, then retry import.\n- Uses Bun subprocess to avoid Node-only assumptions; logs clearly on failure without crashing.\n\nFiles Changed\n- `packages/server/src/managers/PluginLoader.ts`: Integrate auto-install retry path.\n- …
> feat(server): auto-install missing plugins in PluginLoader

- packages/core/src/elizaos.ts
- packages/server/src/index.ts
issue: https://linear.app/eliza-labs/issue/ELIZA-741/unhandled-exception-when-getagents-fails-in-runtimets-missing-agents
- core: add RuntimeSettings import and accept `settings` in `ElizaOS.addAgents`
- core: pass `settings` into `AgentRuntime` constructor during agent creation
- server: load env settings once and pass to `addAgents`
- server: remove post-creation runtime mutation via Object.assign(settings)
This ensures runtimes and plugins receive configuration during initialization, avoiding late mutations and potential race conditions.
> fix: initialize runtimes with settings at creation
